/- Generated by emit_majorant.py: 1 leaves, 0 logs. -/
import SpinCodes.Numeric.MajorantDefs
set_option maxRecDepth 8000000
set_option maxHeartbeats 0
namespace Spin.Majorant.S5.P17
open Spin.Numeric Spin.Numeric.Fix
def table : LogTree := .leaf
def tree : BoxTree := .leaf (1)
def A : Fix := ⟨0, 500000000000000000000000000000⟩
def B : Fix := ⟨500000000000000000000000000000, 1000000000000000000000000000000⟩
def W : Fix := ⟨170863082808760000000000000000, 186080216750413333333333333334⟩
def S : Fix := ⟨1550000000000000000000000000000, 1550000000000000000000000000000⟩
def I : Fix := ⟨-154045203238254000000000000000, -154045203238254000000000000000⟩
theorem logs_ok : table.check 10 = true := by decide
theorem tree_ok : checkTree (majorantLeaf (treeLog table) S I) tree A B W = true := by decide
end Spin.Majorant.S5.P17
