/- Generated by emit_majorant.py: 1 leaves, 0 logs. -/
import SpinCodes.Numeric.MajorantDefs
set_option maxRecDepth 8000000
set_option maxHeartbeats 0
namespace Spin.Majorant.S4.P13
open Spin.Numeric Spin.Numeric.Fix
def table : LogTree := .leaf
def tree : BoxTree := .leaf (1)
def A : Fix := ⟨375000000000000000000000000000, 500000000000000000000000000000⟩
def B : Fix := ⟨375000000000000000000000000000, 500000000000000000000000000000⟩
def W : Fix := ⟨164652567555266666666666666666, 170863082808760000000000000000⟩
def S : Fix := ⟨1600000000000000000000000000000, 1600000000000000000000000000000⟩
def I : Fix := ⟨-162588357378692000000000000000, -162588357378692000000000000000⟩
theorem logs_ok : table.check 10 = true := by decide
theorem tree_ok : checkTree (majorantLeaf (treeLog table) S I) tree A B W = true := by decide
end Spin.Majorant.S4.P13
