#!/usr/bin/env python3
"""Exponential-moment bound for block-recursive cancellation.

Fix the first active block and its local input mask v.  Let A be the complete
zero-input trajectory generated by v through the end of the inner recursion,
including the terminal state.  Later input coordinates generate shifted
one-coordinate trajectories.  If the final trajectory has weight at most d,
then the later trajectory must overlap A in at least

    ceil((wt(A) - d) / 2)

positions.  This script computes the exact overlap score of every later
coordinate against A and applies the standard sampling-without-replacement
Chernoff/Hoeffding mgf bound.

The result is deliberately pessimistic: it ignores the positive weight of the
later trajectory and treats the later overlap score additively before XOR
cancellations among later inputs.  Its purpose is to identify whether the
current early-branch proof can close with a one-line hypergeometric ledger or
needs a sharper state-conditioned argument.
"""

from __future__ import annotations

import argparse
import math
from collections.abc import Iterable

from check_bch_generator_inner import iter_weight_masks
from probe_block_recursive_inner import (
    build_output_systematic_basis,
    build_parity_tables,
    parity_state,
    parse_int_list,
)


def logsumexp(vals: Iterable[float]) -> float:
    vals = list(vals)
    if not vals:
        return -math.inf
    mx = max(vals)
    if mx == -math.inf:
        return mx
    return mx + math.log(sum(math.exp(v - mx) for v in vals))


def trajectory(tables: list[list[int]], mask: int, length: int) -> list[int]:
    out = []
    x = mask
    for _ in range(length):
        out.append(x)
        x = parity_state(tables, 16, x) if x else 0
    return out


def overlap_population(
    tables: list[list[int]],
    b: int,
    first_traj: list[int],
    live_blocks: int,
) -> list[int]:
    """Return overlap scores for all later coordinates.

    first_traj has length live_blocks+1: block outputs from the first active
    block through the final emitted state.  Later inputs may occur in the
    remaining live_blocks-1 data blocks.
    """

    basis_traj = [trajectory(tables, 1 << bit, live_blocks + 1) for bit in range(b)]
    scores: list[int] = []
    for lag in range(1, live_blocks):
        suffix_len = live_blocks + 1 - lag
        for bit in range(b):
            col = basis_traj[bit]
            score = 0
            for t in range(suffix_len):
                score += (first_traj[lag + t] & col[t]).bit_count()
            scores.append(score)
    return scores


def log_mgf_bound(scores: list[int], draws: int, threshold: int, theta: float) -> float:
    if threshold <= 0:
        return 0.0
    if draws <= 0:
        return -math.inf
    log_mean = logsumexp(theta * score for score in scores) - math.log(len(scores))
    return draws * log_mean - theta * threshold


def best_log2_bound(scores: list[int], draws: int, threshold: int) -> tuple[float, float]:
    if threshold <= 0:
        return 0.0, 0.0
    if draws <= 0:
        return -math.inf, 0.0
    # A deterministic cap: if the largest possible additive score is too small,
    # cancellation cannot reach the threshold.
    top = sorted(scores, reverse=True)[:draws]
    if sum(top) < threshold:
        return -math.inf, math.inf

    best = 0.0
    best_theta = 0.0
    # Log-spaced grid is enough for this diagnostic and avoids scipy.
    for e in range(-80, 81):
        theta = math.exp(e / 8)
        val = log_mgf_bound(scores, draws, threshold, theta)
        if val < best:
            best = val
            best_theta = theta
    return best / math.log(2), best_theta


def summarize_scores(scores: list[int]) -> tuple[int, float, int, int, int]:
    ordered = sorted(scores)
    n = len(ordered)
    return (
        ordered[-1],
        sum(ordered) / n,
        ordered[n // 2],
        ordered[(99 * n) // 100],
        ordered[(999 * n) // 1000],
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--m", type=int, default=7)
    parser.add_argument("--delta-bch", type=int, default=21)
    parser.add_argument("--N", type=int, default=2**21)
    parser.add_argument("--distance-delta", type=float, default=0.09)
    parser.add_argument("--h", type=int, default=32)
    parser.add_argument("--first-r-values", default="1,2")
    parser.add_argument("--gaps-before-late", default="1,10,50,100,500,1000")
    parser.add_argument("--late-blocks", type=int, default=5949)
    parser.add_argument("--exact-mask-limit", type=int, default=5000)
    parser.add_argument(
        "--max-overlap-work",
        type=float,
        default=2.0e8,
        help="Skip rows whose rough mask*b*live_blocks^2 work estimate exceeds this value.",
    )
    args = parser.parse_args()

    sys_basis, b, ext_n, row_d0 = build_output_systematic_basis(args.m, args.delta_bch)
    tables = build_parity_tables(sys_basis, b)
    if args.N % b:
        raise ValueError("N must be divisible by block size")
    blocks_n = args.N // b
    d = math.floor(args.distance_delta * args.N)
    late_start = blocks_n - args.late_blocks

    print("Block-recursive early-cancellation mgf bound")
    print(
        f"m={args.m}, designed_delta={args.delta_bch}, b={b}, local_length={ext_n}, "
        f"N={args.N}, blocks={blocks_n}, h={args.h}, d={d}, late_blocks={args.late_blocks}, "
        f"row_d0={row_d0}"
    )
    print(
        "first_r,gap,live_blocks,masks,draws,min_first_wt,min_threshold,"
        "worst_log2_bound,worst_theta,max_score,avg_score,p50_score,p99_score,p999_score"
    )

    for first_r in parse_int_list(args.first_r_values):
        mask_count = math.comb(b, first_r)
        if mask_count > args.exact_mask_limit:
            print(f"# skipping first_r={first_r}: {mask_count} masks exceed exact limit")
            continue
        masks = list(iter_weight_masks(b, first_r))
        draws = args.h - first_r
        for gap in parse_int_list(args.gaps_before_late):
            first_block = late_start - gap
            if first_block < 0:
                continue
            live_blocks = blocks_n - first_block
            rough_work = len(masks) * b * live_blocks * live_blocks
            if rough_work > args.max_overlap_work:
                print(
                    f"# skipping first_r={first_r}, gap={gap}: live_blocks={live_blocks}, "
                    f"rough_work={rough_work:.3g} exceeds max_overlap_work={args.max_overlap_work:.3g}"
                )
                continue
            worst_log2 = -math.inf
            worst_theta = math.inf
            min_first = 10**18
            min_threshold = 10**18
            worst_stats = (0, 0.0, 0, 0, 0)
            for mask in masks:
                first_traj = trajectory(tables, mask, live_blocks + 1)
                first_wt = sum(x.bit_count() for x in first_traj)
                threshold = max(0, (first_wt - d + 1) // 2)
                scores = overlap_population(tables, b, first_traj, live_blocks)
                log2_bound, theta = best_log2_bound(scores, draws, threshold)
                if log2_bound > worst_log2:
                    worst_log2 = log2_bound
                    worst_theta = theta
                    worst_stats = summarize_scores(scores)
                min_first = min(min_first, first_wt)
                min_threshold = min(min_threshold, threshold)
            max_score, avg_score, p50_score, p99_score, p999_score = worst_stats
            print(
                f"{first_r},{gap},{live_blocks},{len(masks)},{draws},"
                f"{min_first},{min_threshold},{worst_log2:.6f},{worst_theta:.6g},"
                f"{max_score},{avg_score:.6f},{p50_score},{p99_score},{p999_score}"
            )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
