#!/usr/bin/env python3
"""Generate an exact low-XOR A circuit for an RM2Sub inner."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
import probe_bch_forward_xor_circuit as paar  # noqa: E402


DEFAULT_SELECTION = ROOT / (
    "constructions/riffle_bchperm_transpose_bitshuffle_"
    "splitstate_preaddmul_t128_s32/receipts/smaller_state/"
    "s16_rm2sub_selection.json"
)
DEFAULT_INCLUDE = ROOT / (
    "constructions/riffle_bchperm_transpose_bitshuffle_"
    "splitstate_preaddmul_t128_s32/benchmark/"
    "RiffleRm2SubS16PaarA.inc"
)
DEFAULT_RECEIPT = ROOT / (
    "constructions/riffle_bchperm_transpose_bitshuffle_"
    "splitstate_preaddmul_t128_s32/receipts/performance/"
    "s16_rm2sub_a_circuit.json"
)


def xor_expression(signals: list[int], state_bits: int) -> str:
    def name(signal: int) -> str:
        return f"state[{signal}]" if signal < state_bits else f"a{signal}"

    expression = name(signals[0])
    for signal in signals[1:]:
        expression = f"xorBlock({expression}, {name(signal)})"
    return expression


def write_include(
    path: Path, circuit: paar.Circuit, seed: int, state_bits: int
) -> None:
    outputs_at: dict[int, list[int]] = {}
    for output, signals in enumerate(circuit.output_signals):
        outputs_at.setdefault(max(signals), []).append(output)

    lines = [
        f"// Exact {circuit.xor_count}-XOR Paar circuit, seed {seed}.",
        "// Generated by scripts/build_riffle_rm2sub_s16_a_circuit.py.",
    ]

    def emit_outputs(ready_at: int) -> None:
        for output in outputs_at.get(ready_at, []):
            expression = xor_expression(circuit.output_signals[output], state_bits)
            lines.extend(
                [
                    f"const Block addend{output} = {expression};",
                    f"const Block encoded{output} = xorBlock(word[{output}], addend{output});",
                    f"word[{output}] = encoded{output};",
                    f"values[{output}] = encoded{output};",
                ]
            )

    for signal in range(state_bits):
        emit_outputs(signal)
    for gate_index, (left, right) in enumerate(circuit.gates, start=state_bits):
        left_name = f"state[{left}]" if left < state_bits else f"a{left}"
        right_name = f"state[{right}]" if right < state_bits else f"a{right}"
        lines.append(f"const Block a{gate_index} = xorBlock({left_name}, {right_name});")
        emit_outputs(gate_index)
    if sum(len(outputs) for outputs in outputs_at.values()) != 128:
        raise AssertionError("did not emit every A output")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--selection", type=Path, default=DEFAULT_SELECTION)
    parser.add_argument("--output", type=Path, default=DEFAULT_INCLUDE)
    parser.add_argument("--receipt", type=Path, default=DEFAULT_RECEIPT)
    parser.add_argument("--seed", type=int, default=485)
    parser.add_argument("--minimum-overlap", type=int, default=2)
    args = parser.parse_args()

    selection = json.loads(args.selection.read_text(encoding="utf-8"))
    state_bits = int(selection["parameters"]["state_bits"])
    target = [int(word, 16) for word in selection["selected"]["B_columns_hex"]]
    paar.DIMENSION = state_bits
    circuit = paar.synthesize(args.seed, args.minimum_overlap, target)
    write_include(args.output, circuit, args.seed, state_bits)

    receipt = {
        "schema": "riffle-rm2sub-a-paar-circuit-v1",
        "seed": args.seed,
        "minimum_overlap": args.minimum_overlap,
        "input_bits": state_bits,
        "output_bits": 128,
        "shared_gates": len(circuit.gates),
        "output_xors": circuit.xor_count - len(circuit.gates),
        "a_form_xors": circuit.xor_count,
        "a_output_addition_xors": 128,
        "a_total_xors": circuit.xor_count + 128,
        "transpose_xors": paar.transpose_xor_count(circuit),
        "max_depth_upper": circuit.max_depth,
        "max_live_signals": circuit.max_live_signals,
        "selection": str(args.selection.resolve().relative_to(ROOT)),
        "generated_include": str(args.output.resolve().relative_to(ROOT)),
        "gates": circuit.gates,
        "outputs": circuit.output_signals,
    }
    args.receipt.parent.mkdir(parents=True, exist_ok=True)
    args.receipt.write_text(json.dumps(receipt, indent=2) + "\n", encoding="utf-8")
    print(f"a_form_xors,{circuit.xor_count}")
    print(f"a_total_xors,{circuit.xor_count + 128}")
    print(f"transpose_xors,{paar.transpose_xor_count(circuit)}")
    print(f"wrote,{args.output}")
    print(f"wrote,{args.receipt}")


if __name__ == "__main__":
    main()
