/- Generated by `scripts/emit_cover.py`.  Do not edit.

Part 43 of the cover: 1 leaves, 0 logarithms.
Self-contained — its own table, its own subtree, its own claim. -/
import SpinCodes.Cover.Params
import SpinCodes.Numeric.BAEval

set_option maxRecDepth 8000000
set_option maxHeartbeats 0

namespace Spin.Cover

open Spin.Numeric Spin.Numeric.Fix

def table43 : LogTree :=
  .leaf

def tree43 : BoxTree :=
  .leaf 1

def a43 : Fix := ⟨8000000000000000000000000000, 1000000000000000000000000000000⟩
def b43 : Fix := ⟨500000000000000000000000000000, 1000000000000000000000000000000⟩
def w43 : Fix := ⟨2000000000000000000000000000, 104000000000000000000000000000⟩

theorem logs43_ok : (table43).check terms = true := by decide

theorem tree43_ok :
    checkTree (leafOK (treeLog table43) thr) tree43 a43 b43 w43 = true := by decide

theorem part43_claim (x y z : ℝ) (hx : Mem a43 x)
    (hy : Mem b43 y) (hz : Mem w43 z) :
    DenseClaim thr x y z :=
  denseTail_of_checkTree (treeLog_oracle logs43_ok) tree43 tree43_ok hx hy hz

end Spin.Cover
