/- Generated by `scripts/emit_cover.py`.  Do not edit.

Part 19 of the cover: 1 leaves, 0 logarithms.
Self-contained — its own table, its own subtree, its own claim. -/
import SpinCodes.Cover.Params
import SpinCodes.Numeric.BAEval

set_option maxRecDepth 8000000
set_option maxHeartbeats 0

namespace Spin.Cover

open Spin.Numeric Spin.Numeric.Fix

def table19 : LogTree :=
  .leaf

def tree19 : BoxTree :=
  .leaf 1

def a19 : Fix := ⟨132000000000000000000000000000, 256000000000000000000000000000⟩
def b19 : Fix := ⟨125000000000000000000000000000, 250000000000000000000000000000⟩
def w19 : Fix := ⟨2000000000000000000000000000, 53000000000000000000000000000⟩

theorem logs19_ok : (table19).check terms = true := by decide

theorem tree19_ok :
    checkTree (leafOK (treeLog table19) thr) tree19 a19 b19 w19 = true := by decide

theorem part19_claim (x y z : ℝ) (hx : Mem a19 x)
    (hy : Mem b19 y) (hz : Mem w19 z) :
    DenseClaim thr x y z :=
  denseTail_of_checkTree (treeLog_oracle logs19_ok) tree19 tree19_ok hx hy hz

end Spin.Cover
