/- Generated by `scripts/emit_cover.py`.  Do not edit.

Part 41 of the cover: 1 leaves, 0 logarithms.
Self-contained — its own table, its own subtree, its own claim. -/
import SpinCodes.Cover.Params
import SpinCodes.Numeric.BAEval

set_option maxRecDepth 8000000
set_option maxHeartbeats 0

namespace Spin.Cover

open Spin.Numeric Spin.Numeric.Fix

def table41 : LogTree :=
  .leaf

def tree41 : BoxTree :=
  .leaf 1

def a41 : Fix := ⟨8000000000000000000000000000, 504000000000000000000000000000⟩
def b41 : Fix := ⟨250000000000000000000000000000, 500000000000000000000000000000⟩
def w41 : Fix := ⟨2000000000000000000000000000, 104000000000000000000000000000⟩

theorem logs41_ok : (table41).check terms = true := by decide

theorem tree41_ok :
    checkTree (leafOK (treeLog table41) thr) tree41 a41 b41 w41 = true := by decide

theorem part41_claim (x y z : ℝ) (hx : Mem a41 x)
    (hy : Mem b41 y) (hz : Mem w41 z) :
    DenseClaim thr x y z :=
  denseTail_of_checkTree (treeLog_oracle logs41_ok) tree41 tree41_ok hx hy hz

end Spin.Cover
