/- Generated by `scripts/emit_cover.py`.  Do not edit.

Part 31 of the cover: 1 leaves, 0 logarithms.
Self-contained — its own table, its own subtree, its own claim. -/
import SpinCodes.Cover.Params
import SpinCodes.Numeric.BAEval

set_option maxRecDepth 8000000
set_option maxHeartbeats 0

namespace Spin.Cover

open Spin.Numeric Spin.Numeric.Fix

def table31 : LogTree :=
  .leaf

def tree31 : BoxTree :=
  .leaf 1

def a31 : Fix := ⟨256000000000000000000000000000, 380000000000000000000000000000⟩
def b31 : Fix := ⟨125000000000000000000000000000, 250000000000000000000000000000⟩
def w31 : Fix := ⟨2000000000000000000000000000, 53000000000000000000000000000⟩

theorem logs31_ok : (table31).check terms = true := by decide

theorem tree31_ok :
    checkTree (leafOK (treeLog table31) thr) tree31 a31 b31 w31 = true := by decide

theorem part31_claim (x y z : ℝ) (hx : Mem a31 x)
    (hy : Mem b31 y) (hz : Mem w31 z) :
    DenseClaim thr x y z :=
  denseTail_of_checkTree (treeLog_oracle logs31_ok) tree31 tree31_ok hx hy hz

end Spin.Cover
