/- Generated by `scripts/emit_cover.py`.  Do not edit.

Part 42 of the cover: 2 leaves, 0 logarithms.
Self-contained — its own table, its own subtree, its own claim. -/
import SpinCodes.Cover.Params
import SpinCodes.Numeric.BAEval

set_option maxRecDepth 8000000
set_option maxHeartbeats 0

namespace Spin.Cover

open Spin.Numeric Spin.Numeric.Fix

def table42 : LogTree :=
  .leaf

def tree42 : BoxTree :=
  .split 1 250000000000000000000000000000 (.leaf 1) (.leaf 1)

def a42 : Fix := ⟨504000000000000000000000000000, 1000000000000000000000000000000⟩
def b42 : Fix := ⟨0, 500000000000000000000000000000⟩
def w42 : Fix := ⟨2000000000000000000000000000, 104000000000000000000000000000⟩

theorem logs42_ok : (table42).check terms = true := by decide

theorem tree42_ok :
    checkTree (leafOK (treeLog table42) thr) tree42 a42 b42 w42 = true := by decide

theorem part42_claim (x y z : ℝ) (hx : Mem a42 x)
    (hy : Mem b42 y) (hz : Mem w42 z) :
    DenseClaim thr x y z :=
  denseTail_of_checkTree (treeLog_oracle logs42_ok) tree42 tree42_ok hx hy hz

end Spin.Cover
