/- Generated by `scripts/emit_cover.py`.  Do not edit.

Part 30 of the cover: 1 leaves, 0 logarithms.
Self-contained — its own table, its own subtree, its own claim. -/
import SpinCodes.Cover.Params
import SpinCodes.Numeric.BAEval

set_option maxRecDepth 8000000
set_option maxHeartbeats 0

namespace Spin.Cover

open Spin.Numeric Spin.Numeric.Fix

def table30 : LogTree :=
  .leaf

def tree30 : BoxTree :=
  .leaf 1

def a30 : Fix := ⟨256000000000000000000000000000, 504000000000000000000000000000⟩
def b30 : Fix := ⟨0, 125000000000000000000000000000⟩
def w30 : Fix := ⟨2000000000000000000000000000, 104000000000000000000000000000⟩

theorem logs30_ok : (table30).check terms = true := by decide

theorem tree30_ok :
    checkTree (leafOK (treeLog table30) thr) tree30 a30 b30 w30 = true := by decide

theorem part30_claim (x y z : ℝ) (hx : Mem a30 x)
    (hy : Mem b30 y) (hz : Mem w30 z) :
    DenseClaim thr x y z :=
  denseTail_of_checkTree (treeLog_oracle logs30_ok) tree30 tree30_ok hx hy hz

end Spin.Cover
