"""Emit small independent kernel checks and assemble their coverage proofs."""
import argparse
from functools import lru_cache
import json
from pathlib import Path
import fixmirror as F
import majorant_cover as M

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT/'SpinCodes/Majorant'
HEADER = 'set_option maxRecDepth 8000000\nset_option maxHeartbeats 0\n'


def fix(x):
    return f'⟨{x[0]}, {x[1]}⟩'


def children(t, box):
    _, d, m, l, r = t
    left, right = list(box), list(box)
    left[d], right[d] = (box[d][0], m), (m, box[d][1])
    return (l, left), (r, right)


def tree(t):
    if t[0] == 'leaf':
        return f'.leaf ({t[1]})'
    return f'.split {t[1]} ({t[2]}) ({tree(t[3])}) ({tree(t[4])})'


def logs(items):
    if not items:
        return '.leaf'
    m = len(items)//2
    k, v = items[m]
    return f'.node {k} {fix(v)} ({logs(items[:m])}) ({logs(items[m+1:])})'


def count(t):
    return 1 if t[0] == 'leaf' else count(t[3])+count(t[4])


def emit(segment, limit):
    data = json.loads((ROOT/f'scripts/majorant_data/segment{segment}.json').read_text())
    folder = OUT/f'Segment{segment}'
    folder.mkdir(parents=True, exist_ok=True)
    slope, intercept = tuple(data['slope']), tuple(data['intercept'])
    parts = []

    def cut(t, box):
        if count(t) <= limit:
            parts.append((t, box))
            return ['part', len(parts)-1]
        (l, lb), (r, rb) = children(t, box)
        return [*t[:3], cut(l, lb), cut(r, rb)]

    skeleton = cut(data['tree'], [data['A'], data['B'], data['W']])
    lg = lru_cache(maxsize=500000)(F.directLog(data['terms']))
    total_logs = 0
    entries = []
    for j, (t, box) in enumerate(parts):
        table = {}

        def oracle(k):
            v = lg(k)
            if v is not None:
                table[k] = v
            return v

        def collect(t, box):
            if t[0] == 'leaf':
                if F.infeasible(*box):
                    return
                u = t[1]
                v = (M.centered if u > 0 else M.plain)(
                    oracle, F.sc(abs(u)), *box, slope, intercept)
                assert v is not None and v[1] < 0
            else:
                for child, bounds in children(t, box):
                    collect(child, bounds)

        collect(t, box)
        total_logs += len(table)
        ns = f'Spin.Majorant.S{segment}.P{j}'
        a,b,w = map(fix, box)
        path = folder/f'Part{j}.lean'
        path.write_text(
            f'/- Generated by emit_majorant.py: {count(t)} leaves, {len(table)} logs. -/\n'
            'import SpinCodes.Numeric.MajorantDefs\n'+HEADER+
            f'namespace {ns}\nopen Spin.Numeric Spin.Numeric.Fix\n'
            f'def table : LogTree := {logs(sorted(table.items()))}\n'
            f'def tree : BoxTree := {tree(t)}\n'
            f'def A : Fix := {a}\ndef B : Fix := {b}\ndef W : Fix := {w}\n'
            f'def S : Fix := {fix(slope)}\ndef I : Fix := {fix(intercept)}\n'
            f'theorem logs_ok : table.check {data["terms"]} = true := by decide\n'
            'theorem tree_ok : checkTree (majorantLeaf (treeLog table) S I) tree A B W = true := by decide\n'
            f'end {ns}\n',encoding='utf-8')
        entries.append(dict(module=f'SpinCodes.Majorant.Segment{segment}.Part{j}',
                            leaves=count(t), logs=len(table)))

    imports = '\n'.join('import '+entry['module'] for entry in entries)
    source = imports+'\nimport SpinCodes.Numeric.MajorantEval\n'+HEADER
    source += f'namespace Spin.Majorant.S{segment}\nopen Spin.Numeric Spin.Numeric.Fix\n'
    for j in range(len(parts)):
        source += f'''theorem part{j} {{s i : ℝ}} (hs : Mem P{j}.S s) (hi : Mem P{j}.I i)
    (a b w : ℝ) (ha : Mem P{j}.A a) (hb : Mem P{j}.B b) (hw : Mem P{j}.W w) :
    MajorantClaim s i a b w :=
  majorant_of_checkTree (treeLog_oracle P{j}.logs_ok) hs hi P{j}.tree P{j}.tree_ok ha hb hw
'''

    def claim(t, box):
        if t[0] == 'part':
            return f'(part{t[1]} hs hi)'
        (_, lb), (_, rb) = children(t, box)
        a,b,w = map(fix, box)
        fn = ['claim_split_fst','claim_split_snd','claim_split_thd'][t[1]]
        return (f'({fn} (A := {a}) (B := {b}) (W := {w}) (m := {t[2]}) '
                f'{claim(t[3], lb)} {claim(t[4], rb)})')

    a,b,w = map(fix, [data['A'], data['B'], data['W']])
    source += f'''theorem cover {{s i : ℝ}} (hs : Mem {fix(slope)} s) (hi : Mem {fix(intercept)} i)
    (a b w : ℝ) (ha : Mem {a} a) (hb : Mem {b} b) (hw : Mem {w} w) :
    MajorantClaim s i a b w :=
  {claim(skeleton,[data['A'], data['B'], data['W']])} a b w ha hb hw
end Spin.Majorant.S{segment}
'''
    (OUT/f'Segment{segment}.lean').write_text(source,encoding='utf-8')
    return dict(segment=segment, parts=entries, logs=total_logs, stats=data['stats'])


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('segment')
    p.add_argument('--limit',type=int,default=400)
    args = p.parse_args()
    segs = range(19) if args.segment == 'all' else [int(args.segment)]
    manifest = []
    for i in segs:
        record = emit(i,args.limit)
        manifest.append(record)
        print('segment',i,'parts',len(record['parts']),'logs',record['logs'],flush=True)
    (ROOT/'scripts/majorant_data/manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')


if __name__ == '__main__':
    main()
