"""Emit the dense-tail certificate as Lean data.

Writes three files:

  SpinCodes/Cover/DenseTailLogs.lean   the verified logarithm table
  SpinCodes/Cover/DenseTailTree.lean   the split tree
  SpinCodes/Cover/DenseTail.lean       the theorem

The logarithm table holds only the arguments the *leaves* request.  The search
also evaluates internal nodes, to decide whether to split, but Lean never does
— it recurses there — so those arguments are not needed.

Usage:
  python -B scripts/emit_dense_tail.py [--small] [max_nodes] [terms]
"""
import sys, os, json, math

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import fixmirror as F

S = F.SCALE
SMALL = "--small" in sys.argv
argv = [a for a in sys.argv[1:] if not a.startswith("--")]
MAXN = int(argv[0]) if argv else 400000
TERMS = int(argv[1]) if len(argv) > 1 else 10
THR = -76800000000000000000000
MAXDEPTH = 60

if SMALL:
    # a small interior region, for validating the pipeline cheaply
    A0 = (10 * S // 1000, 200 * S // 1000)
    B0 = (100 * S // 1000, 300 * S // 1000)
    W0 = (50 * S // 1000, 104 * S // 1000)
    SUFFIX = "Small"
else:
    A0 = (S // 125, S)
    B0 = (0, S)
    W0 = (S // 500, 13 * S // 125)
    SUFFIX = ""

W_A, W_B, W_W = A0[1] - A0[0], B0[1] - B0[0], W0[1] - W0[0]


def gobj_real(u, a):
    G = 1 + 759 * u ** 8 + 2576 * u ** 12 + 759 * u ** 16 + u ** 24
    return math.log(G) / 24 - a * math.log(u)


def pick_u(A):
    a = (A[0] + A[1]) / 2 / S
    lo, hi = 1e-4, 3.0
    for _ in range(200):
        m1 = lo + (hi - lo) / 3
        m2 = hi - (hi - lo) / 3
        if gobj_real(m1, a) < gobj_real(m2, a):
            hi = m2
        else:
            lo = m1
    return max(1, int(round((lo + hi) / 2 * S)))


def widest(A, B, W):
    wa = A[1] - A[0]
    wb = B[1] - B[0]
    ww = (W[1] - W[0]) * 125 // 99
    if wa >= wb and wa >= ww:
        return 0
    return 1 if wb >= ww else 2


plain_lg = F.directLog(TERMS)
nodes = 0


def build(A, B, W, depth):
    global nodes
    nodes += 1
    if nodes > MAXN:
        raise RuntimeError(f"node cap {MAXN} exceeded")
    if nodes % 4000 == 0:
        print(f"  search nodes={nodes}", flush=True)
    if F.infeasible(A, B, W):
        return ("leaf", 1)
    u = pick_u(A)
    v = F.leafValue(plain_lg, u, A, B, W)
    if v is not None and v[1] < THR:
        return ("leaf", u)
    if depth >= MAXDEPTH:
        raise RuntimeError(f"depth cap at {A} {B} {W}")
    d = widest(A, B, W)
    if d == 0:
        m = F.fdiv(A[0] + A[1], 2)
        return ("split", 0, m, build((A[0], m), B, W, depth + 1),
                build((m, A[1]), B, W, depth + 1))
    if d == 1:
        m = F.fdiv(B[0] + B[1], 2)
        return ("split", 1, m, build(A, (B[0], m), W, depth + 1),
                build(A, (m, B[1]), W, depth + 1))
    m = F.fdiv(W[0] + W[1], 2)
    return ("split", 2, m, build(A, B, (W[0], m), depth + 1),
            build(A, B, (m, W[1]), depth + 1))


def collect(tree, A, B, W, out):
    """Exactly the logarithms Lean will request: leaves only."""
    if tree[0] == "leaf":
        def rec(p):
            out.add(p)
            return F.flogQ(p, S, TERMS)
        F.leafOK(rec, THR, tree[1], A, B, W)
        return
    _, d, m, l, r = tree
    if d == 0:
        collect(l, (A[0], m), B, W, out); collect(r, (m, A[1]), B, W, out)
    elif d == 1:
        collect(l, A, (B[0], m), W, out); collect(r, A, (m, B[1]), W, out)
    else:
        collect(l, A, B, (W[0], m), out); collect(r, A, B, (m, W[1]), out)


def emit_tree(t, buf):
    if t[0] == "leaf":
        buf.append(f".leaf {t[1]}")
        return
    buf.append(f".split {t[1]} {t[2]} (")
    emit_tree(t[3], buf)
    buf.append(") (")
    emit_tree(t[4], buf)
    buf.append(")")


def emit_logs(keys, vals, lo, hi, buf):
    if lo > hi:
        buf.append(".leaf")
        return
    mid = (lo + hi) // 2
    k = keys[mid]
    v = vals[k]
    buf.append(f".node {k} ⟨{v[0]}, {v[1]}⟩ (")
    emit_logs(keys, vals, lo, mid - 1, buf)
    buf.append(") (")
    emit_logs(keys, vals, mid + 1, hi, buf)
    buf.append(")")


if __name__ == "__main__":
    sys.setrecursionlimit(200000)
    tree = build(A0, B0, W0, 0)
    print(f"search closed: {nodes} nodes")
    args = set()
    collect(tree, A0, B0, W0, args)
    keys = sorted(args)
    vals = {k: F.flogQ(k, S, TERMS) for k in keys}
    assert all(v is not None for v in vals.values()), "a table entry has no value"
    print(f"leaf-requested logarithms: {len(keys)}")

    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)
    cov = os.path.join(root, "SpinCodes", "Cover")
    os.makedirs(cov, exist_ok=True)

    buf = []
    emit_logs(keys, vals, 0, len(keys) - 1, buf)
    with open(os.path.join(cov, f"DenseTailLogs{SUFFIX}.lean"), "w", encoding="utf-8") as f:
        f.write("/- Generated by `scripts/emit_dense_tail.py`.  Do not edit.\n\n"
                f"The {len(keys)} distinct logarithm arguments the cover's leaves request,\n"
                "each with an enclosure `flogQ` agrees with.  `LogTree.check` re-derives\n"
                "every one of them, so nothing here is trusted. -/\n"
                "import SpinCodes.Numeric.BAEvalDefs\n\n"
                "set_option maxRecDepth 8000000" + chr(10) +
                "set_option maxHeartbeats 0" + chr(10) + chr(10) +
                "namespace Spin.Cover\n\nopen Spin.Numeric Spin.Numeric.Fix\n\n"
                f"def logTable{SUFFIX} : LogTree :=\n  " + "".join(buf) + "\n\n"
                "end Spin.Cover\n")

    buf = []
    emit_tree(tree, buf)
    with open(os.path.join(cov, f"DenseTailTree{SUFFIX}.lean"), "w", encoding="utf-8") as f:
        f.write("/- Generated by `scripts/emit_dense_tail.py`.  Do not edit.\n\n"
                f"The branch-and-bound's own split tree, {nodes} nodes.  Each leaf\n"
                "carries the witness `u` for `g`; each split carries the coordinate and\n"
                "the cut.  `checkTree_sound` turns this shape into the covering\n"
                "argument. -/\n"
                "import SpinCodes.Numeric.BAEvalDefs\n\n"
                "set_option maxRecDepth 8000000" + chr(10) +
                "set_option maxHeartbeats 0" + chr(10) + chr(10) +
                "namespace Spin.Cover\n\nopen Spin.Numeric Spin.Numeric.Fix\n\n"
                f"def denseTree{SUFFIX} : BoxTree :=\n  " + "".join(buf) + "\n\n"
                "end Spin.Cover\n")

    with open(os.path.join(here, f"dense_tail_meta{SUFFIX}.json"), "w") as f:
        json.dump({"nodes": nodes, "logs": len(keys), "terms": TERMS,
                   "thr": str(THR), "A0": [str(x) for x in A0],
                   "B0": [str(x) for x in B0], "W0": [str(x) for x in W0]}, f)
    print("wrote Cover files with suffix", repr(SUFFIX))
