import SpinCodes.Structured.ConcreteNativeDistanceConsequencesFinal
open Spin.Structured.ConcreteNativeFamily
#print relative_distance_success_tendsto
#print axioms relative_distance_success_tendsto
#print eventually_exists_rate_half_distance_gt_eleven_percent
#print axioms eventually_exists_rate_half_distance_gt_eleven_percent
