import SpinCodes.Structured.SparseModelData
import SpinCodes.Structured.SparseValidationDefs
namespace Spin.Structured.SparsePolynomial.Data
set_option maxRecDepth 100000
set_option maxHeartbeats 0
theorem weight0_valid : checkData 0 weight0 = true := by decide
theorem weight1_valid : checkData 1 weight1 = true := by decide
theorem weight2_valid : checkData 2 weight2 = true := by decide
theorem weight3_valid : checkData 3 weight3 = true := by decide
theorem weight4_valid : checkData 4 weight4 = true := by decide
theorem weight5_valid : checkData 5 weight5 = true := by decide
theorem weight6_valid : checkData 6 weight6 = true := by decide
theorem weight7_valid : checkData 7 weight7 = true := by decide
theorem weight8_valid : checkData 8 weight8 = true := by decide
theorem weight9_valid : checkData 9 weight9 = true := by decide
theorem weight10_valid : checkData 10 weight10 = true := by decide
theorem weight11_valid : checkData 11 weight11 = true := by decide
theorem weight12_valid : checkData 12 weight12 = true := by decide
theorem weight13_valid : checkData 13 weight13 = true := by decide
theorem weight14_valid : checkData 14 weight14 = true := by decide
theorem weight15_valid : checkData 15 weight15 = true := by decide
theorem weight16_valid : checkData 16 weight16 = true := by decide
theorem weight17_valid : checkData 17 weight17 = true := by decide
theorem weight18_valid : checkData 18 weight18 = true := by decide
theorem weight19_valid : checkData 19 weight19 = true := by decide
theorem weight20_valid : checkData 20 weight20 = true := by decide
theorem weight21_valid : checkData 21 weight21 = true := by decide
theorem weight22_valid : checkData 22 weight22 = true := by decide
theorem weight23_valid : checkData 23 weight23 = true := by decide
theorem weight24_valid : checkData 24 weight24 = true := by decide
theorem weight25_valid : checkData 25 weight25 = true := by decide
theorem weight26_valid : checkData 26 weight26 = true := by decide
theorem weight27_valid : checkData 27 weight27 = true := by decide
theorem weight28_valid : checkData 28 weight28 = true := by decide
theorem weight29_valid : checkData 29 weight29 = true := by decide
theorem weight30_valid : checkData 30 weight30 = true := by decide
theorem weight31_valid : checkData 31 weight31 = true := by decide
theorem weight32_valid : checkData 32 weight32 = true := by decide
theorem weight33_valid : checkData 33 weight33 = true := by decide
theorem weight34_valid : checkData 34 weight34 = true := by decide
theorem weight35_valid : checkData 35 weight35 = true := by decide
theorem weight36_valid : checkData 36 weight36 = true := by decide
theorem weight37_valid : checkData 37 weight37 = true := by decide
theorem weight38_valid : checkData 38 weight38 = true := by decide
theorem weight39_valid : checkData 39 weight39 = true := by decide
theorem weight40_valid : checkData 40 weight40 = true := by decide
theorem weight41_valid : checkData 41 weight41 = true := by decide
theorem weight42_valid : checkData 42 weight42 = true := by decide
theorem weight43_valid : checkData 43 weight43 = true := by decide
theorem weight44_valid : checkData 44 weight44 = true := by decide
theorem weight45_valid : checkData 45 weight45 = true := by decide
theorem weight46_valid : checkData 46 weight46 = true := by decide
theorem weight47_valid : checkData 47 weight47 = true := by decide
theorem weight48_valid : checkData 48 weight48 = true := by decide
theorem weight49_valid : checkData 49 weight49 = true := by decide
theorem weight50_valid : checkData 50 weight50 = true := by decide
theorem weight51_valid : checkData 51 weight51 = true := by decide
theorem weight52_valid : checkData 52 weight52 = true := by decide
theorem weight53_valid : checkData 53 weight53 = true := by decide
theorem weight54_valid : checkData 54 weight54 = true := by decide
theorem weight55_valid : checkData 55 weight55 = true := by decide
theorem weight56_valid : checkData 56 weight56 = true := by decide
theorem weight57_valid : checkData 57 weight57 = true := by decide
theorem weight58_valid : checkData 58 weight58 = true := by decide
theorem weight59_valid : checkData 59 weight59 = true := by decide
theorem weight60_valid : checkData 60 weight60 = true := by decide
theorem weight61_valid : checkData 61 weight61 = true := by decide
theorem weight62_valid : checkData 62 weight62 = true := by decide
theorem weight63_valid : checkData 63 weight63 = true := by decide
theorem weight64_valid : checkData 64 weight64 = true := by decide
theorem weight65_valid : checkData 65 weight65 = true := by decide
theorem weight66_valid : checkData 66 weight66 = true := by decide
theorem weight67_valid : checkData 67 weight67 = true := by decide
theorem weight68_valid : checkData 68 weight68 = true := by decide
theorem weight69_valid : checkData 69 weight69 = true := by decide
theorem weight70_valid : checkData 70 weight70 = true := by decide
theorem weight71_valid : checkData 71 weight71 = true := by decide
theorem weight72_valid : checkData 72 weight72 = true := by decide
theorem weight73_valid : checkData 73 weight73 = true := by decide
theorem weight74_valid : checkData 74 weight74 = true := by decide
theorem weight75_valid : checkData 75 weight75 = true := by decide
theorem weight76_valid : checkData 76 weight76 = true := by decide
theorem weight77_valid : checkData 77 weight77 = true := by decide
theorem weight78_valid : checkData 78 weight78 = true := by decide
theorem weight79_valid : checkData 79 weight79 = true := by decide
theorem weight80_valid : checkData 80 weight80 = true := by decide
theorem weight81_valid : checkData 81 weight81 = true := by decide
theorem weight82_valid : checkData 82 weight82 = true := by decide
theorem weight83_valid : checkData 83 weight83 = true := by decide
theorem weight84_valid : checkData 84 weight84 = true := by decide
theorem weight85_valid : checkData 85 weight85 = true := by decide
theorem weight86_valid : checkData 86 weight86 = true := by decide
theorem weight87_valid : checkData 87 weight87 = true := by decide
theorem weight88_valid : checkData 88 weight88 = true := by decide
theorem weight89_valid : checkData 89 weight89 = true := by decide
theorem weight90_valid : checkData 90 weight90 = true := by decide
theorem weight91_valid : checkData 91 weight91 = true := by decide
theorem weight92_valid : checkData 92 weight92 = true := by decide
theorem weight93_valid : checkData 93 weight93 = true := by decide
theorem weight94_valid : checkData 94 weight94 = true := by decide
theorem weight95_valid : checkData 95 weight95 = true := by decide
theorem weight96_valid : checkData 96 weight96 = true := by decide
theorem weight97_valid : checkData 97 weight97 = true := by decide
theorem weight98_valid : checkData 98 weight98 = true := by decide
theorem weight99_valid : checkData 99 weight99 = true := by decide
theorem weight100_valid : checkData 100 weight100 = true := by decide
theorem weight101_valid : checkData 101 weight101 = true := by decide
theorem weight102_valid : checkData 102 weight102 = true := by decide
theorem weight103_valid : checkData 103 weight103 = true := by decide
theorem weight104_valid : checkData 104 weight104 = true := by decide
theorem weight105_valid : checkData 105 weight105 = true := by decide
theorem weight106_valid : checkData 106 weight106 = true := by decide
theorem weight107_valid : checkData 107 weight107 = true := by decide
theorem weight108_valid : checkData 108 weight108 = true := by decide
theorem weight109_valid : checkData 109 weight109 = true := by decide
theorem weight110_valid : checkData 110 weight110 = true := by decide
theorem weight111_valid : checkData 111 weight111 = true := by decide
theorem weight112_valid : checkData 112 weight112 = true := by decide
theorem weight113_valid : checkData 113 weight113 = true := by decide
theorem weight114_valid : checkData 114 weight114 = true := by decide
theorem weight115_valid : checkData 115 weight115 = true := by decide
theorem weight116_valid : checkData 116 weight116 = true := by decide
theorem weight117_valid : checkData 117 weight117 = true := by decide
theorem weight118_valid : checkData 118 weight118 = true := by decide
theorem weight119_valid : checkData 119 weight119 = true := by decide
theorem weight120_valid : checkData 120 weight120 = true := by decide
theorem weight121_valid : checkData 121 weight121 = true := by decide
theorem weight122_valid : checkData 122 weight122 = true := by decide
theorem weight123_valid : checkData 123 weight123 = true := by decide
theorem weight124_valid : checkData 124 weight124 = true := by decide
theorem weight125_valid : checkData 125 weight125 = true := by decide
theorem weight126_valid : checkData 126 weight126 = true := by decide
theorem weight127_valid : checkData 127 weight127 = true := by decide
theorem weight128_valid : checkData 128 weight128 = true := by decide
end Spin.Structured.SparsePolynomial.Data
