#!/usr/bin/env python3
"""Validate retained measurements and regenerate the paper's comparison table."""
import argparse
import hashlib
import json
import math
from pathlib import Path
from run import MODES, summarize

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
RESULTS = HERE / "results_no_reset_20260911.json"
LABELS = {
    "spin": (r"SPIN, $(128,19)$", "1/2", "(0.10,50.448)"),
    "golay": ("Chosen Golay BAA", "1/2", "(0.10,46.386)"),
    "rm": ("Chosen RM BAA", "1/2", "(0.10,47.093)"),
    "exconv": ("EC $(33,25)$", "1/2", "(0.05,20)"),
    "raa3": ("Binary RAA, repetition 3", "1/3", r"\text{--}"),
    "raa4": ("Binary RAA, repetition 4", "1/4", r"(0.19,{\approx}13)^{*}"),
}


def validate(data):
    if data.get("schema") != 2 or data.get("input_policy") != "no_reset":
        raise ValueError("expected no-reset campaign")
    if data.get("exconv_parameters") != dict(implementation="ExConvCodeOld", w=33, m=25,
                                            random_taps=24, systematic=False, convolution_passes=1):
        raise ValueError("wrong EC configuration")
    if data["status"] != "complete" or len(data["runs"]) != 54:
        raise ValueError("expected all 54 serial processes")
    seen = set()
    for row in data["runs"]:
        key = (row["mode"], row["m"], row["run"])
        if key in seen or key[0] not in MODES or key[1] not in (16, 18, 20) or key[2] not in (0, 1, 2):
            raise ValueError("duplicate or unexpected cell")
        seen.add(key)
        if row.get("input_policy") != "no_reset":
            raise ValueError("row uses wrong input policy")
        samples = row["samples_ms"]
        if len(samples) != 101 or not all(math.isfinite(x) and x > 0 for x in samples):
            raise ValueError("invalid timing samples")
        k = 1 << row["m"]
        n = k * ({"raa3": 3, "raa4": 4}.get(row["mode"], 2))
        if row["mode"] in ("golay", "rm"):
            n = (2 * k // 192) * 192
            k = n // 2
        if (row["n"], row["k"], row["warmups"], row["cpu"]) != (n, k, 3, 15):
            raise ValueError("workload or protocol mismatch")
    if summarize(data["runs"]) != data["summary"]:
        raise ValueError("summary disagrees with raw measurements")
    for name, expected in data["source_sha256"].items():
        actual = hashlib.sha256((ROOT / name).read_bytes()).hexdigest()
        if actual != expected:
            raise ValueError(f"measured source changed: {name}")


def table(data):
    rows = {(r["mode"], r["m"]): r for r in data["summary"]}
    lines = ["% Generated by workstreams/transposed_comparison/report.py; do not edit.",
             r"\begin{tabular}{@{}lccrrr@{}}", r"\toprule",
             r"Encoder & Rate & $(\delta,\lambda)$ & $K\approx2^{16}$ & $K\approx2^{18}$ & $K\approx2^{20}$ \\",
             r"\midrule"]
    for mode in MODES:
        label, rate, guarantee = LABELS[mode]
        vals = " & ".join(f"{rows[mode, m]['median_ms']:.3f}" for m in (16, 18, 20))
        lines.append(f"{label} & ${rate}$ & ${guarantee}$ & {vals}" + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--check", action="store_true")
    args = p.parse_args()
    data = json.loads(RESULTS.read_text())
    validate(data)
    target = ROOT / "paper/figures/transposed_comparison.tex"
    content = table(data)
    if args.check:
        if target.read_text() != content:
            raise ValueError("paper comparison table is stale")
    else:
        target.write_text(content, encoding="utf-8")
    print("COMPARISON CHECK PASSED: 54 serial runs, 5454 samples, 18 table cells")


if __name__ == "__main__":
    main()
