# Optional upstream imports are kept out of the default transpose build.
if(SPIN_FORWARD_EXPANSION AND (NOT SPIN_BIDIRECTIONAL_SOURCE OR SPIN_BUILD_WIDE))
  message(FATAL_ERROR "Forward expansion experiment requires bidirectional source and excludes wide lifting")
endif()
if(SPIN_INNER_PROBE AND (NOT SPIN_BIDIRECTIONAL_SOURCE OR NOT SPIN_BCH_AVX512))
  message(FATAL_ERROR "SPIN_INNER_PROBE requires the bidirectional source and AVX-512 build")
endif()
if(NOT SPIN_FORWARD_SCHEDULE STREQUAL "global" AND NOT SPIN_FORWARD_FOUR)
  message(FATAL_ERROR "SPIN_FORWARD_SCHEDULE requires SPIN_FORWARD_FOUR")
endif()
if(SPIN_FORWARD_DIRECT AND (NOT SPIN_FORWARD_FOUR OR NOT SPIN_BIDIRECTIONAL_SOURCE))
  message(FATAL_ERROR "SPIN_FORWARD_DIRECT requires SPIN_FORWARD_FOUR and SPIN_BIDIRECTIONAL_SOURCE")
endif()
if(SPIN_FORWARD_DIRECT AND (SPIN_FORWARD_PROFILE OR NOT SPIN_FORWARD_PREFETCH STREQUAL "0"))
  message(FATAL_ERROR "Direct forward currently excludes the tiled profiler and prefetch experiment")
endif()
if((SPIN_BUILD_WIDE OR SPIN_FORWARD_FOUR OR SPIN_FORWARD_PROFILE OR NOT SPIN_FORWARD_PREFETCH STREQUAL "0") AND NOT SPIN_BIDIRECTIONAL_SOURCE)
  message(FATAL_ERROR "Forward/wide options require SPIN_BIDIRECTIONAL_SOURCE")
endif()
if(SPIN_BIDIRECTIONAL_SOURCE)
  set(BID "${CMAKE_CURRENT_BINARY_DIR}/bidirectional")
  file(GLOB_RECURSE BID_INPUT CONFIGURE_DEPENDS "${SPIN_BIDIRECTIONAL_SOURCE}/*.h" "${SPIN_BIDIRECTIONAL_SOURCE}/*.cpp")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${BID_INPUT} "${CMAKE_CURRENT_SOURCE_DIR}/bidirectional.py")
  execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/bidirectional.py"
    "${SPIN_BIDIRECTIONAL_SOURCE}" "${GEN}" "${BID}" COMMAND_ERROR_IS_FATAL ANY)
  if(NOT SMALL_MODE STREQUAL "0")
    execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/small.py" "${BID}" "${SMALL_MODE}" COMMAND_ERROR_IS_FATAL ANY)
  endif()
  execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/k16.py" "${BID}" COMMAND_ERROR_IS_FATAL ANY)
  execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/k16_r2.py" "${BID}" COMMAND_ERROR_IS_FATAL ANY)
  if(SPIN_FORWARD_EXPANSION)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/forward_expansion.py"
      "${ROOT}/scripts/probe_bch_forward_xor_circuit.py")
    execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/forward_expansion.py" "${BID}" COMMAND_ERROR_IS_FATAL ANY)
  endif()
  if(NOT K18_MODE STREQUAL "0")
    execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/k18.py" "${BID}" "${K18_MODE}" COMMAND_ERROR_IS_FATAL ANY)
  endif()
  add_library(spin_half_bidirectional STATIC "${BID}/Spin.cpp" "${BID}/generated/BchCircuit.cpp" "${BID}/generated/BchForward.cpp")
  target_compile_definitions(spin_half_bidirectional PUBLIC SPIN_GENERAL_LENGTHS=1)
  if(SPIN_K20_EXPERIMENT MATCHES "^[567]$")
    execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/k20_tiled.py" "${BID}" "${SPIN_K20_EXPERIMENT}" COMMAND_ERROR_IS_FATAL ANY)
  elseif(NOT SPIN_K20_EXPERIMENT STREQUAL "0")
    execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/k18.py" "${BID}" "${SPIN_K20_EXPERIMENT}" 20 COMMAND_ERROR_IS_FATAL ANY)
  endif()
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/forward_fast.py" "${CMAKE_CURRENT_SOURCE_DIR}/forward_profile.py"
    "${CMAKE_CURRENT_SOURCE_DIR}/ForwardProfile.h")
  if(SPIN_FORWARD_FOUR)
    execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/forward_fast.py" "${BID}" COMMAND_ERROR_IS_FATAL ANY)
    if(NOT SPIN_FORWARD_SCHEDULE STREQUAL "global")
      set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/forward_schedule.py")
      execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/forward_schedule.py"
        "${BID}" "${SPIN_FORWARD_SCHEDULE}" COMMAND_ERROR_IS_FATAL ANY)
    endif()
  endif()
  if(SPIN_FORWARD_DIRECT)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/forward_direct.py")
    execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/forward_direct.py" "${BID}" COMMAND_ERROR_IS_FATAL ANY)
  endif()
  if(SPIN_FORWARD_PROFILE)
    execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/forward_profile.py" "${BID}" COMMAND_ERROR_IS_FATAL ANY)
  endif()
  target_include_directories(spin_half_bidirectional PUBLIC "${BID}")
  if(SPIN_STAGE_PROFILE)
    execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/stage_profile.py" "${BID}" COMMAND_ERROR_IS_FATAL ANY)
  endif()
  target_link_libraries(spin_half_bidirectional PUBLIC spin_baseline)
  target_compile_definitions(spin_half_bidirectional PRIVATE SPIN_GROUPED_A=1 SPIN_WORKSPACE_ROUTING_OPT=1
    SPIN_BCH_AVX512=$<BOOL:${SPIN_BCH_AVX512}> SPIN_TEST_NO_AVX512=$<BOOL:${SPIN_TEST_NO_AVX512}>)
  if(SPIN_BCH_AVX512)
    add_library(spin_bidir512 OBJECT "${BID}/Fast.cpp" "${BID}/generated/BchAvx512.cpp")
    if(SPIN_FORWARD_FOUR)
      target_sources(spin_bidir512 PRIVATE "${BID}/ForwardFast.cpp" "${BID}/generated/BchForward512.cpp")
    endif()
    target_include_directories(spin_bidir512 PRIVATE "${BID}")
    target_compile_options(spin_bidir512 PRIVATE -march=x86-64-v3 "-mtune=${SPIN_TUNE}" -mpclmul -mvpclmulqdq -mavx512f -mavx512vl -fno-lto)
    target_compile_definitions(spin_bidir512 PRIVATE SPIN_GROUPED_A=1)
    set_property(TARGET spin_bidir512 PROPERTY INTERPROCEDURAL_OPTIMIZATION FALSE)
    target_sources(spin_half_bidirectional PRIVATE $<TARGET_OBJECTS:spin_bidir512>)
  endif()
  set_property(TARGET spin_half_bidirectional PROPERTY INTERPROCEDURAL_OPTIMIZATION FALSE)
  if(SPIN_INNER_PROBE)
    add_library(spin_inner_probe OBJECT InnerProbe.cpp)
    target_include_directories(spin_inner_probe PRIVATE "${BID}")
    target_compile_options(spin_inner_probe PRIVATE -march=x86-64-v3 "-mtune=${SPIN_TUNE}" -mpclmul -mvpclmulqdq -mavx512f -mavx512vl -fno-lto)
    target_compile_definitions(spin_inner_probe PRIVATE SPIN_GROUPED_A=1)
    set_property(TARGET spin_inner_probe PROPERTY INTERPROCEDURAL_OPTIMIZATION FALSE)
    add_executable(spin_inner_probe_benchmark inner_probe_benchmark.cpp $<TARGET_OBJECTS:spin_inner_probe>)
    target_link_libraries(spin_inner_probe_benchmark PRIVATE spin_half_bidirectional)
    set_property(TARGET spin_inner_probe_benchmark PROPERTY INTERPROCEDURAL_OPTIMIZATION FALSE)
  endif()
  if(BUILD_TESTING)
    add_executable(spin_forward_lengths_test natural_forward_test.cpp)
    target_link_libraries(spin_forward_lengths_test PRIVATE spin_half_bidirectional)
    add_test(NAME forward_natural_lengths COMMAND spin_forward_lengths_test)
    set_tests_properties(forward_natural_lengths PROPERTIES RUN_SERIAL TRUE)
    add_executable(spin_bidirectional_test bidirectional_test.cpp)
    target_link_libraries(spin_bidirectional_test PRIVATE spin_half_bidirectional)
    add_test(NAME bidirectional COMMAND spin_bidirectional_test)
    set_tests_properties(bidirectional PROPERTIES RUN_SERIAL TRUE)
    add_executable(spin_k16_bidirectional_test k16_test.cpp)
    target_compile_definitions(spin_k16_bidirectional_test PRIVATE SPIN_K16_BIDIRECTIONAL=1)
    target_link_libraries(spin_k16_bidirectional_test PRIVATE spin_half_bidirectional)
    add_test(NAME k16_bidirectional COMMAND spin_k16_bidirectional_test)
    set_tests_properties(k16_bidirectional PROPERTIES RUN_SERIAL TRUE)
  endif()
  if(SPIN_BUILD_BENCHMARK)
    add_executable(spin_single_benchmark single_benchmark.cpp)
    target_link_libraries(spin_single_benchmark PRIVATE spin_half_bidirectional)
    add_executable(spin_single_transpose_benchmark single_benchmark.cpp)
    target_compile_definitions(spin_single_transpose_benchmark PRIVATE SPIN_SINGLE_TRANSPOSE=1)
    target_link_libraries(spin_single_transpose_benchmark PRIVATE spin_half_transpose)
    add_executable(spin_bidirectional_benchmark benchmark.cpp)
    target_compile_definitions(spin_bidirectional_benchmark PRIVATE SPIN_BIDIRECTIONAL_BENCH=1)
    target_link_libraries(spin_bidirectional_benchmark PRIVATE spin_half_bidirectional)
  endif()
endif()
include("${CMAKE_CURRENT_SOURCE_DIR}/wide.cmake")
if(SPIN_BIDIRECTIONAL_SOURCE AND NOT SPIN_FORWARD_PREFETCH STREQUAL "0")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/forward_prefetch.py")
  execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/forward_prefetch.py"
    "${BID}" "${SPIN_FORWARD_PREFETCH}" COMMAND_ERROR_IS_FATAL ANY)
endif()
if(SPIN_BIDIRECTIONAL_SOURCE)
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${CMAKE_CURRENT_SOURCE_DIR}/forward_lengths.py" "${CMAKE_CURRENT_SOURCE_DIR}/LengthGeometry.h")
  execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/forward_lengths.py"
    "${BID}" COMMAND_ERROR_IS_FATAL ANY)
endif()
