"""Combine authenticated IMT timing with the retained external comparison.

The two serial measurement campaigns share host and protocol, not run dates.
The old report.py and its measurement data remain unchanged.
"""
import argparse
import hashlib
import subprocess
import sys
from pathlib import Path
import imt_results

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'workstreams/transposed_comparison'))
import report as historical


def validate_external(data):
    # Shared SPIN files changed after this campaign: check their measured bytes
    # from a known commit, without substituting current implementation bytes.
    revision = 'aafb3f59e7c3541e19b8623520c8a407ee2219e8'
    archived = {'workstreams/bare_bch_rm2sub/Spin.h',
                'workstreams/bare_bch_rm2sub/Spin.cpp'}
    for name, expected in data['source_sha256'].items():
        path = (ROOT / name).resolve()
        imt_results.require(path.is_relative_to(ROOT), 'External source escapes repository')
        raw = path.read_bytes()
        if hashlib.sha256(raw).hexdigest() != expected and name in archived:
            raw = subprocess.check_output(['git', 'show', f'{revision}:{name}'], cwd=ROOT)
        imt_results.require(hashlib.sha256(raw).hexdigest() == expected,
                            f'External measured source changed: {name}')
    # All source entries were checked above. Reuse the unchanged protocol,
    # raw-sample, and summary validation without rereading current source bytes.
    historical.validate({**data, 'source_sha256': {}})


def table(evidence=None):
    raw = historical.RESULTS.read_bytes()
    imt_results.require(hashlib.sha256(raw).hexdigest() ==
                        '1cf216448cf9faeb04aa73d526e23d1737426b02cfe84ff69a534c4d564b523a',
                        'External measurement receipt changed')
    data = historical.json.loads(raw)
    validate_external(data)
    evidence = evidence or imt_results.load()
    timings = {r['message_exponent']: r['summaries']['sparse_pages']['median_ms']
               for r in evidence['timing']['cells']}
    rows = {(r['mode'], r['m']): r for r in data['summary']}
    lines = ['% Generated by paper/build_imt_comparison.py; do not edit.',
             r'\begin{tabular}{@{}lccrrr@{}}', r'\toprule',
             r'Encoder & Rate & $(\delta,\lambda)$ & $K\approx2^{16}$ & $K\approx2^{18}$ & $K\approx2^{20}$ \\',
             r'\midrule']
    for mode in historical.MODES:
        label, rate, guarantee = historical.LABELS[mode]
        if mode == 'spin':
            label = 'SPIN, IMT $(128,19)$'
            guarantee = f"(0.10,{evidence['half'][20]['margin_bits']:.3f})"
            values = [timings[m] for m in (16, 18, 20)]
        else:
            values = [rows[mode, m]['median_ms'] for m in (16, 18, 20)]
        lines.append(f'{label} & ${rate}$ & ${guarantee}$ & ' +
                     ' & '.join(f'{v:.3f}' for v in values) + r' \\')
        if mode == 'spin':
            # Separate author-confirmed Ryzen measurement; no archived raw
            # samples or smaller-length timings. See APPLICATION_RESULTS.md.
            lines.append(r'Original BAA & $1/2$ & $\text{--}$ & -- & -- & ${\approx}32^{\dagger}$ \\')
    return '\n'.join(lines + [r'\bottomrule', r'\end{tabular}', ''])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    content = table()
    target = ROOT / 'paper/figures/transposed_comparison.tex'
    if args.check:
        imt_results.require(target.read_text() == content, 'Comparison table is stale')
    else:
        target.write_text(content, encoding='utf-8', newline='\n')
    print('IMT comparison PASS: 3 replacement cells; archived external measurements unchanged; separate approximate original-BAA reference included.')


if __name__ == '__main__':
    main()
