"""Reproduce IMT Q1 slices and a matched Q1/full certificate comparison.

Authenticates retained inputs, not a new numerical replay. Historical figure
producers and their outputs are left unchanged. No third-party dependencies.
"""
import argparse
import math
from pathlib import Path

import imt_results as evidence
import build_imt_length_figure as length_figure

ROOT = evidence.ROOT
OUT = ROOT / 'paper/figures'
GRID_PIN = ('finite_migration/PARAMETER_NO_CONSTANT_Q1_v1.json',
            '1a48a6f4d5a4c6c1449f35cd7e5584b7a14d4a08f8effc2c4508497e8ef20058')
REPLAY_PIN = ('finite_migration/PARAMETER_NO_CONSTANT_Q1_VERIFIED_v1.json',
              '6a65f58ed3cdc14ebaa124edf031a32636b47b10a64e7a0fcf3d339ead2173d8')
require = evidence.require
COLORS = ('blue!70!black', 'orange!85!black', 'purple!80!black')


def validate_grid(grid, replay):
    require(grid['status'] == 'BINARY64_IMT_PARAMETER_Q1_ONLY', 'Wrong Q1 study')
    require(replay['status'] == 'VERIFIED_BINARY64_IMT_Q1_GRID', 'Wrong Q1 replay')
    require(replay['producer_sha256'] == GRID_PIN[1], 'Replay binds a different grid')
    require(grid['geometry_complete'] and not grid['full_distance_proved']
            and not replay['full_distance_proved'], 'Wrong Q1 evidence scope')
    require((replay['geometries_checked'], replay['exact_maps_reconstructed'],
             replay['log_domain_cells_checked']) == (130, 39, 7), 'Incomplete Q1 replay')
    require(0 <= replay['largest_log_domain_difference_bits'] < 1e-10,
            'Q1 log-domain disagreement')
    expected = {(b, 64, 20, m) for b in (64, 128) for m in range(12, 27)}
    expected |= {(b, t, s, 20) for b in (64, 128) for t in (64, 128, 256)
                 for s in range(t.bit_length(), 21)}
    expected |= {(b, 64, s, m) for b in (64, 128) for s in (10, 12, 16)
                 for m in (16, 18, 20, 22, 24)}
    rows = {}
    for row in grid['rows']:
        key = row['b'], row['t'], row['s'], row['exponent']
        require(key not in rows, 'Duplicate Q1 geometry')
        b, t, s, m = key
        require(not row['full_distance_proved'] and row['full_margin_bits'] is None,
                'Full-bound claim in Q1 grid')
        require(row['outer_rows'] == 2**(m+1)//b and row['bad_weight'] == 2**(m+1)//10,
                'Wrong Q1 cutoff or rate')
        require(math.isfinite(row['q1_margin_bits']), 'Non-finite Q1 value')
        rows[key] = row['q1_margin_bits']
    require(set(rows) == expected, 'Missing or extra Q1 geometries')
    require(set(grid['maps']) == {f't{t}_s{s}' for _, t, s, _ in expected},
            'Wrong Q1 map coverage')
    for name, record in grid['maps'].items():
        t, s = record['t'], record['s']
        require(name == f't{t}_s{s}' and record['transvection_rounds'] == 1,
                'Wrong IMT map identity')
        require(sum(record['spectrum'].values()) == 2**s-1
                and all(0 < int(w) < t for w in record['spectrum']),
                'Expansion is not injective and constant-free')
        for field in ('expansion_columns', 'feedback_columns'):
            columns = record[field]
            require(len(columns) == t and all(0 < v < 2**s for v in columns),
                    'Invalid map columns')
            largest = grid['maps'][f't{t}_s20'][field]
            require(columns == [v & (2**s-1) for v in largest], 'Non-nested maps')
    return rows


def load_grid():
    seen = {}
    grid = evidence.authenticate(GRID_PIN, seen)
    replay = evidence.authenticate(REPLAY_PIN, seen)
    return validate_grid(grid, replay)


def plot(points, style):
    coordinates = ' '.join(f'({x},{y:.10f})' for x, y in points)
    return f'\\addplot[{style}] coordinates {{{coordinates}}};\n'


def panel(options, body, width=r'.485\linewidth'):
    return (f'\\begin{{minipage}}[t]{{{width}}}\n\\centering\n'
            '\\begin{tikzpicture}\n\\begin{axis}['
            r'tick label style={font=\footnotesize},label style={font=\small},'
            r'title style={font=\small},grid=major,grid style={black!10},'
            r'legend style={font=\footnotesize,draw=none},' + options + ']\n'
            + body + '\\end{axis}\n\\end{tikzpicture}\n\\end{minipage}\n')


def figure(body, caption, label, placement='tb'):
    return ('% Generated by paper/build_imt_parameter_figures.py; do not hand edit.\n'
            f'% Q1 grid SHA-256: {GRID_PIN[1]}\n'
            '\\begin{figure}[' + placement + ']\n\\centering\n' + body
            + '\\caption{' + caption + '}\n\\label{' + label + '}\n\\end{figure}\n')


def figures(rows, data):
    outputs = {'imt_parameter_k_b.tex': length_figure.render(length_figure.load(data))}
    panels = []
    for b in (64, 128):
        body = ''
        for t, color, mark in zip((64, 128, 256), COLORS, ('*', 'square*', 'triangle*')):
            body += plot([(s, rows[b, t, s, 20]) for s in range(t.bit_length(), 21)],
                         f'{color},thick,mark={mark},mark size=1.5pt')
            body += f'\\addlegendentry{{$t={t}$}}\n'
        panels.append(panel(r'width=\linewidth,height=5.5cm,title={BCH-' + str(b) + r'},'
            r'xlabel={State bits $s$},ylabel={Q1 margin (bits)},xmin=6.5,xmax=20.5,'
            r'ymin=0,ymax=40,xtick={8,12,16,20},legend pos='
            + ('north east,' if b == 64 else 'south east,'), body))
    outputs['imt_parameter_s_t.tex'] = figure('\\hfill\n'.join(panels),
        r'IMT state and step size at $K=2^{20}$. Each $t$ uses its own nested'
        '\nmap chain. More state gives diminishing Q1 gains; the step-size curves'
        '\nnearly coincide at shared states.',
        'fig:finite-s-t')
    panels = []
    for b in (64, 128):
        body = ''
        for m, color in zip((16, 20, 24), COLORS):
            body += plot([(s, rows[b, 64, s, m]) for s in (10, 12, 16, 20)],
                         color + ',thick,mark=*,mark size=1.5pt')
            body += f'\\addlegendentry{{$\\log_2 K={m}$}}\n'
        panels.append(panel(r'width=\linewidth,height=5.5cm,title={BCH-' + str(b) + r'},'
            r'xlabel={State bits $s$},ylabel={Q1 margin (bits)},xmin=9.5,xmax=20.5,'
            r'ymin=0,ymax=40,xtick={10,12,16,20},legend pos='
            + ('north east,' if b == 64 else 'south east,'), body))
    outputs['imt_parameter_k_s.tex'] = figure('\\hfill\n'.join(panels),
        r'IMT state slices at three message lengths, with $t=64$ fixed.'
        '\nOnly the four marked states are compared at every length. Increasing'
        '\nmessage length lowers the Q1 plateau; increasing state gives diminishing gains.',
        'fig:finite-k-s')
    body = plot([(m, r['margin_bits']) for m, r in data['half'].items()],
                'blue!70!black,thick,mark=*,mark size=2pt')
    body += '\\addlegendentry{Full certificate}\n'
    body += plot([(m, r['component_margin_bits'][0]) for m, r in data['half'].items()],
                 'orange!85!black,dashed,mark=o,mark size=2.5pt')
    body += '\\addlegendentry{Q1 component}\n'
    body += plot([(16, 40), (24, 40)], 'black,dotted')
    body += '\\addlegendentry{40-bit target}\n'
    outputs['imt_certified_curve.tex'] = figure(panel(
        r'width=.92\linewidth,height=5.7cm,xlabel={$\log_2 K$},ylabel={Margin (bits)},'
        r'xmin=15.6,xmax=24.4,ymin=38,ymax=56,xtick={16,18,20,22,24},'
        r'ytick={40,44,48,52,56},legend style={at={(.5,.98)},anchor=north,legend columns=3},',
        body, r'\linewidth'),
        r'Matched Q1 components and complete outward bounds for the selected'
        '\nBCH-256, IMT $(128,19)$ construction. Both curves use exactly the same'
        '\nmaps and setup distribution. The four larger-length pairs nearly coincide.'
        '\nConnecting segments do not certify intermediate lengths.', 'fig:finite-bch-curve')
    return outputs


def check(data=None):
    outputs = figures(load_grid(), evidence.load() if data is None else data)
    for name, contents in outputs.items():
        require((OUT / name).read_text(encoding='utf-8') == contents, f'Stale IMT figure: {name}')
    return dict(q1_geometries=130, adaptive_length_cells=110, matched_full_anchors=5, figures=4,
                full_grid_certified=False, numerical_replay=False)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    if args.check:
        print(check())
    else:
        for name, contents in figures(load_grid(), evidence.load()).items():
            (OUT / name).write_text(contents, encoding='utf-8', newline='\n')
        print('Generated adaptive-length and state Q1 slices plus five Q1/full anchors; no new proof replay.')


if __name__ == '__main__':
    main()
