"""Fresh whole-code replay for the fixed disjoint-pair t64/s16 RS16 code.

The setup uses independent uniform-nonzero-image linear symbol and state
maps, independent within-group packet permutations, and independent regional
permutations. There are 512 groups, 128 message bits per group, 64 four-bit
regions, 32 physical t64 steps per region, and no state reset or final flush.
The fixed expansion and feedback are regenerated by disjoint_pair_maps.
No numerical receipt is read. Tilts below are rational selection hints.
Every occupancy is freshly evaluated at 256-bit outward precision. The
positive dyadic endpoints are summed exactly before one upward rounding.
"""
from __future__ import annotations

import argparse
from fractions import Fraction as Q
import hashlib
import json
from math import comb
from pathlib import Path
import sys
from time import monotonic

import disjoint_pair_maps as maps
import screen_t128 as screen
from flint import arb, ctx
import packet_rs_length_whole as exact_sum

HERE=Path(__file__).resolve().parent
PRECISION=256
Q1_TILTS=('.00256','.00512','.01024')
Q2_TILTS=('.00512','.01024')
TAIL_RECIPES=(
    (3,128,('.01024','.0256','.0512','.0768','.1024','.12','.14','.16','.18','.20','.24','.28','.32','.40','.50')),
    (129,512,('.40','.50','.64','.80','1.0','1.2288','1.6384','2.1972246')),
)


def sources():
    result=screen.q1.source_snapshot()
    for module in tuple(sys.modules.values()):
        filename=getattr(module,'__file__',None)
        if filename:
            path=Path(filename).resolve()
            if path.parent==HERE and path.suffix=='.py':
                result[str(path)]=hashlib.sha256(path.read_bytes()).hexdigest()
    path=Path(__file__).resolve()
    result[str(path)]=hashlib.sha256(path.read_bytes()).hexdigest()
    return result


def margin(value):
    return str(-value.log()/arb(2).log())


def reproduce(output):
    output=Path(output).resolve()
    if output.exists():
        raise FileExistsError('fresh output required')
    ctx.prec=PRECISION
    start=monotonic()
    data,map_record=maps.prepare()
    beta,counts=screen.tail.uniform_envelope(16,8,4)
    pins=sources()
    values,choices={},{}
    record=dict(schema='k16-disjoint-pair-complete-replay-1',K=65536,N=131072,
        threshold=13107,distance='1/10',target_margin_bits=40,target_minimum_distance=13108,
        outer='four parallel GF16 RS[16,8] rows',group_count=512,group_dimension=128,
        regions=64,packet_bits=4,physical_t=64,state_bits=16,physical_steps=2048,
        physical_steps_per_region=32,macro_steps_per_region=16,zero_initial_state=True,
        final_flush=False,state_continuity='retained_between_every_step_and_region',
        randomizer_law='independently sampled invertible linear maps sending each fixed nonzero input uniformly to all nonzero vectors',
        routing_law='independent uniform within-group packet and regional slot permutations',
        map_record=map_record,source_sha256=pins,precision=PRECISION,
        q1_tilts=Q1_TILTS,q2_tilts=Q2_TILTS,tail_recipes=TAIL_RECIPES,
        fresh_replay=True,whole_code_certificate=False,all_occupancies_covered=False,
        beta=str(beta),exact_expected_outer_shells=True,
        scope='Whole-code first-moment bound over the stated ideal independent setup ensemble. No deterministic-seed or implementation timing guarantee.')

    def checkpoint():
        if pins!=sources() or ctx.prec!=PRECISION:
            raise ArithmeticError('source identity or outward precision changed')
        if any(not x.is_finite() or not x>0 for x in values.values()):
            raise ArithmeticError('positive finite outward endpoints required')
        record.update(occupancy_uppers={str(q):screen.q1.endpoint(x) for q,x in values.items()},
            occupancy_margin_bits={str(q):margin(x) for q,x in values.items()},
            tail_choices=choices,elapsed_seconds=monotonic()-start)
        output.write_text(json.dumps(record,indent=2)+'\n')

    one_best=[arb(1)]*65
    for tilt in Q1_TILTS:
        local=screen.q1.kernel_t64.local_operators(data,Q(tilt),Q(1,2))
        regional=screen.q1.placement(local,epochs=16,windows=32,rounding=screen.q1.rounded,maximum_groups=1)
        factor=(screen.aq(Q(tilt))*13107).exp()
        moments=screen.q1.support_moments(regional[0],regional[1],64)
        one_best=[min(old,screen.up(factor*m)) for old,m in zip(one_best,moments)]
    values[1]=screen.up(512*sum((screen.aq(c)*m for c,m in zip(counts,one_best)),arb(0)))
    record['q1_support_probability_uppers']=[screen.q1.endpoint(x) for x in one_best]
    checkpoint()
    print(f'Fresh q1={margin(values[1])}',flush=True)

    two_best=[[arb(1)]*(v+1) for v in range(65)]
    for tilt in Q2_TILTS:
        local=screen.q1.kernel_t64.local_operators(data,Q(tilt),Q(1,2))
        regional=screen.q1.placement(local,epochs=16,windows=32,rounding=screen.q1.rounded,maximum_groups=2)
        factor=(screen.aq(Q(tilt))*13107).exp()
        moments=screen.q2.pair_support_moments(regional,64)
        for v,column in enumerate(moments):
            for u,m in enumerate(column):
                two_best[v][u]=min(two_best[v][u],screen.up(factor*m))
    values[2]=screen.q2.fold_shell_pairs(counts,two_best,512)
    checkpoint()
    print(f'Fresh q2={margin(values[2])}',flush=True)

    for first,last,tilts in TAIL_RECIPES:
        for tilt in tilts:
            local=screen.q1.kernel_t64.local_operators(data,Q(tilt),Q(1,2))
            regional=screen.q1.placement(local,epochs=16,windows=32,rounding=screen.q1.rounded,maximum_groups=last)
            factor=(screen.aq(Q(tilt))*13107).exp()
            for q in range(first,last+1):
                matrix=screen.tail.regional_uniform(regional,q)**64
                moment=sum((matrix[0,j] for j in range(matrix.ncols())),arb(0))
                candidate=screen.up(comb(512,q)*screen.aq(beta)**q*factor*moment)
                if q not in values or candidate<values[q]:
                    values[q],choices[str(q)]=candidate,tilt
            checkpoint()
            worst=min(range(first,last+1),key=lambda q:float(-values[q].log()/arb(2).log()))
            print(f'Fresh q={first}..{last} tilt={tilt}, worst q={worst}: {margin(values[worst])}',flush=True)
    if set(values)!=set(range(1,513)):
        raise ArithmeticError('incomplete occupancy coverage')
    endpoints={q:screen.q1.endpoint(x) for q,x in values.items()}
    union_exact=exact_sum.dyadic_sum(endpoints.values())
    union=exact_sum.rounded_endpoint(union_exact,PRECISION)
    union_value=arb(union[0])*arb(2)**union[1]
    passed=exact_sum.dyadic_less(exact_sum.dyadic(union),(1,-40))
    record.update(all_occupancies_covered=True,occupancy_covered=[1,512],
        union_exact_mantissa_hex=hex(union_exact[0]),union_exact_exponent=union_exact[1],
        union_upper=union,margin_bits=margin(union_value),
        arithmetic='Exact positive dyadic sum followed by one upward rounding; target comparison uses exact integers.',
        target_met=passed,whole_code_certificate=passed)
    checkpoint()
    print(f'Complete fresh union: {record["margin_bits"]}; target_met={passed}',flush=True)
    if not passed:
        raise ArithmeticError('all occupancies computed but requested bound not met')
    return record


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output',type=Path,required=True)
    args=parser.parse_args()
    reproduce(args.output)
