"""Transpose the retained outer schedule and reuse its unrolled inner schedule.

Generated sources preserve the production transpose implementation.
"""
from pathlib import Path
import re, sys, tempfile
root=Path(__file__).resolve().parents[1]
check='--check' in sys.argv
temporary=tempfile.TemporaryDirectory() if check else None
dest=Path(temporary.name) if check else root/'src/packet'
outer=(root/'src/packet/PacketOuterFast.cpp').read_text()
inner=(root/'src/packet/PacketRsInner.h').read_text()
fast=(root/'src/packet/PacketFast.cpp').read_text()
def indices(s,name):
 return [b for x in re.search(r'const auto '+name+r'=_mm512_setr_epi64\((.*?)\);',s).group(1).split(',') for b in int(x.removesuffix('ULL'),16).to_bytes(8,'little')]
def inverse(a,b):
 joined=a+b;assert sorted(joined)==list(range(128))
 return [[joined.index(i) for i in range(start,start+64)] for start in (0,64)]
def constant(a):
 return '_mm512_setr_epi64('+','.join('0x'+int.from_bytes(bytes(a[i:i+8]),'little').to_bytes(8,'big').hex()+'ULL' for i in range(0,64,8))+')'
def perm(a,b,idx):return f'_mm512_permutex2var_epi8({a},{constant(idx)},{b})'
def transpose(m):
 return sum(((m>>(8*(7-i)+j))&1)<<(8*(7-j)+i) for i in range(8) for j in range(8))
# Invert the exact byte permutations and bit-transposes of the retained outer.
p=outer[outer.index('static SPIN_FORCEINLINE void packHalf'):outer.index('static SPIN_FORCEINLINE void mixSymbol')]
a,b=inverse(indices(p,'i0'),indices(p,'i1'));c,d=inverse(indices(p,'i2'),indices(p,'i3'))
code=['// Generated by tools/generate_packet_forward.py.\n#include "PacketForward.h"\nnamespace spin::detail::packet { namespace {\n']
code+=['static SPIN_FORCEINLINE void unpackHalf(const __m512i* v,Block* out,const std::uint32_t* route) {\nconst auto basis=_mm512_set1_epi64(0x0102040810204080ULL);\n']
for j in range(4):code += [f'const auto z{j}=_mm512_gf2p8affine_epi64_epi8(basis,v[{j}],0);\n']
for name,l,r,idx in [('a0','z0','z1',c),('a2','z0','z1',d),('a1','z2','z3',c),('a3','z2','z3',d)]:code += [f'const auto {name}={perm(l,r,idx)};\n']
for off,l,r,idx in [(0,'a0','a1',a),(4,'a0','a1',b),(8,'a2','a3',a),(12,'a2','a3',b)]:code += [f'_mm512_stream_si512(reinterpret_cast<__m512i*>(out+route[{off//4}]),{perm(l,r,idx)});\n']
code+=['}\n']
p=outer[outer.index('static SPIN_FORCEINLINE void storePairSymbol('):outer.index('template<unsigned Plane>')]
a,b=inverse(indices(p,'index0'),indices(p,'index1'))
# Reverse bytes within each GFNI matrix before the self-inverse bit transpose.
a=[a[i^7] for i in range(64)];b=[b[i^7] for i in range(64)]
code+=['template<unsigned S,unsigned P> static SPIN_FORCEINLINE void packMessage(const Block* in,__m512i* out) {\nconst auto x=_mm512_loadu_si512(in+32*P+4*S);const auto y=_mm512_loadu_si512(in+32*(P+1)+4*S);\nconst auto basis=_mm512_set1_epi64(0x0102040810204080ULL);\n']
code += [f'out[4*S+P]=_mm512_gf2p8affine_epi64_epi8(basis,{perm("x","y",a)},0);\nout[4*S+P+1]=_mm512_gf2p8affine_epi64_epi8(basis,{perm("x","y",b)},0);\n}}\n']
p=outer[outer.index('x0=_mm512_xor_si512(x0,x1);'):outer.index('return {{')]
pre,rest=p.split('auto y0=x0;');mid,post=rest.split('y0=_mm512_xor_si512(y0,y1);');post='y0=_mm512_xor_si512(y0,y1);'+post
code+=['template<unsigned P> static SPIN_FORCEINLINE void parityForward(__m512i* packed) {\n']
for i in range(8):code += [f'auto y{i}=packed[4*{i}+P];\n']
for i,j in reversed(re.findall(r'y(\d)=_mm512_xor_si512\(y\d,y(\d)\);',post)):code += [f'y{j}=_mm512_xor_si512(y{j},y{i});\n']
for i in range(8):code += [f'auto x{i}=y{i};\n']
for i,j,m in re.findall(r'y(\d)=_mm512_xor_si512\(y\d,_mm512_gf2p8affine_epi64_epi8\(x(\d),m(\d+),0\)\);',mid):
 mval=int(re.search(r'const auto m'+m+r'=_mm512_set1_epi64\(0x([0-9a-f]+)ULL\);',outer).group(1),16)
 code += [f'x{j}=_mm512_xor_si512(x{j},_mm512_gf2p8affine_epi64_epi8(y{i},_mm512_set1_epi64(0x{transpose(mval):016x}ULL),0));\n']
for i,j in reversed(re.findall(r'x(\d)=_mm512_xor_si512\(x\d,x(\d)\);',pre)):code += [f'x{j}=_mm512_xor_si512(x{j},x{i});\n']
for i in range(8):code += [f'packed[32+4*{i}+P]=x{i};\n']
code += ['}\nstruct Pair {__m512i lo,hi;};\nstatic SPIN_FORCEINLINE Pair adjoint2(__m512i a,__m512i b,const std::uint64_t* c) {\nconst auto p=_mm512_gf2p8affine_epi64_epi8(_mm512_xor_si512(a,b),_mm512_set1_epi64(c[0]),0);\nconst auto q=_mm512_gf2p8affine_epi64_epi8(a,_mm512_set1_epi64(c[1]),0);\nconst auto r=_mm512_gf2p8affine_epi64_epi8(b,_mm512_set1_epi64(c[2]),0);\nreturn {_mm512_xor_si512(p,r),_mm512_xor_si512(q,r)};\n}\nstatic SPIN_FORCEINLINE void adjoint4(__m512i& a,__m512i& b,__m512i& c,__m512i& d,const std::uint64_t* coeff) {\nconst auto p=adjoint2(_mm512_xor_si512(a,c),_mm512_xor_si512(b,d),coeff);\nconst auto q=adjoint2(a,b,coeff+3);const auto r=adjoint2(c,d,coeff+6);\na=_mm512_xor_si512(p.lo,r.lo);b=_mm512_xor_si512(p.hi,r.hi);c=_mm512_xor_si512(q.lo,r.lo);d=_mm512_xor_si512(q.hi,r.hi);\n}\nstatic SPIN_NOINLINE void groupForward(const Block* in,Block* out,const std::array<std::uint64_t,9>* coeff,const std::uint32_t* route) {\nalignas(64) __m512i lo[64],hi[64];\n']
for half,name in [(0,'lo'),(128,'hi')]:
 for s in range(8):
  for p in (0,2):code += [f'packMessage<{s},{p}>(in+{half},{name});\n']
 for p in range(4):code += [f'parityForward<{p}>({name});\n']
code += ['for(unsigned s=0;s<16;++s) {\n__m512i v[8]={lo[4*s],lo[4*s+1],lo[4*s+2],lo[4*s+3],hi[4*s],hi[4*s+1],hi[4*s+2],hi[4*s+3]};\nadjoint4(v[0],v[2],v[4],v[6],coeff[s].data());adjoint4(v[1],v[3],v[5],v[7],coeff[s].data());\nunpackHalf(v,out,route+8*s);unpackHalf(v+4,out,route+8*s+4);\n}\n}\n}\nvoid forwardOuter(const Block* in,Block* out,const Plan& p,const ForwardPlan& f) {\nfor(std::size_t g=0;g<p.groups;++g)groupForward(in+256*g,out,f.outer.data()+16*g,f.inverseRoute.data()+groupStride*g/4);_mm_sfence();\n}\n}\n']
(dest/'PacketForwardOuter.cpp').write_text(''.join(code))
# Keep the fused inner schedule; only replace its input loads by routed loads.
inner=inner[inner.index('namespace spin::detail::packet::rsfast'):]
inner=inner.replace('::rsfast','::forwardfast').replace('const block* raw','const block* raw,const std::uint32_t* route')
inner=re.sub(r'_mm512_loadu_si512\(raw\+(\d+)\)',lambda m:f'_mm512_loadu_si512(raw+{int(m[1])})',inner)
inner=inner.replace('(state,extra,raw,packetBase','(state,extra,raw,route,packetBase')
common=fast[fast.index('namespace spin::detail::packet {'):fast.index('struct StreamingRoute')]
body=fast[fast.index('template<unsigned Extra,class Emit>'):fast.index('\n}\n}\nvoid reverseRoute')+2]
body=body.replace('reverseBorder','forwardBorder').replace('const BorderRow* rows,Emit& emit','const BorderRow* rows,const std::uint32_t* route,Emit& emit')
body=body.replace('for(std::size_t epoch=n/64;epoch-->0;)', 'for(std::size_t epoch=0;epoch<n/64;++epoch)')
body=body.replace('const auto* raw=input+64*epoch;const bool first=epoch+1==n/64;', 'const auto* raw=input+64*epoch;const auto* addresses=route+16*epoch;const bool first=epoch==0;')
body=body.replace('loadPackets(raw,packets,std::make_index_sequence<16>{});','for(unsigned h=0;h<16;++h)packets[h]=_mm512_loadu_si512(raw+4*h);')
body=body.replace('rsfast::','forwardfast::').replace('(words,extraWords,raw,16*epoch','(words,extraWords,raw,addresses,16*epoch')
body=body.replace('if(!epoch)break;','if(epoch+1==n/64)break;')
(dest/'PacketForwardInner.cpp').write_text('// Generated by tools/generate_packet_forward.py.\n#include "PacketForward.h"\n#include "PacketLargeInner.h"\n'+inner+'\n'+common+'struct DirectOutput {Block* output; SPIN_FORCEINLINE void operator()(std::size_t p,__m512i v) {_mm512_storeu_si512(output+4*p,v);}};\n'+body+'\n}\nvoid forwardInner(const Block* in,Block* out,const Plan& p,const ForwardPlan& f) {DirectOutput emit{out};forwardBorder<4>(in,p.n,f.updates.data(),p.route.data(),emit);_mm_sfence();}\n}\n')
# Keep a contiguous outer / gathered inner variant for cache-resident workloads.
t=(dest/'PacketForwardOuter.cpp').read_text().replace('void forwardOuter(', 'void forwardOuterGather(')
t=re.sub(r'out\+route\[(\d+)\]',lambda m:'out+'+str(4*int(m[1])),t)
t=t.replace('unpackHalf(v,out,route+8*s);unpackHalf(v+4,out,route+8*s+4);',
            'unpackHalf(v,out+32*s,route+8*s);unpackHalf(v+4,out+32*s+16,route+8*s+4);')
t=t.replace('groupForward(in+256*g,out,f.outer.data()', 'groupForward(in+256*g,out+groupStride*g,f.outer.data()')
t=t.replace('_mm512_stream_si512(reinterpret_cast<__m512i*>(', '_mm512_storeu_si512(reinterpret_cast<__m512i*>(')
(dest/'PacketForwardOuterGather.cpp').write_text(t)
baseInner=(dest/'PacketForwardInner.cpp').read_text()
t=baseInner
t=t.replace('const bool first=epoch==0;', '''const bool first=epoch==0;
        if(epoch+8<n/64) {
            for(unsigned i=0;i<16;++i) {
#ifdef _MSC_VER
                _mm_prefetch(reinterpret_cast<const char*>(input+64*(epoch+8)+4*i),_MM_HINT_T0);
#else
                __builtin_prefetch(input+64*(epoch+8)+4*i,1,3);
#endif
            }
        }''')
(dest/'PacketForwardInner.cpp').write_text(t)
t=baseInner.replace('void forwardInner(', 'void forwardInnerGather(')
t=re.sub(r'_mm512_loadu_si512\(raw\+(\d+)\)',lambda m:f'_mm512_loadu_si512(raw+route[{int(m[1])//4}])',t)
t=t.replace('const auto* raw=input+64*epoch;', 'const auto* raw=input;')
t=t.replace('raw+4*h','raw+addresses[h]')
t=t.replace('_mm512_storeu_si512(output+4*p,v);',
 '''if((reinterpret_cast<std::uintptr_t>(output)&63)==0)_mm512_stream_si512(reinterpret_cast<__m512i*>(output+4*p),v);else _mm512_storeu_si512(output+4*p,v);''')
(dest/'PacketForwardInnerGather.cpp').write_text(t)
print('Generated exact adjoint outer and fused inner variants.')

for name in ['Outer','Inner','OuterGather','InnerGather']:
 p=dest/('PacketForward'+name+'.cpp')
 p.write_text(p.read_text(), newline='\n')
if check:
 for p in dest.iterdir():
  assert p.read_bytes()==(root/"src/packet"/p.name).read_bytes(),p.name+" is stale"
 print("Production forward sources match generator.")
