"""Import the measured RS packet kernel without changing its instruction schedule.

Maintainer-only. Package builds consume the committed C++ snapshots and do not
read research files or run Python. The selected implementation is the fixed
t64/s20 reverseRouteFused followed by outerFastFusedPairNt with TowerByte32.
Small inputs use the same schedule with cached stores; large inputs retain
the streaming-store schedule. Selection happens once, outside the hot loops.
Run: python -B spin/tools/import_rs_packet.py [--check]
"""
import argparse
import hashlib
from pathlib import Path

PACKAGE = Path(__file__).resolve().parents[1]
REPO = PACKAGE.parent
SOURCE = REPO / 'research/workstreams/k16_design/implementation'
DESTINATION = PACKAGE / 'src/packet'


def definition(source, marker, semicolon=False):
    if source.count(marker) != 1:
        raise ArithmeticError(f'expected exactly one definition: {marker}')
    start = source.index(marker)
    opening = source.index('{', start)
    depth, end = 1, opening + 1
    while depth:
        depth += (source[end] == '{') - (source[end] == '}')
        end += 1
    if semicolon:
        if source[end] != ';':
            raise ArithmeticError(f'missing definition terminator: {marker}')
        end += 1
    return source[start:end]


def replace_once(source, old, new):
    if source.count(old) != 1:
        raise ArithmeticError(f'expected exactly one selected fragment: {old}')
    return source.replace(old, new)


def prelude(paths, header=False):
    lines = ['// Generated by spin/tools/import_rs_packet.py; do not edit by hand.',
             '// Exact retained s20 fused inner / GF32 byte-multiply RS outer schedule.']
    for path in paths:
        lines.append(f'// {path.relative_to(REPO).as_posix()} SHA256 '
                     f'{hashlib.sha256(path.read_bytes()).hexdigest()}')
    if header:
        lines.append('#pragma once')
    return '\n'.join(lines) + '\n'


def field_header():
    tower = SOURCE / 'rs16x8/Tower32Randomizer.h'
    byte = SOURCE / 'rs16x8/Tower32ByteRandomizer.h'
    original, packed = tower.read_text(), byte.read_text()
    chunks = [prelude([tower, byte], True),
              '#include "../kernels/Block.h"\n#include <array>\n#include <cstdint>\n'
              '#include <stdexcept>\nnamespace spin::detail::packet::tower32 {\n'
              'inline constexpr std::uint8_t Mu = 0x20;\n'
              'inline constexpr std::uint16_t Nu = 0x2000;']
    for marker in ('inline std::uint8_t multiply8(', 'inline std::uint16_t multiply16(',
                   'inline std::uint32_t multiply32(',
                   'template<class Words>\ninline std::uint32_t sampleNonzero('):
        chunks.append(definition(original, marker))
    chunks += ['}\nnamespace spin::detail::packet::tower32byte {']
    for marker in ('inline void coefficients16(',
                   'inline std::array<std::uint8_t,9> coefficients(',
                   'inline std::array<std::uint32_t,32> multiplyRows('):
        chunks.append(definition(packed, marker))
    chunks.append('#if defined(__AVX512F__) || defined(SPIN_PACKET_ENABLE_VBMI)')
    for marker in ('struct Pair', 'static SPIN_FORCEINLINE Pair quadraticMultiply(',
                   'static SPIN_FORCEINLINE void applyMultiply('):
        chunks.append(definition(packed, marker, marker.startswith('struct ')))
    chunks += ['#endif', '} // namespace spin::detail::packet::tower32byte']
    return '\n'.join(chunks) + '\n'


def inner_header():
    path = SOURCE / 'rs16x8_border/BorderEvaluator.h'
    source = path.read_text()
    source = source[source.index('#include'):]
    source = replace_once(source, '#include "../../../../../spin/src/packet/PacketLargeInner.h"',
                          '#include "PacketLargeInner.h"')
    source = replace_once(source, 'namespace spin::research::rsborder::fast {',
                          'namespace spin::detail::packet::rsfast {')
    return prelude([path], True) + source


def inner_source(cached=False):
    path = SOURCE / 'rs16x8_border/RsBorderFused.cpp'
    source = path.read_text()
    chunks = [prelude([path]), '#include "PacketPlan.h"\n#include "PacketRsInner.h"\n'
              'namespace spin::detail::packet {\nnamespace {\nusing namespace large;']
    markers = ('struct PackedExtra',
               'template<unsigned Extra> static SPIN_FORCEINLINE PackedExtra packExtra(',
               'template<unsigned Extra> static SPIN_FORCEINLINE void unpackExtra(',
               'static SPIN_FORCEINLINE void update(', 'struct StreamingRoute',
               'template<unsigned Extra,class Emit>\nstatic SPIN_NOINLINE void reverseBorder(')
    for marker in markers:
        text = definition(source, marker, marker.startswith('struct '))
        text = text.replace('fast::streamStepBorder', 'rsfast::streamStepBorder')
        chunks.append(text)
    chunks.append('}\nvoid reverseRoute(const Block* input,Block* scratch,const Plan& plan) {\n'
                  '    StreamingRoute emit{scratch,plan.route.data()};\n'
                  '    reverseBorder<4>(input,plan.n,plan.updates.data(),emit);\n'
                  '    _mm_sfence();\n}\n')
    if not cached:
        chunks.append(
                  'void transposeFast(const Block* input,Block* output,Block* scratch,const Plan& plan) {\n'
                  '    if(plan.k<=262144) {\n'
                  '        reverseRouteCached(input,scratch,plan);\n'
                  '        outerFastCached(scratch,output,plan);\n'
                  '        return;\n    }\n'
                  '    reverseRoute(input,scratch,plan);\n'
                  '    outerFast(scratch,output,plan);\n}\n')
    chunks.append('} // namespace spin::detail::packet')
    result = '\n'.join(chunks) + '\n'
    if cached:
        result = result.replace('void reverseRoute(', 'void reverseRouteCached(')
        result = result.replace('_mm512_stream_si512', '_mm512_store_si512')
        result = result.replace('    _mm_sfence();\n', '')
    return result


def outer_source(cached=False):
    path = SOURCE / 'rs16x8/RsWideOuterVariants.cpp'
    source = path.read_text()
    chunks = [prelude([path]), '#include "PacketPlan.h"\n#include "PacketRsField.h"\n'
              'namespace spin::detail::packet {\nnamespace {']
    chunks.append(definition(source, 'static SPIN_FORCEINLINE void packHalf('))
    mix = definition(source, 'template<Randomizer Mode>\nstatic SPIN_FORCEINLINE void mixSymbol(')
    # Select only the measured field-byte branch; leave its statement order intact.
    start = mix.index('    if constexpr(Mode==Randomizer::DenseGl32)')
    mix = mix[:start] + (
        '    tower32byte::applyMultiply(v[0],v[2],v[4],v[6],bytes);\n'
        '    tower32byte::applyMultiply(v[1],v[3],v[5],v[7],bytes);\n'
        '    low[0]=v[0];low[1]=v[1];low[2]=v[2];low[3]=v[3];\n'
        '    high[0]=v[4];high[1]=v[5];high[2]=v[6];high[3]=v[7];\n}')
    mix = replace_once(mix, 'template<Randomizer Mode>\n', '')
    chunks.append(mix)
    for marker in ('struct PlaneValues',
                   'template<unsigned plane> static SPIN_FORCEINLINE PlaneValues parityValues(',
                   'template<unsigned Symbol,unsigned Plane>\nstatic SPIN_FORCEINLINE void storePairSymbol(',
                   'template<unsigned Plane>\nstatic SPIN_NOINLINE void finishPairFused(',
                   'template<unsigned Symbol,unsigned Plane>\nstatic SPIN_FORCEINLINE void storePairSymbolNt(',
                   'template<unsigned Plane>\nstatic SPIN_NOINLINE void finishPairFusedNt('):
        chunks.append(definition(source, marker, marker.startswith('struct ')))
    normal = definition(source, 'template<Randomizer Mode,bool FusedPair>\n'
                        'static SPIN_NOINLINE void outerGroupFurther(')
    branch = definition(normal, 'if constexpr(FusedPair)')
    other = definition(normal[normal.index(branch) + len(branch):], 'else')
    normal = replace_once(normal, branch + ' ' + other, branch[len('if constexpr(FusedPair) {'):-1])
    normal = replace_once(normal, 'template<Randomizer Mode,bool FusedPair>\n', '')
    normal = normal.replace('outerGroupFurther(', 'outerGroupNormal(')
    nt = definition(source, 'template<Randomizer Mode>\n'
                    'static SPIN_NOINLINE void outerGroupFusedPairNt(')
    nt = replace_once(nt, 'template<Randomizer Mode>\n', '')
    for text in (normal, nt):
        text = replace_once(text, 'constexpr unsigned stride=Mode==Randomizer::DenseGl32?128:'
                            '(Mode==Randomizer::TowerByte32?9:72);', 'constexpr unsigned stride=9;')
        chunks.append(text.replace('mixSymbol<Mode>(', 'mixSymbol('))
    chunks.append('}\nvoid outerFast(const Block* scratch,Block* output,const Plan& plan) {\n'
                  '    const auto* coeff=reinterpret_cast<const std::uint8_t*>(plan.compactCoefficients());\n'
                  '    if((reinterpret_cast<std::uintptr_t>(output)&63u)!=0) {\n'
                  '        for(std::size_t group=0;group<plan.groups;++group)\n'
                  '            outerGroupNormal(scratch+groupStride*group,output+256*group,coeff+144*group);\n'
                  '        return;\n    }\n'
                  '    for(std::size_t group=0;group<plan.groups;++group)\n'
                  '        outerGroupFusedPairNt(scratch+groupStride*group,output+256*group,coeff+144*group);\n'
                  '    _mm_sfence();\n}\n} // namespace spin::detail::packet')
    result = '\n'.join(chunks) + '\n'
    if cached:
        result = result.replace('void outerFast(', 'void outerFastCached(')
        result = result.replace('_mm512_stream_si512', '_mm512_store_si512')
        result = result.replace('    _mm_sfence();\n', '')
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='verify committed snapshots without writing')
    args = parser.parse_args()
    outputs = {'PacketRsField.h': field_header(), 'PacketRsInner.h': inner_header(),
               'PacketFast.cpp': inner_source(), 'PacketOuterFast.cpp': outer_source(),
               'PacketCachedInner.cpp': inner_source(cached=True),
               'PacketCachedOuter.cpp': outer_source(cached=True)}
    for name, text in outputs.items():
        text = '\n'.join(line.rstrip() for line in text.splitlines()) + '\n'
        path = DESTINATION / name
        if args.check:
            if not path.exists() or path.read_text() != text:
                raise SystemExit(f'generated RS packet snapshot differs: {path}')
        else:
            path.write_text(text, encoding='utf-8', newline='\n')
        print(f'{"Verified" if args.check else "Generated"} {path.relative_to(REPO).as_posix()} '
              f'{hashlib.sha256(text.encode()).hexdigest()}')


if __name__ == '__main__':
    main()
