"""Import the measured packet transpose into a standalone private SIMD unit.

Maintainer-only: normal package builds consume the committed headers and never
read research sources or invoke Python.  The importer selects the wide-state
false/false stream, compact coefficients, and mixed-layout BCH transpose.  It
does not copy benchmark drivers, setup owners, alternate kernels, or tests.

Run from any directory: python -B spin/tools/import_packet.py [--check]
"""
import argparse
from contextlib import redirect_stdout
import hashlib
from io import StringIO
from pathlib import Path
import re
import sys

PACKAGE = Path(__file__).resolve().parents[1]
REPO = PACKAGE.parent
WORKSTREAM = REPO / 'research/workstreams/permutation_locality'
DESTINATION = PACKAGE / 'src/packet'


def definition(source, marker, semicolon=False):
    if source.count(marker) != 1:
        raise ArithmeticError(f'expected exactly one source definition: {marker}')
    start = source.index(marker)
    opening = source.index('{', start)
    depth, end = 1, opening + 1
    while depth:
        if source[end] == '{':
            depth += 1
        elif source[end] == '}':
            depth -= 1
        end += 1
    if semicolon:
        if source[end] != ';':
            raise ArithmeticError(f'missing definition terminator: {marker}')
        end += 1
    return source[start:end]


def header_prelude(sources):
    lines = ['// Generated by spin/tools/import_packet.py; do not edit by hand.',
             '// Selected exact t64/s16 packet transpose. Private to PacketFast.cpp.']
    for path in sources:
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        lines.append(f'// Source {path.relative_to(REPO).as_posix()}: {digest}')
    return '\n'.join(lines) + '\n#pragma once\n'


def inner_header():
    names = ('InnerPacketMaps.h', 'InnerPacketFeedback.h', 'InnerVbmiState.h',
             'InnerComposed.h', 'PacketInnerKernel.h', 'further_mapWide.h')
    paths = [WORKSTREAM / name for name in names]
    maps, feedback, vbmi, composed, kernel, wide = [path.read_text() for path in paths]
    selected_maps = maps[maps.index('template<> struct Maps<true>'):]
    chunks = [header_prelude(paths),
              '#include "../kernels/Block.h"\n#include <array>\n#include <cstddef>\n'
              '#include <cstdint>\n#include <utility>\n'
              'namespace spin::detail::packet::fast {\n'
              'using Block=storage::block;\n'
              'struct alignas(64) PackedState { __m512i v[4]; };\n']
    specs = (
        (maps, 'static SPIN_FORCEINLINE __m128i vx('),
        (maps, 'static SPIN_FORCEINLINE __m512i join('),
        (composed, 'struct alignas(64) WordPackets16'),
        (vbmi, 'template<unsigned FirstPayloadByte>\nstatic SPIN_FORCEINLINE __m512i packIndex('),
        (vbmi, 'template<unsigned FirstCoordinate>\nstatic SPIN_FORCEINLINE __m512i unpackIndex('),
        (composed, 'template<unsigned Group>\nstatic SPIN_FORCEINLINE void packWordGroup('),
        (composed, 'static SPIN_FORCEINLINE void wordPackets('),
        (composed, 'static SPIN_FORCEINLINE void applyPackedToPackets('),
        (feedback, 'struct FourMoments'),
        (feedback, 'template<unsigned First>\nSPIN_PACKET_FEEDBACK_INLINE FourMoments firstStage('),
        (feedback, 'template<unsigned Mask, unsigned Degree>\nSPIN_PACKET_FEEDBACK_INLINE void storeLowMoments('),
        (feedback, 'SPIN_PACKET_FEEDBACK_INLINE void packetMoments('),
        (selected_maps, 'static SPIN_FORCEINLINE void finish('),
        (kernel, 'template<std::size_t... I>\nstatic SPIN_FORCEINLINE void loadPackets('),
    )
    for source, marker in specs:
        text = definition(source, marker, marker.startswith('struct '))
        text = (text.replace('gf::Packed<16>', 'PackedState')
                .replace('gf::join(', 'join(')
                .replace('vbmi_state_detail::', '')
                .replace('SPIN_PACKET_FEEDBACK_INLINE', 'static SPIN_FORCEINLINE')
                .replace('using feedback_detail::firstStage;', '')
                .replace('using feedback_detail::storeLowMoments;', '')
                .replace('const ComposedWordRow16& row', 'const std::uint64_t* row')
                .replace('row.data[', 'row['))
        chunks.append(text)
    stream = definition(wide, 'template<bool Pruned,bool Incremental,class Emit>\n'
                        'static SPIN_FORCEINLINE void streamHigh(')
    # Select the retained grouped branch exactly; reject unexpected formatting.
    branch = definition(stream, 'if constexpr(Incremental)')
    marker = branch + 'else{'
    if stream.count(marker) != 1:
        raise ArithmeticError('wide stream no longer has the selected grouped branch')
    start = stream.index(marker)
    grouped = definition(stream[start + len(branch):], 'else')
    stream = stream[:start] + grouped[len('else{'):-1] + stream[start + len(branch) + len(grouped):]
    stream = stream.replace('template<bool Pruned,bool Incremental,class Emit>', 'template<class Emit>')
    stream = stream.replace('composed_detail::WordPackets16', 'WordPackets16')
    stream = stream.replace('spin::detail::kernel::block', 'Block')
    stream = '\n'.join(line for line in stream.splitlines() if 'const auto cache' not in line)
    stream = re.sub(r'Pruned\?[^:;]+:([^;]+)', r'\1', stream)
    if 'Pruned' in stream or 'Incremental' in stream:
        raise ArithmeticError('unselected stream branch survived import')
    chunks.append(stream)
    for name in ('streamMoments', 'reverse'):
        text = definition(wide, 'template<bool Pruned,bool Incremental,class Emit>\n'
                          f'static SPIN_FORCEINLINE void {name}(')
        text = (text.replace('template<bool Pruned,bool Incremental,class Emit>', 'template<class Emit>')
                .replace('<Pruned,Incremental>', '')
                .replace('composed_detail::WordPackets16', 'WordPackets16')
                .replace('spin::detail::kernel::block', 'Block')
                .replace('const ComposedWordRow16* rows', 'const std::uint64_t* rows')
                .replace('using namespace composed_detail;', '')
                .replace('using feedback_detail::storeLowMoments;', '')
                .replace('gf::Packed<16>', 'PackedState')
                .replace('packet_kernel_detail::loadPackets', 'loadPackets')
                .replace('Maps<true>::finish(', 'finish(')
                .replace('rows[epoch]', 'rows+4*epoch'))
        chunks.append(text)
    chunks.append('} // namespace spin::detail::packet::fast\n')
    result = '\n'.join(line.rstrip() for line in '\n'.join(chunks).splitlines()) + '\n'
    if any(word in result for word in ('spin::research', 'ComposedWordRow16', 'PreparedComposed')):
        raise ArithmeticError('research interface survived inner import')
    return result


def outer_header():
    sys.path.insert(0, str(WORKSTREAM))
    import outer_transpose_codegen as outer
    matrix_header = PACKAGE / 'src/kernels/generated/BchCircuit.h'
    source = outer.generate(matrix_header)
    rows = outer.read_rows(matrix_header)
    parity = [sum(255 << (8 * j) for j in range(8) if rows[8 * output + j] >> 127 & 1)
              for output in range(16)]
    sources = [WORKSTREAM / name for name in ('outer_transpose_codegen.py', 'outer_unpack_codegen.py',
               'outer_layout_codegen.py', 'packed_coeff_codegen.py', 'packed_bch_tune_codegen.py')]
    sources.append(matrix_header)
    chunks = [header_prelude(sources), '#include "../kernels/Block.h"\n#include <cstdint>\n'
              'namespace spin::detail::packet::fast {\nusing block=storage::block;\n',
              'static constexpr std::uint64_t parityMasks[16]={' +
              ','.join(f'0x{value:016x}ULL' for value in parity) + '};']
    specs = ('static SPIN_FORCEINLINE void packedTuneByteTranspose5(',
             'static SPIN_FORCEINLINE void packedTunePack5(',
             'alignas(64) static constexpr std::uint64_t transposedMatrices[16][16]=',
             'template<unsigned output> static SPIN_NOINLINE void packedCoeffTile(',
             'SPIN_NOINLINE void bchPackedCoeffCompact(')
    for marker in specs:
        text = definition(source, marker, marker.startswith('alignas'))
        text = text.replace('using namespace coeff_probe_detail;', '')
        text = text.replace('packedCoeffTile', 'outerTile').replace('bchPackedCoeffCompact', 'outerCompact')
        text = text.replace('SPIN_NOINLINE void outerCompact(', 'static SPIN_NOINLINE void outerCompact(')
        for output in range(2):
            old = (f'constexpr auto parity{output}=[]{{std::uint64_t mask=0;for(unsigned j=0;j<8;++j)'
                   f'if(BchRows[8*(output+{output})+j][1]>>63)mask|=std::uint64_t(255)<<(8*j);return mask;}}();')
            if old in text:
                text = text.replace(old, f'constexpr auto parity{output}=parityMasks[output+{output}];')
        chunks.append(text)
    chunks.append('} // namespace spin::detail::packet::fast\n')
    result = '\n'.join(line.rstrip() for line in '\n'.join(chunks).splitlines()) + '\n'
    if any(word in result for word in ('BchRows', 'spin::research', 'coeff_probe_detail')):
        raise ArithmeticError('research interface survived outer import')
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='verify committed generated files without writing')
    args = parser.parse_args()
    outputs = {'PacketInnerFast.h': inner_header(), 'PacketOuterFast.h': outer_header()}
    for name, text in outputs.items():
        path = DESTINATION / name
        if args.check:
            if not path.exists() or path.read_text() != text:
                raise SystemExit(f'generated packet snapshot differs: {path}')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding='utf-8', newline='\n')
        print(f'{"Verified" if args.check else "Generated"} {path.relative_to(REPO).as_posix()} '
              f'{hashlib.sha256(text.encode()).hexdigest()}')


if __name__ == '__main__':
    main()
