/- Generated by emit_majorant.py: 1 leaves, 0 logs. -/
import SpinCodes.Numeric.MajorantDefs
set_option maxRecDepth 8000000
set_option maxHeartbeats 0
namespace Spin.Majorant.S1.P14
open Spin.Numeric Spin.Numeric.Fix
def table : LogTree := .leaf
def tree : BoxTree := .leaf (1)
def A : Fix := ⟨0, 500000000000000000000000000000⟩
def B : Fix := ⟨500000000000000000000000000000, 1000000000000000000000000000000⟩
def W : Fix := ⟨152466884341666666666666666666, 158319841724600000000000000000⟩
def S : Fix := ⟨1660000000000000000000000000000, 1660000000000000000000000000000⟩
def I : Fix := ⟨-172329198693950000000000000000, -172329198693950000000000000000⟩
theorem logs_ok : table.check 10 = true := by decide
theorem tree_ok : checkTree (majorantLeaf (treeLog table) S I) tree A B W = true := by decide
end Spin.Majorant.S1.P14
