if(NOT SPIN_BUILD_WIDE)
  return()
endif()
if(NOT SPIN_BIDIRECTIONAL_SOURCE)
  message(FATAL_ERROR "SPIN_BUILD_WIDE requires SPIN_BIDIRECTIONAL_SOURCE")
endif()
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/wide.py"
  "${SPIN_BIDIRECTIONAL_SOURCE}/generate_wide.py")
execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/wide.py"
  "${SPIN_BIDIRECTIONAL_SOURCE}" "${BID}" COMMAND_ERROR_IS_FATAL ANY)
add_library(spin_wide256 OBJECT "${BID}/wide/Wide256.cpp")
target_link_libraries(spin_wide256 PRIVATE spin_baseline)
target_include_directories(spin_wide256 PRIVATE "${BID}")
add_library(spin_wide512 OBJECT "${BID}/wide/Wide512.cpp")
target_link_libraries(spin_wide512 PRIVATE spin_baseline)
target_include_directories(spin_wide512 PRIVATE "${BID}")
target_compile_options(spin_wide512 PRIVATE -mavx512f -mavx512vl -mavx512bw -mavx512dq)
add_library(spin_wide STATIC Wide.cpp $<TARGET_OBJECTS:spin_wide256> $<TARGET_OBJECTS:spin_wide512>)
target_link_libraries(spin_wide PUBLIC spin_half_bidirectional)
target_include_directories(spin_wide PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")
target_compile_definitions(spin_wide PRIVATE SPIN_TEST_NO_AVX512=$<BOOL:${SPIN_TEST_NO_AVX512}>)
foreach(t spin_wide spin_wide256 spin_wide512)
  set_property(TARGET ${t} PROPERTY INTERPROCEDURAL_OPTIMIZATION FALSE)
endforeach()
if(BUILD_TESTING)
  add_executable(spin_wide_test wide_test.cpp)
  target_link_libraries(spin_wide_test PRIVATE spin_wide)
  add_test(NAME wide_forward COMMAND spin_wide_test)
  set_tests_properties(wide_forward PROPERTIES RUN_SERIAL TRUE)
endif()
if(SPIN_BUILD_BENCHMARK)
  add_library(spin_column512 OBJECT ColumnAssembly.cpp "${BID}/Column128.cpp")
  target_link_libraries(spin_column512 PRIVATE spin_half_bidirectional)
  target_compile_options(spin_column512 PRIVATE -mavx512f -mavx512dq)
  add_executable(spin_wide_benchmark wide_benchmark.cpp $<TARGET_OBJECTS:spin_column512>)
  target_link_libraries(spin_wide_benchmark PRIVATE spin_wide)
endif()
