/- Generated by emit_majorant.py: 1 leaves, 0 logs. -/
import SpinCodes.Numeric.MajorantDefs
set_option maxRecDepth 8000000
set_option maxHeartbeats 0
namespace Spin.Majorant.S0.P74
open Spin.Numeric Spin.Numeric.Fix
def table : LogTree := .leaf
def tree : BoxTree := .leaf (1)
def A : Fix := ⟨312500000000000000000000000000, 375000000000000000000000000000⟩
def B : Fix := ⟨312500000000000000000000000000, 375000000000000000000000000000⟩
def W : Fix := ⟨104000000000000000000000000000, 152466884341666666666666666667⟩
def S : Fix := ⟨1666000000000000000000000000000, 1666000000000000000000000000000⟩
def I : Fix := ⟨-173244000000000000000000000000, -173244000000000000000000000000⟩
theorem logs_ok : table.check 10 = true := by decide
theorem tree_ok : checkTree (majorantLeaf (treeLog table) S I) tree A B W = true := by decide
end Spin.Majorant.S0.P74
