// Generated by tools/generate_packet_forward.py.
#include "PacketForward.h"
namespace spin::detail::packet { namespace {
static SPIN_FORCEINLINE void unpackHalf(const __m512i* v,Block* out,const std::uint32_t* route) {
const auto basis=_mm512_set1_epi64(0x0102040810204080ULL);
const auto z0=_mm512_gf2p8affine_epi64_epi8(basis,v[0],0);
const auto z1=_mm512_gf2p8affine_epi64_epi8(basis,v[1],0);
const auto z2=_mm512_gf2p8affine_epi64_epi8(basis,v[2],0);
const auto z3=_mm512_gf2p8affine_epi64_epi8(basis,v[3],0);
const auto a0=_mm512_permutex2var_epi8(z0,_mm512_setr_epi64(0x0f0e0b0a07060302ULL,0x1f1e1b1a17161312ULL,0x2f2e2b2a27262322ULL,0x3f3e3b3a37363332ULL,0x4f4e4b4a47464342ULL,0x5f5e5b5a57565352ULL,0x6f6e6b6a67666362ULL,0x7f7e7b7a77767372ULL),z1);
const auto a2=_mm512_permutex2var_epi8(z0,_mm512_setr_epi64(0x0d0c090805040100ULL,0x1d1c191815141110ULL,0x2d2c292825242120ULL,0x3d3c393835343130ULL,0x4d4c494845444140ULL,0x5d5c595855545150ULL,0x6d6c696865646160ULL,0x7d7c797875747170ULL),z1);
const auto a1=_mm512_permutex2var_epi8(z2,_mm512_setr_epi64(0x0f0e0b0a07060302ULL,0x1f1e1b1a17161312ULL,0x2f2e2b2a27262322ULL,0x3f3e3b3a37363332ULL,0x4f4e4b4a47464342ULL,0x5f5e5b5a57565352ULL,0x6f6e6b6a67666362ULL,0x7f7e7b7a77767372ULL),z3);
const auto a3=_mm512_permutex2var_epi8(z2,_mm512_setr_epi64(0x0d0c090805040100ULL,0x1d1c191815141110ULL,0x2d2c292825242120ULL,0x3d3c393835343130ULL,0x4d4c494845444140ULL,0x5d5c595855545150ULL,0x6d6c696865646160ULL,0x7d7c797875747170ULL),z3);
_mm512_stream_si512(reinterpret_cast<__m512i*>(out+route[0]),_mm512_permutex2var_epi8(a0,_mm512_setr_epi64(0x1f1b17130f0b0703ULL,0x3f3b37332f2b2723ULL,0x1d1915110d090501ULL,0x3d3935312d292521ULL,0x5f5b57534f4b4743ULL,0x7f7b77736f6b6763ULL,0x5d5955514d494541ULL,0x7d7975716d696561ULL),a1));
_mm512_stream_si512(reinterpret_cast<__m512i*>(out+route[1]),_mm512_permutex2var_epi8(a0,_mm512_setr_epi64(0x1e1a16120e0a0602ULL,0x3e3a36322e2a2622ULL,0x1c1814100c080400ULL,0x3c3834302c282420ULL,0x5e5a56524e4a4642ULL,0x7e7a76726e6a6662ULL,0x5c5854504c484440ULL,0x7c7874706c686460ULL),a1));
_mm512_stream_si512(reinterpret_cast<__m512i*>(out+route[2]),_mm512_permutex2var_epi8(a2,_mm512_setr_epi64(0x1f1b17130f0b0703ULL,0x3f3b37332f2b2723ULL,0x1d1915110d090501ULL,0x3d3935312d292521ULL,0x5f5b57534f4b4743ULL,0x7f7b77736f6b6763ULL,0x5d5955514d494541ULL,0x7d7975716d696561ULL),a3));
_mm512_stream_si512(reinterpret_cast<__m512i*>(out+route[3]),_mm512_permutex2var_epi8(a2,_mm512_setr_epi64(0x1e1a16120e0a0602ULL,0x3e3a36322e2a2622ULL,0x1c1814100c080400ULL,0x3c3834302c282420ULL,0x5e5a56524e4a4642ULL,0x7e7a76726e6a6662ULL,0x5c5854504c484440ULL,0x7c7874706c686460ULL),a3));
}
template<unsigned S,unsigned P> static SPIN_FORCEINLINE void packMessage(const Block* in,__m512i* out) {
const auto x=_mm512_loadu_si512(in+32*P+4*S);const auto y=_mm512_loadu_si512(in+32*(P+1)+4*S);
const auto basis=_mm512_set1_epi64(0x0102040810204080ULL);
out[4*S+P]=_mm512_gf2p8affine_epi64_epi8(basis,_mm512_permutex2var_epi8(x,_mm512_setr_epi64(0x0010203040506070ULL,0x0111213141516171ULL,0x0212223242526272ULL,0x0313233343536373ULL,0x0414243444546474ULL,0x0515253545556575ULL,0x0616263646566676ULL,0x0717273747576777ULL),y),0);
out[4*S+P+1]=_mm512_gf2p8affine_epi64_epi8(basis,_mm512_permutex2var_epi8(x,_mm512_setr_epi64(0x0818283848586878ULL,0x0919293949596979ULL,0x0a1a2a3a4a5a6a7aULL,0x0b1b2b3b4b5b6b7bULL,0x0c1c2c3c4c5c6c7cULL,0x0d1d2d3d4d5d6d7dULL,0x0e1e2e3e4e5e6e7eULL,0x0f1f2f3f4f5f6f7fULL),y),0);
}
template<unsigned P> static SPIN_FORCEINLINE void parityForward(__m512i* packed) {
auto y0=packed[4*0+P];
auto y1=packed[4*1+P];
auto y2=packed[4*2+P];
auto y3=packed[4*3+P];
auto y4=packed[4*4+P];
auto y5=packed[4*5+P];
auto y6=packed[4*6+P];
auto y7=packed[4*7+P];
y7=_mm512_xor_si512(y7,y3);
y6=_mm512_xor_si512(y6,y2);
y5=_mm512_xor_si512(y5,y1);
y4=_mm512_xor_si512(y4,y0);
y7=_mm512_xor_si512(y7,y5);
y6=_mm512_xor_si512(y6,y4);
y3=_mm512_xor_si512(y3,y1);
y2=_mm512_xor_si512(y2,y0);
y7=_mm512_xor_si512(y7,y6);
y5=_mm512_xor_si512(y5,y4);
y3=_mm512_xor_si512(y3,y2);
y1=_mm512_xor_si512(y1,y0);
auto x0=y0;
auto x1=y1;
auto x2=y2;
auto x3=y3;
auto x4=y4;
auto x5=y5;
auto x6=y6;
auto x7=y7;
x0=_mm512_xor_si512(x0,_mm512_gf2p8affine_epi64_epi8(y1,_mm512_set1_epi64(0x0b0d0a05b0d0a050ULL),0));
x0=_mm512_xor_si512(x0,_mm512_gf2p8affine_epi64_epi8(y2,_mm512_set1_epi64(0x0809020480902040ULL),0));
x0=_mm512_xor_si512(x0,_mm512_gf2p8affine_epi64_epi8(y3,_mm512_set1_epi64(0x0708010370801030ULL),0));
x1=_mm512_xor_si512(x1,_mm512_gf2p8affine_epi64_epi8(y3,_mm512_set1_epi64(0x0809020480902040ULL),0));
x2=_mm512_xor_si512(x2,_mm512_gf2p8affine_epi64_epi8(y3,_mm512_set1_epi64(0x0b0d0a05b0d0a050ULL),0));
x0=_mm512_xor_si512(x0,_mm512_gf2p8affine_epi64_epi8(y4,_mm512_set1_epi64(0x050e0d0a50e0d0a0ULL),0));
x0=_mm512_xor_si512(x0,_mm512_gf2p8affine_epi64_epi8(y5,_mm512_set1_epi64(0x060a050b60a050b0ULL),0));
x1=_mm512_xor_si512(x1,_mm512_gf2p8affine_epi64_epi8(y5,_mm512_set1_epi64(0x050e0d0a50e0d0a0ULL),0));
x4=_mm512_xor_si512(x4,_mm512_gf2p8affine_epi64_epi8(y5,_mm512_set1_epi64(0x0b0d0a05b0d0a050ULL),0));
x0=_mm512_xor_si512(x0,_mm512_gf2p8affine_epi64_epi8(y6,_mm512_set1_epi64(0x0b0d0a05b0d0a050ULL),0));
x2=_mm512_xor_si512(x2,_mm512_gf2p8affine_epi64_epi8(y6,_mm512_set1_epi64(0x050e0d0a50e0d0a0ULL),0));
x4=_mm512_xor_si512(x4,_mm512_gf2p8affine_epi64_epi8(y6,_mm512_set1_epi64(0x0809020480902040ULL),0));
x0=_mm512_xor_si512(x0,_mm512_gf2p8affine_epi64_epi8(y7,_mm512_set1_epi64(0x02060c092060c090ULL),0));
x1=_mm512_xor_si512(x1,_mm512_gf2p8affine_epi64_epi8(y7,_mm512_set1_epi64(0x0b0d0a05b0d0a050ULL),0));
x2=_mm512_xor_si512(x2,_mm512_gf2p8affine_epi64_epi8(y7,_mm512_set1_epi64(0x060a050b60a050b0ULL),0));
x3=_mm512_xor_si512(x3,_mm512_gf2p8affine_epi64_epi8(y7,_mm512_set1_epi64(0x050e0d0a50e0d0a0ULL),0));
x4=_mm512_xor_si512(x4,_mm512_gf2p8affine_epi64_epi8(y7,_mm512_set1_epi64(0x0708010370801030ULL),0));
x5=_mm512_xor_si512(x5,_mm512_gf2p8affine_epi64_epi8(y7,_mm512_set1_epi64(0x0809020480902040ULL),0));
x6=_mm512_xor_si512(x6,_mm512_gf2p8affine_epi64_epi8(y7,_mm512_set1_epi64(0x0b0d0a05b0d0a050ULL),0));
x7=_mm512_xor_si512(x7,x3);
x6=_mm512_xor_si512(x6,x2);
x5=_mm512_xor_si512(x5,x1);
x4=_mm512_xor_si512(x4,x0);
x7=_mm512_xor_si512(x7,x5);
x6=_mm512_xor_si512(x6,x4);
x3=_mm512_xor_si512(x3,x1);
x2=_mm512_xor_si512(x2,x0);
x7=_mm512_xor_si512(x7,x6);
x5=_mm512_xor_si512(x5,x4);
x3=_mm512_xor_si512(x3,x2);
x1=_mm512_xor_si512(x1,x0);
packed[32+4*0+P]=x0;
packed[32+4*1+P]=x1;
packed[32+4*2+P]=x2;
packed[32+4*3+P]=x3;
packed[32+4*4+P]=x4;
packed[32+4*5+P]=x5;
packed[32+4*6+P]=x6;
packed[32+4*7+P]=x7;
}
struct Pair {__m512i lo,hi;};
static SPIN_FORCEINLINE Pair adjoint2(__m512i a,__m512i b,const std::uint64_t* c) {
const auto p=_mm512_gf2p8affine_epi64_epi8(_mm512_xor_si512(a,b),_mm512_set1_epi64(c[0]),0);
const auto q=_mm512_gf2p8affine_epi64_epi8(a,_mm512_set1_epi64(c[1]),0);
const auto r=_mm512_gf2p8affine_epi64_epi8(b,_mm512_set1_epi64(c[2]),0);
return {_mm512_xor_si512(p,r),_mm512_xor_si512(q,r)};
}
static SPIN_FORCEINLINE void adjoint4(__m512i& a,__m512i& b,__m512i& c,__m512i& d,const std::uint64_t* coeff) {
const auto p=adjoint2(_mm512_xor_si512(a,c),_mm512_xor_si512(b,d),coeff);
const auto q=adjoint2(a,b,coeff+3);const auto r=adjoint2(c,d,coeff+6);
a=_mm512_xor_si512(p.lo,r.lo);b=_mm512_xor_si512(p.hi,r.hi);c=_mm512_xor_si512(q.lo,r.lo);d=_mm512_xor_si512(q.hi,r.hi);
}
static SPIN_NOINLINE void groupForward(const Block* in,Block* out,const std::array<std::uint64_t,9>* coeff,const std::uint32_t* route) {
alignas(64) __m512i lo[64],hi[64];
packMessage<0,0>(in+0,lo);
packMessage<0,2>(in+0,lo);
packMessage<1,0>(in+0,lo);
packMessage<1,2>(in+0,lo);
packMessage<2,0>(in+0,lo);
packMessage<2,2>(in+0,lo);
packMessage<3,0>(in+0,lo);
packMessage<3,2>(in+0,lo);
packMessage<4,0>(in+0,lo);
packMessage<4,2>(in+0,lo);
packMessage<5,0>(in+0,lo);
packMessage<5,2>(in+0,lo);
packMessage<6,0>(in+0,lo);
packMessage<6,2>(in+0,lo);
packMessage<7,0>(in+0,lo);
packMessage<7,2>(in+0,lo);
parityForward<0>(lo);
parityForward<1>(lo);
parityForward<2>(lo);
parityForward<3>(lo);
packMessage<0,0>(in+128,hi);
packMessage<0,2>(in+128,hi);
packMessage<1,0>(in+128,hi);
packMessage<1,2>(in+128,hi);
packMessage<2,0>(in+128,hi);
packMessage<2,2>(in+128,hi);
packMessage<3,0>(in+128,hi);
packMessage<3,2>(in+128,hi);
packMessage<4,0>(in+128,hi);
packMessage<4,2>(in+128,hi);
packMessage<5,0>(in+128,hi);
packMessage<5,2>(in+128,hi);
packMessage<6,0>(in+128,hi);
packMessage<6,2>(in+128,hi);
packMessage<7,0>(in+128,hi);
packMessage<7,2>(in+128,hi);
parityForward<0>(hi);
parityForward<1>(hi);
parityForward<2>(hi);
parityForward<3>(hi);
for(unsigned s=0;s<16;++s) {
__m512i v[8]={lo[4*s],lo[4*s+1],lo[4*s+2],lo[4*s+3],hi[4*s],hi[4*s+1],hi[4*s+2],hi[4*s+3]};
adjoint4(v[0],v[2],v[4],v[6],coeff[s].data());adjoint4(v[1],v[3],v[5],v[7],coeff[s].data());
unpackHalf(v,out,route+8*s);unpackHalf(v+4,out,route+8*s+4);
}
}
}
void forwardOuter(const Block* in,Block* out,const Plan& p,const ForwardPlan& f) {
for(std::size_t g=0;g<p.groups;++g)groupForward(in+256*g,out,f.outer.data()+16*g,f.inverseRoute.data()+groupStride*g/4);_mm_sfence();
}
}
