// Generated by spin/tools/import_packet.py; do not edit by hand.
// Retained inner_fusion_probe mode 19 and PackedCoeff1 tile-mode 1.
// Source research/workstreams/permutation_locality/FusedR4Gfni.h: d2f340910e175ded705b74a3bb5eedbfbe78964c9be49bbf00fe3db31a51c179
#pragma once
#include <cstdint>
namespace spin::detail::packet::large {
struct Dense16Row {std::uint64_t matrix[4]{};};
static_assert(sizeof(Dense16Row)==32);
} // namespace spin::detail::packet::large
