// Generated by spin/tools/import_rs_packet.py; do not edit by hand.
// Exact retained s20 fused inner / GF32 byte-multiply RS outer schedule.
// research/workstreams/k16_design/implementation/rs16x8/Tower32Randomizer.h SHA256 e22060caa6692d4599f18aaffe7a3fa7b743026fed5ba1c4c56b3145904857f7
// research/workstreams/k16_design/implementation/rs16x8/Tower32ByteRandomizer.h SHA256 61a8e3b14d9f3949eb99e0e479ad8347dbae8b39ac491207964661febc555f45
#pragma once

#include "../kernels/Block.h"
#include <array>
#include <cstdint>
#include <stdexcept>
namespace spin::detail::packet::tower32 {
inline constexpr std::uint8_t Mu = 0x20;
inline constexpr std::uint16_t Nu = 0x2000;
inline std::uint8_t multiply8(std::uint8_t a, std::uint8_t b) {
    std::uint8_t result = 0;
    for(unsigned bit = 0; bit < 8; ++bit) {
        if(b & 1U) result ^= a;
        a = std::uint8_t((unsigned(a) << 1) ^ ((a & 128U) ? 0x11bU : 0U));
        b >>= 1;
    }
    return result;
}
inline std::uint16_t multiply16(std::uint16_t a, std::uint16_t b) {
    const auto a0 = std::uint8_t(a), a1 = std::uint8_t(a >> 8);
    const auto b0 = std::uint8_t(b), b1 = std::uint8_t(b >> 8);
    const auto lo = multiply8(a0,b0) ^ multiply8(Mu,multiply8(a1,b1));
    const auto hi = multiply8(a0,b1) ^ multiply8(a1,b0) ^ multiply8(a1,b1);
    return std::uint16_t(lo | (unsigned(hi) << 8));
}
inline std::uint32_t multiply32(std::uint32_t a, std::uint32_t b) {
    const auto a0 = std::uint16_t(a), a1 = std::uint16_t(a >> 16);
    const auto b0 = std::uint16_t(b), b1 = std::uint16_t(b >> 16);
    const auto lo = multiply16(a0,b0) ^ multiply16(Nu,multiply16(a1,b1));
    const auto hi = multiply16(a0,b1) ^ multiply16(a1,b0) ^ multiply16(a1,b1);
    return std::uint32_t(lo) | (std::uint32_t(hi) << 16);
}
template<class Words>
inline std::uint32_t sampleNonzero(Words& words) {
    std::uint32_t scalar;
    do { scalar = std::uint32_t(words()); } while(!scalar);
    return scalar;
}
}
namespace spin::detail::packet::tower32byte {
inline void coefficients16(std::uint16_t scalar, std::uint8_t* output) {
    const auto c0 = std::uint8_t(scalar), c1 = std::uint8_t(scalar >> 8);
    output[0] = c0;
    output[1] = tower32::multiply8(tower32::Mu,c1);
    output[2] = c0 ^ c1;
}
inline std::array<std::uint8_t,9> coefficients(std::uint32_t scalar) {
    if(!scalar) throw std::invalid_argument("tower32byte requires a nonzero scalar");
    const auto c0 = std::uint16_t(scalar), c1 = std::uint16_t(scalar >> 16);
    std::array<std::uint8_t,9> result{};
    coefficients16(c0,result.data());
    coefficients16(tower32::multiply16(tower32::Nu,c1),result.data()+3);
    coefficients16(c0 ^ c1,result.data()+6);
    return result;
}
inline std::array<std::uint32_t,32> multiplyRows(std::uint32_t scalar) {
    if(!scalar) throw std::invalid_argument("tower32byte requires a nonzero scalar");
    std::array<std::uint32_t,32> result{};
    for(unsigned column = 0; column < 32; ++column) {
        const auto image = tower32::multiply32(scalar, std::uint32_t{1} << column);
        for(unsigned row = 0; row < 32; ++row)
            result[row] |= ((image >> row) & 1U) << column;
    }
    return result;
}
#if defined(__AVX512F__) || defined(SPIN_PACKET_ENABLE_VBMI)
struct Pair { __m512i lo,hi; };
static SPIN_FORCEINLINE Pair quadraticMultiply(__m512i x0, __m512i x1, const std::uint8_t* c) {
    const auto m0 = _mm512_set1_epi8(char(c[0]));
    const auto m1 = _mm512_set1_epi8(char(c[1]));
    const auto m2 = _mm512_set1_epi8(char(c[2]));
    const auto p0 = _mm512_gf2p8mul_epi8(x0,m0);
    const auto p1 = _mm512_gf2p8mul_epi8(x1,m1);
    const auto p2 = _mm512_gf2p8mul_epi8(_mm512_xor_si512(x0,x1),m2);
    return {_mm512_xor_si512(p0,p1),_mm512_xor_si512(p0,p2)};
}
static SPIN_FORCEINLINE void applyMultiply(__m512i& y0, __m512i& y1,
    __m512i& y2, __m512i& y3, const std::uint8_t* coeff) {
    const auto p = quadraticMultiply(y0,y1,coeff);
    const auto q = quadraticMultiply(y2,y3,coeff+3);
    const auto r = quadraticMultiply(_mm512_xor_si512(y0,y2),_mm512_xor_si512(y1,y3),coeff+6);
    y0 = _mm512_xor_si512(p.lo,q.lo);
    y1 = _mm512_xor_si512(p.hi,q.hi);
    y2 = _mm512_xor_si512(p.lo,r.lo);
    y3 = _mm512_xor_si512(p.hi,r.hi);
}
#endif
} // namespace spin::detail::packet::tower32byte
