// Generated by tools/generate_packet_forward.py.
#include "PacketForward.h"
#include "PacketLargeInner.h"
namespace spin::detail::packet::forwardfast {
using namespace detail::packet::large;
template<unsigned Extra,class Emit>
static SPIN_FORCEINLINE void streamStepHighBorder(const __m128i* state,
const __m128i* extra,const block* raw,const std::uint32_t* route,std::size_t packetBase,Emit& emit,__m512i* high){
// State to 22 ANF coefficients: 12 XMM XORs.
const auto cs0=vx(state[10],state[12]);
const auto cs1=vx(state[12],state[15]);
const auto cs2=vx(state[11],state[13]);
const auto c0=state[0];
const auto c1=state[1];
const auto c2=state[2];
const auto c3=vx(state[7],extra[0]);
const auto c4=state[3];
const auto c5=Extra>=2?vx(state[8],extra[1]):state[8];
const auto c6=state[12];
const auto c8=state[4];
const auto c9=Extra>=3?vx(state[9],extra[2]):state[9];
const auto c10=state[13];
const auto c12=state[15];
const auto c16=state[5];
const auto c17=Extra>=4?vx(state[10],extra[3]):state[10];
const auto c18=cs0;
const auto c20=vx(vx(state[9],state[14]),cs1);
const auto c24=vx(cs1,cs2);
const auto c32=state[6];
const auto c33=state[11];
const auto c34=state[14];
const auto c36=vx(vx(vx(vx(state[7],state[8]),state[9]),cs0),cs2);
const auto c40=vx(state[14],cs0);
const auto c48=vx(state[7],cs1);
const auto l01=vx(c0,c1);
const auto l02=vx(c0,c2);
const auto l03=vx(vx(l01,c2),c3);
const auto d0=join(c0,l01,l02,l03);
const auto l11=vx(c4,c5);
const auto l12=vx(c4,c6);
const auto l13=vx(l11,c6);
const auto d1=join(c4,l11,l12,l13);
const auto l21=vx(c8,c9);
const auto l22=vx(c8,c10);
const auto l23=vx(l21,c10);
const auto d2=join(c8,l21,l22,l23);
const auto d3=_mm512_broadcast_i32x4(c12);
const auto l41=vx(c16,c17);
const auto l42=vx(c16,c18);
const auto l43=vx(l41,c18);
const auto d4=join(c16,l41,l42,l43);
const auto d5=_mm512_broadcast_i32x4(c20);
const auto d6=_mm512_broadcast_i32x4(c24);
const auto l81=vx(c32,c33);
const auto l82=vx(c32,c34);
const auto l83=vx(l81,c34);
const auto d8=join(c32,l81,l82,l83);
const auto d9=_mm512_broadcast_i32x4(c36);
const auto d10=_mm512_broadcast_i32x4(c40);
const auto d12=_mm512_broadcast_i32x4(c48);
// Shared group-2 coefficients reduce the block evaluator from29 to26 XORs.

__m512i g30,g31,g32,g33;
{
const auto b0=_mm512_xor_si512(_mm512_xor_si512(_mm512_xor_si512(d0,d4),d8),d12);
const auto b1=_mm512_xor_si512(_mm512_xor_si512(d1,d5),d9);
const auto b2=_mm512_xor_si512(_mm512_xor_si512(d2,d6),d10);
const auto e1=_mm512_xor_si512(b0,b1);
const auto e2=_mm512_xor_si512(b0,b2);
const auto e3=_mm512_xor_si512(_mm512_xor_si512(e1,b2),d3);
const auto y3=_mm512_xor_si512(e3,_mm512_loadu_si512(raw+route[15]));
emit(packetBase+15,y3);
const auto y2=_mm512_xor_si512(e2,_mm512_loadu_si512(raw+route[14]));
emit(packetBase+14,y2);
const auto y1=_mm512_xor_si512(e1,_mm512_loadu_si512(raw+route[13]));
emit(packetBase+13,y1);
const auto y0=_mm512_xor_si512(b0,_mm512_loadu_si512(raw+route[12]));
emit(packetBase+12,y0);
g31=_mm512_xor_si512(y1,y3);
g32=_mm512_xor_si512(y2,y3);
g30=_mm512_ternarylogic_epi64(y0,y2,g31,0x96);
g33=y3;
}
__m512i g20,g21,g22,g23;
{
const auto b0=_mm512_xor_si512(d0,d8);
const auto b1=_mm512_xor_si512(d1,d9);
const auto b2=_mm512_xor_si512(d2,d10);
const auto e1=_mm512_xor_si512(b0,b1);
const auto e2=_mm512_xor_si512(b0,b2);
const auto e3=_mm512_xor_si512(_mm512_xor_si512(e1,b2),d3);
const auto y3=_mm512_xor_si512(e3,_mm512_loadu_si512(raw+route[11]));
emit(packetBase+11,y3);
const auto y2=_mm512_xor_si512(e2,_mm512_loadu_si512(raw+route[10]));
emit(packetBase+10,y2);
const auto y1=_mm512_xor_si512(e1,_mm512_loadu_si512(raw+route[9]));
emit(packetBase+9,y1);
const auto y0=_mm512_xor_si512(b0,_mm512_loadu_si512(raw+route[8]));
emit(packetBase+8,y0);
g21=_mm512_xor_si512(y1,y3);
g22=_mm512_xor_si512(y2,y3);
g20=_mm512_ternarylogic_epi64(y0,y2,g21,0x96);
g23=y3;
}
const auto cd0=_mm512_xor_si512(g20,g30);
const auto cd1=_mm512_xor_si512(g21,g31);
const auto cd2=_mm512_xor_si512(g22,g32);
const auto cd3=_mm512_xor_si512(g23,g33);
__m512i g10,g11,g12,g13;
{
const auto b0=_mm512_xor_si512(d0,d4);
const auto b1=_mm512_xor_si512(d1,d5);
const auto b2=_mm512_xor_si512(d2,d6);
const auto e1=_mm512_xor_si512(b0,b1);
const auto e2=_mm512_xor_si512(b0,b2);
const auto e3=_mm512_xor_si512(_mm512_xor_si512(e1,b2),d3);
const auto y3=_mm512_xor_si512(e3,_mm512_loadu_si512(raw+route[7]));
emit(packetBase+7,y3);
const auto y2=_mm512_xor_si512(e2,_mm512_loadu_si512(raw+route[6]));
emit(packetBase+6,y2);
const auto y1=_mm512_xor_si512(e1,_mm512_loadu_si512(raw+route[5]));
emit(packetBase+5,y1);
const auto y0=_mm512_xor_si512(b0,_mm512_loadu_si512(raw+route[4]));
emit(packetBase+4,y0);
g11=_mm512_xor_si512(y1,y3);
g12=_mm512_xor_si512(y2,y3);
g10=_mm512_ternarylogic_epi64(y0,y2,g11,0x96);
g13=y3;
}
__m512i g00,g01,g02,g03;
{
const auto b0=d0;
const auto b1=d1;
const auto b2=d2;
const auto e1=_mm512_xor_si512(b0,b1);
const auto e2=_mm512_xor_si512(b0,b2);
const auto e3=_mm512_xor_si512(_mm512_xor_si512(e1,b2),d3);
const auto y3=_mm512_xor_si512(e3,_mm512_loadu_si512(raw+route[3]));
emit(packetBase+3,y3);
const auto y2=_mm512_xor_si512(e2,_mm512_loadu_si512(raw+route[2]));
emit(packetBase+2,y2);
const auto y1=_mm512_xor_si512(e1,_mm512_loadu_si512(raw+route[1]));
emit(packetBase+1,y1);
const auto y0=_mm512_xor_si512(b0,_mm512_loadu_si512(raw+route[0]));
emit(packetBase+0,y0);
g01=_mm512_xor_si512(y1,y3);
g02=_mm512_xor_si512(y2,y3);
g00=_mm512_ternarylogic_epi64(y0,y2,g01,0x96);
g03=y3;
}
high[0]=_mm512_ternarylogic_epi64(g00,g10,cd0,0x96);
high[4]=_mm512_xor_si512(g10,g30);
high[8]=cd0;
high[1]=_mm512_ternarylogic_epi64(g01,g11,cd1,0x96);
high[5]=_mm512_xor_si512(g11,g31);
high[9]=cd1;
high[2]=_mm512_ternarylogic_epi64(g02,g12,cd2,0x96);
high[6]=_mm512_xor_si512(g12,g32);
high[10]=cd2;
high[3]=_mm512_ternarylogic_epi64(g03,g13,cd3,0x96);
high[12]=g30;

}
template<unsigned Extra,class Emit>
static SPIN_FORCEINLINE void streamStepBorder(const __m128i* state,
const __m128i* extra,const block* raw,const std::uint32_t* route,std::size_t packetBase,Emit& emit,__m128i* moments){
alignas(64) __m512i high[16];
streamStepHighBorder<Extra>(state,extra,raw,route,packetBase,emit,high);

storeLowMoments<0,2>(high[0],moments);
storeLowMoments<4,1>(high[1],moments);
storeLowMoments<8,1>(high[2],moments);
storeLowMoments<12,0>(high[3],moments);
storeLowMoments<16,1>(high[4],moments);
storeLowMoments<20,0>(high[5],moments);
storeLowMoments<24,0>(high[6],moments);
storeLowMoments<32,1>(high[8],moments);
storeLowMoments<36,0>(high[9],moments);
storeLowMoments<40,0>(high[10],moments);
storeLowMoments<48,0>(high[12],moments);
}
}

namespace spin::detail::packet {
namespace {
using namespace large;
struct PackedExtra {__m512i lo,hi;};
template<unsigned Extra> static SPIN_FORCEINLINE PackedExtra packExtra(const __m128i* words) {
    const auto zero=_mm_setzero_si128();
    const auto a=join(words[0],Extra>=2?words[1]:zero,Extra>=3?words[2]:zero,Extra>=4?words[3]:zero);
    const auto b=_mm512_setzero_si512();
    const auto basis=_mm512_set1_epi64(0x0102040810204080ULL);
    return {_mm512_gf2p8affine_epi64_epi8(basis,_mm512_permutex2var_epi8(a,packIndex<0>(),b),0),
            _mm512_gf2p8affine_epi64_epi8(basis,_mm512_permutex2var_epi8(a,packIndex<8>(),b),0)};
}
template<unsigned Extra> static SPIN_FORCEINLINE void unpackExtra(const PackedExtra& packed,__m128i* words) {
    const auto basis=_mm512_set1_epi64(0x8040201008040201ULL);
    const auto lo=_mm512_gf2p8affine_epi64_epi8(basis,packed.lo,0);
    const auto hi=_mm512_gf2p8affine_epi64_epi8(basis,packed.hi,0);
    const auto joint=_mm512_permutex2var_epi8(lo,unpackIndex<0>(),hi);
    words[0]=_mm512_castsi512_si128(joint);
    if constexpr(Extra>=2)words[1]=_mm512_extracti32x4_epi32(joint,1);
    if constexpr(Extra>=3)words[2]=_mm512_extracti32x4_epi32(joint,2);
    if constexpr(Extra>=4)words[3]=_mm512_extracti32x4_epi32(joint,3);
}
static SPIN_FORCEINLINE void update(PackedState& state,PackedExtra& extra,const PackedState& feedback,
    const PackedExtra& extraFeedback,const BorderRow& row) {
    const auto r00=_mm512_set1_epi64(row.base.matrix[0]);
    const auto r01=_mm512_set1_epi64(row.base.matrix[1]);
    const auto r02=_mm512_set1_epi64(row.upper[0]);
    const auto n0=_mm512_xor_si512(_mm512_ternarylogic_epi64(
        _mm512_gf2p8affine_epi64_epi8(state.v[0],r00,0),
        _mm512_gf2p8affine_epi64_epi8(state.v[2],r01,0),
        _mm512_gf2p8affine_epi64_epi8(extra.lo,r02,0),0x96),feedback.v[0]);
    const auto n1=_mm512_xor_si512(_mm512_ternarylogic_epi64(
        _mm512_gf2p8affine_epi64_epi8(state.v[1],r00,0),
        _mm512_gf2p8affine_epi64_epi8(state.v[3],r01,0),
        _mm512_gf2p8affine_epi64_epi8(extra.hi,r02,0),0x96),feedback.v[1]);
    const auto r10=_mm512_set1_epi64(row.base.matrix[2]);
    const auto r11=_mm512_set1_epi64(row.base.matrix[3]);
    const auto r12=_mm512_set1_epi64(row.upper[1]);
    const auto n2=_mm512_xor_si512(_mm512_ternarylogic_epi64(
        _mm512_gf2p8affine_epi64_epi8(state.v[0],r10,0),
        _mm512_gf2p8affine_epi64_epi8(state.v[2],r11,0),
        _mm512_gf2p8affine_epi64_epi8(extra.lo,r12,0),0x96),feedback.v[2]);
    const auto n3=_mm512_xor_si512(_mm512_ternarylogic_epi64(
        _mm512_gf2p8affine_epi64_epi8(state.v[1],r10,0),
        _mm512_gf2p8affine_epi64_epi8(state.v[3],r11,0),
        _mm512_gf2p8affine_epi64_epi8(extra.hi,r12,0),0x96),feedback.v[3]);
    const auto r20=_mm512_set1_epi64(row.lower[0]);
    const auto r21=_mm512_set1_epi64(row.lower[1]);
    const auto r22=_mm512_set1_epi64(row.corner);
    const auto n4=_mm512_xor_si512(_mm512_ternarylogic_epi64(
        _mm512_gf2p8affine_epi64_epi8(state.v[0],r20,0),
        _mm512_gf2p8affine_epi64_epi8(state.v[2],r21,0),
        _mm512_gf2p8affine_epi64_epi8(extra.lo,r22,0),0x96),extraFeedback.lo);
    const auto n5=_mm512_xor_si512(_mm512_ternarylogic_epi64(
        _mm512_gf2p8affine_epi64_epi8(state.v[1],r20,0),
        _mm512_gf2p8affine_epi64_epi8(state.v[3],r21,0),
        _mm512_gf2p8affine_epi64_epi8(extra.hi,r22,0),0x96),extraFeedback.hi);
    state.v[0]=n0;state.v[1]=n1;state.v[2]=n2;state.v[3]=n3;
    extra.lo=n4;extra.hi=n5;
}
struct EpochOutput {
    __m512i* packets;
    SPIN_FORCEINLINE void operator()(std::size_t p,__m512i v) {packets[p&15]=v;}
};
template<bool Stream> static SPIN_FORCEINLINE void storeWide(Block* out,__m512i v) {
    if constexpr(Stream)_mm512_stream_si512(reinterpret_cast<__m512i*>(out),v);
    else _mm512_storeu_si512(out,v);
}
template<unsigned L,bool Stream> static SPIN_FORCEINLINE void emitWide(Block* out,const __m512i (&v)[L][16]) {
    const auto low=_mm512_setr_epi64(0,1,8,9,2,3,10,11);
    const auto high=_mm512_setr_epi64(4,5,12,13,6,7,14,15);
    for(unsigned p=0;p<16;++p) {
        const auto a=_mm512_permutex2var_epi64(v[0][p],low,v[1][p]);
        const auto b=_mm512_permutex2var_epi64(v[0][p],high,v[1][p]);
        if constexpr(L==2) {storeWide<Stream>(out+8*p,a);storeWide<Stream>(out+8*p+4,b);}
        else {
            const auto c=_mm512_permutex2var_epi64(v[2][p],low,v[3][p]);
            const auto d=_mm512_permutex2var_epi64(v[2][p],high,v[3][p]);
            storeWide<Stream>(out+16*p,_mm512_shuffle_i32x4(a,c,0x44));
            storeWide<Stream>(out+16*p+4,_mm512_shuffle_i32x4(a,c,0xee));
            storeWide<Stream>(out+16*p+8,_mm512_shuffle_i32x4(b,d,0x44));
            storeWide<Stream>(out+16*p+12,_mm512_shuffle_i32x4(b,d,0xee));
        }
    }
}
template<unsigned L,bool Stream,unsigned Extra=4>
static SPIN_NOINLINE void forwardBorder(const Block* input,std::size_t n,const BorderRow* rows,const std::uint32_t* route,Block* output,std::size_t stride) {
    alignas(64) __m128i words[16],extraWords[4],moments[64],syndrome[16],extraSyndrome[4];
    alignas(64) __m512i packets[16];
    PackedState states[L]{},feedback;PackedExtra extras[L]{};
    alignas(64) __m512i results[L][16];
    for(std::size_t epoch=0;epoch<n/64;++epoch) {
        const auto* addresses=route+16*epoch;const bool first=epoch==0;
        for(unsigned lane=0;lane<L;++lane) {
        const auto* raw=input+stride*lane;auto& state=states[lane];auto& extra=extras[lane];
        EpochOutput emit{results[lane]};
        if(first) {
            for(unsigned h=0;h<16;++h)packets[h]=_mm512_loadu_si512(raw+addresses[h]);
            for(unsigned h=16;h-->0;)emit(16*epoch+h,packets[h]);
        } else {
            wideUnpackVbmi(state,words);unpackExtra<Extra>(extra,extraWords);
            forwardfast::streamStepBorder<Extra>(words,extraWords,raw,addresses,16*epoch,emit,moments);
        }
        if(epoch+1==n/64)continue;
        if(first)packetMoments(packets,moments);
        finish(moments,syndrome);widePackVbmi(syndrome,feedback);
        extraSyndrome[0]=moments[3];
        if constexpr(Extra>=2)extraSyndrome[1]=moments[5];
        if constexpr(Extra>=3)extraSyndrome[2]=moments[9];
        if constexpr(Extra>=4)extraSyndrome[3]=moments[17];
        const auto extraFeedback=packExtra<Extra>(extraSyndrome);
        if(first){state=feedback;extra=extraFeedback;}
        else update(state,extra,feedback,extraFeedback,rows[epoch]);
        }
        emitWide<L,Stream>(output+64*L*epoch,results);
    }
}
}

template<unsigned L> void innerWide(const Block* in,Block* out,const Plan& p,const ForwardPlan& f,bool stream) {
    if(stream && (reinterpret_cast<std::uintptr_t>(out)&63U)==0) {
        forwardBorder<L,true>(in,p.n,f.updates.data(),p.route.data(),out,p.scratchBlocks());
        _mm_sfence();
    } else forwardBorder<L,false>(in,p.n,f.updates.data(),p.route.data(),out,p.scratchBlocks());
}

namespace wide256k16 {
struct V {__m512i lo,hi;};
static SPIN_FORCEINLINE __m256i vx(__m256i a,__m256i b){return _mm256_xor_si256(a,b);}
static SPIN_FORCEINLINE V px(V a,V b){return {_mm512_xor_si512(a.lo,b.lo),_mm512_xor_si512(a.hi,b.hi)};}
static SPIN_FORCEINLINE V pt(V a,V b,V c,int){return {_mm512_ternarylogic_epi64(a.lo,b.lo,c.lo,0x96),_mm512_ternarylogic_epi64(a.hi,b.hi,c.hi,0x96)};}
static SPIN_FORCEINLINE V join(__m256i a,__m256i b,__m256i c,__m256i d){return {_mm512_inserti64x4(_mm512_castsi256_si512(a),b,1),_mm512_inserti64x4(_mm512_castsi256_si512(c),d,1)};}
static SPIN_FORCEINLINE V broadcast(__m256i a){const auto x=_mm512_broadcast_i64x4(a);return {x,x};}
static SPIN_FORCEINLINE V load(const Block* raw,std::uint32_t offset,std::size_t stride){
 const auto a=_mm512_loadu_si512(raw+offset),b=_mm512_loadu_si512(raw+stride+offset);
 return {_mm512_permutex2var_epi64(a,_mm512_setr_epi64(0,1,8,9,2,3,10,11),b),_mm512_permutex2var_epi64(a,_mm512_setr_epi64(4,5,12,13,6,7,14,15),b)};
}
template<unsigned Mask,unsigned Degree> static SPIN_FORCEINLINE void storeLowMoments(V x,__m256i* moments){
 const auto folded=_mm512_xor_si512(x.lo,x.hi);const auto odd=_mm512_extracti64x4_epi64(folded,1);
 moments[Mask]=vx(_mm512_castsi512_si256(folded),odd);
 if constexpr(Degree>=1){const auto last=_mm512_extracti64x4_epi64(x.hi,1);moments[Mask+1]=odd;moments[Mask+2]=vx(_mm512_castsi512_si256(x.hi),last);if constexpr(Degree==2)moments[Mask+3]=last;}
}
template<bool Stream> struct Output {Block* out;SPIN_FORCEINLINE void operator()(std::size_t p,V v){
 if constexpr(Stream){_mm512_stream_si512(reinterpret_cast<__m512i*>(out+8*p),v.lo);_mm512_stream_si512(reinterpret_cast<__m512i*>(out+8*p+4),v.hi);}
 else {_mm512_storeu_si512(out+8*p,v.lo);_mm512_storeu_si512(out+8*p+4,v.hi);}
}};
struct FourMoments {
    V z0, z1, z2, z3;
};
template<unsigned First>
static SPIN_FORCEINLINE FourMoments firstStage(const V* packets) {
    const auto x0 = packets[First];
    const auto x1 = packets[First + 1];
    const auto x2 = packets[First + 2];
    const auto x3 = packets[First + 3];
    const auto z1 = px(x1, x3);
    const auto z2 = px(x2, x3);
    const auto z0 = pt(x0, x2, z1, 0x96);
    return {z0, z1, z2, x3};
}
static SPIN_FORCEINLINE void packetMoments(
    const V* packets, __m256i* moments) {



    const auto a = firstStage<0>(packets);
    const auto b = firstStage<4>(packets);
    const auto c = firstStage<8>(packets);
    const auto d = firstStage<12>(packets);

    // The remaining high-index zeta is pruned to degree two. Together with
    // firstStage, this needs 15 binary XORs and 8 XOR3 operations.
    // Low lane folding then needs 27 logical operations and 27 extracts.
    const auto z4 = px(b.z0, d.z0);
    const auto z8 = px(c.z0, d.z0);
    const auto z0 = pt(a.z0, c.z0, z4, 0x96);
    storeLowMoments<0, 2>(z0, moments);
    storeLowMoments<16, 1>(z4, moments);
    storeLowMoments<32, 1>(z8, moments);
    storeLowMoments<48, 0>(d.z0, moments);

    const auto z5 = px(b.z1, d.z1);
    const auto z9 = px(c.z1, d.z1);
    const auto z1 = pt(a.z1, c.z1, z5, 0x96);
    storeLowMoments<4, 1>(z1, moments);
    storeLowMoments<20, 0>(z5, moments);
    storeLowMoments<36, 0>(z9, moments);

    const auto z6 = px(b.z2, d.z2);
    const auto z10 = px(c.z2, d.z2);
    const auto z2 = pt(a.z2, c.z2, z6, 0x96);
    storeLowMoments<8, 1>(z2, moments);
    storeLowMoments<24, 0>(z6, moments);
    storeLowMoments<40, 0>(z10, moments);

    const auto z3 = pt(a.z3, b.z3,
        px(c.z3, d.z3), 0x96);
    storeLowMoments<12, 0>(z3, moments);
}
static SPIN_FORCEINLINE void finish(const __m256i* z,__m256i* out){
// P A^T on the same 22 zeta moments: 32 XMM XORs.
const auto fse0=vx(z[9],z[34]);
const auto fse1=vx(z[5],z[6]);
const auto fse2=vx(z[24],fse0);
const auto fse3=vx(z[33],z[36]);
const auto fse4=vx(z[10],z[12]);
const auto fse5=vx(z[18],z[48]);
const auto fse6=vx(z[20],z[40]);
const auto fse7=vx(fse3,fse5);
const auto fse8=vx(z[17],fse1);
const auto fse9=vx(z[40],fse2);
const auto fse10=vx(fse4,fse7);
const auto f0=z[0];
const auto f1=z[1];
const auto f2=z[2];
const auto f3=z[4];
const auto f4=z[8];
const auto f5=z[16];
const auto f6=z[32];
const auto f7=vx(z[34],fse6);
const auto f8=vx(vx(vx(z[9],z[12]),z[20]),fse8);
const auto f9=vx(vx(vx(z[18],fse1),fse2),fse4);
const auto f10=vx(vx(fse1,fse6),fse7);
const auto f11=vx(vx(vx(z[17],z[24]),z[34]),fse10);
const auto f12=vx(vx(vx(z[48],fse2),fse6),fse8);
const auto f13=vx(z[33],fse9);
const auto f14=vx(vx(vx(z[3],z[6]),fse0),fse10);
const auto f15=vx(vx(z[5],fse3),fse9);
out[0]=f0;
out[1]=f1;
out[2]=f2;
out[3]=f3;
out[4]=f4;
out[5]=f5;
out[6]=f6;
out[7]=f7;
out[8]=f8;
out[9]=f9;
out[10]=f10;
out[11]=f11;
out[12]=f12;
out[13]=f13;
out[14]=f14;
out[15]=f15;
}
template<unsigned Extra,class Emit>
static SPIN_FORCEINLINE void streamStepHighBorder(const __m256i* state,
const __m256i* extra,const Block* raw,const std::uint32_t* route,std::size_t packetBase,std::size_t stride,Emit& emit,V* high){
// State to 22 ANF coefficients: 12 XMM XORs.
const auto cs0=vx(state[10],state[12]);
const auto cs1=vx(state[12],state[15]);
const auto cs2=vx(state[11],state[13]);
const auto c0=state[0];
const auto c1=state[1];
const auto c2=state[2];
const auto c3=vx(state[7],extra[0]);
const auto c4=state[3];
const auto c5=Extra>=2?vx(state[8],extra[1]):state[8];
const auto c6=state[12];
const auto c8=state[4];
const auto c9=Extra>=3?vx(state[9],extra[2]):state[9];
const auto c10=state[13];
const auto c12=state[15];
const auto c16=state[5];
const auto c17=Extra>=4?vx(state[10],extra[3]):state[10];
const auto c18=cs0;
const auto c20=vx(vx(state[9],state[14]),cs1);
const auto c24=vx(cs1,cs2);
const auto c32=state[6];
const auto c33=state[11];
const auto c34=state[14];
const auto c36=vx(vx(vx(vx(state[7],state[8]),state[9]),cs0),cs2);
const auto c40=vx(state[14],cs0);
const auto c48=vx(state[7],cs1);
const auto l01=vx(c0,c1);
const auto l02=vx(c0,c2);
const auto l03=vx(vx(l01,c2),c3);
const auto d0=join(c0,l01,l02,l03);
const auto l11=vx(c4,c5);
const auto l12=vx(c4,c6);
const auto l13=vx(l11,c6);
const auto d1=join(c4,l11,l12,l13);
const auto l21=vx(c8,c9);
const auto l22=vx(c8,c10);
const auto l23=vx(l21,c10);
const auto d2=join(c8,l21,l22,l23);
const auto d3=broadcast(c12);
const auto l41=vx(c16,c17);
const auto l42=vx(c16,c18);
const auto l43=vx(l41,c18);
const auto d4=join(c16,l41,l42,l43);
const auto d5=broadcast(c20);
const auto d6=broadcast(c24);
const auto l81=vx(c32,c33);
const auto l82=vx(c32,c34);
const auto l83=vx(l81,c34);
const auto d8=join(c32,l81,l82,l83);
const auto d9=broadcast(c36);
const auto d10=broadcast(c40);
const auto d12=broadcast(c48);
// Shared group-2 coefficients reduce the block evaluator from29 to26 XORs.

V g30,g31,g32,g33;
{
const auto b0=px(px(px(d0,d4),d8),d12);
const auto b1=px(px(d1,d5),d9);
const auto b2=px(px(d2,d6),d10);
const auto e1=px(b0,b1);
const auto e2=px(b0,b2);
const auto e3=px(px(e1,b2),d3);
const auto y3=px(e3,load(raw,route[15],stride));
emit(packetBase+15,y3);
const auto y2=px(e2,load(raw,route[14],stride));
emit(packetBase+14,y2);
const auto y1=px(e1,load(raw,route[13],stride));
emit(packetBase+13,y1);
const auto y0=px(b0,load(raw,route[12],stride));
emit(packetBase+12,y0);
g31=px(y1,y3);
g32=px(y2,y3);
g30=pt(y0,y2,g31,0x96);
g33=y3;
}
V g20,g21,g22,g23;
{
const auto b0=px(d0,d8);
const auto b1=px(d1,d9);
const auto b2=px(d2,d10);
const auto e1=px(b0,b1);
const auto e2=px(b0,b2);
const auto e3=px(px(e1,b2),d3);
const auto y3=px(e3,load(raw,route[11],stride));
emit(packetBase+11,y3);
const auto y2=px(e2,load(raw,route[10],stride));
emit(packetBase+10,y2);
const auto y1=px(e1,load(raw,route[9],stride));
emit(packetBase+9,y1);
const auto y0=px(b0,load(raw,route[8],stride));
emit(packetBase+8,y0);
g21=px(y1,y3);
g22=px(y2,y3);
g20=pt(y0,y2,g21,0x96);
g23=y3;
}
const auto cd0=px(g20,g30);
const auto cd1=px(g21,g31);
const auto cd2=px(g22,g32);
const auto cd3=px(g23,g33);
V g10,g11,g12,g13;
{
const auto b0=px(d0,d4);
const auto b1=px(d1,d5);
const auto b2=px(d2,d6);
const auto e1=px(b0,b1);
const auto e2=px(b0,b2);
const auto e3=px(px(e1,b2),d3);
const auto y3=px(e3,load(raw,route[7],stride));
emit(packetBase+7,y3);
const auto y2=px(e2,load(raw,route[6],stride));
emit(packetBase+6,y2);
const auto y1=px(e1,load(raw,route[5],stride));
emit(packetBase+5,y1);
const auto y0=px(b0,load(raw,route[4],stride));
emit(packetBase+4,y0);
g11=px(y1,y3);
g12=px(y2,y3);
g10=pt(y0,y2,g11,0x96);
g13=y3;
}
V g00,g01,g02,g03;
{
const auto b0=d0;
const auto b1=d1;
const auto b2=d2;
const auto e1=px(b0,b1);
const auto e2=px(b0,b2);
const auto e3=px(px(e1,b2),d3);
const auto y3=px(e3,load(raw,route[3],stride));
emit(packetBase+3,y3);
const auto y2=px(e2,load(raw,route[2],stride));
emit(packetBase+2,y2);
const auto y1=px(e1,load(raw,route[1],stride));
emit(packetBase+1,y1);
const auto y0=px(b0,load(raw,route[0],stride));
emit(packetBase+0,y0);
g01=px(y1,y3);
g02=px(y2,y3);
g00=pt(y0,y2,g01,0x96);
g03=y3;
}
high[0]=pt(g00,g10,cd0,0x96);
high[4]=px(g10,g30);
high[8]=cd0;
high[1]=pt(g01,g11,cd1,0x96);
high[5]=px(g11,g31);
high[9]=cd1;
high[2]=pt(g02,g12,cd2,0x96);
high[6]=px(g12,g32);
high[10]=cd2;
high[3]=pt(g03,g13,cd3,0x96);
high[12]=g30;

}
template<unsigned Extra,class Emit>
static SPIN_FORCEINLINE void streamStepBorder(const __m256i* state,
const __m256i* extra,const Block* raw,const std::uint32_t* route,std::size_t packetBase,std::size_t stride,Emit& emit,__m256i* moments){
alignas(64) V high[16];
streamStepHighBorder<Extra>(state,extra,raw,route,packetBase,stride,emit,high);

storeLowMoments<0,2>(high[0],moments);
storeLowMoments<4,1>(high[1],moments);
storeLowMoments<8,1>(high[2],moments);
storeLowMoments<12,0>(high[3],moments);
storeLowMoments<16,1>(high[4],moments);
storeLowMoments<20,0>(high[5],moments);
storeLowMoments<24,0>(high[6],moments);
storeLowMoments<32,1>(high[8],moments);
storeLowMoments<36,0>(high[9],moments);
storeLowMoments<40,0>(high[10],moments);
storeLowMoments<48,0>(high[12],moments);
}
template<bool Stream> static SPIN_NOINLINE void run(const Block* input,Block* output,const Plan& p,const ForwardPlan& f){
 PackedState states[2]{},feedback;PackedExtra extras[2]{};
 alignas(64) __m128i unpacked[2][16],extraWords[2][4],syndrome128[16],extraSyndrome[4];
 alignas(64) __m256i words[16],ext[4],moments[64],syndrome[16];
 alignas(64) V packets[16];Output<Stream> emit{output};
 for(std::size_t epoch=0;epoch<p.n/64;++epoch){
  const auto* addresses=p.route.data()+16*epoch;const bool first=epoch==0;
  if(first){for(unsigned h=0;h<16;++h){packets[h]=load(input,addresses[h],p.scratchBlocks());emit(h,packets[h]);}}
  else {
   for(unsigned lane=0;lane<2;++lane){wideUnpackVbmi(states[lane],unpacked[lane]);unpackExtra<4>(extras[lane],extraWords[lane]);}
   for(unsigned j=0;j<16;++j)words[j]=_mm256_inserti128_si256(_mm256_castsi128_si256(unpacked[0][j]),unpacked[1][j],1);
   for(unsigned j=0;j<4;++j)ext[j]=_mm256_inserti128_si256(_mm256_castsi128_si256(extraWords[0][j]),extraWords[1][j],1);
   streamStepBorder<4>(words,ext,input,addresses,16*epoch,p.scratchBlocks(),emit,moments);
  }
  if(epoch+1==p.n/64)continue;
  if(first)packetMoments(packets,moments);
  finish(moments,syndrome);
  const auto finishLane=[&]<unsigned Lane>(){
   for(unsigned j=0;j<16;++j)syndrome128[j]=_mm256_extracti128_si256(syndrome[j],Lane);
   extraSyndrome[0]=_mm256_extracti128_si256(moments[3],Lane);
   extraSyndrome[1]=_mm256_extracti128_si256(moments[5],Lane);
   extraSyndrome[2]=_mm256_extracti128_si256(moments[9],Lane);
   extraSyndrome[3]=_mm256_extracti128_si256(moments[17],Lane);
   widePackVbmi(syndrome128,feedback);const auto ef=packExtra<4>(extraSyndrome);
   if(first){states[Lane]=feedback;extras[Lane]=ef;}else update(states[Lane],extras[Lane],feedback,ef,f.updates[epoch]);
  };
  finishLane.template operator()<0>();finishLane.template operator()<1>();
 }
 if constexpr(Stream)_mm_sfence();
}
}
void forwardInnerWide(const Block* in,Block* out,const Plan& p,const ForwardPlan& f,unsigned lanes,bool stream) {
    if(lanes==2 && p.k==65536) {
        if(stream && (reinterpret_cast<std::uintptr_t>(out)&63U)==0)wide256k16::run<true>(in,out,p,f);
        else wide256k16::run<false>(in,out,p,f);
    } else if(lanes==2)innerWide<2>(in,out,p,f,stream);else innerWide<4>(in,out,p,f,stream);
}
}
