// Generated by spin/tools/import_packet.py; do not edit by hand.
// Selected exact t64/s16 packet transpose. Private to PacketFast.cpp.
// Source research/workstreams/permutation_locality/outer_transpose_codegen.py: 3ecd30a8997969b3e466c3dae6250907416bfd4495532a81048f03d71c1a5776
// Source research/workstreams/permutation_locality/outer_unpack_codegen.py: 64520ba7b61c9ae31dc0228fc4a1db968e5d0a443bb69dd2b900a32a6cc0d326
// Source research/workstreams/permutation_locality/outer_layout_codegen.py: 729d6133911e3e94bc7774c4c56b69f6f3a84ba58087d0fc6151ac8207ac4fbf
// Source research/workstreams/permutation_locality/packed_coeff_codegen.py: 2526f7caf159fc4b209a89c9063633799c9b4eea74a9d66b84a8cb235182ffbe
// Source research/workstreams/permutation_locality/packed_bch_tune_codegen.py: d58daea63388b6bb9cf0a6b3d7f3c7014d1f7b04cff3bf21c34e22369dab26eb
// Source spin/src/kernels/generated/BchCircuit.h: c13131ca9d02861ac5b4688849a4550196120abdce5c5aa0bec7df71eac02424
#pragma once

#include "../kernels/Block.h"
#include <cstdint>
namespace spin::detail::packet::fast {
using block=storage::block;

static constexpr std::uint64_t parityMasks[16]={0xffff0000ff00ffffULL,0xffffffffff00ff00ULL,0x0000ffff00000000ULL,0xffff00ff00ffff00ULL,0xffffffff00000000ULL,0xffff00ff0000ffffULL,0xffff0000ffffff00ULL,0x000000000000ff00ULL,0xffffff00ff000000ULL,0x00000000ffff00ffULL,0xffffff0000ffffffULL,0xffff0000000000ffULL,0xff0000ff00ffff00ULL,0x0000000000ffffffULL,0xffff00ff00ff0000ULL,0x0000ff0000ffff00ULL};
static SPIN_FORCEINLINE void packedTuneByteTranspose5(__m512i& x0,__m512i& x1,__m512i& x2,__m512i& x3,__m512i& x4,__m512i& x5,__m512i& x6,__m512i& x7) {
const auto t0=_mm512_unpacklo_epi8(x0,x1);
const auto t1=_mm512_unpackhi_epi8(x0,x1);
const auto t2=_mm512_unpacklo_epi8(x2,x3);
const auto t3=_mm512_unpackhi_epi8(x2,x3);
const auto t4=_mm512_unpacklo_epi8(x4,x5);
const auto t5=_mm512_unpackhi_epi8(x4,x5);
const auto t6=_mm512_unpacklo_epi8(x6,x7);
const auto t7=_mm512_unpackhi_epi8(x6,x7);
const auto u0=_mm512_unpacklo_epi16(t0,t2);
const auto u1=_mm512_unpackhi_epi16(t0,t2);
const auto u2=_mm512_unpacklo_epi16(t1,t3);
const auto u3=_mm512_unpackhi_epi16(t1,t3);
const auto u4=_mm512_unpacklo_epi16(t4,t6);
const auto u5=_mm512_unpackhi_epi16(t4,t6);
const auto u6=_mm512_unpacklo_epi16(t5,t7);
const auto u7=_mm512_unpackhi_epi16(t5,t7);
x0=_mm512_unpacklo_epi32(u0,u4);
x1=_mm512_unpackhi_epi32(u0,u4);
x2=_mm512_unpacklo_epi32(u1,u5);
x3=_mm512_unpackhi_epi32(u1,u5);
x4=_mm512_unpacklo_epi32(u2,u6);
x5=_mm512_unpackhi_epi32(u2,u6);
x6=_mm512_unpacklo_epi32(u3,u7);
x7=_mm512_unpackhi_epi32(u3,u7);
}
static SPIN_FORCEINLINE void packedTunePack5(__m512i& x0,__m512i& x1,__m512i& x2,__m512i& x3,__m512i& x4,__m512i& x5,__m512i& x6,__m512i& x7) {
packedTuneByteTranspose5(x7,x6,x5,x4,x3,x2,x1,x0);
const auto basis=_mm512_set1_epi64(0x0102040810204080ULL);
const auto y0=_mm512_gf2p8affine_epi64_epi8(basis,x7,0);
const auto y1=_mm512_gf2p8affine_epi64_epi8(basis,x6,0);
const auto y2=_mm512_gf2p8affine_epi64_epi8(basis,x5,0);
const auto y3=_mm512_gf2p8affine_epi64_epi8(basis,x4,0);
const auto y4=_mm512_gf2p8affine_epi64_epi8(basis,x3,0);
const auto y5=_mm512_gf2p8affine_epi64_epi8(basis,x2,0);
const auto y6=_mm512_gf2p8affine_epi64_epi8(basis,x1,0);
const auto y7=_mm512_gf2p8affine_epi64_epi8(basis,x0,0);
x0=y0;
x1=y1;
x2=y2;
x3=y3;
x4=y4;
x5=y5;
x6=y6;
x7=y7;
}
alignas(64) static constexpr std::uint64_t transposedMatrices[16][16]={
{0xf1783c2914bd69b4ULL,0x428c6b94ca691527ULL,0xd63dc8d96cdd53ffULL,0xac47b2c462bdc3f0ULL,0x9451338643250d1dULL,0x1301887cbe6f8f4fULL,0x034262bb5d67b99fULL,0x82740fdc6e59f74eULL,0x0a4065289495d0adULL,0xb18f9045224b2843ULL,0x659368040210b8fdULL,0x7c238c12890dd2f4ULL,0x8df8c26733219675ULL,0x4193fa349ab7927aULL,0xbbf5d2bfdf919e67ULL,0xb50f92e5b2605cbbULL},
{0x0db1352dcc51a839ULL,0xb4561980532512bbULL,0xda86812bea1e8f85ULL,0x50a43797b355aab0ULL,0xab51b9d862b55a3cULL,0x72099bfdd95c2e08ULL,0xcfae1240ef3e9f0aULL,0xc50c7a538ea9d496ULL,0xc43d5276ed299406ULL,0xf3a3fda473e37194ULL,0x4fb6151bf368b414ULL,0x5e661dc719c5629fULL,0xeb4d1ab56088441eULL,0xf002f5003de4f20dULL,0x1076de11bb2311edULL,0xd9559b74e74a25a3ULL},
{0x0c31f52010088475ULL,0x11a9cbf6562b152bULL,0x7a80d4959ccee7ceULL,0x865e5b553b1d0e9aULL,0x1017814ebcdeef68ULL,0xe1c8f3de67b35994ULL,0x1f05848d0502018aULL,0xbc054b02349acd3dULL,0x46b955fc3b9d4ebdULL,0xd7e608a585c2e1fdULL,0xc7d386bd7f3f9fffULL,0x09509b3706038114ULL,0x1a0b07b9e271b8daULL,0x3a54edcbd6eb7573ULL,0x18daa0e3d96cb68dULL,0xdac1845fba9d8eebULL},
{0x592c2110650558acULL,0xd841ac5699ede55fULL,0x0bd30281023ce1a6ULL,0x1d1f0381a5cf9fdeULL,0x82da69348b5a230aULL,0x98c452a94b1d299cULL,0x5ced3f9f0a0fc827ULL,0x173e713860ebd25cULL,0x6e7266b31510deaaULL,0x69636b3536162a42ULL,0xcec672b912b92230ULL,0x28898dc64df283dcULL,0x003e2793f57c043cULL,0x22a22b95be16b668ULL,0x7d16f5fa18da5e07ULL,0x3a887d3eaefb60a5ULL},
{0x3da9399c94100869ULL,0xdce2c3ccf544228eULL,0xbd3558fa02a8543eULL,0x73357f2eef9e4fd3ULL,0x56afc6f8f26c3611ULL,0x0fb7c46a1226131eULL,0x62f8b99f80cc66b5ULL,0x6b5bd15d89d6ebbcULL,0x869c828414198ccfULL,0x84986067127fbf24ULL,0x6925dc4fd9b35943ULL,0x4def5931e2160b36ULL,0x5693750438180c04ULL,0x2d6c429274341acaULL,0x664dc3c957b05861ULL,0x41d91d9b5060303cULL},
{0x190c3198cc514515ULL,0x84effbfd53885ba1ULL,0xae812b951c338dadULL,0xb54ba9d47b20e4feULL,0xb0432512129641a4ULL,0xf9f44aa55a159d7eULL,0x3c5de773fa773d57ULL,0xa8e11e0fb202c80aULL,0x2f52f67b78a6dab2ULL,0xef204a25c56fccbcULL,0x9eeee6f3d85cc1f1ULL,0x8a58e5f264668009ULL,0xd1d653292a93cbddULL,0x2f24683429dda9aeULL,0xf8d4148aeda09d30ULL,0xf12defb70e6b11f1ULL},
{0xe97460dd59c1605dULL,0x609ddd7119bef24bULL,0xfca82b81fd3cc826ULL,0xa3c0187821f56b50ULL,0x091f814a3a0c9d5fULL,0xd964159df6643a82ULL,0x75f9339fc527506dULL,0xc3540d4ffc0234e6ULL,0x64f7ad5fb5164e6bULL,0x1adacc9d430dd1c4ULL,0xf3d81266830f265dULL,0x260efdcdb27726bdULL,0x5992733b1b3126afULL,0xbb6e0a42e88073cdULL,0xbaf549e9a2b4725cULL,0x49b145066f8616baULL},
{0x84188c1c549d14bdULL,0xe34fa7edc8451c82ULL,0x343399659bf0d183ULL,0xc00904eb1c13e07cULL,0xfbe8f46f228e522dULL,0x9565b2f65492e6c3ULL,0xceeb753697c16cffULL,0x2d8442330b5ebd30ULL,0x0292c9f768ae44fdULL,0x0b73b92a633ce82eULL,0xf9a351f7a4e22e86ULL,0xf61c0e60577f58e5ULL,0xa850a8502c100cbeULL,0x6eb95ca05e663de4ULL,0xb640a0cbfea94fd9ULL,0xf3f1b8d4e2dde64aULL},
{0xd5ddb46dec2cccbcULL,0x201c1d82ff6c08baULL,0x1c654dcdcf18253bULL,0xc1ec8ecb8c3e7652ULL,0x359e4124070d93dcULL,0xdfdf48142535b575ULL,0x70f137d2e53d1285ULL,0xbd303ff16a92db7fULL,0x606f61ef64e46123ULL,0x234b8418fadc18faULL,0x82d0169a12f7244dULL,0x3ad4104147d98b22ULL,0xfec759148e7dba59ULL,0xb9262e6d38219ec1ULL,0xca1bbe210b36805bULL,0xb360ed4f6feafdf6ULL},
{0xa40884758d1c3971ULL,0x33a7d3c8c5f17425ULL,0x09add656167451bcULL,0x45cbe56f2aed7a49ULL,0xa045220e18028548ULL,0x02ae5713313f2f80ULL,0x399048aedd21d96aULL,0x81d269efacf19682ULL,0xfa6e37815afba258ULL,0xf00e070e0a24c81fULL,0xcf389c7e0ff9ed99ULL,0x3df9fcaa01fa3429ULL,0xbf5bad50ae6d0e85ULL,0xaed96c7f7686b99bULL,0xa6c8e4a404b1265eULL,0x7a753a7154f74205ULL},
{0x957d646859414dfcULL,0xdbe1e3e26e28a640ULL,0xeb1e7047b7cf25edULL,0xd9e0883c6ac1057aULL,0x0d020f89ce6da75dULL,0x6683e6543d89db4aULL,0x62f8b3160d0045edULL,0x0b6b92ee3e56d74cULL,0xbe00d6bd57a21d58ULL,0x19d6ca44595707a2ULL,0x875257d505ed3862ULL,0xf732e38b7688ea8fULL,0xb96488fe7dbc620bULL,0x6ecd5b908f803427ULL,0x7bc3521ac0ad332aULL,0x30e16deb91ac27ceULL},
{0xa9d430188c1c39f1ULL,0xeddb7e3f9f7199d3ULL,0xba0b7a3d9e668e53ULL,0xeae40a85c2081978ULL,0x31030f87c3f46538ULL,0x93c1472391e7cbf2ULL,0x4063feff7f33934fULL,0xd0ddc9e4722b4eeeULL,0x27d6bd5e2f84d8e5ULL,0x5afa5cae575d236aULL,0x0d276d369b92f993ULL,0x1b1072399ca900b3ULL,0xcfd956ab552e110aULL,0x1738a150a85ae435ULL,0x042aa6d3e96fe13dULL,0xc234c7a391c0cc82ULL},
{0xa0d08518e19d143dULL,0xa9f9e3cfd5752998ULL,0x2842b573fb69cb0eULL,0x1a9c3af41f7bc5eeULL,0xbdc5e8e1e17ab35dULL,0x78340d298bd2ce57ULL,0xffbc5820d5ecb995ULL,0x8776f26bc9adf116ULL,0x526cbf4c6a3c487bULL,0x79eb0ef1d491e9aeULL,0x45036e687a52d77aULL,0x3901b33e31abaf9eULL,0x4f190e03bddc5492ULL,0x322ad26747648fbdULL,0xd0c0adcd830cb5a4ULL,0xa105265b9caa48ddULL},
{0x24c86468d901ed41ULL,0xf0c6638fd8730b09ULL,0xcfce671a99d82efcULL,0x3b74bab4aea33416ULL,0x01954a301203904cULL,0x4f88448dd17fa0e0ULL,0x95c6633d984a6079ULL,0x8dd4eae73ad41665ULL,0x24018053a059e02fULL,0x46d5ea037a460f5dULL,0x686bb5852df9b2c8ULL,0x0de170dfdc5d0049ULL,0xa556ab512a17b7e3ULL,0x9ec160be980bf102ULL,0xcefcfe647ff21cf0ULL,0x466b35520d22a069ULL},
{0xedace17055f0f8fcULL,0x56b85028262d3b9dULL,0x32e6984c649b9bcdULL,0x09fc72b9b9b54ba5ULL,0xb8d26d360a905329ULL,0xae7088c47d1180c0ULL,0xe7bc178b804c6532ULL,0xbb7ad3e908967e3fULL,0x3fc93b1d4232dc6eULL,0xe0517239b02ec060ULL,0x495a3c1e41ffde6fULL,0x1273f078126eaad5ULL,0x1db462b1e4768542ULL,0x7f82bb5ddae34221ULL,0xace58c46c6f854aaULL,0x46fe4623a0d8391cULL},
{0xda6dec2ca1bd04b5ULL,0x3e32278061afc4eeULL,0x29c2c89b702ce91fULL,0xe9e51b7527674b29ULL,0x15119dc07f35944eULL,0x2f9fe0d7533e382cULL,0x0c452e58a6d525dbULL,0x92fcec5173f05fc1ULL,0x13cc75ececff294bULL,0xf6aca0f1754101daULL,0xdf4ef8023177c5f3ULL,0x67ae30e2a5e18a8cULL,0x043c1a379d4c1c36ULL,0x8ef47407ca222c6cULL,0x9b6529a7054f14f4ULL,0x48b1d075560fda54ULL},
};
template<unsigned output> static SPIN_NOINLINE void outerTile(const __m512i* __restrict src,block* __restrict out){
static_assert(output+2<=16);
const auto parityByte=_mm512_setr_epi64(0x0707070707070707ULL,0x0f0f0f0f0f0f0f0fULL,0x0707070707070707ULL,0x0f0f0f0f0f0f0f0fULL,0x0707070707070707ULL,0x0f0f0f0f0f0f0f0fULL,0x0707070707070707ULL,0x0f0f0f0f0f0f0f0fULL);
constexpr auto parity0=parityMasks[output+0];
auto y0=_mm512_load_si512(src+8*(output+0)+0);
if constexpr(output+0==15)y0=_mm512_and_si512(y0,_mm512_set1_epi64(0x00ffffffffffffffULL));
y0=_mm512_ternarylogic_epi64(y0,_mm512_shuffle_epi8(_mm512_load_si512(src+120+0),parityByte),_mm512_set1_epi64(parity0),0x78);
auto y1=_mm512_load_si512(src+8*(output+0)+1);
if constexpr(output+0==15)y1=_mm512_and_si512(y1,_mm512_set1_epi64(0x00ffffffffffffffULL));
y1=_mm512_ternarylogic_epi64(y1,_mm512_shuffle_epi8(_mm512_load_si512(src+120+1),parityByte),_mm512_set1_epi64(parity0),0x78);
auto y2=_mm512_load_si512(src+8*(output+0)+2);
if constexpr(output+0==15)y2=_mm512_and_si512(y2,_mm512_set1_epi64(0x00ffffffffffffffULL));
y2=_mm512_ternarylogic_epi64(y2,_mm512_shuffle_epi8(_mm512_load_si512(src+120+2),parityByte),_mm512_set1_epi64(parity0),0x78);
auto y3=_mm512_load_si512(src+8*(output+0)+3);
if constexpr(output+0==15)y3=_mm512_and_si512(y3,_mm512_set1_epi64(0x00ffffffffffffffULL));
y3=_mm512_ternarylogic_epi64(y3,_mm512_shuffle_epi8(_mm512_load_si512(src+120+3),parityByte),_mm512_set1_epi64(parity0),0x78);
auto y4=_mm512_load_si512(src+8*(output+0)+4);
if constexpr(output+0==15)y4=_mm512_and_si512(y4,_mm512_set1_epi64(0x00ffffffffffffffULL));
y4=_mm512_ternarylogic_epi64(y4,_mm512_shuffle_epi8(_mm512_load_si512(src+120+4),parityByte),_mm512_set1_epi64(parity0),0x78);
auto y5=_mm512_load_si512(src+8*(output+0)+5);
if constexpr(output+0==15)y5=_mm512_and_si512(y5,_mm512_set1_epi64(0x00ffffffffffffffULL));
y5=_mm512_ternarylogic_epi64(y5,_mm512_shuffle_epi8(_mm512_load_si512(src+120+5),parityByte),_mm512_set1_epi64(parity0),0x78);
auto y6=_mm512_load_si512(src+8*(output+0)+6);
if constexpr(output+0==15)y6=_mm512_and_si512(y6,_mm512_set1_epi64(0x00ffffffffffffffULL));
y6=_mm512_ternarylogic_epi64(y6,_mm512_shuffle_epi8(_mm512_load_si512(src+120+6),parityByte),_mm512_set1_epi64(parity0),0x78);
auto y7=_mm512_load_si512(src+8*(output+0)+7);
if constexpr(output+0==15)y7=_mm512_and_si512(y7,_mm512_set1_epi64(0x00ffffffffffffffULL));
y7=_mm512_ternarylogic_epi64(y7,_mm512_shuffle_epi8(_mm512_load_si512(src+120+7),parityByte),_mm512_set1_epi64(parity0),0x78);
constexpr auto parity1=parityMasks[output+1];
auto y8=_mm512_load_si512(src+8*(output+1)+0);
if constexpr(output+1==15)y8=_mm512_and_si512(y8,_mm512_set1_epi64(0x00ffffffffffffffULL));
y8=_mm512_ternarylogic_epi64(y8,_mm512_shuffle_epi8(_mm512_load_si512(src+120+0),parityByte),_mm512_set1_epi64(parity1),0x78);
auto y9=_mm512_load_si512(src+8*(output+1)+1);
if constexpr(output+1==15)y9=_mm512_and_si512(y9,_mm512_set1_epi64(0x00ffffffffffffffULL));
y9=_mm512_ternarylogic_epi64(y9,_mm512_shuffle_epi8(_mm512_load_si512(src+120+1),parityByte),_mm512_set1_epi64(parity1),0x78);
auto y10=_mm512_load_si512(src+8*(output+1)+2);
if constexpr(output+1==15)y10=_mm512_and_si512(y10,_mm512_set1_epi64(0x00ffffffffffffffULL));
y10=_mm512_ternarylogic_epi64(y10,_mm512_shuffle_epi8(_mm512_load_si512(src+120+2),parityByte),_mm512_set1_epi64(parity1),0x78);
auto y11=_mm512_load_si512(src+8*(output+1)+3);
if constexpr(output+1==15)y11=_mm512_and_si512(y11,_mm512_set1_epi64(0x00ffffffffffffffULL));
y11=_mm512_ternarylogic_epi64(y11,_mm512_shuffle_epi8(_mm512_load_si512(src+120+3),parityByte),_mm512_set1_epi64(parity1),0x78);
auto y12=_mm512_load_si512(src+8*(output+1)+4);
if constexpr(output+1==15)y12=_mm512_and_si512(y12,_mm512_set1_epi64(0x00ffffffffffffffULL));
y12=_mm512_ternarylogic_epi64(y12,_mm512_shuffle_epi8(_mm512_load_si512(src+120+4),parityByte),_mm512_set1_epi64(parity1),0x78);
auto y13=_mm512_load_si512(src+8*(output+1)+5);
if constexpr(output+1==15)y13=_mm512_and_si512(y13,_mm512_set1_epi64(0x00ffffffffffffffULL));
y13=_mm512_ternarylogic_epi64(y13,_mm512_shuffle_epi8(_mm512_load_si512(src+120+5),parityByte),_mm512_set1_epi64(parity1),0x78);
auto y14=_mm512_load_si512(src+8*(output+1)+6);
if constexpr(output+1==15)y14=_mm512_and_si512(y14,_mm512_set1_epi64(0x00ffffffffffffffULL));
y14=_mm512_ternarylogic_epi64(y14,_mm512_shuffle_epi8(_mm512_load_si512(src+120+6),parityByte),_mm512_set1_epi64(parity1),0x78);
auto y15=_mm512_load_si512(src+8*(output+1)+7);
if constexpr(output+1==15)y15=_mm512_and_si512(y15,_mm512_set1_epi64(0x00ffffffffffffffULL));
y15=_mm512_ternarylogic_epi64(y15,_mm512_shuffle_epi8(_mm512_load_si512(src+120+7),parityByte),_mm512_set1_epi64(parity1),0x78);
for(unsigned input=0;input<16;input+=2){
const auto m0=_mm512_set1_epi64(transposedMatrices[output+0][input]);
const auto n0=_mm512_set1_epi64(transposedMatrices[output+0][input+1]);
const auto m1=_mm512_set1_epi64(transposedMatrices[output+1][input]);
const auto n1=_mm512_set1_epi64(transposedMatrices[output+1][input+1]);
const auto x0=_mm512_load_si512(src+128+8*input+0);
const auto z0=_mm512_load_si512(src+136+8*input+0);
y0=_mm512_ternarylogic_epi64(y0,_mm512_gf2p8affine_epi64_epi8(m0,x0,0),_mm512_gf2p8affine_epi64_epi8(n0,z0,0),0x96);
y8=_mm512_ternarylogic_epi64(y8,_mm512_gf2p8affine_epi64_epi8(m1,x0,0),_mm512_gf2p8affine_epi64_epi8(n1,z0,0),0x96);
const auto x1=_mm512_load_si512(src+128+8*input+1);
const auto z1=_mm512_load_si512(src+136+8*input+1);
y1=_mm512_ternarylogic_epi64(y1,_mm512_gf2p8affine_epi64_epi8(m0,x1,0),_mm512_gf2p8affine_epi64_epi8(n0,z1,0),0x96);
y9=_mm512_ternarylogic_epi64(y9,_mm512_gf2p8affine_epi64_epi8(m1,x1,0),_mm512_gf2p8affine_epi64_epi8(n1,z1,0),0x96);
const auto x2=_mm512_load_si512(src+128+8*input+2);
const auto z2=_mm512_load_si512(src+136+8*input+2);
y2=_mm512_ternarylogic_epi64(y2,_mm512_gf2p8affine_epi64_epi8(m0,x2,0),_mm512_gf2p8affine_epi64_epi8(n0,z2,0),0x96);
y10=_mm512_ternarylogic_epi64(y10,_mm512_gf2p8affine_epi64_epi8(m1,x2,0),_mm512_gf2p8affine_epi64_epi8(n1,z2,0),0x96);
const auto x3=_mm512_load_si512(src+128+8*input+3);
const auto z3=_mm512_load_si512(src+136+8*input+3);
y3=_mm512_ternarylogic_epi64(y3,_mm512_gf2p8affine_epi64_epi8(m0,x3,0),_mm512_gf2p8affine_epi64_epi8(n0,z3,0),0x96);
y11=_mm512_ternarylogic_epi64(y11,_mm512_gf2p8affine_epi64_epi8(m1,x3,0),_mm512_gf2p8affine_epi64_epi8(n1,z3,0),0x96);
const auto x4=_mm512_load_si512(src+128+8*input+4);
const auto z4=_mm512_load_si512(src+136+8*input+4);
y4=_mm512_ternarylogic_epi64(y4,_mm512_gf2p8affine_epi64_epi8(m0,x4,0),_mm512_gf2p8affine_epi64_epi8(n0,z4,0),0x96);
y12=_mm512_ternarylogic_epi64(y12,_mm512_gf2p8affine_epi64_epi8(m1,x4,0),_mm512_gf2p8affine_epi64_epi8(n1,z4,0),0x96);
const auto x5=_mm512_load_si512(src+128+8*input+5);
const auto z5=_mm512_load_si512(src+136+8*input+5);
y5=_mm512_ternarylogic_epi64(y5,_mm512_gf2p8affine_epi64_epi8(m0,x5,0),_mm512_gf2p8affine_epi64_epi8(n0,z5,0),0x96);
y13=_mm512_ternarylogic_epi64(y13,_mm512_gf2p8affine_epi64_epi8(m1,x5,0),_mm512_gf2p8affine_epi64_epi8(n1,z5,0),0x96);
const auto x6=_mm512_load_si512(src+128+8*input+6);
const auto z6=_mm512_load_si512(src+136+8*input+6);
y6=_mm512_ternarylogic_epi64(y6,_mm512_gf2p8affine_epi64_epi8(m0,x6,0),_mm512_gf2p8affine_epi64_epi8(n0,z6,0),0x96);
y14=_mm512_ternarylogic_epi64(y14,_mm512_gf2p8affine_epi64_epi8(m1,x6,0),_mm512_gf2p8affine_epi64_epi8(n1,z6,0),0x96);
const auto x7=_mm512_load_si512(src+128+8*input+7);
const auto z7=_mm512_load_si512(src+136+8*input+7);
y7=_mm512_ternarylogic_epi64(y7,_mm512_gf2p8affine_epi64_epi8(m0,x7,0),_mm512_gf2p8affine_epi64_epi8(n0,z7,0),0x96);
y15=_mm512_ternarylogic_epi64(y15,_mm512_gf2p8affine_epi64_epi8(m1,x7,0),_mm512_gf2p8affine_epi64_epi8(n1,z7,0),0x96);
}
const auto fusedIndex0=_mm512_setr_epi64(0x4941090148400800ULL,0x4b430b034a420a02ULL,0x5951191158501810ULL,0x5b531b135a521a12ULL,0x6961292168602820ULL,0x6b632b236a622a22ULL,0x7971393178703830ULL,0x7b733b337a723a32ULL);
const auto fusedIndex1=_mm512_setr_epi64(0x4d450d054c440c04ULL,0x4f470f074e460e06ULL,0x5d551d155c541c14ULL,0x5f571f175e561e16ULL,0x6d652d256c642c24ULL,0x6f672f276e662e26ULL,0x7d753d357c743c34ULL,0x7f773f377e763e36ULL);
const auto fusedIndex2=_mm512_setr_epi64(0x4342414003020100ULL,0x4746454407060504ULL,0x4b4a49480b0a0908ULL,0x4f4e4d4c0f0e0d0cULL,0x5352515013121110ULL,0x5756555417161514ULL,0x5b5a59581b1a1918ULL,0x5f5e5d5c1f1e1d1cULL);
const auto fusedIndex3=_mm512_setr_epi64(0x6362616023222120ULL,0x6766656427262524ULL,0x6b6a69682b2a2928ULL,0x6f6e6d6c2f2e2d2cULL,0x7372717033323130ULL,0x7776757437363534ULL,0x7b7a79783b3a3938ULL,0x7f7e7d7c3f3e3d3cULL);
const auto fusedIndex4=_mm512_setr_epi64(0x0706050403020100ULL,0x4746454443424140ULL,0x0f0e0d0c0b0a0908ULL,0x4f4e4d4c4b4a4948ULL,0x1716151413121110ULL,0x5756555453525150ULL,0x1f1e1d1c1b1a1918ULL,0x5f5e5d5c5b5a5958ULL);
const auto fusedIndex5=_mm512_setr_epi64(0x2726252423222120ULL,0x6766656463626160ULL,0x2f2e2d2c2b2a2928ULL,0x6f6e6d6c6b6a6968ULL,0x3736353433323130ULL,0x7776757473727170ULL,0x3f3e3d3c3b3a3938ULL,0x7f7e7d7c7b7a7978ULL);
{
const auto basis=_mm512_set1_epi64(0x8040201008040201ULL);
const auto x0=y0;
const auto x1=y1;
const auto x2=y2;
const auto x3=y3;
const auto x4=y4;
const auto x5=y5;
const auto x6=y6;
const auto x7=y7;
const auto a0=_mm512_permutex2var_epi8(x0,fusedIndex0,x1);
const auto a1=_mm512_permutex2var_epi8(x0,fusedIndex1,x1);
const auto a2=_mm512_permutex2var_epi8(x2,fusedIndex0,x3);
const auto a3=_mm512_permutex2var_epi8(x2,fusedIndex1,x3);
const auto a4=_mm512_permutex2var_epi8(x4,fusedIndex0,x5);
const auto a5=_mm512_permutex2var_epi8(x4,fusedIndex1,x5);
const auto a6=_mm512_permutex2var_epi8(x6,fusedIndex0,x7);
const auto a7=_mm512_permutex2var_epi8(x6,fusedIndex1,x7);
const auto b0=_mm512_permutex2var_epi8(a0,fusedIndex2,a2);
const auto b1=_mm512_permutex2var_epi8(a0,fusedIndex3,a2);
const auto b2=_mm512_permutex2var_epi8(a1,fusedIndex2,a3);
const auto b3=_mm512_permutex2var_epi8(a1,fusedIndex3,a3);
const auto b4=_mm512_permutex2var_epi8(a4,fusedIndex2,a6);
const auto b5=_mm512_permutex2var_epi8(a4,fusedIndex3,a6);
const auto b6=_mm512_permutex2var_epi8(a5,fusedIndex2,a7);
const auto b7=_mm512_permutex2var_epi8(a5,fusedIndex3,a7);
const auto c0=_mm512_permutex2var_epi8(b0,fusedIndex4,b4);
_mm512_storeu_si512(out+0+8*(output+0)+0,c0);
const auto c1=_mm512_permutex2var_epi8(b0,fusedIndex5,b4);
_mm512_storeu_si512(out+128+8*(output+0)+0,c1);
const auto c2=_mm512_permutex2var_epi8(b1,fusedIndex4,b5);
_mm512_storeu_si512(out+256+8*(output+0)+0,c2);
const auto c3=_mm512_permutex2var_epi8(b1,fusedIndex5,b5);
_mm512_storeu_si512(out+384+8*(output+0)+0,c3);
const auto c4=_mm512_permutex2var_epi8(b2,fusedIndex4,b6);
_mm512_storeu_si512(out+0+8*(output+0)+4,c4);
const auto c5=_mm512_permutex2var_epi8(b2,fusedIndex5,b6);
_mm512_storeu_si512(out+128+8*(output+0)+4,c5);
const auto c6=_mm512_permutex2var_epi8(b3,fusedIndex4,b7);
_mm512_storeu_si512(out+256+8*(output+0)+4,c6);
const auto c7=_mm512_permutex2var_epi8(b3,fusedIndex5,b7);
_mm512_storeu_si512(out+384+8*(output+0)+4,c7);
}
{
const auto basis=_mm512_set1_epi64(0x8040201008040201ULL);
const auto x0=y8;
const auto x1=y9;
const auto x2=y10;
const auto x3=y11;
const auto x4=y12;
const auto x5=y13;
const auto x6=y14;
const auto x7=y15;
const auto a0=_mm512_permutex2var_epi8(x0,fusedIndex0,x1);
const auto a1=_mm512_permutex2var_epi8(x0,fusedIndex1,x1);
const auto a2=_mm512_permutex2var_epi8(x2,fusedIndex0,x3);
const auto a3=_mm512_permutex2var_epi8(x2,fusedIndex1,x3);
const auto a4=_mm512_permutex2var_epi8(x4,fusedIndex0,x5);
const auto a5=_mm512_permutex2var_epi8(x4,fusedIndex1,x5);
const auto a6=_mm512_permutex2var_epi8(x6,fusedIndex0,x7);
const auto a7=_mm512_permutex2var_epi8(x6,fusedIndex1,x7);
const auto b0=_mm512_permutex2var_epi8(a0,fusedIndex2,a2);
const auto b1=_mm512_permutex2var_epi8(a0,fusedIndex3,a2);
const auto b2=_mm512_permutex2var_epi8(a1,fusedIndex2,a3);
const auto b3=_mm512_permutex2var_epi8(a1,fusedIndex3,a3);
const auto b4=_mm512_permutex2var_epi8(a4,fusedIndex2,a6);
const auto b5=_mm512_permutex2var_epi8(a4,fusedIndex3,a6);
const auto b6=_mm512_permutex2var_epi8(a5,fusedIndex2,a7);
const auto b7=_mm512_permutex2var_epi8(a5,fusedIndex3,a7);
const auto c0=_mm512_permutex2var_epi8(b0,fusedIndex4,b4);
_mm512_storeu_si512(out+0+8*(output+1)+0,c0);
const auto c1=_mm512_permutex2var_epi8(b0,fusedIndex5,b4);
_mm512_storeu_si512(out+128+8*(output+1)+0,c1);
const auto c2=_mm512_permutex2var_epi8(b1,fusedIndex4,b5);
_mm512_storeu_si512(out+256+8*(output+1)+0,c2);
const auto c3=_mm512_permutex2var_epi8(b1,fusedIndex5,b5);
_mm512_storeu_si512(out+384+8*(output+1)+0,c3);
const auto c4=_mm512_permutex2var_epi8(b2,fusedIndex4,b6);
_mm512_storeu_si512(out+0+8*(output+1)+4,c4);
const auto c5=_mm512_permutex2var_epi8(b2,fusedIndex5,b6);
_mm512_storeu_si512(out+128+8*(output+1)+4,c5);
const auto c6=_mm512_permutex2var_epi8(b3,fusedIndex4,b7);
_mm512_storeu_si512(out+256+8*(output+1)+4,c6);
const auto c7=_mm512_permutex2var_epi8(b3,fusedIndex5,b7);
_mm512_storeu_si512(out+384+8*(output+1)+4,c7);
}

}
static SPIN_NOINLINE void outerCompact(const block* __restrict a,block* __restrict out,const std::uint64_t* __restrict coeff){

alignas(64) __m512i src[256];
const auto duplicate=_mm512_setr_epi64(0,0,1,1,2,2,3,3);
const auto duplicateOdd=_mm512_setr_epi64(3,3,0,0,1,1,2,2);
const auto reverseBytes=_mm512_setr_epi64(0x0001020304050607ULL,0x08090a0b0c0d0e0fULL,0x0001020304050607ULL,0x08090a0b0c0d0e0fULL,0x0001020304050607ULL,0x08090a0b0c0d0e0fULL,0x0001020304050607ULL,0x08090a0b0c0d0e0fULL);
const auto reverseEven=_mm512_setr_epi64(0x0001020304050607ULL,0x0001020304050607ULL,0x08090a0b0c0d0e0fULL,0x08090a0b0c0d0e0fULL,0x1011121314151617ULL,0x1011121314151617ULL,0x18191a1b1c1d1e1fULL,0x18191a1b1c1d1e1fULL);
const auto reverseOdd=_mm512_setr_epi64(0x18191a1b1c1d1e1fULL,0x18191a1b1c1d1e1fULL,0x0001020304050607ULL,0x0001020304050607ULL,0x08090a0b0c0d0e0fULL,0x08090a0b0c0d0e0fULL,0x1011121314151617ULL,0x1011121314151617ULL);
for(unsigned group=0;group<16;++group){
auto v0=_mm512_loadu_si512(a+4*(8*group+0));
auto v1=_mm512_loadu_si512(a+4*(8*group+1));
auto v2=_mm512_loadu_si512(a+4*(8*group+2));
auto v3=_mm512_loadu_si512(a+4*(8*group+3));
auto v4=_mm512_loadu_si512(a+4*(8*group+4));
auto v5=_mm512_loadu_si512(a+4*(8*group+5));
auto v6=_mm512_loadu_si512(a+4*(8*group+6));
auto v7=_mm512_loadu_si512(a+4*(8*group+7));
packedTunePack5(v0,v1,v2,v3,v4,v5,v6,v7);
const auto c0=_mm256_load_si256(reinterpret_cast<const __m256i*>(coeff+16*group+4*0));
const auto m0=_mm512_permutexvar_epi8(reverseEven,_mm512_castsi256_si512(c0));
const auto c1=_mm256_load_si256(reinterpret_cast<const __m256i*>(coeff+16*group+4*1));
const auto m1=_mm512_permutexvar_epi8(reverseOdd,_mm512_castsi256_si512(c1));
const auto c2=_mm256_load_si256(reinterpret_cast<const __m256i*>(coeff+16*group+4*2));
const auto m2=_mm512_permutexvar_epi8(reverseEven,_mm512_castsi256_si512(c2));
const auto c3=_mm256_load_si256(reinterpret_cast<const __m256i*>(coeff+16*group+4*3));
const auto m3=_mm512_permutexvar_epi8(reverseOdd,_mm512_castsi256_si512(c3));
{
const auto u=_mm512_shuffle_i32x4(v0,v0,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(m1,v0,0),_mm512_gf2p8affine_epi64_epi8(m3,u,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(m0,v0,0),_mm512_gf2p8affine_epi64_epi8(m2,u,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(src+8*group+0,mixed);
}
{
const auto u=_mm512_shuffle_i32x4(v1,v1,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(m1,v1,0),_mm512_gf2p8affine_epi64_epi8(m3,u,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(m0,v1,0),_mm512_gf2p8affine_epi64_epi8(m2,u,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(src+8*group+1,mixed);
}
{
const auto u=_mm512_shuffle_i32x4(v2,v2,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(m1,v2,0),_mm512_gf2p8affine_epi64_epi8(m3,u,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(m0,v2,0),_mm512_gf2p8affine_epi64_epi8(m2,u,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(src+8*group+2,mixed);
}
{
const auto u=_mm512_shuffle_i32x4(v3,v3,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(m1,v3,0),_mm512_gf2p8affine_epi64_epi8(m3,u,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(m0,v3,0),_mm512_gf2p8affine_epi64_epi8(m2,u,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(src+8*group+3,mixed);
}
{
const auto u=_mm512_shuffle_i32x4(v4,v4,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(m1,v4,0),_mm512_gf2p8affine_epi64_epi8(m3,u,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(m0,v4,0),_mm512_gf2p8affine_epi64_epi8(m2,u,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(src+8*group+4,mixed);
}
{
const auto u=_mm512_shuffle_i32x4(v5,v5,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(m1,v5,0),_mm512_gf2p8affine_epi64_epi8(m3,u,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(m0,v5,0),_mm512_gf2p8affine_epi64_epi8(m2,u,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(src+8*group+5,mixed);
}
{
const auto u=_mm512_shuffle_i32x4(v6,v6,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(m1,v6,0),_mm512_gf2p8affine_epi64_epi8(m3,u,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(m0,v6,0),_mm512_gf2p8affine_epi64_epi8(m2,u,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(src+8*group+6,mixed);
}
{
const auto u=_mm512_shuffle_i32x4(v7,v7,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(m1,v7,0),_mm512_gf2p8affine_epi64_epi8(m3,u,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(m0,v7,0),_mm512_gf2p8affine_epi64_epi8(m2,u,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(src+8*group+7,mixed);
}
}
for(unsigned group=16;group<32;++group){
auto v0=_mm512_loadu_si512(a+4*(8*group+0));
auto v1=_mm512_loadu_si512(a+4*(8*group+1));
auto v2=_mm512_loadu_si512(a+4*(8*group+2));
auto v3=_mm512_loadu_si512(a+4*(8*group+3));
auto v4=_mm512_loadu_si512(a+4*(8*group+4));
auto v5=_mm512_loadu_si512(a+4*(8*group+5));
auto v6=_mm512_loadu_si512(a+4*(8*group+6));
auto v7=_mm512_loadu_si512(a+4*(8*group+7));
packedTunePack5(v0,v1,v2,v3,v4,v5,v6,v7);
const auto c0=_mm256_load_si256(reinterpret_cast<const __m256i*>(coeff+16*group+4*0));
const auto m0=_mm512_permutexvar_epi64(duplicate,_mm512_castsi256_si512(c0));
const auto c1=_mm256_load_si256(reinterpret_cast<const __m256i*>(coeff+16*group+4*1));
const auto m1=_mm512_permutexvar_epi64(duplicateOdd,_mm512_castsi256_si512(c1));
const auto c2=_mm256_load_si256(reinterpret_cast<const __m256i*>(coeff+16*group+4*2));
const auto m2=_mm512_permutexvar_epi64(duplicate,_mm512_castsi256_si512(c2));
const auto c3=_mm256_load_si256(reinterpret_cast<const __m256i*>(coeff+16*group+4*3));
const auto m3=_mm512_permutexvar_epi64(duplicateOdd,_mm512_castsi256_si512(c3));
{
const auto u=_mm512_shuffle_i32x4(v0,v0,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(v0,m1,0),_mm512_gf2p8affine_epi64_epi8(u,m3,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(v0,m0,0),_mm512_gf2p8affine_epi64_epi8(u,m2,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(src+8*group+0,mixed);
}
{
const auto u=_mm512_shuffle_i32x4(v1,v1,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(v1,m1,0),_mm512_gf2p8affine_epi64_epi8(u,m3,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(v1,m0,0),_mm512_gf2p8affine_epi64_epi8(u,m2,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(src+8*group+1,mixed);
}
{
const auto u=_mm512_shuffle_i32x4(v2,v2,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(v2,m1,0),_mm512_gf2p8affine_epi64_epi8(u,m3,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(v2,m0,0),_mm512_gf2p8affine_epi64_epi8(u,m2,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(src+8*group+2,mixed);
}
{
const auto u=_mm512_shuffle_i32x4(v3,v3,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(v3,m1,0),_mm512_gf2p8affine_epi64_epi8(u,m3,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(v3,m0,0),_mm512_gf2p8affine_epi64_epi8(u,m2,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(src+8*group+3,mixed);
}
{
const auto u=_mm512_shuffle_i32x4(v4,v4,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(v4,m1,0),_mm512_gf2p8affine_epi64_epi8(u,m3,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(v4,m0,0),_mm512_gf2p8affine_epi64_epi8(u,m2,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(src+8*group+4,mixed);
}
{
const auto u=_mm512_shuffle_i32x4(v5,v5,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(v5,m1,0),_mm512_gf2p8affine_epi64_epi8(u,m3,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(v5,m0,0),_mm512_gf2p8affine_epi64_epi8(u,m2,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(src+8*group+5,mixed);
}
{
const auto u=_mm512_shuffle_i32x4(v6,v6,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(v6,m1,0),_mm512_gf2p8affine_epi64_epi8(u,m3,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(v6,m0,0),_mm512_gf2p8affine_epi64_epi8(u,m2,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(src+8*group+6,mixed);
}
{
const auto u=_mm512_shuffle_i32x4(v7,v7,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(v7,m1,0),_mm512_gf2p8affine_epi64_epi8(u,m3,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(v7,m0,0),_mm512_gf2p8affine_epi64_epi8(u,m2,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(src+8*group+7,mixed);
}
}
outerTile<0>(src,out);
outerTile<2>(src,out);
outerTile<4>(src,out);
outerTile<6>(src,out);
outerTile<8>(src,out);
outerTile<10>(src,out);
outerTile<12>(src,out);
outerTile<14>(src,out);
}
} // namespace spin::detail::packet::fast
