// Generated by tools/generate_packet_forward.py.
#include "PacketForward.h"
#include "PacketLargeInner.h"
namespace spin::detail::packet::forwardfast {
using namespace detail::packet::large;
template<unsigned Extra,class Emit>
static SPIN_FORCEINLINE void streamStepHighBorder(const __m128i* state,
const __m128i* extra,const block* raw,const std::uint32_t* route,std::size_t packetBase,Emit& emit,__m512i* high){
// State to 22 ANF coefficients: 12 XMM XORs.
const auto cs0=vx(state[10],state[12]);
const auto cs1=vx(state[12],state[15]);
const auto cs2=vx(state[11],state[13]);
const auto c0=state[0];
const auto c1=state[1];
const auto c2=state[2];
const auto c3=vx(state[7],extra[0]);
const auto c4=state[3];
const auto c5=Extra>=2?vx(state[8],extra[1]):state[8];
const auto c6=state[12];
const auto c8=state[4];
const auto c9=Extra>=3?vx(state[9],extra[2]):state[9];
const auto c10=state[13];
const auto c12=state[15];
const auto c16=state[5];
const auto c17=Extra>=4?vx(state[10],extra[3]):state[10];
const auto c18=cs0;
const auto c20=vx(vx(state[9],state[14]),cs1);
const auto c24=vx(cs1,cs2);
const auto c32=state[6];
const auto c33=state[11];
const auto c34=state[14];
const auto c36=vx(vx(vx(vx(state[7],state[8]),state[9]),cs0),cs2);
const auto c40=vx(state[14],cs0);
const auto c48=vx(state[7],cs1);
const auto l01=vx(c0,c1);
const auto l02=vx(c0,c2);
const auto l03=vx(vx(l01,c2),c3);
const auto d0=join(c0,l01,l02,l03);
const auto l11=vx(c4,c5);
const auto l12=vx(c4,c6);
const auto l13=vx(l11,c6);
const auto d1=join(c4,l11,l12,l13);
const auto l21=vx(c8,c9);
const auto l22=vx(c8,c10);
const auto l23=vx(l21,c10);
const auto d2=join(c8,l21,l22,l23);
const auto d3=_mm512_broadcast_i32x4(c12);
const auto l41=vx(c16,c17);
const auto l42=vx(c16,c18);
const auto l43=vx(l41,c18);
const auto d4=join(c16,l41,l42,l43);
const auto d5=_mm512_broadcast_i32x4(c20);
const auto d6=_mm512_broadcast_i32x4(c24);
const auto l81=vx(c32,c33);
const auto l82=vx(c32,c34);
const auto l83=vx(l81,c34);
const auto d8=join(c32,l81,l82,l83);
const auto d9=_mm512_broadcast_i32x4(c36);
const auto d10=_mm512_broadcast_i32x4(c40);
const auto d12=_mm512_broadcast_i32x4(c48);
// Shared group-2 coefficients reduce the block evaluator from29 to26 XORs.

__m512i g30,g31,g32,g33;
{
const auto b0=_mm512_xor_si512(_mm512_xor_si512(_mm512_xor_si512(d0,d4),d8),d12);
const auto b1=_mm512_xor_si512(_mm512_xor_si512(d1,d5),d9);
const auto b2=_mm512_xor_si512(_mm512_xor_si512(d2,d6),d10);
const auto e1=_mm512_xor_si512(b0,b1);
const auto e2=_mm512_xor_si512(b0,b2);
const auto e3=_mm512_xor_si512(_mm512_xor_si512(e1,b2),d3);
const auto y3=_mm512_xor_si512(e3,_mm512_loadu_si512(raw+route[15]));
emit(packetBase+15,y3);
const auto y2=_mm512_xor_si512(e2,_mm512_loadu_si512(raw+route[14]));
emit(packetBase+14,y2);
const auto y1=_mm512_xor_si512(e1,_mm512_loadu_si512(raw+route[13]));
emit(packetBase+13,y1);
const auto y0=_mm512_xor_si512(b0,_mm512_loadu_si512(raw+route[12]));
emit(packetBase+12,y0);
g31=_mm512_xor_si512(y1,y3);
g32=_mm512_xor_si512(y2,y3);
g30=_mm512_ternarylogic_epi64(y0,y2,g31,0x96);
g33=y3;
}
__m512i g20,g21,g22,g23;
{
const auto b0=_mm512_xor_si512(d0,d8);
const auto b1=_mm512_xor_si512(d1,d9);
const auto b2=_mm512_xor_si512(d2,d10);
const auto e1=_mm512_xor_si512(b0,b1);
const auto e2=_mm512_xor_si512(b0,b2);
const auto e3=_mm512_xor_si512(_mm512_xor_si512(e1,b2),d3);
const auto y3=_mm512_xor_si512(e3,_mm512_loadu_si512(raw+route[11]));
emit(packetBase+11,y3);
const auto y2=_mm512_xor_si512(e2,_mm512_loadu_si512(raw+route[10]));
emit(packetBase+10,y2);
const auto y1=_mm512_xor_si512(e1,_mm512_loadu_si512(raw+route[9]));
emit(packetBase+9,y1);
const auto y0=_mm512_xor_si512(b0,_mm512_loadu_si512(raw+route[8]));
emit(packetBase+8,y0);
g21=_mm512_xor_si512(y1,y3);
g22=_mm512_xor_si512(y2,y3);
g20=_mm512_ternarylogic_epi64(y0,y2,g21,0x96);
g23=y3;
}
const auto cd0=_mm512_xor_si512(g20,g30);
const auto cd1=_mm512_xor_si512(g21,g31);
const auto cd2=_mm512_xor_si512(g22,g32);
const auto cd3=_mm512_xor_si512(g23,g33);
__m512i g10,g11,g12,g13;
{
const auto b0=_mm512_xor_si512(d0,d4);
const auto b1=_mm512_xor_si512(d1,d5);
const auto b2=_mm512_xor_si512(d2,d6);
const auto e1=_mm512_xor_si512(b0,b1);
const auto e2=_mm512_xor_si512(b0,b2);
const auto e3=_mm512_xor_si512(_mm512_xor_si512(e1,b2),d3);
const auto y3=_mm512_xor_si512(e3,_mm512_loadu_si512(raw+route[7]));
emit(packetBase+7,y3);
const auto y2=_mm512_xor_si512(e2,_mm512_loadu_si512(raw+route[6]));
emit(packetBase+6,y2);
const auto y1=_mm512_xor_si512(e1,_mm512_loadu_si512(raw+route[5]));
emit(packetBase+5,y1);
const auto y0=_mm512_xor_si512(b0,_mm512_loadu_si512(raw+route[4]));
emit(packetBase+4,y0);
g11=_mm512_xor_si512(y1,y3);
g12=_mm512_xor_si512(y2,y3);
g10=_mm512_ternarylogic_epi64(y0,y2,g11,0x96);
g13=y3;
}
__m512i g00,g01,g02,g03;
{
const auto b0=d0;
const auto b1=d1;
const auto b2=d2;
const auto e1=_mm512_xor_si512(b0,b1);
const auto e2=_mm512_xor_si512(b0,b2);
const auto e3=_mm512_xor_si512(_mm512_xor_si512(e1,b2),d3);
const auto y3=_mm512_xor_si512(e3,_mm512_loadu_si512(raw+route[3]));
emit(packetBase+3,y3);
const auto y2=_mm512_xor_si512(e2,_mm512_loadu_si512(raw+route[2]));
emit(packetBase+2,y2);
const auto y1=_mm512_xor_si512(e1,_mm512_loadu_si512(raw+route[1]));
emit(packetBase+1,y1);
const auto y0=_mm512_xor_si512(b0,_mm512_loadu_si512(raw+route[0]));
emit(packetBase+0,y0);
g01=_mm512_xor_si512(y1,y3);
g02=_mm512_xor_si512(y2,y3);
g00=_mm512_ternarylogic_epi64(y0,y2,g01,0x96);
g03=y3;
}
high[0]=_mm512_ternarylogic_epi64(g00,g10,cd0,0x96);
high[4]=_mm512_xor_si512(g10,g30);
high[8]=cd0;
high[1]=_mm512_ternarylogic_epi64(g01,g11,cd1,0x96);
high[5]=_mm512_xor_si512(g11,g31);
high[9]=cd1;
high[2]=_mm512_ternarylogic_epi64(g02,g12,cd2,0x96);
high[6]=_mm512_xor_si512(g12,g32);
high[10]=cd2;
high[3]=_mm512_ternarylogic_epi64(g03,g13,cd3,0x96);
high[12]=g30;

}
template<unsigned Extra,class Emit>
static SPIN_FORCEINLINE void streamStepBorder(const __m128i* state,
const __m128i* extra,const block* raw,const std::uint32_t* route,std::size_t packetBase,Emit& emit,__m128i* moments){
alignas(64) __m512i high[16];
streamStepHighBorder<Extra>(state,extra,raw,route,packetBase,emit,high);

storeLowMoments<0,2>(high[0],moments);
storeLowMoments<4,1>(high[1],moments);
storeLowMoments<8,1>(high[2],moments);
storeLowMoments<12,0>(high[3],moments);
storeLowMoments<16,1>(high[4],moments);
storeLowMoments<20,0>(high[5],moments);
storeLowMoments<24,0>(high[6],moments);
storeLowMoments<32,1>(high[8],moments);
storeLowMoments<36,0>(high[9],moments);
storeLowMoments<40,0>(high[10],moments);
storeLowMoments<48,0>(high[12],moments);
}
}

namespace spin::detail::packet {
namespace {
using namespace large;
struct PackedExtra {__m512i lo,hi;};
template<unsigned Extra> static SPIN_FORCEINLINE PackedExtra packExtra(const __m128i* words) {
    const auto zero=_mm_setzero_si128();
    const auto a=join(words[0],Extra>=2?words[1]:zero,Extra>=3?words[2]:zero,Extra>=4?words[3]:zero);
    const auto b=_mm512_setzero_si512();
    const auto basis=_mm512_set1_epi64(0x0102040810204080ULL);
    return {_mm512_gf2p8affine_epi64_epi8(basis,_mm512_permutex2var_epi8(a,packIndex<0>(),b),0),
            _mm512_gf2p8affine_epi64_epi8(basis,_mm512_permutex2var_epi8(a,packIndex<8>(),b),0)};
}
template<unsigned Extra> static SPIN_FORCEINLINE void unpackExtra(const PackedExtra& packed,__m128i* words) {
    const auto basis=_mm512_set1_epi64(0x8040201008040201ULL);
    const auto lo=_mm512_gf2p8affine_epi64_epi8(basis,packed.lo,0);
    const auto hi=_mm512_gf2p8affine_epi64_epi8(basis,packed.hi,0);
    const auto joint=_mm512_permutex2var_epi8(lo,unpackIndex<0>(),hi);
    words[0]=_mm512_castsi512_si128(joint);
    if constexpr(Extra>=2)words[1]=_mm512_extracti32x4_epi32(joint,1);
    if constexpr(Extra>=3)words[2]=_mm512_extracti32x4_epi32(joint,2);
    if constexpr(Extra>=4)words[3]=_mm512_extracti32x4_epi32(joint,3);
}
static SPIN_FORCEINLINE void update(PackedState& state,PackedExtra& extra,const PackedState& feedback,
    const PackedExtra& extraFeedback,const BorderRow& row) {
    const auto r00=_mm512_set1_epi64(row.base.matrix[0]);
    const auto r01=_mm512_set1_epi64(row.base.matrix[1]);
    const auto r02=_mm512_set1_epi64(row.upper[0]);
    const auto n0=_mm512_xor_si512(_mm512_ternarylogic_epi64(
        _mm512_gf2p8affine_epi64_epi8(state.v[0],r00,0),
        _mm512_gf2p8affine_epi64_epi8(state.v[2],r01,0),
        _mm512_gf2p8affine_epi64_epi8(extra.lo,r02,0),0x96),feedback.v[0]);
    const auto n1=_mm512_xor_si512(_mm512_ternarylogic_epi64(
        _mm512_gf2p8affine_epi64_epi8(state.v[1],r00,0),
        _mm512_gf2p8affine_epi64_epi8(state.v[3],r01,0),
        _mm512_gf2p8affine_epi64_epi8(extra.hi,r02,0),0x96),feedback.v[1]);
    const auto r10=_mm512_set1_epi64(row.base.matrix[2]);
    const auto r11=_mm512_set1_epi64(row.base.matrix[3]);
    const auto r12=_mm512_set1_epi64(row.upper[1]);
    const auto n2=_mm512_xor_si512(_mm512_ternarylogic_epi64(
        _mm512_gf2p8affine_epi64_epi8(state.v[0],r10,0),
        _mm512_gf2p8affine_epi64_epi8(state.v[2],r11,0),
        _mm512_gf2p8affine_epi64_epi8(extra.lo,r12,0),0x96),feedback.v[2]);
    const auto n3=_mm512_xor_si512(_mm512_ternarylogic_epi64(
        _mm512_gf2p8affine_epi64_epi8(state.v[1],r10,0),
        _mm512_gf2p8affine_epi64_epi8(state.v[3],r11,0),
        _mm512_gf2p8affine_epi64_epi8(extra.hi,r12,0),0x96),feedback.v[3]);
    const auto r20=_mm512_set1_epi64(row.lower[0]);
    const auto r21=_mm512_set1_epi64(row.lower[1]);
    const auto r22=_mm512_set1_epi64(row.corner);
    const auto n4=_mm512_xor_si512(_mm512_ternarylogic_epi64(
        _mm512_gf2p8affine_epi64_epi8(state.v[0],r20,0),
        _mm512_gf2p8affine_epi64_epi8(state.v[2],r21,0),
        _mm512_gf2p8affine_epi64_epi8(extra.lo,r22,0),0x96),extraFeedback.lo);
    const auto n5=_mm512_xor_si512(_mm512_ternarylogic_epi64(
        _mm512_gf2p8affine_epi64_epi8(state.v[1],r20,0),
        _mm512_gf2p8affine_epi64_epi8(state.v[3],r21,0),
        _mm512_gf2p8affine_epi64_epi8(extra.hi,r22,0),0x96),extraFeedback.hi);
    state.v[0]=n0;state.v[1]=n1;state.v[2]=n2;state.v[3]=n3;
    extra.lo=n4;extra.hi=n5;
}
template<bool Stream> static SPIN_FORCEINLINE void storeOutput(Block* out,__m512i value) {
    if constexpr(Stream)_mm512_stream_si512(reinterpret_cast<__m512i*>(out),value);
    else _mm512_storeu_si512(out,value);
}
template<bool Stream> struct DirectOutput {
    Block* output;
    SPIN_FORCEINLINE void operator()(std::size_t p,__m512i value) {storeOutput<Stream>(output+4*p,value);}
};
template<unsigned Extra,class Emit>
static SPIN_NOINLINE void forwardBorder(const Block* input,std::size_t n,const BorderRow* rows,const std::uint32_t* route,Emit& emit) {
    alignas(64) __m128i words[16],extraWords[4],moments[64],syndrome[16],extraSyndrome[4];
    alignas(64) __m512i packets[16];
    PackedState state{},feedback;PackedExtra extra{};
    for(std::size_t epoch=0;epoch<n/64;++epoch) {
        const auto* raw=input;const auto* addresses=route+16*epoch;const bool first=epoch==0;
        if(first) {
            for(unsigned h=0;h<16;++h)packets[h]=_mm512_loadu_si512(raw+addresses[h]);
            for(unsigned h=16;h-->0;)emit(16*epoch+h,packets[h]);
        } else {
            wideUnpackVbmi(state,words);unpackExtra<Extra>(extra,extraWords);
            forwardfast::streamStepBorder<Extra>(words,extraWords,raw,addresses,16*epoch,emit,moments);
        }
        if(epoch+1==n/64)break;
        if(first)packetMoments(packets,moments);
        finish(moments,syndrome);widePackVbmi(syndrome,feedback);
        extraSyndrome[0]=moments[3];
        if constexpr(Extra>=2)extraSyndrome[1]=moments[5];
        if constexpr(Extra>=3)extraSyndrome[2]=moments[9];
        if constexpr(Extra>=4)extraSyndrome[3]=moments[17];
        const auto extraFeedback=packExtra<Extra>(extraSyndrome);
        if(first){state=feedback;extra=extraFeedback;}
        else update(state,extra,feedback,extraFeedback,rows[epoch]);
    }
}
}
void forwardInnerGather(const Block* in,Block* out,const Plan& p,const ForwardPlan& f,bool stream) {
    if(stream && (reinterpret_cast<std::uintptr_t>(out)&63U)==0) {
        DirectOutput<true> emit{out};
        forwardBorder<4>(in,p.n,f.updates.data(),p.route.data(),emit);
        _mm_sfence();
    } else {
        DirectOutput<false> emit{out};
        forwardBorder<4>(in,p.n,f.updates.data(),p.route.data(),emit);
    }
}
}
