// Generated by spin/tools/import_packet.py; do not edit by hand.
// Retained inner_fusion_probe mode 19 and PackedCoeff1 tile-mode 1.
// Source research/workstreams/permutation_locality/FusedR4Gfni.h: d2f340910e175ded705b74a3bb5eedbfbe78964c9be49bbf00fe3db31a51c179
// Source research/workstreams/permutation_locality/InnerPacketMaps.h: 842f3e726d65a9719bd7677dfdf81d2152b39778475873ac157559d8613bb84f
// Source research/workstreams/permutation_locality/InnerPacketFeedback.h: b3b9b95f512cbdc12f77e51eddd806ada8513bd3f5606f33faba54ff4bd9dcc1
// Source research/workstreams/permutation_locality/InnerVbmiState.h: c13dba64599bac5c67159ea03c03211ec9176f8548acb0908ddc834088c84e94
// Source research/workstreams/permutation_locality/InnerPacketStream.h: 845878ed1c3ddd861918fd7c587a3dfe979db693c9d21a8a61c6efe155e9f9b1
// Source research/workstreams/permutation_locality/inner_packet_probe.cpp: 1f796772fc380519fecec1dd45418fcbaeab701f56e9fcd71d3bdd9faaaeb733
// Source research/workstreams/permutation_locality/inner_fusion_probe.cpp: 2b6e197f555ba3fec597ca0b77905751cde0754e72d753ee520a50daf86ded92
#pragma once

#include "PacketLargeTypes.h"
#include "../kernels/Block.h"
#include <array>
#include <cstddef>
#include <utility>
namespace spin::detail::packet::large {
using block=storage::block;
struct alignas(64) PackedState { __m512i v[4]; };

static SPIN_FORCEINLINE __m128i vx(__m128i a,__m128i b){return _mm_xor_si128(a,b);}
static SPIN_FORCEINLINE __m512i join(__m128i a,__m128i b,__m128i c,__m128i d){
auto x=_mm512_castsi128_si512(a);
x=_mm512_inserti32x4(x,b,1);x=_mm512_inserti32x4(x,c,2);
return _mm512_inserti32x4(x,d,3);
}
template<unsigned FirstPayloadByte>
static SPIN_FORCEINLINE __m512i packIndex() {
    static_assert(FirstPayloadByte == 0 || FirstPayloadByte == 8);
    alignas(64) static constexpr auto indices = [] {
        std::array<std::uint8_t,64> result{};
        for(unsigned byte = 0; byte < 8; ++byte)
            for(unsigned coordinate = 0; coordinate < 8; ++coordinate)
                result[8 * byte + coordinate] = static_cast<std::uint8_t>(
                    16 * (7 - coordinate) + FirstPayloadByte + byte);
        return result;
    }();
    return _mm512_load_si512(indices.data());
}
template<unsigned FirstCoordinate>
static SPIN_FORCEINLINE __m512i unpackIndex() {
    static_assert(FirstCoordinate == 0 || FirstCoordinate == 4);
    alignas(64) static constexpr auto indices = [] {
        std::array<std::uint8_t,64> result{};
        for(unsigned coordinate = 0; coordinate < 4; ++coordinate)
            for(unsigned byte = 0; byte < 16; ++byte)
                result[16 * coordinate + byte] = static_cast<std::uint8_t>(
                    8 * byte + FirstCoordinate + coordinate);
        return result;
    }();
    return _mm512_load_si512(indices.data());
}
template<unsigned Group>
static SPIN_FORCEINLINE void packGroup(const __m128i* state,
    PackedState& out) {
    static_assert(Group < 2);
    const auto a = join(
        state[8 * Group], state[8 * Group + 1],
        state[8 * Group + 2], state[8 * Group + 3]);
    const auto b = join(
        state[8 * Group + 4], state[8 * Group + 5],
        state[8 * Group + 6], state[8 * Group + 7]);
    const auto lo = _mm512_permutex2var_epi8(a, packIndex<0>(), b);
    const auto hi = _mm512_permutex2var_epi8(a, packIndex<8>(), b);
    const auto basis = _mm512_set1_epi64(0x0102040810204080ULL);
    out.v[2 * Group] = _mm512_gf2p8affine_epi64_epi8(basis, lo, 0);
    out.v[2 * Group + 1] = _mm512_gf2p8affine_epi64_epi8(basis, hi, 0);
}
template<unsigned First>
static SPIN_FORCEINLINE void storeFour(__m128i* out, __m512i value) {
    out[First] = _mm512_castsi512_si128(value);
    out[First + 1] = _mm512_extracti32x4_epi32(value, 1);
    out[First + 2] = _mm512_extracti32x4_epi32(value, 2);
    out[First + 3] = _mm512_extracti32x4_epi32(value, 3);
}
template<unsigned Group>
static SPIN_FORCEINLINE void unpackGroup(
    const PackedState& state, __m128i* out) {
    static_assert(Group < 2);
    const auto basis = _mm512_set1_epi64(0x8040201008040201ULL);
    const auto lo = _mm512_gf2p8affine_epi64_epi8(basis, state.v[2 * Group], 0);
    const auto hi = _mm512_gf2p8affine_epi64_epi8(basis, state.v[2 * Group + 1], 0);
    storeFour<8 * Group>(out, _mm512_permutex2var_epi8(lo, unpackIndex<0>(), hi));
    storeFour<8 * Group + 4>(out, _mm512_permutex2var_epi8(lo, unpackIndex<4>(), hi));
}
static SPIN_FORCEINLINE void widePackVbmi(const __m128i* state,
    PackedState& out) {
    packGroup<0>(state, out);
    packGroup<1>(state, out);
}
static SPIN_FORCEINLINE void wideUnpackVbmi(
    const PackedState& state, __m128i* out) {
    unpackGroup<0>(state, out);
    unpackGroup<1>(state, out);
}
struct FourMoments {
    __m512i z0, z1, z2, z3;
};
template<unsigned First>
static SPIN_FORCEINLINE FourMoments firstStage(const __m512i* packets) {
    const auto x0 = _mm512_loadu_si512(packets + First);
    const auto x1 = _mm512_loadu_si512(packets + First + 1);
    const auto x2 = _mm512_loadu_si512(packets + First + 2);
    const auto x3 = _mm512_loadu_si512(packets + First + 3);
    const auto z1 = _mm512_xor_si512(x1, x3);
    const auto z2 = _mm512_xor_si512(x2, x3);
    const auto z0 = _mm512_ternarylogic_epi64(x0, x2, z1, 0x96);
    return {z0, z1, z2, x3};
}
template<unsigned Mask, unsigned Degree>
static SPIN_FORCEINLINE void storeLowMoments(__m512i x, __m128i* moments) {
    static_assert((Mask & 3) == 0 && Mask < 64 && Degree <= 2);
    const auto upper = _mm512_extracti64x4_epi64(x, 1);
    const auto folded = _mm256_xor_si256(_mm512_castsi512_si256(x), upper);
    const auto odd = _mm256_extracti128_si256(folded, 1);
    _mm_storeu_si128(moments + Mask,
        _mm_xor_si128(_mm256_castsi256_si128(folded), odd));
    if constexpr (Degree >= 1) {
        const auto last = _mm256_extracti128_si256(upper, 1);
        _mm_storeu_si128(moments + Mask + 1, odd);
        _mm_storeu_si128(moments + Mask + 2,
            _mm_xor_si128(_mm256_castsi256_si128(upper), last));
        if constexpr (Degree == 2)
            _mm_storeu_si128(moments + Mask + 3, last);
    }
}
static SPIN_FORCEINLINE void packetMoments(
    const __m512i* packets, __m128i* moments) {



    const auto a = firstStage<0>(packets);
    const auto b = firstStage<4>(packets);
    const auto c = firstStage<8>(packets);
    const auto d = firstStage<12>(packets);

    // The remaining high-index zeta is pruned to degree two. Together with
    // firstStage, this needs 15 binary XORs and 8 XOR3 operations.
    // Low lane folding then needs 27 logical operations and 27 extracts.
    const auto z4 = _mm512_xor_si512(b.z0, d.z0);
    const auto z8 = _mm512_xor_si512(c.z0, d.z0);
    const auto z0 = _mm512_ternarylogic_epi64(a.z0, c.z0, z4, 0x96);
    storeLowMoments<0, 2>(z0, moments);
    storeLowMoments<16, 1>(z4, moments);
    storeLowMoments<32, 1>(z8, moments);
    storeLowMoments<48, 0>(d.z0, moments);

    const auto z5 = _mm512_xor_si512(b.z1, d.z1);
    const auto z9 = _mm512_xor_si512(c.z1, d.z1);
    const auto z1 = _mm512_ternarylogic_epi64(a.z1, c.z1, z5, 0x96);
    storeLowMoments<4, 1>(z1, moments);
    storeLowMoments<20, 0>(z5, moments);
    storeLowMoments<36, 0>(z9, moments);

    const auto z6 = _mm512_xor_si512(b.z2, d.z2);
    const auto z10 = _mm512_xor_si512(c.z2, d.z2);
    const auto z2 = _mm512_ternarylogic_epi64(a.z2, c.z2, z6, 0x96);
    storeLowMoments<8, 1>(z2, moments);
    storeLowMoments<24, 0>(z6, moments);
    storeLowMoments<40, 0>(z10, moments);

    const auto z3 = _mm512_ternarylogic_epi64(a.z3, b.z3,
        _mm512_xor_si512(c.z3, d.z3), 0x96);
    storeLowMoments<12, 0>(z3, moments);
}
static SPIN_FORCEINLINE void finish(const __m128i* z,__m128i* out){
// P A^T on the same 22 zeta moments: 32 XMM XORs.
const auto fse0=vx(z[9],z[34]);
const auto fse1=vx(z[5],z[6]);
const auto fse2=vx(z[24],fse0);
const auto fse3=vx(z[33],z[36]);
const auto fse4=vx(z[10],z[12]);
const auto fse5=vx(z[18],z[48]);
const auto fse6=vx(z[20],z[40]);
const auto fse7=vx(fse3,fse5);
const auto fse8=vx(z[17],fse1);
const auto fse9=vx(z[40],fse2);
const auto fse10=vx(fse4,fse7);
const auto f0=z[0];
const auto f1=z[1];
const auto f2=z[2];
const auto f3=z[4];
const auto f4=z[8];
const auto f5=z[16];
const auto f6=z[32];
const auto f7=vx(z[34],fse6);
const auto f8=vx(vx(vx(z[9],z[12]),z[20]),fse8);
const auto f9=vx(vx(vx(z[18],fse1),fse2),fse4);
const auto f10=vx(vx(fse1,fse6),fse7);
const auto f11=vx(vx(vx(z[17],z[24]),z[34]),fse10);
const auto f12=vx(vx(vx(z[48],fse2),fse6),fse8);
const auto f13=vx(z[33],fse9);
const auto f14=vx(vx(vx(z[3],z[6]),fse0),fse10);
const auto f15=vx(vx(z[5],fse3),fse9);
out[0]=f0;
out[1]=f1;
out[2]=f2;
out[3]=f3;
out[4]=f4;
out[5]=f5;
out[6]=f6;
out[7]=f7;
out[8]=f8;
out[9]=f9;
out[10]=f10;
out[11]=f11;
out[12]=f12;
out[13]=f13;
out[14]=f14;
out[15]=f15;
}
template<std::size_t... I> SPIN_FORCEINLINE void loadPackets(
    const block* input,__m512i* out,std::index_sequence<I...>) {
    ((out[I]=_mm512_loadu_si512(input+4*I)),...);
}
SPIN_FORCEINLINE void denseStep16(
    PackedState& state,const Dense16Row& row,const PackedState* syndrome=nullptr) {
    const auto m00=_mm512_set1_epi64(row.matrix[0]),m01=_mm512_set1_epi64(row.matrix[1]);
    const auto m10=_mm512_set1_epi64(row.matrix[2]),m11=_mm512_set1_epi64(row.matrix[3]);
    const auto a0=_mm512_gf2p8affine_epi64_epi8(state.v[0],m00,0);
    const auto b0=_mm512_gf2p8affine_epi64_epi8(state.v[2],m01,0);
    const auto a1=_mm512_gf2p8affine_epi64_epi8(state.v[1],m00,0);
    const auto b1=_mm512_gf2p8affine_epi64_epi8(state.v[3],m01,0);
    const auto a2=_mm512_gf2p8affine_epi64_epi8(state.v[0],m10,0);
    const auto b2=_mm512_gf2p8affine_epi64_epi8(state.v[2],m11,0);
    const auto a3=_mm512_gf2p8affine_epi64_epi8(state.v[1],m10,0);
    const auto b3=_mm512_gf2p8affine_epi64_epi8(state.v[3],m11,0);

        state.v[0]=_mm512_ternarylogic_epi64(a0,b0,syndrome->v[0],0x96);
        state.v[1]=_mm512_ternarylogic_epi64(a1,b1,syndrome->v[1],0x96);
        state.v[2]=_mm512_ternarylogic_epi64(a2,b2,syndrome->v[2],0x96);
        state.v[3]=_mm512_ternarylogic_epi64(a3,b3,syndrome->v[3],0x96);

}
template<class Emit>
static SPIN_FORCEINLINE void streamStepHigh(const __m128i* state,
const block* raw,std::size_t packetBase,Emit& emit,__m512i* high){
// State to 22 ANF coefficients: 12 XMM XORs.
const auto cs0=vx(state[10],state[12]);
const auto cs1=vx(state[12],state[15]);
const auto cs2=vx(state[11],state[13]);
const auto c0=state[0];
const auto c1=state[1];
const auto c2=state[2];
const auto c3=state[7];
const auto c4=state[3];
const auto c5=state[8];
const auto c6=state[12];
const auto c8=state[4];
const auto c9=state[9];
const auto c10=state[13];
const auto c12=state[15];
const auto c16=state[5];
const auto c17=state[10];
const auto c18=cs0;
const auto c20=vx(vx(state[9],state[14]),cs1);
const auto c24=vx(cs1,cs2);
const auto c32=state[6];
const auto c33=state[11];
const auto c34=state[14];
const auto c36=vx(vx(vx(vx(state[7],state[8]),state[9]),cs0),cs2);
const auto c40=vx(state[14],cs0);
const auto c48=vx(state[7],cs1);
const auto l01=vx(c0,c1);
const auto l02=vx(c0,c2);
const auto l03=vx(vx(l01,c2),c3);
const auto d0=join(c0,l01,l02,l03);
const auto l11=vx(c4,c5);
const auto l12=vx(c4,c6);
const auto l13=vx(l11,c6);
const auto d1=join(c4,l11,l12,l13);
const auto l21=vx(c8,c9);
const auto l22=vx(c8,c10);
const auto l23=vx(l21,c10);
const auto d2=join(c8,l21,l22,l23);
const auto d3=_mm512_broadcast_i32x4(c12);
const auto l41=vx(c16,c17);
const auto l42=vx(c16,c18);
const auto l43=vx(l41,c18);
const auto d4=join(c16,l41,l42,l43);
const auto d5=_mm512_broadcast_i32x4(c20);
const auto d6=_mm512_broadcast_i32x4(c24);
const auto l81=vx(c32,c33);
const auto l82=vx(c32,c34);
const auto l83=vx(l81,c34);
const auto d8=join(c32,l81,l82,l83);
const auto d9=_mm512_broadcast_i32x4(c36);
const auto d10=_mm512_broadcast_i32x4(c40);
const auto d12=_mm512_broadcast_i32x4(c48);
// Shared group-2 coefficients reduce the block evaluator from29 to26 XORs.

__m512i g30,g31,g32,g33;
{
const auto b0=_mm512_xor_si512(_mm512_xor_si512(_mm512_xor_si512(d0,d4),d8),d12);
const auto b1=_mm512_xor_si512(_mm512_xor_si512(d1,d5),d9);
const auto b2=_mm512_xor_si512(_mm512_xor_si512(d2,d6),d10);
const auto e1=_mm512_xor_si512(b0,b1);
const auto e2=_mm512_xor_si512(b0,b2);
const auto e3=_mm512_xor_si512(_mm512_xor_si512(e1,b2),d3);
const auto y3=_mm512_xor_si512(e3,_mm512_loadu_si512(raw+60));
emit(packetBase+15,y3);
const auto y2=_mm512_xor_si512(e2,_mm512_loadu_si512(raw+56));
emit(packetBase+14,y2);
const auto y1=_mm512_xor_si512(e1,_mm512_loadu_si512(raw+52));
emit(packetBase+13,y1);
const auto y0=_mm512_xor_si512(b0,_mm512_loadu_si512(raw+48));
emit(packetBase+12,y0);
g31=_mm512_xor_si512(y1,y3);
g32=_mm512_xor_si512(y2,y3);
g30=_mm512_ternarylogic_epi64(y0,y2,g31,0x96);
g33=y3;
}
__m512i g20,g21,g22,g23;
{
const auto b0=_mm512_xor_si512(d0,d8);
const auto b1=_mm512_xor_si512(d1,d9);
const auto b2=_mm512_xor_si512(d2,d10);
const auto e1=_mm512_xor_si512(b0,b1);
const auto e2=_mm512_xor_si512(b0,b2);
const auto e3=_mm512_xor_si512(_mm512_xor_si512(e1,b2),d3);
const auto y3=_mm512_xor_si512(e3,_mm512_loadu_si512(raw+44));
emit(packetBase+11,y3);
const auto y2=_mm512_xor_si512(e2,_mm512_loadu_si512(raw+40));
emit(packetBase+10,y2);
const auto y1=_mm512_xor_si512(e1,_mm512_loadu_si512(raw+36));
emit(packetBase+9,y1);
const auto y0=_mm512_xor_si512(b0,_mm512_loadu_si512(raw+32));
emit(packetBase+8,y0);
g21=_mm512_xor_si512(y1,y3);
g22=_mm512_xor_si512(y2,y3);
g20=_mm512_ternarylogic_epi64(y0,y2,g21,0x96);
g23=y3;
}
const auto cd0=_mm512_xor_si512(g20,g30);
const auto cd1=_mm512_xor_si512(g21,g31);
const auto cd2=_mm512_xor_si512(g22,g32);
const auto cd3=_mm512_xor_si512(g23,g33);
__m512i g10,g11,g12,g13;
{
const auto b0=_mm512_xor_si512(d0,d4);
const auto b1=_mm512_xor_si512(d1,d5);
const auto b2=_mm512_xor_si512(d2,d6);
const auto e1=_mm512_xor_si512(b0,b1);
const auto e2=_mm512_xor_si512(b0,b2);
const auto e3=_mm512_xor_si512(_mm512_xor_si512(e1,b2),d3);
const auto y3=_mm512_xor_si512(e3,_mm512_loadu_si512(raw+28));
emit(packetBase+7,y3);
const auto y2=_mm512_xor_si512(e2,_mm512_loadu_si512(raw+24));
emit(packetBase+6,y2);
const auto y1=_mm512_xor_si512(e1,_mm512_loadu_si512(raw+20));
emit(packetBase+5,y1);
const auto y0=_mm512_xor_si512(b0,_mm512_loadu_si512(raw+16));
emit(packetBase+4,y0);
g11=_mm512_xor_si512(y1,y3);
g12=_mm512_xor_si512(y2,y3);
g10=_mm512_ternarylogic_epi64(y0,y2,g11,0x96);
g13=y3;
}
__m512i g00,g01,g02,g03;
{
const auto b0=d0;
const auto b1=d1;
const auto b2=d2;
const auto e1=_mm512_xor_si512(b0,b1);
const auto e2=_mm512_xor_si512(b0,b2);
const auto e3=_mm512_xor_si512(_mm512_xor_si512(e1,b2),d3);
const auto y3=_mm512_xor_si512(e3,_mm512_loadu_si512(raw+12));
emit(packetBase+3,y3);
const auto y2=_mm512_xor_si512(e2,_mm512_loadu_si512(raw+8));
emit(packetBase+2,y2);
const auto y1=_mm512_xor_si512(e1,_mm512_loadu_si512(raw+4));
emit(packetBase+1,y1);
const auto y0=_mm512_xor_si512(b0,_mm512_loadu_si512(raw+0));
emit(packetBase+0,y0);
g01=_mm512_xor_si512(y1,y3);
g02=_mm512_xor_si512(y2,y3);
g00=_mm512_ternarylogic_epi64(y0,y2,g01,0x96);
g03=y3;
}
high[0]=_mm512_ternarylogic_epi64(g00,g10,cd0,0x96);
high[4]=_mm512_xor_si512(g10,g30);
high[8]=cd0;
high[1]=_mm512_ternarylogic_epi64(g01,g11,cd1,0x96);
high[5]=_mm512_xor_si512(g11,g31);
high[9]=cd1;
high[2]=_mm512_ternarylogic_epi64(g02,g12,cd2,0x96);
high[6]=_mm512_xor_si512(g12,g32);
high[10]=cd2;
high[3]=_mm512_ternarylogic_epi64(g03,g13,cd3,0x96);
high[12]=g30;

}
template<class Emit>
static SPIN_FORCEINLINE void streamStep(const __m128i* state,
const block* raw,std::size_t packetBase,Emit& emit,__m128i* moments){
alignas(64) __m512i high[16];
streamStepHigh(state,raw,packetBase,emit,high);

storeLowMoments<0,2>(high[0],moments);
storeLowMoments<4,1>(high[1],moments);
storeLowMoments<8,1>(high[2],moments);
storeLowMoments<12,0>(high[3],moments);
storeLowMoments<16,1>(high[4],moments);
storeLowMoments<20,0>(high[5],moments);
storeLowMoments<24,0>(high[6],moments);
storeLowMoments<32,1>(high[8],moments);
storeLowMoments<36,0>(high[9],moments);
storeLowMoments<40,0>(high[10],moments);
storeLowMoments<48,0>(high[12],moments);
}
template<class Emit>
SPIN_FORCEINLINE void reverse(const block* input,std::size_t n,
    const Dense16Row* rows,Emit& emit) {
    alignas(64) __m128i words[16],moments[64],syndrome[16];
    alignas(64) __m512i packets[16],high[16];
    PackedState state{},feedback;
    for(std::size_t epoch=n/64;epoch-->0;) {
        const auto* raw=input+64*epoch;
        const bool first=epoch+1==n/64;
        if(first) {
            loadPackets(raw,packets,std::make_index_sequence<16>{});
            for(unsigned h=16;h-->0;)emit(16*epoch+h,packets[h]);
        } else {
            wideUnpackVbmi(state,words);
            streamStep(words,raw,16*epoch,emit,moments);
        }
        if(!epoch)break;

            if(first)packetMoments(packets,moments);
            finish(moments,syndrome);
            widePackVbmi(syndrome,feedback);

        if(first)state=feedback;
        else denseStep16(state,rows[epoch],&feedback);
    }
}
} // namespace spin::detail::packet::large
