// Generated by spin/tools/import_packet.py; do not edit by hand.
// Selected exact t64/s16 packet transpose. Private to PacketFast.cpp.
// Source research/workstreams/permutation_locality/InnerPacketMaps.h: 842f3e726d65a9719bd7677dfdf81d2152b39778475873ac157559d8613bb84f
// Source research/workstreams/permutation_locality/InnerPacketFeedback.h: b3b9b95f512cbdc12f77e51eddd806ada8513bd3f5606f33faba54ff4bd9dcc1
// Source research/workstreams/permutation_locality/InnerVbmiState.h: c13dba64599bac5c67159ea03c03211ec9176f8548acb0908ddc834088c84e94
// Source research/workstreams/permutation_locality/InnerComposed.h: 3fd6f90b28302aebb2f438aac68288c84eba96fbc624489ae765d280295b6cce
// Source research/workstreams/permutation_locality/PacketInnerKernel.h: 5c3d32f42507fb76fdb537834954f67aea0dc3c2176a10df01cdbb7f72dd6b4f
// Source research/workstreams/permutation_locality/further_mapWide.h: f4daab3c89ff7a5fb24f8542f9670d54881a8dc900b2d9b7be18d3d85a1b13f7
#pragma once

#include "../kernels/Block.h"
#include <array>
#include <cstddef>
#include <cstdint>
#include <utility>
namespace spin::detail::packet::fast {
using Block=storage::block;
struct alignas(64) PackedState { __m512i v[4]; };

static SPIN_FORCEINLINE __m128i vx(__m128i a,__m128i b){return _mm_xor_si128(a,b);}
static SPIN_FORCEINLINE __m512i join(__m128i a,__m128i b,__m128i c,__m128i d){
auto x=_mm512_castsi128_si512(a);
x=_mm512_inserti32x4(x,b,1);x=_mm512_inserti32x4(x,c,2);
return _mm512_inserti32x4(x,d,3);
}
struct alignas(64) WordPackets16 { __m512i v[4]; };
template<unsigned FirstPayloadByte>
static SPIN_FORCEINLINE __m512i packIndex() {
    static_assert(FirstPayloadByte == 0 || FirstPayloadByte == 8);
    alignas(64) static constexpr auto indices = [] {
        std::array<std::uint8_t,64> result{};
        for(unsigned byte = 0; byte < 8; ++byte)
            for(unsigned coordinate = 0; coordinate < 8; ++coordinate)
                result[8 * byte + coordinate] = static_cast<std::uint8_t>(
                    16 * (7 - coordinate) + FirstPayloadByte + byte);
        return result;
    }();
    return _mm512_load_si512(indices.data());
}
template<unsigned FirstCoordinate>
static SPIN_FORCEINLINE __m512i unpackIndex() {
    static_assert(FirstCoordinate == 0 || FirstCoordinate == 4);
    alignas(64) static constexpr auto indices = [] {
        std::array<std::uint8_t,64> result{};
        for(unsigned coordinate = 0; coordinate < 4; ++coordinate)
            for(unsigned byte = 0; byte < 16; ++byte)
                result[16 * coordinate + byte] = static_cast<std::uint8_t>(
                    8 * byte + FirstCoordinate + coordinate);
        return result;
    }();
    return _mm512_load_si512(indices.data());
}
template<unsigned Group>
static SPIN_FORCEINLINE void packWordGroup(const WordPackets16& words, PackedState& packed) {
    const auto lo = _mm512_permutex2var_epi8(words.v[2 * Group],
        packIndex<0>(), words.v[2 * Group + 1]);
    const auto hi = _mm512_permutex2var_epi8(words.v[2 * Group],
        packIndex<8>(), words.v[2 * Group + 1]);
    const auto basis = _mm512_set1_epi64(0x0102040810204080ULL);
    packed.v[2 * Group] = _mm512_gf2p8affine_epi64_epi8(basis, lo, 0);
    packed.v[2 * Group + 1] = _mm512_gf2p8affine_epi64_epi8(basis, hi, 0);
}
static SPIN_FORCEINLINE void wordPackets(const __m128i* words, WordPackets16& packets) {
    packets.v[0] = join(words[0], words[1], words[2], words[3]);
    packets.v[1] = join(words[4], words[5], words[6], words[7]);
    packets.v[2] = join(words[8], words[9], words[10], words[11]);
    packets.v[3] = join(words[12], words[13], words[14], words[15]);
}
static SPIN_FORCEINLINE void applyPackedToPackets(const PackedState& before,
    const std::uint64_t* row, const __m128i* feedback, WordPackets16& words) {
    const auto m00 = _mm512_set1_epi64(row[0]);
    const auto m01 = _mm512_set1_epi64(row[1]);
    const auto m10 = _mm512_set1_epi64(row[2]);
    const auto m11 = _mm512_set1_epi64(row[3]);
    const auto lo0 = _mm512_xor_si512(
        _mm512_gf2p8affine_epi64_epi8(m00, before.v[0], 0),
        _mm512_gf2p8affine_epi64_epi8(m01, before.v[2], 0));
    const auto hi0 = _mm512_xor_si512(
        _mm512_gf2p8affine_epi64_epi8(m00, before.v[1], 0),
        _mm512_gf2p8affine_epi64_epi8(m01, before.v[3], 0));
    const auto lo1 = _mm512_xor_si512(
        _mm512_gf2p8affine_epi64_epi8(m10, before.v[0], 0),
        _mm512_gf2p8affine_epi64_epi8(m11, before.v[2], 0));
    const auto hi1 = _mm512_xor_si512(
        _mm512_gf2p8affine_epi64_epi8(m10, before.v[1], 0),
        _mm512_gf2p8affine_epi64_epi8(m11, before.v[3], 0));
    words.v[0] = _mm512_xor_si512(_mm512_permutex2var_epi8(lo0, unpackIndex<0>(), hi0),
        join(feedback[0], feedback[1], feedback[2], feedback[3]));
    words.v[1] = _mm512_xor_si512(_mm512_permutex2var_epi8(lo0, unpackIndex<4>(), hi0),
        join(feedback[4], feedback[5], feedback[6], feedback[7]));
    words.v[2] = _mm512_xor_si512(_mm512_permutex2var_epi8(lo1, unpackIndex<0>(), hi1),
        join(feedback[8], feedback[9], feedback[10], feedback[11]));
    words.v[3] = _mm512_xor_si512(_mm512_permutex2var_epi8(lo1, unpackIndex<4>(), hi1),
        join(feedback[12], feedback[13], feedback[14], feedback[15]));
}
struct FourMoments {
    __m512i z0, z1, z2, z3;
};
template<unsigned First>
static SPIN_FORCEINLINE FourMoments firstStage(const __m512i* packets) {
    const auto x0 = _mm512_loadu_si512(packets + First);
    const auto x1 = _mm512_loadu_si512(packets + First + 1);
    const auto x2 = _mm512_loadu_si512(packets + First + 2);
    const auto x3 = _mm512_loadu_si512(packets + First + 3);
    const auto z1 = _mm512_xor_si512(x1, x3);
    const auto z2 = _mm512_xor_si512(x2, x3);
    const auto z0 = _mm512_ternarylogic_epi64(x0, x2, z1, 0x96);
    return {z0, z1, z2, x3};
}
template<unsigned Mask, unsigned Degree>
static SPIN_FORCEINLINE void storeLowMoments(__m512i x, __m128i* moments) {
    static_assert((Mask & 3) == 0 && Mask < 64 && Degree <= 2);
    const auto upper = _mm512_extracti64x4_epi64(x, 1);
    const auto folded = _mm256_xor_si256(_mm512_castsi512_si256(x), upper);
    const auto odd = _mm256_extracti128_si256(folded, 1);
    _mm_storeu_si128(moments + Mask,
        _mm_xor_si128(_mm256_castsi256_si128(folded), odd));
    if constexpr (Degree >= 1) {
        const auto last = _mm256_extracti128_si256(upper, 1);
        _mm_storeu_si128(moments + Mask + 1, odd);
        _mm_storeu_si128(moments + Mask + 2,
            _mm_xor_si128(_mm256_castsi256_si128(upper), last));
        if constexpr (Degree == 2)
            _mm_storeu_si128(moments + Mask + 3, last);
    }
}
static SPIN_FORCEINLINE void packetMoments(
    const __m512i* packets, __m128i* moments) {



    const auto a = firstStage<0>(packets);
    const auto b = firstStage<4>(packets);
    const auto c = firstStage<8>(packets);
    const auto d = firstStage<12>(packets);

    // The remaining high-index zeta is pruned to degree two. Together with
    // firstStage, this needs 15 binary XORs and 8 XOR3 operations.
    // Low lane folding then needs 27 logical operations and 27 extracts.
    const auto z4 = _mm512_xor_si512(b.z0, d.z0);
    const auto z8 = _mm512_xor_si512(c.z0, d.z0);
    const auto z0 = _mm512_ternarylogic_epi64(a.z0, c.z0, z4, 0x96);
    storeLowMoments<0, 2>(z0, moments);
    storeLowMoments<16, 1>(z4, moments);
    storeLowMoments<32, 1>(z8, moments);
    storeLowMoments<48, 0>(d.z0, moments);

    const auto z5 = _mm512_xor_si512(b.z1, d.z1);
    const auto z9 = _mm512_xor_si512(c.z1, d.z1);
    const auto z1 = _mm512_ternarylogic_epi64(a.z1, c.z1, z5, 0x96);
    storeLowMoments<4, 1>(z1, moments);
    storeLowMoments<20, 0>(z5, moments);
    storeLowMoments<36, 0>(z9, moments);

    const auto z6 = _mm512_xor_si512(b.z2, d.z2);
    const auto z10 = _mm512_xor_si512(c.z2, d.z2);
    const auto z2 = _mm512_ternarylogic_epi64(a.z2, c.z2, z6, 0x96);
    storeLowMoments<8, 1>(z2, moments);
    storeLowMoments<24, 0>(z6, moments);
    storeLowMoments<40, 0>(z10, moments);

    const auto z3 = _mm512_ternarylogic_epi64(a.z3, b.z3,
        _mm512_xor_si512(c.z3, d.z3), 0x96);
    storeLowMoments<12, 0>(z3, moments);
}
static SPIN_FORCEINLINE void finish(const __m128i* z,__m128i* out){
// P A^T on the same 22 zeta moments: 32 XMM XORs.
const auto fse0=vx(z[9],z[34]);
const auto fse1=vx(z[5],z[6]);
const auto fse2=vx(z[24],fse0);
const auto fse3=vx(z[33],z[36]);
const auto fse4=vx(z[10],z[12]);
const auto fse5=vx(z[18],z[48]);
const auto fse6=vx(z[20],z[40]);
const auto fse7=vx(fse3,fse5);
const auto fse8=vx(z[17],fse1);
const auto fse9=vx(z[40],fse2);
const auto fse10=vx(fse4,fse7);
const auto f0=z[0];
const auto f1=z[1];
const auto f2=z[2];
const auto f3=z[4];
const auto f4=z[8];
const auto f5=z[16];
const auto f6=z[32];
const auto f7=vx(z[34],fse6);
const auto f8=vx(vx(vx(z[9],z[12]),z[20]),fse8);
const auto f9=vx(vx(vx(z[18],fse1),fse2),fse4);
const auto f10=vx(vx(fse1,fse6),fse7);
const auto f11=vx(vx(vx(z[17],z[24]),z[34]),fse10);
const auto f12=vx(vx(vx(z[48],fse2),fse6),fse8);
const auto f13=vx(z[33],fse9);
const auto f14=vx(vx(vx(z[3],z[6]),fse0),fse10);
const auto f15=vx(vx(z[5],fse3),fse9);
out[0]=f0;
out[1]=f1;
out[2]=f2;
out[3]=f3;
out[4]=f4;
out[5]=f5;
out[6]=f6;
out[7]=f7;
out[8]=f8;
out[9]=f9;
out[10]=f10;
out[11]=f11;
out[12]=f12;
out[13]=f13;
out[14]=f14;
out[15]=f15;
}
template<std::size_t... I>
static SPIN_FORCEINLINE void loadPackets(const Block* raw, __m512i* packets,
                                         std::index_sequence<I...>) {
    ((packets[I] = _mm512_loadu_si512(raw + 4 * I)), ...);
}
template<class Emit>
static SPIN_FORCEINLINE void streamHigh(const WordPackets16& state,
const Block* raw,std::size_t packetBase,Emit& emit,__m512i* high){
//16 lane broadcasts +11 masked XORs +12 shared quadratic XORs; no128-bit extracts/inserts.
const auto b0=_mm512_shuffle_i32x4(state.v[0],state.v[0],0x00);
const auto b1=_mm512_shuffle_i32x4(state.v[0],state.v[0],0x55);
const auto b2=_mm512_shuffle_i32x4(state.v[0],state.v[0],0xaa);
const auto b7=_mm512_shuffle_i32x4(state.v[1],state.v[1],0xff);
auto d0=b0;
d0=_mm512_mask_xor_epi64(d0,0xcc,d0,b1);
d0=_mm512_mask_xor_epi64(d0,0xf0,d0,b2);
d0=_mm512_mask_xor_epi64(d0,0xc0,d0,b7);
const auto b3=_mm512_shuffle_i32x4(state.v[0],state.v[0],0xff);
const auto b8=_mm512_shuffle_i32x4(state.v[2],state.v[2],0x00);
const auto b12=_mm512_shuffle_i32x4(state.v[3],state.v[3],0x00);
auto d1=b3;
d1=_mm512_mask_xor_epi64(d1,0xcc,d1,b8);
d1=_mm512_mask_xor_epi64(d1,0xf0,d1,b12);
const auto b4=_mm512_shuffle_i32x4(state.v[1],state.v[1],0x00);
const auto b9=_mm512_shuffle_i32x4(state.v[2],state.v[2],0x55);
const auto b13=_mm512_shuffle_i32x4(state.v[3],state.v[3],0x55);
auto d2=b4;
d2=_mm512_mask_xor_epi64(d2,0xcc,d2,b9);
d2=_mm512_mask_xor_epi64(d2,0xf0,d2,b13);
const auto b5=_mm512_shuffle_i32x4(state.v[1],state.v[1],0x55);
const auto b10=_mm512_shuffle_i32x4(state.v[2],state.v[2],0xaa);
auto d4=b5;
d4=_mm512_mask_xor_epi64(d4,0x3c,d4,b10);
d4=_mm512_mask_xor_epi64(d4,0xf0,d4,b12);
const auto b6=_mm512_shuffle_i32x4(state.v[1],state.v[1],0xaa);
const auto b11=_mm512_shuffle_i32x4(state.v[2],state.v[2],0xff);
const auto b14=_mm512_shuffle_i32x4(state.v[3],state.v[3],0xaa);
auto d8=b6;
d8=_mm512_mask_xor_epi64(d8,0xcc,d8,b11);
d8=_mm512_mask_xor_epi64(d8,0xf0,d8,b14);
const auto b15=_mm512_shuffle_i32x4(state.v[3],state.v[3],0xff);
const auto wcs0=_mm512_xor_si512(b12,b15);
const auto wcs1=_mm512_xor_si512(b10,b12);
const auto wcs2=_mm512_xor_si512(b11,b13);
const auto d3=b15;
const auto d5=_mm512_xor_si512(_mm512_xor_si512(b9,b14),wcs0);
const auto d6=_mm512_xor_si512(wcs0,wcs2);
const auto d9=_mm512_xor_si512(_mm512_xor_si512(_mm512_xor_si512(_mm512_xor_si512(b7,b8),b9),wcs1),wcs2);
const auto d10=_mm512_xor_si512(b14,wcs1);
const auto d12=_mm512_xor_si512(b7,wcs0);

__m512i g30,g31,g32,g33;
{
const auto b0=_mm512_xor_si512(_mm512_xor_si512(_mm512_xor_si512(d0,d4),d8),d12);
const auto b1=_mm512_xor_si512(_mm512_xor_si512(d1,d5),d9);
const auto b2=_mm512_xor_si512(_mm512_xor_si512(d2,d6),d10);
const auto e1=_mm512_xor_si512(b0,b1);
const auto e2=_mm512_xor_si512(b0,b2);
const auto e3=_mm512_xor_si512(_mm512_xor_si512(e1,b2),d3);
const auto y3=_mm512_xor_si512(e3,_mm512_loadu_si512(raw+60));
emit(packetBase+15,y3);
const auto y2=_mm512_xor_si512(e2,_mm512_loadu_si512(raw+56));
emit(packetBase+14,y2);
const auto y1=_mm512_xor_si512(e1,_mm512_loadu_si512(raw+52));
emit(packetBase+13,y1);
const auto y0=_mm512_xor_si512(b0,_mm512_loadu_si512(raw+48));
emit(packetBase+12,y0);
g31=_mm512_xor_si512(y1,y3);
g32=_mm512_xor_si512(y2,y3);
g30=_mm512_ternarylogic_epi64(y0,y2,g31,0x96);
g33=y3;
}
__m512i g20,g21,g22,g23;
{
const auto b0=_mm512_xor_si512(d0,d8);
const auto b1=_mm512_xor_si512(d1,d9);
const auto b2=_mm512_xor_si512(d2,d10);
const auto e1=_mm512_xor_si512(b0,b1);
const auto e2=_mm512_xor_si512(b0,b2);
const auto e3=_mm512_xor_si512(_mm512_xor_si512(e1,b2),d3);
const auto y3=_mm512_xor_si512(e3,_mm512_loadu_si512(raw+44));
emit(packetBase+11,y3);
const auto y2=_mm512_xor_si512(e2,_mm512_loadu_si512(raw+40));
emit(packetBase+10,y2);
const auto y1=_mm512_xor_si512(e1,_mm512_loadu_si512(raw+36));
emit(packetBase+9,y1);
const auto y0=_mm512_xor_si512(b0,_mm512_loadu_si512(raw+32));
emit(packetBase+8,y0);
g21=_mm512_xor_si512(y1,y3);
g22=_mm512_xor_si512(y2,y3);
g20=_mm512_ternarylogic_epi64(y0,y2,g21,0x96);
g23=y3;
}
const auto cd0=_mm512_xor_si512(g20,g30);
const auto cd1=_mm512_xor_si512(g21,g31);
const auto cd2=_mm512_xor_si512(g22,g32);
const auto cd3=_mm512_xor_si512(g23,g33);
__m512i g10,g11,g12,g13;
{
const auto b0=_mm512_xor_si512(d0,d4);
const auto b1=_mm512_xor_si512(d1,d5);
const auto b2=_mm512_xor_si512(d2,d6);
const auto e1=_mm512_xor_si512(b0,b1);
const auto e2=_mm512_xor_si512(b0,b2);
const auto e3=_mm512_xor_si512(_mm512_xor_si512(e1,b2),d3);
const auto y3=_mm512_xor_si512(e3,_mm512_loadu_si512(raw+28));
emit(packetBase+7,y3);
const auto y2=_mm512_xor_si512(e2,_mm512_loadu_si512(raw+24));
emit(packetBase+6,y2);
const auto y1=_mm512_xor_si512(e1,_mm512_loadu_si512(raw+20));
emit(packetBase+5,y1);
const auto y0=_mm512_xor_si512(b0,_mm512_loadu_si512(raw+16));
emit(packetBase+4,y0);
g11=_mm512_xor_si512(y1,y3);
g12=_mm512_xor_si512(y2,y3);
g10=_mm512_ternarylogic_epi64(y0,y2,g11,0x96);
g13=y3;
}
__m512i g00,g01,g02,g03;
{
const auto b0=d0;
const auto b1=d1;
const auto b2=d2;
const auto e1=_mm512_xor_si512(b0,b1);
const auto e2=_mm512_xor_si512(b0,b2);
const auto e3=_mm512_xor_si512(_mm512_xor_si512(e1,b2),d3);
const auto y3=_mm512_xor_si512(e3,_mm512_loadu_si512(raw+12));
emit(packetBase+3,y3);
const auto y2=_mm512_xor_si512(e2,_mm512_loadu_si512(raw+8));
emit(packetBase+2,y2);
const auto y1=_mm512_xor_si512(e1,_mm512_loadu_si512(raw+4));
emit(packetBase+1,y1);
const auto y0=_mm512_xor_si512(b0,_mm512_loadu_si512(raw+0));
emit(packetBase+0,y0);
g01=_mm512_xor_si512(y1,y3);
g02=_mm512_xor_si512(y2,y3);
g00=_mm512_ternarylogic_epi64(y0,y2,g01,0x96);
g03=y3;
}
high[0]=_mm512_ternarylogic_epi64(g00,g10,cd0,0x96);
high[4]=_mm512_xor_si512(g10,g30);
high[8]=cd0;
high[1]=_mm512_ternarylogic_epi64(g01,g11,cd1,0x96);
high[5]=_mm512_xor_si512(g11,g31);
high[9]=cd1;
high[2]=_mm512_ternarylogic_epi64(g02,g12,cd2,0x96);
high[6]=_mm512_xor_si512(g12,g32);
high[10]=cd2;
high[3]=_mm512_ternarylogic_epi64(g03,g13,cd3,0x96);
high[12]=g30;

}
template<class Emit>
static SPIN_FORCEINLINE void streamMoments(const WordPackets16& state,
const Block* raw,std::size_t packetBase,Emit& emit,__m128i* moments){
alignas(64) __m512i high[16];
streamHigh(state,raw,packetBase,emit,high);

storeLowMoments<0,2>(high[0],moments);
storeLowMoments<4,1>(high[1],moments);
storeLowMoments<8,1>(high[2],moments);
storeLowMoments<12,0>(high[3],moments);
storeLowMoments<16,1>(high[4],moments);
storeLowMoments<20,0>(high[5],moments);
storeLowMoments<24,0>(high[6],moments);
storeLowMoments<32,1>(high[8],moments);
storeLowMoments<36,0>(high[9],moments);
storeLowMoments<40,0>(high[10],moments);
storeLowMoments<48,0>(high[12],moments);
}
template<class Emit>
static SPIN_FORCEINLINE void reverse(const Block* input,
std::size_t n,const std::uint64_t* rows,Emit& emit){

alignas(64) __m128i moments[64],syndrome[16];
alignas(64) __m512i packets[16];
PackedState before;
WordPackets16 state;
for(std::size_t epoch=n/64;epoch-- >0;){
const auto* raw=input+64*epoch;
const bool first=epoch+1==n/64;
if(first){
loadPackets(raw,packets,std::make_index_sequence<16>{});
for(unsigned h=16;h-- >0;)emit(16*epoch+h,packets[h]);
}else{
if(epoch){packWordGroup<0>(state,before);packWordGroup<1>(state,before);}
streamMoments(state,raw,16*epoch,emit,moments);
}
if(!epoch)break;
if(first)packetMoments(packets,moments);
finish(moments,syndrome);
if(first)wordPackets(syndrome,state);
else applyPackedToPackets(before,rows+4*epoch,syndrome,state);
}
}
} // namespace spin::detail::packet::fast
