// Generated by spin/tools/import_rs_packet.py; do not edit by hand.
// Exact retained s20 fused inner / GF32 byte-multiply RS outer schedule.
// research/workstreams/k16_design/implementation/rs16x8_border/RsBorderFused.cpp SHA256 6ab3519f6b3e3b39ea956173c8888e1ce64a620ecaa0c0764ca0905de8369fff

#include "PacketPlan.h"
#include "PacketRsInner.h"
namespace spin::detail::packet {
namespace {
using namespace large;
struct PackedExtra {__m512i lo,hi;};
template<unsigned Extra> static SPIN_FORCEINLINE PackedExtra packExtra(const __m128i* words) {
    const auto zero=_mm_setzero_si128();
    const auto a=join(words[0],Extra>=2?words[1]:zero,Extra>=3?words[2]:zero,Extra>=4?words[3]:zero);
    const auto b=_mm512_setzero_si512();
    const auto basis=_mm512_set1_epi64(0x0102040810204080ULL);
    return {_mm512_gf2p8affine_epi64_epi8(basis,_mm512_permutex2var_epi8(a,packIndex<0>(),b),0),
            _mm512_gf2p8affine_epi64_epi8(basis,_mm512_permutex2var_epi8(a,packIndex<8>(),b),0)};
}
template<unsigned Extra> static SPIN_FORCEINLINE void unpackExtra(const PackedExtra& packed,__m128i* words) {
    const auto basis=_mm512_set1_epi64(0x8040201008040201ULL);
    const auto lo=_mm512_gf2p8affine_epi64_epi8(basis,packed.lo,0);
    const auto hi=_mm512_gf2p8affine_epi64_epi8(basis,packed.hi,0);
    const auto joint=_mm512_permutex2var_epi8(lo,unpackIndex<0>(),hi);
    words[0]=_mm512_castsi512_si128(joint);
    if constexpr(Extra>=2)words[1]=_mm512_extracti32x4_epi32(joint,1);
    if constexpr(Extra>=3)words[2]=_mm512_extracti32x4_epi32(joint,2);
    if constexpr(Extra>=4)words[3]=_mm512_extracti32x4_epi32(joint,3);
}
static SPIN_FORCEINLINE void update(PackedState& state,PackedExtra& extra,const PackedState& feedback,
    const PackedExtra& extraFeedback,const BorderRow& row) {
    const auto r00=_mm512_set1_epi64(row.base.matrix[0]);
    const auto r01=_mm512_set1_epi64(row.base.matrix[1]);
    const auto r02=_mm512_set1_epi64(row.upper[0]);
    const auto n0=_mm512_xor_si512(_mm512_ternarylogic_epi64(
        _mm512_gf2p8affine_epi64_epi8(state.v[0],r00,0),
        _mm512_gf2p8affine_epi64_epi8(state.v[2],r01,0),
        _mm512_gf2p8affine_epi64_epi8(extra.lo,r02,0),0x96),feedback.v[0]);
    const auto n1=_mm512_xor_si512(_mm512_ternarylogic_epi64(
        _mm512_gf2p8affine_epi64_epi8(state.v[1],r00,0),
        _mm512_gf2p8affine_epi64_epi8(state.v[3],r01,0),
        _mm512_gf2p8affine_epi64_epi8(extra.hi,r02,0),0x96),feedback.v[1]);
    const auto r10=_mm512_set1_epi64(row.base.matrix[2]);
    const auto r11=_mm512_set1_epi64(row.base.matrix[3]);
    const auto r12=_mm512_set1_epi64(row.upper[1]);
    const auto n2=_mm512_xor_si512(_mm512_ternarylogic_epi64(
        _mm512_gf2p8affine_epi64_epi8(state.v[0],r10,0),
        _mm512_gf2p8affine_epi64_epi8(state.v[2],r11,0),
        _mm512_gf2p8affine_epi64_epi8(extra.lo,r12,0),0x96),feedback.v[2]);
    const auto n3=_mm512_xor_si512(_mm512_ternarylogic_epi64(
        _mm512_gf2p8affine_epi64_epi8(state.v[1],r10,0),
        _mm512_gf2p8affine_epi64_epi8(state.v[3],r11,0),
        _mm512_gf2p8affine_epi64_epi8(extra.hi,r12,0),0x96),feedback.v[3]);
    const auto r20=_mm512_set1_epi64(row.lower[0]);
    const auto r21=_mm512_set1_epi64(row.lower[1]);
    const auto r22=_mm512_set1_epi64(row.corner);
    const auto n4=_mm512_xor_si512(_mm512_ternarylogic_epi64(
        _mm512_gf2p8affine_epi64_epi8(state.v[0],r20,0),
        _mm512_gf2p8affine_epi64_epi8(state.v[2],r21,0),
        _mm512_gf2p8affine_epi64_epi8(extra.lo,r22,0),0x96),extraFeedback.lo);
    const auto n5=_mm512_xor_si512(_mm512_ternarylogic_epi64(
        _mm512_gf2p8affine_epi64_epi8(state.v[1],r20,0),
        _mm512_gf2p8affine_epi64_epi8(state.v[3],r21,0),
        _mm512_gf2p8affine_epi64_epi8(extra.hi,r22,0),0x96),extraFeedback.hi);
    state.v[0]=n0;state.v[1]=n1;state.v[2]=n2;state.v[3]=n3;
    extra.lo=n4;extra.hi=n5;
}
struct StreamingRoute {
    Block* scratch;const std::uint32_t* bases;
    SPIN_FORCEINLINE void operator()(std::size_t packet,__m512i value) {
        _mm512_store_si512(reinterpret_cast<__m512i*>(scratch+bases[packet]),value);
    }
};
template<unsigned Extra,class Emit>
static SPIN_NOINLINE void reverseBorder(const Block* input,std::size_t n,const BorderRow* rows,Emit& emit) {
    alignas(64) __m128i words[16],extraWords[4],moments[64],syndrome[16],extraSyndrome[4];
    alignas(64) __m512i packets[16];
    PackedState state{},feedback;PackedExtra extra{};
    for(std::size_t epoch=n/64;epoch-->0;) {
        const auto* raw=input+64*epoch;const bool first=epoch+1==n/64;
        if(first) {
            loadPackets(raw,packets,std::make_index_sequence<16>{});
            for(unsigned h=16;h-->0;)emit(16*epoch+h,packets[h]);
        } else {
            wideUnpackVbmi(state,words);unpackExtra<Extra>(extra,extraWords);
            rsfast::streamStepBorder<Extra>(words,extraWords,raw,16*epoch,emit,moments);
        }
        if(!epoch)break;
        if(first)packetMoments(packets,moments);
        finish(moments,syndrome);widePackVbmi(syndrome,feedback);
        extraSyndrome[0]=moments[3];
        if constexpr(Extra>=2)extraSyndrome[1]=moments[5];
        if constexpr(Extra>=3)extraSyndrome[2]=moments[9];
        if constexpr(Extra>=4)extraSyndrome[3]=moments[17];
        const auto extraFeedback=packExtra<Extra>(extraSyndrome);
        if(first){state=feedback;extra=extraFeedback;}
        else update(state,extra,feedback,extraFeedback,rows[epoch]);
    }
}
}
void reverseRouteCached(const Block* input,Block* scratch,const Plan& plan) {
    StreamingRoute emit{scratch,plan.route.data()};
    reverseBorder<4>(input,plan.n,plan.updates.data(),emit);
}

} // namespace spin::detail::packet
