"""Form the exact adjoint of the frozen small-outer RS circuit."""
from pathlib import Path
import hashlib
import re
import sys

here = Path(__file__).resolve().parent
source = (here/'NativeOuterFinish.h').read_text(encoding='utf-8')
def indices(name):
    body = re.search(r'const auto '+name+r'=_mm512_setr_epi64\((.*?)\);',source).group(1)
    return [b for x in body.split(',') for b in int(x.removesuffix('ULL'),16).to_bytes(8,'little')]
def constant(a):
    return '_mm512_setr_epi64('+','.join('0x'+int.from_bytes(bytes(a[i:i+8]),'little').to_bytes(8,'big').hex()+'ULL' for i in range(0,64,8))+')'
def transpose(m):
    return sum(((m>>(8*(7-i)+j))&1)<<(8*(7-j)+i) for i in range(8) for j in range(8))
joined = indices('i0') + indices('i1')
assert sorted(joined) == list(range(128))
a,b = [[joined.index(i) for i in range(start,start+64)] for start in (0,64)]
a,b = [[z[i^7] for i in range(64)] for z in (a,b)]
text = '''// Generated by src/paired15/generate_forward_outer.py.
''' + '// NativeOuterFinish.h SHA256: ' + hashlib.sha256(source.encode('utf-8')).hexdigest() + '\n' + '''
#include "Paired15.h"
#include "../packet/PacketInnerFast.h"
#include <utility>
namespace spin::detail::paired15 { namespace {
using packet::fast::unpackIndex;

// Load every physical cache line once even for wide records. All lane
// rearrangement is register-local; there is no full-message staging buffer.
template<unsigned L> struct Quads { __m512i v[L]; };
template<unsigned L> static SPIN_FORCEINLINE Quads<L> loadQuads(const Block* input) {
    if constexpr(L==1) return {{_mm512_loadu_si512(input)}};
    else if constexpr(L==2) {
        const auto a=_mm512_loadu_si512(input),b=_mm512_loadu_si512(input+4);
        return {{_mm512_shuffle_i32x4(a,b,0x88),_mm512_shuffle_i32x4(a,b,0xdd)}};
    } else {
        const auto a=_mm512_loadu_si512(input),b=_mm512_loadu_si512(input+4);
        const auto c=_mm512_loadu_si512(input+8),d=_mm512_loadu_si512(input+12);
        const auto ab0=_mm512_shuffle_i32x4(a,b,0x44),ab1=_mm512_shuffle_i32x4(a,b,0xee);
        const auto cd0=_mm512_shuffle_i32x4(c,d,0x44),cd1=_mm512_shuffle_i32x4(c,d,0xee);
        return {{_mm512_shuffle_i32x4(ab0,cd0,0x88),_mm512_shuffle_i32x4(ab0,cd0,0xdd),
                 _mm512_shuffle_i32x4(ab1,cd1,0x88),_mm512_shuffle_i32x4(ab1,cd1,0xdd)}};
    }
}
template<unsigned L> struct alignas(64) Packed { __m512i v[L][64]; };
template<unsigned S,unsigned P> static SPIN_FORCEINLINE void packMessage(__m512i x,__m512i y,__m512i* out) {
    const auto basis=_mm512_set1_epi64(0x0102040810204080ULL);
'''
text += f'    out[4*S+P]=_mm512_gf2p8affine_epi64_epi8(basis,_mm512_permutex2var_epi8(x,{constant(a)},y),0);\n'
text += f'    out[4*S+P+1]=_mm512_gf2p8affine_epi64_epi8(basis,_mm512_permutex2var_epi8(x,{constant(b)},y),0);\n}}\n'
text += '''template<unsigned S,unsigned P,unsigned L,unsigned... Lane>
static SPIN_FORCEINLINE void packLanes(const Block* input,Packed<L>& out,std::integer_sequence<unsigned,Lane...>) {
    const auto x=loadQuads<L>(input+L*(32*P+4*S));
    const auto y=loadQuads<L>(input+L*(32*(P+1)+4*S));
    (packMessage<S,P>(x.v[Lane],y.v[Lane],out.v[Lane]),...);
}
'''
p=source[source.index('x0=_mm512_xor_si512(x0,x1);'):source.index('return {{')]
pre,rest=p.split('auto y0=x0;');mid,post=rest.split('y0=_mm512_xor_si512(y0,y1);')
post='y0=_mm512_xor_si512(y0,y1);'+post
text += 'template<unsigned P> static SPIN_FORCEINLINE void parityForward(__m512i* packed) {\n'
for i in range(8): text += f'auto y{i}=packed[4*{i}+P];\n'
for i,j in reversed(re.findall(r'y(\d)=_mm512_xor_si512\(y\d,y(\d)\);',post)):
    text += f'y{j}=_mm512_xor_si512(y{j},y{i});\n'
for i in range(8): text += f'auto x{i}=y{i};\n'
products = re.findall(r'y(\d)=_mm512_xor_si512\([xy]\d,_mm512_gf2p8affine_epi64_epi8\(x(\d),m(\d+),0\)\);',mid)
assert len(products) == 19, 'RS adjoint must preserve all nineteen field products'
for i,j,m in products:
    value=int(re.search(r'const auto m'+m+r'=_mm512_set1_epi64\(0x([0-9a-f]+)ULL\);',source).group(1),16)
    text += f'x{j}=_mm512_xor_si512(x{j},_mm512_gf2p8affine_epi64_epi8(y{i},_mm512_set1_epi64(0x{transpose(value):016x}ULL),0));\n'
for i,j in reversed(re.findall(r'x(\d)=_mm512_xor_si512\(x\d,x(\d)\);',pre)):
    text += f'x{j}=_mm512_xor_si512(x{j},x{i});\n'
for i in range(8): text += f'packed[32+4*{i}+P]=x{i};\n'
text += '''}
static SPIN_FORCEINLINE void parityPlanes(__m512i* packed) {
    parityForward<0>(packed);parityForward<1>(packed);
    parityForward<2>(packed);parityForward<3>(packed);
}
struct Pair {__m512i lo,hi;};
static SPIN_FORCEINLINE Pair adjoint2(__m512i a,__m512i b,__m512i m0,__m512i m1,__m512i m2) {
    const auto p=_mm512_gf2p8affine_epi64_epi8(_mm512_xor_si512(a,b),m0,0);
    const auto q=_mm512_gf2p8affine_epi64_epi8(a,m1,0);
    const auto r=_mm512_gf2p8affine_epi64_epi8(b,m2,0);
    return {_mm512_xor_si512(p,r),_mm512_xor_si512(q,r)};
}
// Exact inverse of the native outer's pack-and-transpose permutation.
// Multiplication is adjointed, not inverted; the systematic RS map expands.
static SPIN_FORCEINLINE void unpackPair(__m512i lo,__m512i hi,Block* output) {
    const auto basis=_mm512_set1_epi64(0x8040201008040201ULL);
    const auto a=_mm512_gf2p8affine_epi64_epi8(basis,lo,0);
    const auto b=_mm512_gf2p8affine_epi64_epi8(basis,hi,0);
    _mm512_storeu_si512(output,_mm512_permutex2var_epi8(a,unpackIndex<0>(),b));
    _mm512_storeu_si512(output+4,_mm512_permutex2var_epi8(a,unpackIndex<4>(),b));
}
static SPIN_FORCEINLINE void mixSymbol(const __m512i* input,Block* output,__m512i m0,__m512i m1,__m512i m2) {
    const auto a=adjoint2(input[0],input[2],m0,m1,m2);
    const auto b=adjoint2(input[1],input[3],m0,m1,m2);
    unpackPair(a.lo,b.lo,output);unpackPair(a.hi,b.hi,output+8);
}
template<unsigned L,unsigned... Lane>
static SPIN_NOINLINE void groupForward(const Block* input,Block* output,std::size_t stride,
    const std::array<std::uint64_t,3>* coeff,std::integer_sequence<unsigned,Lane...> lanes) {
    Packed<L> packed;
'''
for s in range(8):
    for p in (0,2): text += f'    packLanes<{s},{p}>(input,packed,lanes);\n'
text += '''    (parityPlanes(packed.v[Lane]),...);
    for(unsigned symbol=0;symbol<16;++symbol) {
        const auto m0=_mm512_set1_epi64(coeff[symbol][0]);
        const auto m1=_mm512_set1_epi64(coeff[symbol][1]);
        const auto m2=_mm512_set1_epi64(coeff[symbol][2]);
        (mixSymbol(packed.v[Lane]+4*symbol,output+Lane*stride+16*symbol,m0,m1,m2),...);
    }
}
template<unsigned L> void outer(const Block* input,Block* scratch,const Plan& p) {
    for(std::size_t group=0;group<p.groups;++group)
        groupForward<L>(input+128*L*group,scratch+groupStride*group,p.scratchBlocks(),
                        p.outerAdjoint.data()+16*group,std::make_integer_sequence<unsigned,L>{});
}
}
void forwardOuterFast(const Block* input,Block* scratch,const Plan& p,unsigned lanes) {
    if(lanes==1)outer<1>(input,scratch,p);
    else if(lanes==2)outer<2>(input,scratch,p);
    else outer<4>(input,scratch,p);
}
}
'''
output = here/'Paired15ForwardOuter.cpp'
if '--check' in sys.argv:
    if not output.exists() or output.read_text(encoding='utf-8') != text:
        raise SystemExit('Paired15ForwardOuter.cpp is stale; run src/paired15/generate_forward_outer.py')
    print('Verified exact forward RS adjoint and direct interleaved loads.')
else:
    output.write_bytes(text.encode('utf-8'))
    print('Generated exact forward RS adjoint and direct interleaved loads.')
