// Generated by src/paired15/generate_forward_outer.py.
// NativeOuterFinish.h SHA256: 260ab130d9ea8687da73462c84ecd6dc1e2826301a41855b657d4ff1516f1904

#include "Paired15.h"
#include "../packet/PacketInnerFast.h"
#include <utility>
namespace spin::detail::paired15 { namespace {
using packet::fast::unpackIndex;

// Load every physical cache line once even for wide records. All lane
// rearrangement is register-local; there is no full-message staging buffer.
template<unsigned L> struct Quads { __m512i v[L]; };
template<unsigned L> static SPIN_FORCEINLINE Quads<L> loadQuads(const Block* input) {
    if constexpr(L==1) return {{_mm512_loadu_si512(input)}};
    else if constexpr(L==2) {
        const auto a=_mm512_loadu_si512(input),b=_mm512_loadu_si512(input+4);
        return {{_mm512_shuffle_i32x4(a,b,0x88),_mm512_shuffle_i32x4(a,b,0xdd)}};
    } else {
        const auto a=_mm512_loadu_si512(input),b=_mm512_loadu_si512(input+4);
        const auto c=_mm512_loadu_si512(input+8),d=_mm512_loadu_si512(input+12);
        const auto ab0=_mm512_shuffle_i32x4(a,b,0x44),ab1=_mm512_shuffle_i32x4(a,b,0xee);
        const auto cd0=_mm512_shuffle_i32x4(c,d,0x44),cd1=_mm512_shuffle_i32x4(c,d,0xee);
        return {{_mm512_shuffle_i32x4(ab0,cd0,0x88),_mm512_shuffle_i32x4(ab0,cd0,0xdd),
                 _mm512_shuffle_i32x4(ab1,cd1,0x88),_mm512_shuffle_i32x4(ab1,cd1,0xdd)}};
    }
}
template<unsigned L> struct alignas(64) Packed { __m512i v[L][64]; };
template<unsigned S,unsigned P> static SPIN_FORCEINLINE void packMessage(__m512i x,__m512i y,__m512i* out) {
    const auto basis=_mm512_set1_epi64(0x0102040810204080ULL);
    out[4*S+P]=_mm512_gf2p8affine_epi64_epi8(basis,_mm512_permutex2var_epi8(x,_mm512_setr_epi64(0x0010203040506070ULL,0x0111213141516171ULL,0x0212223242526272ULL,0x0313233343536373ULL,0x0414243444546474ULL,0x0515253545556575ULL,0x0616263646566676ULL,0x0717273747576777ULL),y),0);
    out[4*S+P+1]=_mm512_gf2p8affine_epi64_epi8(basis,_mm512_permutex2var_epi8(x,_mm512_setr_epi64(0x0818283848586878ULL,0x0919293949596979ULL,0x0a1a2a3a4a5a6a7aULL,0x0b1b2b3b4b5b6b7bULL,0x0c1c2c3c4c5c6c7cULL,0x0d1d2d3d4d5d6d7dULL,0x0e1e2e3e4e5e6e7eULL,0x0f1f2f3f4f5f6f7fULL),y),0);
}
template<unsigned S,unsigned P,unsigned L,unsigned... Lane>
static SPIN_FORCEINLINE void packLanes(const Block* input,Packed<L>& out,std::integer_sequence<unsigned,Lane...>) {
    const auto x=loadQuads<L>(input+L*(32*P+4*S));
    const auto y=loadQuads<L>(input+L*(32*(P+1)+4*S));
    (packMessage<S,P>(x.v[Lane],y.v[Lane],out.v[Lane]),...);
}
template<unsigned P> static SPIN_FORCEINLINE void parityForward(__m512i* packed) {
auto y0=packed[4*0+P];
auto y1=packed[4*1+P];
auto y2=packed[4*2+P];
auto y3=packed[4*3+P];
auto y4=packed[4*4+P];
auto y5=packed[4*5+P];
auto y6=packed[4*6+P];
auto y7=packed[4*7+P];
y7=_mm512_xor_si512(y7,y3);
y6=_mm512_xor_si512(y6,y2);
y5=_mm512_xor_si512(y5,y1);
y4=_mm512_xor_si512(y4,y0);
y7=_mm512_xor_si512(y7,y5);
y6=_mm512_xor_si512(y6,y4);
y3=_mm512_xor_si512(y3,y1);
y2=_mm512_xor_si512(y2,y0);
y7=_mm512_xor_si512(y7,y6);
y5=_mm512_xor_si512(y5,y4);
y3=_mm512_xor_si512(y3,y2);
y1=_mm512_xor_si512(y1,y0);
auto x0=y0;
auto x1=y1;
auto x2=y2;
auto x3=y3;
auto x4=y4;
auto x5=y5;
auto x6=y6;
auto x7=y7;
x0=_mm512_xor_si512(x0,_mm512_gf2p8affine_epi64_epi8(y1,_mm512_set1_epi64(0x0b0d0a05b0d0a050ULL),0));
x0=_mm512_xor_si512(x0,_mm512_gf2p8affine_epi64_epi8(y2,_mm512_set1_epi64(0x0809020480902040ULL),0));
x0=_mm512_xor_si512(x0,_mm512_gf2p8affine_epi64_epi8(y3,_mm512_set1_epi64(0x0708010370801030ULL),0));
x1=_mm512_xor_si512(x1,_mm512_gf2p8affine_epi64_epi8(y3,_mm512_set1_epi64(0x0809020480902040ULL),0));
x2=_mm512_xor_si512(x2,_mm512_gf2p8affine_epi64_epi8(y3,_mm512_set1_epi64(0x0b0d0a05b0d0a050ULL),0));
x0=_mm512_xor_si512(x0,_mm512_gf2p8affine_epi64_epi8(y4,_mm512_set1_epi64(0x050e0d0a50e0d0a0ULL),0));
x0=_mm512_xor_si512(x0,_mm512_gf2p8affine_epi64_epi8(y5,_mm512_set1_epi64(0x060a050b60a050b0ULL),0));
x1=_mm512_xor_si512(x1,_mm512_gf2p8affine_epi64_epi8(y5,_mm512_set1_epi64(0x050e0d0a50e0d0a0ULL),0));
x4=_mm512_xor_si512(x4,_mm512_gf2p8affine_epi64_epi8(y5,_mm512_set1_epi64(0x0b0d0a05b0d0a050ULL),0));
x0=_mm512_xor_si512(x0,_mm512_gf2p8affine_epi64_epi8(y6,_mm512_set1_epi64(0x0b0d0a05b0d0a050ULL),0));
x2=_mm512_xor_si512(x2,_mm512_gf2p8affine_epi64_epi8(y6,_mm512_set1_epi64(0x050e0d0a50e0d0a0ULL),0));
x4=_mm512_xor_si512(x4,_mm512_gf2p8affine_epi64_epi8(y6,_mm512_set1_epi64(0x0809020480902040ULL),0));
x0=_mm512_xor_si512(x0,_mm512_gf2p8affine_epi64_epi8(y7,_mm512_set1_epi64(0x02060c092060c090ULL),0));
x1=_mm512_xor_si512(x1,_mm512_gf2p8affine_epi64_epi8(y7,_mm512_set1_epi64(0x0b0d0a05b0d0a050ULL),0));
x2=_mm512_xor_si512(x2,_mm512_gf2p8affine_epi64_epi8(y7,_mm512_set1_epi64(0x060a050b60a050b0ULL),0));
x3=_mm512_xor_si512(x3,_mm512_gf2p8affine_epi64_epi8(y7,_mm512_set1_epi64(0x050e0d0a50e0d0a0ULL),0));
x4=_mm512_xor_si512(x4,_mm512_gf2p8affine_epi64_epi8(y7,_mm512_set1_epi64(0x0708010370801030ULL),0));
x5=_mm512_xor_si512(x5,_mm512_gf2p8affine_epi64_epi8(y7,_mm512_set1_epi64(0x0809020480902040ULL),0));
x6=_mm512_xor_si512(x6,_mm512_gf2p8affine_epi64_epi8(y7,_mm512_set1_epi64(0x0b0d0a05b0d0a050ULL),0));
x7=_mm512_xor_si512(x7,x3);
x6=_mm512_xor_si512(x6,x2);
x5=_mm512_xor_si512(x5,x1);
x4=_mm512_xor_si512(x4,x0);
x7=_mm512_xor_si512(x7,x5);
x6=_mm512_xor_si512(x6,x4);
x3=_mm512_xor_si512(x3,x1);
x2=_mm512_xor_si512(x2,x0);
x7=_mm512_xor_si512(x7,x6);
x5=_mm512_xor_si512(x5,x4);
x3=_mm512_xor_si512(x3,x2);
x1=_mm512_xor_si512(x1,x0);
packed[32+4*0+P]=x0;
packed[32+4*1+P]=x1;
packed[32+4*2+P]=x2;
packed[32+4*3+P]=x3;
packed[32+4*4+P]=x4;
packed[32+4*5+P]=x5;
packed[32+4*6+P]=x6;
packed[32+4*7+P]=x7;
}
static SPIN_FORCEINLINE void parityPlanes(__m512i* packed) {
    parityForward<0>(packed);parityForward<1>(packed);
    parityForward<2>(packed);parityForward<3>(packed);
}
struct Pair {__m512i lo,hi;};
static SPIN_FORCEINLINE Pair adjoint2(__m512i a,__m512i b,__m512i m0,__m512i m1,__m512i m2) {
    const auto p=_mm512_gf2p8affine_epi64_epi8(_mm512_xor_si512(a,b),m0,0);
    const auto q=_mm512_gf2p8affine_epi64_epi8(a,m1,0);
    const auto r=_mm512_gf2p8affine_epi64_epi8(b,m2,0);
    return {_mm512_xor_si512(p,r),_mm512_xor_si512(q,r)};
}
// Exact inverse of the native outer's pack-and-transpose permutation.
// Multiplication is adjointed, not inverted; the systematic RS map expands.
static SPIN_FORCEINLINE void unpackPair(__m512i lo,__m512i hi,Block* output) {
    const auto basis=_mm512_set1_epi64(0x8040201008040201ULL);
    const auto a=_mm512_gf2p8affine_epi64_epi8(basis,lo,0);
    const auto b=_mm512_gf2p8affine_epi64_epi8(basis,hi,0);
    _mm512_storeu_si512(output,_mm512_permutex2var_epi8(a,unpackIndex<0>(),b));
    _mm512_storeu_si512(output+4,_mm512_permutex2var_epi8(a,unpackIndex<4>(),b));
}
static SPIN_FORCEINLINE void mixSymbol(const __m512i* input,Block* output,__m512i m0,__m512i m1,__m512i m2) {
    const auto a=adjoint2(input[0],input[2],m0,m1,m2);
    const auto b=adjoint2(input[1],input[3],m0,m1,m2);
    unpackPair(a.lo,b.lo,output);unpackPair(a.hi,b.hi,output+8);
}
template<unsigned L,unsigned... Lane>
static SPIN_NOINLINE void groupForward(const Block* input,Block* output,std::size_t stride,
    const std::array<std::uint64_t,3>* coeff,std::integer_sequence<unsigned,Lane...> lanes) {
    Packed<L> packed;
    packLanes<0,0>(input,packed,lanes);
    packLanes<0,2>(input,packed,lanes);
    packLanes<1,0>(input,packed,lanes);
    packLanes<1,2>(input,packed,lanes);
    packLanes<2,0>(input,packed,lanes);
    packLanes<2,2>(input,packed,lanes);
    packLanes<3,0>(input,packed,lanes);
    packLanes<3,2>(input,packed,lanes);
    packLanes<4,0>(input,packed,lanes);
    packLanes<4,2>(input,packed,lanes);
    packLanes<5,0>(input,packed,lanes);
    packLanes<5,2>(input,packed,lanes);
    packLanes<6,0>(input,packed,lanes);
    packLanes<6,2>(input,packed,lanes);
    packLanes<7,0>(input,packed,lanes);
    packLanes<7,2>(input,packed,lanes);
    (parityPlanes(packed.v[Lane]),...);
    for(unsigned symbol=0;symbol<16;++symbol) {
        const auto m0=_mm512_set1_epi64(coeff[symbol][0]);
        const auto m1=_mm512_set1_epi64(coeff[symbol][1]);
        const auto m2=_mm512_set1_epi64(coeff[symbol][2]);
        (mixSymbol(packed.v[Lane]+4*symbol,output+Lane*stride+16*symbol,m0,m1,m2),...);
    }
}
template<unsigned L> void outer(const Block* input,Block* scratch,const Plan& p) {
    for(std::size_t group=0;group<p.groups;++group)
        groupForward<L>(input+128*L*group,scratch+groupStride*group,p.scratchBlocks(),
                        p.outerAdjoint.data()+16*group,std::make_integer_sequence<unsigned,L>{});
}
}
void forwardOuterFast(const Block* input,Block* scratch,const Plan& p,unsigned lanes) {
    if(lanes==1)outer<1>(input,scratch,p);
    else if(lanes==2)outer<2>(input,scratch,p);
    else outer<4>(input,scratch,p);
}
}
