/- Generated by emit_majorant.py: 1 leaves, 0 logs. -/
import SpinCodes.Numeric.MajorantDefs
set_option maxRecDepth 8000000
set_option maxHeartbeats 0
namespace Spin.Majorant.S3.P12
open Spin.Numeric Spin.Numeric.Fix
def table : LogTree := .leaf
def tree : BoxTree := .leaf (1)
def A : Fix := ⟨375000000000000000000000000000, 500000000000000000000000000000⟩
def B : Fix := ⟨375000000000000000000000000000, 500000000000000000000000000000⟩
def W : Fix := ⟨160903293567700000000000000000, 164652567555266666666666666667⟩
def S : Fix := ⟨1630000000000000000000000000000, 1630000000000000000000000000000⟩
def I : Fix := ⟨-167527934405350000000000000000, -167527934405350000000000000000⟩
theorem logs_ok : table.check 10 = true := by decide
theorem tree_ok : checkTree (majorantLeaf (treeLog table) S I) tree A B W = true := by decide
end Spin.Majorant.S3.P12
