#!/usr/bin/env python3
"""Generate tuned transposed XOR kernels for the explicit XBCH [64,32] code."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

import probe_bch_forward_xor_circuit as paar  # noqa: E402


DIMENSION = 32
LENGTH = 64
DEFAULT_ROWS = SCRIPT_DIR / "xbch64_32_philips_generator_rows.txt"


def load_rows(path: Path) -> list[int]:
    rows = [int(line.strip(), 16) for line in path.read_text().splitlines() if line.strip()]
    if len(rows) != DIMENSION:
        raise RuntimeError("expected 32 generator rows")
    identity = (1 << DIMENSION) - 1
    for index, row in enumerate(rows):
        if (row & identity) != 1 << index:
            raise RuntimeError("generator is not in the committed systematic layout")
    return rows


def columns(rows: list[int]) -> list[int]:
    result = [0] * LENGTH
    for row_index, row in enumerate(rows):
        for column in range(LENGTH):
            if (row >> column) & 1:
                result[column] |= 1 << row_index
    return result


def rows_sha256(rows: list[int]) -> str:
    return hashlib.sha256(
        b"".join(row.to_bytes(8, "little") for row in rows)
    ).hexdigest()


def emit_kernel_body(
    circuit: paar.Circuit,
    schedule: list[int],
    packed: int,
) -> list[str]:
    terms = paar.transpose_terms(circuit)

    def term_name(term: tuple[str, int]) -> str:
        kind, index = term
        return f"word[{index}]" if kind == "word" else f"a{index}"

    lines: list[str] = []
    for signal in schedule:
        expression = " ^ ".join(term_name(term) for term in terms[signal])
        if signal < DIMENSION:
            if packed == 1:
                lines.append(f"\t\tmessage[{signal}] = {expression};")
            elif packed == 2:
                lines.extend([
                    f"\t\tconst Xbch64Packed2 output{signal} = {expression};",
                    f"\t\tmessage0[{signal}].mData = _mm256_castsi256_si128(output{signal}.value);",
                    f"\t\tmessage1[{signal}].mData = _mm256_extracti128_si256(output{signal}.value, 1);",
                ])
            else:
                lines.extend([
                    f"\t\tconst Xbch64Packed4 output{signal} = {expression};",
                    f"\t\tmessage0[{signal}].mData = _mm512_extracti32x4_epi32(output{signal}.value, 0);",
                    f"\t\tmessage1[{signal}].mData = _mm512_extracti32x4_epi32(output{signal}.value, 1);",
                    f"\t\tmessage2[{signal}].mData = _mm512_extracti32x4_epi32(output{signal}.value, 2);",
                    f"\t\tmessage3[{signal}].mData = _mm512_extracti32x4_epi32(output{signal}.value, 3);",
                ])
        else:
            if not expression:
                raise RuntimeError("unused internal signal in transposed circuit")
            value_type = "block" if packed == 1 else f"Xbch64Packed{packed}"
            lines.append(f"\t\tconst {value_type} a{signal} = {expression};")
    return lines


def write_header(
    path: Path,
    circuit: paar.Circuit,
    schedule: list[int],
    circuit_seed: int,
    schedule_seed: int,
    row_digest: str,
) -> None:
    transpose_xors = paar.transpose_xor_count(circuit)
    peak, area = paar.transpose_live_stats(circuit, schedule)
    lines = [
        "#pragma once",
        "",
        "// Generated by scripts/build_xbch64_32_philips_circuit.py.",
        f"// Exact {transpose_xors}-XOR transpose; synthesis seed {circuit_seed}, schedule seed {schedule_seed}.",
        f"// Transpose live peak {peak}, live area {area}.",
        f"// Generator rows SHA-256: {row_digest}.",
        "",
        "#include <immintrin.h>",
        "#include <cryptoTools/Common/Defines.h>",
        "",
        "namespace osuCrypto::detail",
        "{",
        "#if defined(_MSC_VER)",
        "#define LIBOTE_RIFFLE_XBCH_NOINLINE __declspec(noinline)",
        "#elif defined(__GNUC__) || defined(__clang__)",
        "#define LIBOTE_RIFFLE_XBCH_NOINLINE __attribute__((noinline))",
        "#else",
        "#define LIBOTE_RIFFLE_XBCH_NOINLINE",
        "#endif",
        "\tLIBOTE_RIFFLE_XBCH_NOINLINE inline void xbch64x32PhilipsTranspose(",
        "\t\tconst block* __restrict word, block* __restrict message)",
        "\t{",
    ]
    lines.extend(emit_kernel_body(circuit, schedule, 1))
    lines.extend([
        "\t}",
        "",
        "#if defined(OC_ENABLE_AVX2)",
        "\tstruct Xbch64Packed2 { __m256i value; };",
        "\tOC_FORCEINLINE Xbch64Packed2 operator^(Xbch64Packed2 a, Xbch64Packed2 b)",
        "\t{ return { _mm256_xor_si256(a.value, b.value) }; }",
        "",
        "\tLIBOTE_RIFFLE_XBCH_NOINLINE inline void xbch64x32PhilipsTranspose2(",
        "\t\tconst block* __restrict word0, const block* __restrict word1,",
        "\t\tblock* __restrict message0, block* __restrict message1)",
        "\t{",
        "\t\tXbch64Packed2 word[64];",
        "\t\tfor (u64 index = 0; index < 64; ++index)",
        "\t\t\tword[index].value = _mm256_set_m128i(word1[index].mData, word0[index].mData);",
    ])
    lines.extend(emit_kernel_body(circuit, schedule, 2))
    lines.extend([
        "\t}",
        "",
        "#if defined(__AVX512F__)",
        "\tstruct Xbch64Packed4 { __m512i value; };",
        "\tOC_FORCEINLINE Xbch64Packed4 operator^(Xbch64Packed4 a, Xbch64Packed4 b)",
        "\t{ return { _mm512_xor_si512(a.value, b.value) }; }",
        "",
        "\tLIBOTE_RIFFLE_XBCH_NOINLINE inline void xbch64x32PhilipsTranspose4(",
        "\t\tconst block* __restrict word0, const block* __restrict word1,",
        "\t\tconst block* __restrict word2, const block* __restrict word3,",
        "\t\tblock* __restrict message0, block* __restrict message1,",
        "\t\tblock* __restrict message2, block* __restrict message3)",
        "\t{",
        "\t\tXbch64Packed4 word[64];",
        "\t\tfor (u64 index = 0; index < 64; ++index)",
        "\t\t{",
        "\t\t\tconst auto low = _mm256_set_m128i(word1[index].mData, word0[index].mData);",
        "\t\t\tconst auto high = _mm256_set_m128i(word3[index].mData, word2[index].mData);",
        "\t\t\tword[index].value = _mm512_inserti64x4(_mm512_castsi256_si512(low), high, 1);",
        "\t\t}",
    ])
    lines.extend(emit_kernel_body(circuit, schedule, 4))
    lines.extend([
        "\t}",
        "#endif",
        "#endif",
        "#undef LIBOTE_RIFFLE_XBCH_NOINLINE",
        "}",
        "",
    ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rows", type=Path, default=DEFAULT_ROWS)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--trials", type=int, default=1024)
    parser.add_argument("--schedule-trials", type=int, default=256)
    parser.add_argument(
        "--selection",
        choices=("xor", "live"),
        default="xor",
        help="Choose the XOR minimum or the lowest-pressure circuit within the XOR allowance.",
    )
    parser.add_argument("--max-extra-xors", type=int, default=0)
    parser.add_argument("--header", type=Path, required=True)
    parser.add_argument("--receipt", type=Path)
    args = parser.parse_args()

    rows = load_rows(args.rows)
    target = columns(rows)
    paar.DIMENSION = DIMENSION
    paar.LENGTH = LENGTH
    candidates: list[tuple[tuple[int, int, int], int, paar.Circuit]] = []
    for seed in range(args.seed, args.seed + args.trials):
        circuit = paar.synthesize(seed, 2, target)
        score = (
            paar.transpose_xor_count(circuit),
            circuit.xor_count,
            len(circuit.gates),
        )
        candidates.append((score, seed, circuit))
    minimum_transpose_xors = min(item[0][0] for item in candidates)
    eligible = [
        item for item in candidates
        if item[0][0] <= minimum_transpose_xors + args.max_extra_xors
    ]
    if args.selection == "xor":
        _, circuit_seed, best = min(eligible, key=lambda item: item[0])
    else:
        screened = []
        for score, seed, circuit in eligible:
            schedule = paar.greedy_transpose_schedule(circuit, 0)
            live = paar.transpose_live_stats(circuit, schedule)
            screened.append((live, score, seed, circuit))
        _, _, circuit_seed, best = min(screened, key=lambda item: (item[0], item[1]))
    schedules = [
        (paar.transpose_live_stats(best, paar.greedy_transpose_schedule(best, seed)), seed,
         paar.greedy_transpose_schedule(best, seed))
        for seed in range(args.schedule_trials)
    ]
    (peak, area), schedule_seed, schedule = min(schedules, key=lambda item: item[0])
    digest = rows_sha256(rows)
    write_header(args.header, best, schedule, circuit_seed, schedule_seed, digest)

    payload = {
        "schema": "xbch64-32-philips-transpose-circuit-v1",
        "generator_rows_sha256": digest,
        "synthesis_seed": circuit_seed,
        "synthesis_trials": args.trials,
        "selection": args.selection,
        "minimum_transpose_xors_in_search": minimum_transpose_xors,
        "max_extra_xors": args.max_extra_xors,
        "forward_xors": best.xor_count,
        "transpose_xors": paar.transpose_xor_count(best),
        "transpose_peak_live": peak,
        "transpose_live_area": area,
        "schedule_seed": schedule_seed,
        "schedule_trials": args.schedule_trials,
        "header": str(args.header),
    }
    if args.receipt is not None:
        args.receipt.parent.mkdir(parents=True, exist_ok=True)
        args.receipt.write_text(json.dumps(payload, indent=2) + "\n")
    for key, value in payload.items():
        print(f"{key},{value}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
