#!/usr/bin/env python3
"""Finite algebra checks behind the fixed-map cluster-peeling lemma.

Pair capacity gives the generic statement: an ``s``-edge subhypergraph has a
tile of degree at most ``floor(sqrt(s))``.  At ``s=64`` equality could leave an
8-regular hypergraph on eight tiles in every band.  This script checks the
finite modular facts used to exclude that equality case for

    (t, l) -> (t, t + 9*l, t + 20*l) mod 256,  0 <= l < 64.

After multiplying tile labels by 57, an edge is

    (a, b, c) = (a, a+l, 116*b - 115*a).

If an 8-regular 64-edge subhypergraph existed, its first two parts A,B would
form K_8,8.  Thus A lies in one length-64 cyclic arc.  Writing U=-115*A and
V=116*B, the eight third-band labels say |U+V|=|U|=8.  Multiplication by 116
has kernel four, so |V|>=2.  Two distinct translates U+v must therefore be
equal, giving U a nonzero period.  Every nontrivial subgroup of Z/256 contains
128; because -115 is odd, A would contain an antipodal pair, contradicting
the length-64 arc.
"""

from __future__ import annotations

from collections import Counter
from math import isqrt


MODULUS = 256
LANES = 64


def generated_subgroup(step: int) -> set[int]:
    return {(multiple * step) % MODULUS for multiple in range(MODULUS)}


def main() -> None:
    inverse_nine = 57
    if 9 * inverse_nine % MODULUS != 1:
        raise SystemExit("inverse-of-nine check failed")
    if 20 * inverse_nine % MODULUS != 116:
        raise SystemExit("normalized third coefficient check failed")
    if (1 - 116) % MODULUS != (-115) % MODULUS:
        raise SystemExit("normalized affine form check failed")

    fibers = Counter(116 * value % MODULUS for value in range(MODULUS))
    if max(fibers.values()) != 4 or set(fibers.values()) != {4}:
        raise SystemExit("multiplication-by-116 kernel check failed")

    for step in range(1, MODULUS):
        if 128 not in generated_subgroup(step):
            raise SystemExit(f"nonzero subgroup generated by {step} misses 128")

    for start in range(MODULUS):
        arc = {(start + offset) % MODULUS for offset in range(LANES)}
        if any((value + 128) % MODULUS in arc for value in arc):
            raise SystemExit("length-64 arc contains an antipodal pair")

    # Exhibit the harmless 4-regular 64-edge pattern used as a regression
    # test: t is a multiple of 16 and l is a multiple of 16.
    edges = [
        (tile, (tile + 9 * lane) % MODULUS, (tile + 20 * lane) % MODULUS)
        for tile in range(0, MODULUS, 16)
        for lane in range(0, LANES, 16)
    ]
    if len(edges) != 64 or len(set(edges)) != 64:
        raise SystemExit("4-regular witness edge count failed")
    for band in range(3):
        degrees = Counter(edge[band] for edge in edges)
        if len(degrees) != 16 or set(degrees.values()) != {4}:
            raise SystemExit(f"4-regular witness failed in band {band}")

    cutoff_blocks = LANES * 106 // 22
    if cutoff_blocks != 308 or isqrt(cutoff_blocks) != 17:
        raise SystemExit("support-cutoff peeling width check failed")

    print("fixed three-band peeling certificate")
    print("normalized_edge=(a,a+l,116*b-115*a) mod 256")
    print("kernel_size_mul_116=4")
    print("every_nonzero_period_contains_antipode=PASS")
    print("length_64_arc_excludes_antipode=PASS")
    print("eight_regular_64_edge_subhypergraph=IMPOSSIBLE")
    print("four_regular_64_edge_witness=PASS")
    print("support_106_active_blocks_max=308")
    print("generic_peeling_cluster_width_max=17")
    print("size_at_most_64_peeling_cluster_width_max=7")
    print("status=EXACT_FINITE_ALGEBRA_CHECKS")


if __name__ == "__main__":
    main()
