#!/usr/bin/env python3
"""Exact dyadic turnoff cap for the systematic striped Riffle kernel.

The exact input-slice rows t<=10 and complements are committed separately.
The exact state-column enumerations q<=10 and complements are summarized by
their maximizing entries in ``ebch128_systematic_column_extrema.csv``; the
full rows are regenerated by ``enumerate_systematic_split_slice.cpp`` in
``column`` mode.

For every remaining (t,q), the joint split count is capped by the ordinary
EBCH spectrum, its input-row mass C(64,t), and its state-column mass C(64,q).
The all-ones pair (64,64) is excluded and handled as a 63-collision outer
event.  This script proves every other one-step exact-support cancellation is
at most 2^-39.  Allowing a factor below two for an episode restart gives the
uniform 2^-38 restart cap used by the group ledger.
"""

from __future__ import annotations

import csv
import math
from collections import Counter
from fractions import Fraction
from pathlib import Path

from certificate_spectra import load_ebch128_spectrum


ROOT = Path(__file__).resolve().parent
B = 64
SPECTRUM = ROOT / "EBCH128_64.wd"
ROWS = ROOT / "ebch128_systematic_split_slices.csv"
COLUMNS = ROOT / "ebch128_systematic_column_extrema.csv"


def load_rows() -> dict[int, Counter[int]]:
    result: dict[int, Counter[int]] = {}
    with ROWS.open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            result.setdefault(int(row["input_weight"]), Counter())[
                int(row["state_weight"])
            ] += int(row["count"])
    return result


def main() -> None:
    loaded = load_ebch128_spectrum(SPECTRUM)
    spectrum = {weight: count for weight, count in loaded if weight and count}
    rows = load_rows()
    exact_columns: dict[int, tuple[int, int]] = {}
    with COLUMNS.open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            q = int(row["state_weight"])
            t = int(row["max_input_weight"])
            count = int(row["max_count"])
            exact_columns[q] = (t, count)
            exact_columns[B - q] = (B - t, count)

    threshold = Fraction(1, 1 << 39)
    worst = Fraction(0)
    worst_case: tuple[int, int, int, str] | None = None
    for t in range(1, B + 1):
        for q in range(1, B + 1):
            if (t, q) == (B, B):
                continue
            if t in rows:
                count = rows[t].get(q, 0)
                source = "exact row"
            else:
                caps = [
                    spectrum.get(t + q, 0),
                    math.comb(B, t),
                    math.comb(B, q),
                ]
                source = "row/column/spectrum caps"
                if q in exact_columns:
                    # The committed column artifact records the maximum count
                    # over every input row, not merely one joint entry.  It is
                    # therefore a valid cap for *all* t in this column.  The
                    # maximizing row is metadata only; using only that row
                    # would fail to check the other denominators C(64,t).
                    _, maximizing_count = exact_columns[q]
                    caps.append(maximizing_count)
                    source = "exact-column/spectrum caps"
                count = min(caps)
            if not count:
                continue
            probability = Fraction(count, math.comb(B, t) * math.comb(B, q))
            if probability > worst:
                worst = probability
                worst_case = (t, q, count, source)

    if worst > threshold:
        raise SystemExit("systematic turnoff: non-all-ones cap exceeds 2^-39")
    # The reached-vector episode envelope has prefactor/rho below two.  Keeping
    # a full factor of two is intentionally coarser than the exact ratio.
    if 2 * worst > Fraction(1, 1 << 38):
        raise SystemExit("systematic turnoff: restart cap exceeds 2^-38")

    assert worst_case is not None
    print("systematic striped turnoff cap")
    print(f"worst_t={worst_case[0]} worst_q={worst_case[1]}")
    print(f"worst_count={worst_case[2]} source={worst_case[3]}")
    print(f"worst_probability={worst.numerator}/{worst.denominator}")
    print(f"worst_log2={math.log2(worst.numerator / worst.denominator):.12f}")
    print("non_allones_turnoff_le_2^-39=PASS")
    print("episode_restart_le_2^-38=PASS")
    print("allones_pair_64_64=SEPARATE_OUTER_COLLISION_CASE")


if __name__ == "__main__":
    main()
