#!/usr/bin/env python3
"""Synthesize the systematic-left EBCH state map P and its transpose.

For E_sys(v)=(v,Pv), the hot transpose step is

    result = current + P^T state.

The final 64 current/result XORs are counted separately from the synthesized
P transpose.  Every candidate circuit is verified exactly by the shared Paar
synthesizer.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from analyze_systematic_group_kernel import B, systematic_state_columns
from probe_bch_forward_xor_circuit import (
    baseline_xors,
    synthesize,
    transpose_terms,
    transpose_xor_count,
)


def target_outputs() -> list[int]:
    columns = systematic_state_columns()
    return [
        sum(((columns[input_bit] >> output_bit) & 1) << input_bit for input_bit in range(B))
        for output_bit in range(B)
    ]


def write_packet_transpose_header(path: Path, circuit, seed: int) -> None:
    """Emit x <- Acc^T(x + P^T state) directly over packet pointers."""
    terms = transpose_terms(circuit)

    def term_name(term: tuple[str, int]) -> str:
        kind, index = term
        if kind == "adjoint":
            return f"a{index}"
        return f"state[{index} / PacketWidth][{index} % PacketWidth]"

    def hot_state_term_name(term: tuple[str, int]) -> str:
        kind, index = term
        if kind == "adjoint":
            return f"a{index}"
        return f"state[{index}]"

    transpose_xors = transpose_xor_count(circuit)
    lines = [
        "#pragma once",
        "",
        "// Generated by scripts/probe_systematic_bch_circuit.py.",
        f"// Exact systematic packet step: {transpose_xors} P^T XORs,",
        "// 64 current merges, and 63 transposed-accumulator XORs.",
        f"// Paar seed: {seed}.",
        "",
        "#include <cryptoTools/Common/Defines.h>",
        "",
        "namespace osuCrypto::detail",
        "{",
        "#if defined(_MSC_VER)",
        "#define LIBOTE_RIFFLE_NOINLINE __declspec(noinline)",
        "#elif defined(__GNUC__) || defined(__clang__)",
        "#define LIBOTE_RIFFLE_NOINLINE __attribute__((noinline))",
        "#else",
        "#define LIBOTE_RIFFLE_NOINLINE",
        "#endif",
        "\ttemplate<u64 PacketWidth>",
        "\tLIBOTE_RIFFLE_NOINLINE inline void extendedBch128x64SystematicPacketTransposeStep(",
        "\t\tblock* const* __restrict current,",
        "\t\tconst block* const* __restrict state)",
        "\t{",
        "\t\tstatic_assert(PacketWidth != 0 && 64 % PacketWidth == 0);",
    ]
    for signal in range(len(terms) - 1, -1, -1):
        expression = " ^ ".join(term_name(term) for term in terms[signal])
        if signal < B:
            if not expression:
                raise ValueError("systematic state map has a zero transpose row")
            lines.append(
                f"\t\tcurrent[{signal} / PacketWidth][{signal} % PacketWidth] "
                f"^= {expression};"
            )
        else:
            if not expression:
                raise ValueError("transpose circuit contains an unused internal signal")
            lines.append(f"\t\tconst block a{signal} = {expression};")
    for signal in range(B - 2, -1, -1):
        lines.append(
            f"\t\tcurrent[{signal} / PacketWidth][{signal} % PacketWidth] ^= "
            f"current[{signal + 1} / PacketWidth][{signal + 1} % PacketWidth];"
        )
    lines.extend([
        "\t}",
        "",
        "\ttemplate<u64 PacketWidth>",
        "\tLIBOTE_RIFFLE_NOINLINE inline void extendedBch128x64SystematicPacketTransposeHotStateStep(",
        "\t\tblock* const* __restrict current,",
        "\t\tblock* __restrict state)",
        "\t{",
        "\t\tstatic_assert(PacketWidth != 0 && 64 % PacketWidth == 0);",
    ])
    for signal in range(len(terms) - 1, -1, -1):
        expression = " ^ ".join(
            hot_state_term_name(term) for term in terms[signal]
        )
        if signal < B:
            if not expression:
                raise ValueError("systematic state map has a zero transpose row")
            lines.append(
                f"\t\tcurrent[{signal} / PacketWidth][{signal} % PacketWidth] "
                f"^= {expression};"
            )
        else:
            if not expression:
                raise ValueError("transpose circuit contains an unused internal signal")
            lines.append(f"\t\tconst block a{signal} = {expression};")
    lines.append(
        f"\t\tstate[{B - 1}] = current[{B - 1} / PacketWidth]"
        f"[{B - 1} % PacketWidth];"
    )
    for signal in range(B - 2, -1, -1):
        lines.append(
            f"\t\tcurrent[{signal} / PacketWidth][{signal} % PacketWidth] ^= "
            f"current[{signal + 1} / PacketWidth][{signal + 1} % PacketWidth];"
        )
        lines.append(
            f"\t\tstate[{signal}] = "
            f"current[{signal} / PacketWidth][{signal} % PacketWidth];"
        )
    lines.extend(["\t}", "#undef LIBOTE_RIFFLE_NOINLINE", "}", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--seeds", type=int, default=64)
    parser.add_argument("--seed-start", type=int, default=0)
    parser.add_argument("--min-overlap", type=int, default=2)
    parser.add_argument("--output-packet-transpose-header", type=Path)
    args = parser.parse_args()
    if args.seeds < 1:
        raise SystemExit("systematic circuit: seeds must be positive")

    target = target_outputs()
    best = None
    for seed in range(args.seed_start, args.seed_start + args.seeds):
        circuit = synthesize(seed, args.min_overlap, target)
        score = (transpose_xor_count(circuit), circuit.xor_count, seed)
        if best is None or score < best[0]:
            best = (score, circuit)
    assert best is not None
    (transpose_xors, forward_xors, seed), circuit = best
    print("systematic-left EBCH state-map XOR circuit")
    print(f"baseline_forward_xors={baseline_xors(target)}")
    print(f"best_seed={seed}")
    print(f"forward_xors={forward_xors}")
    print(f"transpose_xors={transpose_xors}")
    print(f"current_merge_xors={B}")
    print(f"hot_step_total_xors={transpose_xors + B}")
    print(f"max_depth_upper={circuit.max_depth}")
    print("status=EXACT_VERIFIED")
    if args.output_packet_transpose_header:
        write_packet_transpose_header(
            args.output_packet_transpose_header, circuit, seed
        )
        print(f"output_packet_transpose_header={args.output_packet_transpose_header}")


if __name__ == "__main__":
    main()
