#!/usr/bin/env python3
"""Verify the finite-prefix certificate artifacts for the 0.106 checkpoint.

The summary files checked here are generated by:

    python scripts/certify_global_episode_cover.py \
      --k 1048576 --sigmas 25 --delta 0.106 --h-min 1 --h-max 2000 \
      --tail-mode be --exact-survivor-through 30 \
      --out-prefix scripts/global_episode_cover_suffix_be_exactsurv30_k1048576_sig25_d0106_h2000_mixed \
      --no-png

and the conditional geometric-tail summary by:

    python scripts/certify_geometric_tail_from_csv.py \
      --csv scripts/global_episode_cover_suffix_be_exactsurv30_k1048576_sig25_d0106_h2000_mixed.csv \
      --sigma 25 --check-from 500 --tail-after 2000 \
      --out scripts/global_episode_cover_suffix_be_exactsurv30_k1048576_sig25_d0106_h2000_tailcert.csv

This verifier intentionally consumes the small summary artifacts rather than
rerunning the h<=2000 evaluator.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


DEFAULT_STEM = "global_episode_cover_suffix_be_exactsurv30_k1048576_sig25_d0106_h2000"
DEFAULT_SUMMARY = Path(__file__).with_name(DEFAULT_STEM + "_mixed_summary.csv")
DEFAULT_TAILCERT = Path(__file__).with_name(DEFAULT_STEM + "_tailcert.csv")


def read_one(path: Path) -> dict[str, str]:
    with path.open(newline="") as f:
        rows = list(csv.DictReader(f))
    if len(rows) != 1:
        raise SystemExit(f"{path} must contain exactly one row, found {len(rows)}")
    return rows[0]


def check(name: str, passed: bool, detail: str) -> bool:
    print(f"{name}: {'PASS' if passed else 'FAIL'} ({detail})")
    return passed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--summary", type=Path, default=DEFAULT_SUMMARY)
    parser.add_argument("--tailcert", type=Path, default=DEFAULT_TAILCERT)
    parser.add_argument("--k", type=int, default=2**20)
    parser.add_argument("--n", type=int, default=2**21)
    parser.add_argument("--delta", type=float, default=0.106)
    parser.add_argument("--d", type=int, default=222298)
    parser.add_argument("--max-total-log2", type=float, default=-0.34)
    parser.add_argument("--max-tail-log2", type=float, default=-800.0)
    parser.add_argument("--max-ratio-log2", type=float, default=-0.35)
    args = parser.parse_args()

    summary = read_one(args.summary)
    tail = read_one(args.tailcert)

    total = float(summary["total_log2"])
    peak_h = int(summary["peak_h"])
    peak_term = float(summary["peak_term_log2"])
    tail_residual = float(tail["tail_residual_log2"])
    certified_total = float(tail["certified_total_log2_if_ratio_holds"])
    observed_ratio = float(tail["observed_worst_log2_ratio"])

    print("Dense+dense checkpoint finite-prefix verification")
    print(f"summary = {args.summary}")
    print(f"tailcert = {args.tailcert}")
    print(f"total_log2 = {total:.6f}")
    print(f"peak_h = {peak_h}")
    print(f"peak_term_log2 = {peak_term:.6f}")
    print(f"tail_residual_log2 = {tail_residual:.6f}")
    print(f"certified_total_log2_if_ratio_holds = {certified_total:.6f}")
    print(f"observed_worst_log2_ratio = {observed_ratio:.6f}")
    print()

    ok = True
    ok &= check("k", summary["k"] == str(args.k), summary["k"])
    ok &= check("N", summary["N"] == str(args.n), summary["N"])
    ok &= check("delta", abs(float(summary["delta"]) - args.delta) <= 1e-15, summary["delta"])
    ok &= check("d", summary["d"] == str(args.d), summary["d"])
    ok &= check("sigma", summary["sigma"] == "25", summary["sigma"])
    ok &= check("offset", summary["offset"] == "5", summary["offset"])
    ok &= check("h window", summary["h_min"] == "1" and summary["h_max"] == "2000", f"{summary['h_min']}..{summary['h_max']}")
    ok &= check("prefix total", total <= args.max_total_log2, f"{total:.6f} <= {args.max_total_log2:.6f}")
    ok &= check("peak location", peak_h == 2, f"h={peak_h}")
    ok &= check("tail ratio", observed_ratio <= args.max_ratio_log2, f"{observed_ratio:.6f} <= {args.max_ratio_log2:.6f}")
    ok &= check("tail residual", tail_residual <= args.max_tail_log2, f"{tail_residual:.6f} <= {args.max_tail_log2:.6f}")
    ok &= check(
        "certified total",
        certified_total <= args.max_total_log2,
        f"{certified_total:.6f} <= {args.max_total_log2:.6f}",
    )
    print(f"STATUS: {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
