/-
STATEMENT PIN.

This file exists to make *statement drift* a build failure.

Lean's kernel guarantees that no proof in this project is unsound.  It
guarantees nothing about whether the statements still say what the paper
says.  The characteristic failure of an unattended formalization is not a red
build: it is a hypothesis quietly added to a certificate field until the field
becomes provable, or a lemma weakened until it is vacuous.  The build stays
green and `#print axioms` stays clean the whole way down.

So the obligations are pinned here in both directions:

* `mkPinned` constructs a `ScalableCertificate` from exactly the pinned list
  of obligations.  Adding a field, or strengthening one, breaks it.
* `pinned_fields` projects each field back out at its pinned type.  Weakening
  a field breaks it.

Together these fix the certificate up to reordering.  The headline theorems
are pinned by restating them and closing them with the named result.

DO NOT edit this file to make the build pass.  Editing it is a statement
change and must be reviewed as one; it will appear in `git diff` as a change
to the pin rather than as a change to a proof.
-/
import SpinCodes.Framework
import SpinCodes.Selection
import SpinCodes.Distance
import SpinCodes.Structured.Regimes
import SpinCodes.Structured.Certificate
import SpinCodes.Structured.Instantiation
import SpinCodes.Structured.Majorant
import SpinCodes.Structured.Schedule
import SpinCodes.Structured.SparseCert
import SpinCodes.Structured.Accumulator
import SpinCodes.Structured.Interleaver
import SpinCodes.Structured.Composition
import SpinCodes.Structured.Enumerator
import SpinCodes.Structured.GolayEnum
import SpinCodes.Structured.BAGolay
import SpinCodes.Numeric.LogBounds
import SpinCodes.Numeric.BAConstants
import SpinCodes.Numeric.RatLog
import SpinCodes.Numeric.Fixed
import SpinCodes.Numeric.FixedLog
import SpinCodes.Numeric.BAExponent
import SpinCodes.Numeric.BAEval
import SpinCodes.Structured.RouteDomination
import SpinCodes.Structured.Domination
import SpinCodes.Structured.Krawtchouk
import SpinCodes.Structured.Parseval
import SpinCodes.Structured.FiberBounds
import SpinCodes.Structured.VarianceBound
import SpinCodes.Structured.Transvection
import SpinCodes.Structured.Transfer
import SpinCodes.Structured.Step
import SpinCodes.Structured.Induction
import SpinCodes.Structured.KLChain
import SpinCodes.Structured.Convexity
import SpinCodes.Structured.Collatz
import SpinCodes.Structured.EmptyEpoch
import SpinCodes.Structured.Coarse
import SpinCodes.Structured.Simplex
import SpinCodes.Structured.WeightedNorm
import SpinCodes.Structured.BetaSub
import SpinCodes.Structured.BATails
import SpinCodes.Structured.NegBinom
import SpinCodes.Structured.UpperTail
import SpinCodes.Wrapper

set_option linter.unusedSectionVars false

namespace Spin.Pin

open Finset Filter Spin Spin.Structured

attribute [local instance] Classical.propDecidable

/-! ## Framework (`thm:class-first-moment`) -/

example {M W Ωout Ωin : Type} [Fintype M] [DecidableEq M] [Zero M]
    [Fintype Ωout] [Fintype Ωin] (S : Setup M W Ωout Ωin) (d : ℕ) :
    S.joint.expect (fun ω => (S.Z d ω : ℝ))
      = S.Pout.expect (fun ω₁ => ∑ x ∈ nonzeroMsgs M, S.qd d (S.outer ω₁ x)) :=
  S.expect_Z_eq d

example {M W Ωout Ωin : Type} [Fintype M] [DecidableEq M] [Zero M]
    [Fintype Ωout] [Fintype Ωin] (S : Setup M W Ωout Ωin) (d : ℕ)
    {T : Type} [Fintype T] [DecidableEq T] (c : W → T) (Q : T → ℝ)
    (hQ : ∀ u : W, S.qd d u ≤ Q (c u)) :
    S.joint.prob (fun ω => 1 ≤ S.Z d ω) ≤ ∑ τ, S.Aout c τ * Q τ :=
  S.prob_bad_le_class_sum d c Q hQ

/-! ## Conditioning linkage -/

example {M W Ωout Ωin : Type} [Fintype M] [DecidableEq M] [Zero M]
    [Fintype Ωout] [Fintype Ωin] (S : Setup M W Ωout Ωin) (d : ℕ)
    (occ : Ωout → M → ℕ) (G : Ωout → Prop) [DecidablePred G]
    (hG : 0 < S.Pout.prob G) (Lmax : ℕ)
    (hocc : ∀ ω₁ x, x ∈ nonzeroMsgs M → occ ω₁ x ∈ Ico 1 (Lmax + 1)) :
    S.joint.prob (fun ω => 1 ≤ S.Z d ω)
      ≤ S.Pout.prob (fun ω₁ => ¬ G ω₁)
        + ∑ Q ∈ Ico 1 (Lmax + 1),
            ((S.Pout.condition G hG).prod S.Pin).expect
              (fun ω => (S.ZQ d occ Q ω : ℝ)) :=
  S.prob_bad_le_cond_sum d occ G hG Lmax hocc

/-! ## One-sample selection (`lem:structured-one-sample-selection`) -/

example {Ω : Type} [Fintype Ω] (P : FinPMF Ω) (A : Ω → ℕ → ℕ)
    (b : ℕ) (hb : 0 < b) (Wgood : Finset ℕ) (hsub : Wgood ⊆ range (b + 1)) :
    P.prob (fun ω => ¬ Good P A b Wgood ω)
      ≤ (∑ w ∈ badWeights b Wgood, Abar P A w) + (b + 1) / (b : ℝ) ^ 2 :=
  prob_not_good_le P A b hb Wgood hsub

/-! ## Certificate obligations, pinned in both directions -/

/-- Direction A: the certificate is constructible from exactly these
obligations.  A new field, or a strengthened one, breaks this. -/
def mkPinned
    (L b N : ℕ → ℕ)
    (N_eq : ∀ m, N m = L m * b m)
    (b_pos : ∀ m, 0 < b m)
    (b_tendsto : Tendsto b atTop atTop)
    (N_tendsto : Tendsto (fun m => (N m : ℝ)) atTop atTop)
    (L_le_N : ∀ m, (L m : ℝ) ≤ (N m : ℝ))
    (EZ : ℕ → ℕ → ℝ)
    (EZ_nonneg : ∀ m Q, 0 ≤ EZ m Q)
    (probNotGood : ℕ → ℝ)
    (probNotGood_tendsto : Tendsto probNotGood atTop (nhds 0))
    (fixed : ∀ Q ∈ Ico 1 4096, Tendsto (fun m => EZ m Q) atTop (nhds 0))
    (cut : ℕ → ℕ)
    (cut_spec : ∀ᶠ m in atTop, 4095 ≤ cut m ∧ cut m ≤ L m)
    (sparse : ∀ m, ∀ Q ∈ Ico 4096 (cut m + 1),
      EZ m Q ≤ Real.exp (-(0.006 : ℝ) * Q * b m))
    (eta : ℝ) (eta_pos : 0 < eta)
    (denseErr : ℕ → ℝ)
    (denseErr_tendsto : Tendsto denseErr atTop (nhds 0))
    (dense : ∀ m, ∑ Q ∈ Ico (cut m + 1) (L m + 1), EZ m Q
      ≤ (L m : ℝ) * Real.exp (-eta * N m + denseErr m * N m))
    (probBad : ℕ → ℝ)
    (probBad_nonneg : ∀ m, 0 ≤ probBad m)
    (probBad_le : ∀ m, probBad m ≤ probNotGood m + ∑ Q ∈ Ico 1 (L m + 1), EZ m Q) :
    ScalableCertificate :=
  { L, b, N, N_eq, b_pos, b_tendsto, N_tendsto, L_le_N, EZ, EZ_nonneg,
    probNotGood, probNotGood_tendsto, fixed, cut, cut_spec, sparse,
    eta, eta_pos, denseErr, denseErr_tendsto, dense,
    probBad, probBad_nonneg, probBad_le }

/-- Direction B: every field still carries at least its pinned strength.
Weakening a field breaks this. -/
theorem pinned_fields (C : ScalableCertificate) :
    (∀ m, C.N m = C.L m * C.b m)
    ∧ (∀ m, 0 < C.b m)
    ∧ Tendsto C.b atTop atTop
    ∧ Tendsto (fun m => (C.N m : ℝ)) atTop atTop
    ∧ (∀ m, (C.L m : ℝ) ≤ (C.N m : ℝ))
    ∧ (∀ m Q, 0 ≤ C.EZ m Q)
    ∧ Tendsto C.probNotGood atTop (nhds 0)
    ∧ (∀ Q ∈ Ico 1 4096, Tendsto (fun m => C.EZ m Q) atTop (nhds 0))
    ∧ (∀ᶠ m in atTop, 4095 ≤ C.cut m ∧ C.cut m ≤ C.L m)
    ∧ (∀ m, ∀ Q ∈ Ico 4096 (C.cut m + 1),
        C.EZ m Q ≤ Real.exp (-(0.006 : ℝ) * Q * C.b m))
    ∧ 0 < C.eta
    ∧ Tendsto C.denseErr atTop (nhds 0)
    ∧ (∀ m, ∑ Q ∈ Ico (C.cut m + 1) (C.L m + 1), C.EZ m Q
        ≤ (C.L m : ℝ) * Real.exp (-C.eta * C.N m + C.denseErr m * C.N m))
    ∧ (∀ m, 0 ≤ C.probBad m)
    ∧ (∀ m, C.probBad m ≤ C.probNotGood m + ∑ Q ∈ Ico 1 (C.L m + 1), C.EZ m Q) :=
  ⟨C.N_eq, C.b_pos, C.b_tendsto, C.N_tendsto, C.L_le_N, C.EZ_nonneg,
   C.probNotGood_tendsto, C.fixed, C.cut_spec, C.sparse, C.eta_pos,
   C.denseErr_tendsto, C.dense, C.probBad_nonneg, C.probBad_le⟩

/-! ## Concrete family — added by T1.

These are *additional* constraints.  Adding pin entries can only tighten the
guard; it never relaxes it.  The important one is the first: it fixes what
`probBad` means, so the quantity the theorem concludes about cannot later be
redefined into something trivially small. -/

/-- `probBad m` is exactly `Pr[∃ a nonzero message encoding to weight ≤ d_m]`. -/
example (F : Family) (m : ℕ) :
    F.probBad m
      = (letI := F.outFin m; letI := F.inrFin m
         (F.S m).joint.prob (fun ω => ∃ x : Fin (F.K m) → ZMod 2,
           x ≠ 0 ∧ (F.S m).innerWt ω.2 ((F.S m).outer ω.1 x) ≤ F.d m)) := by
  letI := F.outFin m
  letI := F.inrFin m
  exact FinPMF.prob_congr _ (fun ω => Spin.one_le_Z_iff (F.S m) (F.d m) ω)

/-- The linkage is proved for a concrete family, not assumed. -/
example (F : Family) (m : ℕ) :
    F.probBad m ≤ F.probNotGood m + ∑ Q ∈ Ico 1 (F.L m + 1), F.EZ m Q :=
  F.probBad_le m

/-- Non-injectivity or a light nonzero codeword both force the bad event. -/
example {M W : Type} [Fintype M] [DecidableEq M] [AddGroup M] [AddGroup W]
    (wt : W → ℕ) (E : M → W) (d : ℕ)
    (hsub : ∀ x y, E (x - y) = E x - E y) (hwt0 : wt 0 = 0)
    (h : ¬ Function.Injective E ∨ ∃ y ∈ Set.range E, y ≠ 0 ∧ wt y ≤ d) :
    ∃ x : M, x ≠ 0 ∧ wt (E x) ≤ d :=
  exists_nonzero_light wt E d hsub hwt0 h

/-! ## Outer majorant and Jensen — added by T2. -/

/-- `â_BA` is the lower envelope of finitely many rational affine supports,
and that representation alone makes it concave. -/
example (M : ConcaveMajorant) (s : Set ℝ) (hs : Convex ℝ s) :
    ConcaveOn ℝ s M.toFun :=
  M.concaveOn s hs

/-- `eq:structured-ba-jensen` on the certified window `𝒲 = [0.104, 0.896]`. -/
example (M : ConcaveMajorant) {ι : Type} (t : Finset ι) (ht : t.Nonempty)
    (x : ι → ℝ) (hx : ∀ i ∈ t, x i ∈ Set.Icc (0.104 : ℝ) 0.896) :
    (∑ i ∈ t, M.toFun (x i)) / t.card ≤ M.toFun ((∑ i ∈ t, x i) / t.card) :=
  M.jensen_on_window t ht x hx

/-! ## Native schedule — added by T2.

The existence claim matters: without it `eq:structured-native-schedule` could
define an empty family and the theorem would be vacuous. -/

/-- Some positive multiple of 24 satisfies `b ≥ (39/4) log₂(L_m b)`. -/
example (m : ℕ) : ∃ n : ℕ, SchedOK m (24 * (n + 1)) := exists_sched m

/-- The chosen `b_m` satisfies the constraint, is a positive multiple of 24,
and diverges. -/
example (m : ℕ) : SchedOK m (bsched m) ∧ 0 < bsched m ∧ 24 ∣ bsched m :=
  ⟨bsched_spec m, bsched_pos m, twentyfour_dvd_bsched m⟩

example : Tendsto bsched atTop atTop := bsched_tendsto

example (m : ℕ) : Nsched m = Lsched m * bsched m := Nsched_eq m

/-! ## Sparse Collatz certificate — added by T3.

These pin the *numerical* content: all seven degree-257 residual rows are
strictly negative on `[0,1]`, kernel-checked.  What they do not yet pin is the
bridge from `T_occ` to these polynomials, which needs the finite IMT transfer
construction (T9). -/

example : ∀ r ∈ sparseRows, tailBound r < 0 := sparseRows_cert

example {x : ℝ} (hx0 : 0 ≤ x) (hx1 : x ≤ 1) :
    ∀ r ∈ sparseRows, listEval r x < 0 := sparseRows_neg hx0 hx1

example : sparseRows.length = 7 := rfl

/-! ## Requested-length wrapper — added by T2a. -/

example {M : Type} {N n : ℕ} (h : N ≤ n) (E : M → (Fin N → ZMod 2)) :
    (Function.Injective (fun x => zeroExtend h (E x)) ↔ Function.Injective E)
      ∧ ∀ x, wt (zeroExtend h (E x)) = wt (E x) :=
  zeroExtend_preserves h E

/-! ## Schedule gap and wrapper rate — added by T2b. -/

/-- Consecutive direct lengths have relative gap `o(1)`. -/
example : Tendsto (fun m => (Nsched (m + 1) : ℝ) / (Nsched m : ℝ)) atTop (nhds 1) :=
  Nsched_ratio_tendsto_one

/-- `b` is monotone and each step costs at most one extra multiple of 24 —
the two facts the gap argument actually rests on. -/
example : Monotone bsched := bsched_mono

example (m : ℕ) : bsched (m + 1) ≤ bsched m + 24 := bsched_succ_le m

/-- `N_{m(n)}/n = 1 - o(1)`, for `m(n)` the largest index fitting in `n`. -/
example : Tendsto (fun n => (Nsched (mOf n) : ℝ) / (n : ℝ)) atTop (nhds 1) :=
  wrapper_rate

/-! ## Exact accumulator transition — added by T4.

`T_b(a,c)` really counts the words it is claimed to count.  This is the
accumulator half of `lem:structured-exact-ba-spectrum`; composing two of these
with the Golay enumerator is T4b. -/

example (b a c : ℕ) : accCount b a c = accT b a c := accCount_eq_accT b a c

/-- The recursion the proof rests on: appending a letter extends the
accumulation by the parity of the whole word. -/
example (b a c : ℕ) :
    accCount (b + 1) (a + 1) (c + (a + 1) % 2)
      = accCount b (a + 1) c + accCount b a c :=
  accCount_succ b a c

/-- A nonzero word has nonzero accumulated weight. -/
example (b : ℕ) {a : ℕ} (ha : a ≠ 0) : accCount b a 0 = 0 := accCount_zero_right b ha

/-! ## Uniform interleaver — added by T4b.

The paper asserts in one sentence that "the second permutation makes the word
uniform on its Hamming slice".  These pin the proved form of that step. -/

/-- Two tuples of equal weight are related by a permutation of positions:
the permutation action is transitive on each Hamming slice. -/
example {b : ℕ} {v v' : Fin b → Bool} (h : wtF v = wtF v') :
    ∃ ρ : Equiv.Perm (Fin b), v ∘ ρ = v' :=
  exists_perm_comp h

/-- The weight-`a` slice has `C(b,a)` elements — the denominator of
`P_b(a,c) = T_b(a,c)/C(b,a)`. -/
example (b a : ℕ) : sliceCount b a = b.choose a := sliceCount_eq_choose b a

/-- **`P_b(a,c)` is what the paper says it is.**  For a fixed word of weight
`a` and a uniformly random permutation of positions, the accumulated weight is
`c` with probability `T_b(a,c)/C(b,a)`; stated multiplicatively to stay in `ℕ`. -/
example {b a c : ℕ} (u : Fin b → Bool) (hu : wtF u = a) :
    (Finset.univ.filter (fun τ : Equiv.Perm (Fin b) => accWtF (u ∘ τ) = c)).card
        * b.choose a
      = accT b a c * Fintype.card (Equiv.Perm (Fin b)) :=
  card_perm_accWt_eq u hu

/-! ## Two-stage composition — added by T4c. -/

/-- `P_b(a,c)` as a probability. -/
example {b a c : ℕ} (u : Fin b → Bool) (hu : wtF u = a) :
    (FinPMF.uniform (Equiv.Perm (Fin b))).prob (fun τ => accWtF (u ∘ τ) = c)
      = Pt b a c :=
  prob_accWt u hu

/-- The transition probabilities out of a fixed weight sum to one. -/
example {b a : ℕ} (hab : a ≤ b) : ∑ c ∈ range (b + 1), Pt b a c = 1 := sum_Pt hab

/-- **The inner identity of `eq:structured-exact-ba-spectrum`**: two
interleaved accumulator stages compose by the Chapman-Kolmogorov sum. -/
example {b a w : ℕ} (u : Fin b → Bool) (hu : wtF u = a) :
    ((FinPMF.uniform (Equiv.Perm (Fin b))).prod
        (FinPMF.uniform (Equiv.Perm (Fin b)))).prob
        (fun τ => accWtF ((accF (u ∘ τ.1)) ∘ τ.2) = w)
      = ∑ c ∈ range (b + 1), Pt b a c * Pt b c w :=
  prob_two_stage u hu

/-! ## Direct-sum enumerator — added by T4d.

The general fact behind `G_b(a) := [u^a] G(u)^{b/24}`, with no Golay and no
coding theory in it. -/

example {σ : Type} [Fintype σ] [DecidableEq σ] (w : σ → ℕ) (k a : ℕ) :
    (Finset.univ.filter (fun f : Fin k → σ => ∑ i, w (f i) = a)).card
      = ((enumerator w) ^ k).coeff a :=
  card_tuples_weight w k a

/-! ## Golay weight enumerator — added by T4e.

The paper takes `G(u)` as known.  Here it is computed: all 4096 codewords are
evaluated by the Lean kernel. -/

/-- The weight distribution, as computed. -/
example : Golay.hist
    = [1, 0, 0, 0, 0, 0, 0, 0, 759, 0, 0, 0, 2576,
       0, 0, 0, 759, 0, 0, 0, 0, 0, 0, 0, 1] :=
  Golay.hist_eq

/-- **`G(u) = 1 + 759u⁸ + 2576u¹² + 759u¹⁶ + u²⁴`.** -/
example : enumerator Golay.W
    = 1 + Polynomial.C 759 * Polynomial.X ^ 8 + Polynomial.C 2576 * Polynomial.X ^ 12
      + Polynomial.C 759 * Polynomial.X ^ 16 + Polynomial.X ^ 24 :=
  Golay.enumerator_eq

/-- The code has minimum distance 8, so it really is `[24,12,8]`. -/
example (m : Fin 12 → Bool) (hm : Golay.W m ≠ 0) : 8 ≤ Golay.W m :=
  Golay.min_distance m hm

/-- The counting bridge that made the computation affordable: a count over
tuples equals a count over the list enumeration. -/
example {n : ℕ} (P : List Bool → Prop) [DecidablePred P] :
    (Finset.univ.filter (fun v : Fin n → Bool => P (List.ofFn v))).card
      = (allWords n).countP (fun l => decide (P l)) :=
  card_filter_ofFn_eq_countP P

/-! ## The exact BA spectrum — added by T4f.

`lem:structured-exact-ba-spectrum`, complete: every ingredient is proved, not
assumed. -/

/-- The general form, for any base map whose only weight-zero message is zero. -/
example {k n : ℕ} {σ : Type} [Fintype σ] [DecidableEq σ] [Zero σ]
    (blockEnc : σ → (Fin n → Bool))
    (hzero : ∀ s : σ, blockW blockEnc s = 0 ↔ s = 0) (Wt : ℕ) :
    (∑ x ∈ Finset.univ.filter (fun x : Fin k → σ => x ≠ 0),
        ((FinPMF.uniform (Equiv.Perm (Fin (k * n)))).prod
            (FinPMF.uniform (Equiv.Perm (Fin (k * n))))).prob
          (fun τ => accWtF ((accF (outerWord blockEnc x ∘ τ.1)) ∘ τ.2) = Wt))
      = ∑ a ∈ Finset.Icc 1 (k * n),
          (((enumerator (blockW blockEnc)) ^ k).coeff a : ℝ)
            * ∑ c ∈ range (k * n + 1), Pt (k * n) a c * Pt (k * n) c Wt :=
  expected_spectrum blockEnc hzero Wt

/-- Only the zero message has Golay weight zero — derived from the computed
distribution, not assumed. -/
example (m : Fin 12 → Bool) : Golay.W m = 0 ↔ m = 0 := Golay.W_eq_zero_iff m

/-! ## Rigorous log enclosure — added by T5.

The basis for every box-cover check to come (see `DECISIONS.md` D1). -/

example {q : ℝ} (hq0 : 0 < q) (hq2 : q < 2) (n : ℕ) :
    -Spin.Numeric.logSeries n (1 - q) - Spin.Numeric.logRem n (1 - q) ≤ Real.log q ∧
      Real.log q ≤ -Spin.Numeric.logSeries n (1 - q) + Spin.Numeric.logRem n (1 - q) :=
  Spin.Numeric.log_mem_Icc hq0 hq2 n

/-- Argument reduction to `|x| ≤ 1/3` makes the remainder shrink like `3^{-n}`. -/
example {x : ℝ} (hx : |x| ≤ 1 / 3) (n : ℕ) :
    Spin.Numeric.logRem n x ≤ (3 / 2) * (1 / 3) ^ (n + 1) :=
  Spin.Numeric.logRem_le hx n

/-! ## BA sparse tail, combinatorial core — added by T6. -/

/-- `Σ_{h ≤ D} T_b(2ℓ,h) ≤ C(b,ℓ)·C(D,ℓ)`. -/
example {b ℓ D : ℕ} (hℓ : 1 ≤ ℓ) :
    ∑ h ∈ range (D + 1), accT b (2 * ℓ) h ≤ b.choose ℓ * D.choose ℓ :=
  sum_accT_even_le hℓ

/-- `eq:structured-ba-one-acc-tail` up to the middle equality, division-free:
`p_{2ℓ} ≤ C(2ℓ,ℓ)·C(D,ℓ)/C(b-ℓ,ℓ)`. -/
example {b ℓ D : ℕ} (hℓ : 1 ≤ ℓ) :
    (∑ h ∈ range (D + 1), accT b (2 * ℓ) h) * (b - ℓ).choose ℓ
      ≤ (2 * ℓ).choose ℓ * D.choose ℓ * b.choose (2 * ℓ) :=
  sum_accT_even_mul_le hℓ

/-- **`eq:structured-ba-one-acc-tail`**: `p_{2ℓ} ≤ (13/28)^ℓ`, division-free.
`δ_o = 13/125`, `c_o = 4δ_o/(1-δ_o) = 13/28`. -/
example {b ℓ D : ℕ} (hℓ : 1 ≤ ℓ) (hℓD : ℓ ≤ D) (hDb : 125 * D ≤ 13 * b) :
    (∑ h ∈ range (D + 1), accT b (2 * ℓ) h) * 28 ^ ℓ ≤ 13 ^ ℓ * b.choose (2 * ℓ) :=
  sum_accT_even_le_pow hℓ hℓD hDb

/-- The binomial ratio bound behind it: `C(D,ℓ)/C(m,ℓ) ≤ (D/m)^ℓ` for `D ≤ m`. -/
example {D m : ℕ} (hDm : D ≤ m) (ℓ : ℕ) :
    D.choose ℓ * m ^ ℓ ≤ D ^ ℓ * m.choose ℓ :=
  choose_mul_pow_le hDm ℓ

/-- **The negative-binomial bound** behind `eq:structured-ba-sparse-moment`:
`Σ_{h ≥ ℓ} C(h-1,ℓ-1) z^h ≤ (z/(1-z))^ℓ`, for partial sums, so no convergence
argument is needed. -/
example {z : ℝ} (hz0 : 0 ≤ z) (hz1 : z < 1) {ℓ : ℕ} (hℓ : 1 ≤ ℓ) (H : ℕ) :
    ∑ j ∈ range H, (j.choose (ℓ - 1) : ℝ) * z ^ (j + 1) ≤ (z / (1 - z)) ^ ℓ :=
  moment_sum_le hz0 hz1 hℓ H

/-- `eq:structured-ba-one-acc-tail`, odd input weight: `p_{2ℓ+1} ≤ (13/28)^ℓ`. -/
example {b ℓ D : ℕ} (hℓ : 1 ≤ ℓ) (hℓD : ℓ ≤ D) (hDb : 125 * D ≤ 13 * b) :
    (∑ h ∈ range (D + 1), accT b (2 * ℓ + 1) h) * 28 ^ ℓ
      ≤ 13 ^ ℓ * b.choose (2 * ℓ + 1) :=
  sum_accT_odd_le_pow hℓ hℓD hDb

/-- The last step of `eq:structured-ba-sparse-moment`, with the common
`(ζ/(1-ζ))^ℓ` cancelled: `C(b,ℓ)·(b-2ℓ+1)^ℓ ≤ 4^ℓ·ℓ^ℓ·C(b,2ℓ)`. -/
example {b ℓ : ℕ} (hℓ : 1 ≤ ℓ) (hb : 2 * ℓ ≤ b) :
    b.choose ℓ * (b + 1 - 2 * ℓ) ^ ℓ ≤ 4 ^ ℓ * ℓ ^ ℓ * b.choose (2 * ℓ) :=
  choose_ratio_le hℓ hb

/-- The split-and-bound structure of `eq:structured-ba-sparse-sum`. -/
example {r q : ℝ} (hr0 : 0 ≤ r) (hr1 : r < 1) (hq0 : 0 ≤ q) (hq1 : q < 1)
    (f : ℕ → ℝ) (J M : ℕ) (hJ1 : 1 ≤ J) (hJM : J ≤ M + 1)
    (hlow : ∀ j ∈ Ico 1 J, f j ≤ r ^ j)
    (hhigh : ∀ j ∈ Ico J (M + 1), f j ≤ q ^ j) :
    ∑ j ∈ Ico 1 (M + 1), f j ≤ r / (1 - r) + q ^ J / (1 - q) :=
  sum_split_geom hr0 hr1 hq0 hq1 f J M hJ1 hJM hlow hhigh

/-- A geometric factor with a `√x` exponent beats every polynomial — why the
high half of the split is still `O(b^{-3/2})`. -/
example {q : ℝ} (hq0 : 0 < q) (hq1 : q < 1) (k : ℕ) :
    Tendsto (fun x : ℝ => x ^ k * q ^ Real.sqrt x) atTop (nhds 0) :=
  pow_mul_rpow_sqrt_tendsto hq0 hq1 k

/-- **`Acc(V + e₁) = ¬Acc(V)`** — the identity that turns the accumulator's
upper tail into a lower tail, so `eq:structured-ba-one-acc-tail` can be reused
for the sparse upper tail. -/
example (v : List Bool) : accWtL (flipHead v) = v.length - accWtL v :=
  accWtL_flipHead v

example (v : List Bool) (D : ℕ) (hD : D ≤ v.length) :
    v.length - D ≤ accWtL v ↔ accWtL (flipHead v) ≤ D :=
  accWtL_ge_iff v D hD

/-! ## BA sparse-tail constants — added by T6h. -/

/-- `ζ = √(13/28)` enclosed to seven places. -/
example : (6813851 : ℝ) / 10000000 < Spin.Numeric.zeta
    ∧ Spin.Numeric.zeta < (6813852 : ℝ) / 10000000 :=
  ⟨Spin.Numeric.zeta_lower, Spin.Numeric.zeta_upper⟩

/-- `8.5543 < κ < 8.5544`. -/
example : (85543 : ℝ) / 10000 < Spin.Numeric.kappa
    ∧ Spin.Numeric.kappa < (85544 : ℝ) / 10000 :=
  ⟨Spin.Numeric.kappa_lower, Spin.Numeric.kappa_upper⟩

/-- **`C_* η³ < 0.657`** — the paper's constant, verified. -/
example : Spin.Numeric.Cstar * Spin.Numeric.eta ^ 3 < 657 / 1000 :=
  Spin.Numeric.Cstar_eta_cubed_lt

/-- **The upper-tail counting step**: upper-tail words of weight `v` inject,
via `V ↦ V + e₁`, into the lower-tail words of weights `v-1` and `v+1`. -/
example {b D v : ℕ} (hv : 1 ≤ v) (hD : D ≤ b + 1) :
    (Finset.univ.filter (fun w : Fin (b + 1) → Bool =>
        wtF w = v ∧ (b + 1) - D ≤ accWtF w)).card
      ≤ (Finset.univ.filter (fun w : Fin (b + 1) → Bool =>
            wtF w = v - 1 ∧ accWtF w ≤ D)).card
        + (Finset.univ.filter (fun w : Fin (b + 1) → Bool =>
            wtF w = v + 1 ∧ accWtF w ≤ D)).card :=
  card_upper_tail_le hv hD

/-- **The monotonicity check** of `eq:structured-ba-sparse-moment`:
`ln(κx/(1-2x)) + 1 + 2x/(1-2x) < -1.22` at `x = 12η`. -/
example :
    Real.log Spin.Numeric.logArg + 1 + 2 * (3 / 250) / (1 - 2 * ((3 : ℝ) / 250))
      < -((122 : ℝ) / 100) :=
  Spin.Numeric.logDeriv_lt

/-- **`b · S_b → 0`** — the asymptotic conclusion of
`eq:structured-ba-sparse-sum`, from the split-and-bound shape. -/
example {C q : ℝ} (hq0 : 0 < q) (hq1 : q < 1) (S : ℕ → ℝ) (hSnn : ∀ b, 0 ≤ S b)
    (hbound : ∀ᶠ b : ℕ in atTop,
      S b ≤ 2 * (C / ((b : ℝ) * Real.sqrt (b : ℝ))) + q ^ Real.sqrt (b : ℝ) / (1 - q)) :
    Tendsto (fun b : ℕ => (b : ℝ) * S b) atTop (nhds 0) :=
  sparse_sum_mul_tendsto hq0 hq1 S hSnn hbound

/-- The upper tail against the two neighbouring lower-tail sums — the form
`eq:structured-ba-one-acc-tail` bounds. -/
example {b D v : ℕ} (hv : 1 ≤ v) (hD : D ≤ b + 1) :
    (Finset.univ.filter (fun w : Fin (b + 1) → Bool =>
        wtF w = v ∧ (b + 1) - D ≤ accWtF w)).card
      ≤ (∑ h ∈ range (D + 1), accT (b + 1) (v - 1) h)
        + (∑ h ∈ range (D + 1), accT (b + 1) (v + 1) h) :=
  upper_tail_le_sums hv hD

/-- The paper's two coefficients, both instances of `Nat.choose_succ_right_eq`. -/
example {b v : ℕ} (hv : 1 ≤ v) : b.choose v * v = b.choose (v - 1) * (b - (v - 1)) :=
  choose_pred_ratio hv

example (b v : ℕ) : b.choose (v + 1) * (v + 1) = b.choose v * (b - v) :=
  choose_succ_ratio b v

/-- **The upper tail at odd weight**, numerically: the paper's
`b(ζ⁻²+1)ζ^v` with `ζ² = 13/28`, the `41 = 28 + 13` collecting the two
neighbouring contributions. -/
example {b D m : ℕ} (hm : 1 ≤ m) (hmD : m + 1 ≤ D)
    (hDb : 125 * D ≤ 13 * (b + 1)) (hDle : D ≤ b + 1) :
    (Finset.univ.filter (fun w : Fin (b + 1) → Bool =>
        wtF w = 2 * m + 1 ∧ (b + 1) - D ≤ accWtF w)).card * 28 ^ (m + 1)
      ≤ 41 * 13 ^ m * ((b + 1) * (b + 1).choose (2 * m + 1)) :=
  upper_tail_odd_bound hm hmD hDb hDle

/-- The upper tail at even weight, completing `lem:structured-ba-tails`'s
sparse half: with the odd case, every input weight is covered. -/
example {b D k : ℕ} (hkD : k + 1 ≤ D)
    (hDb : 125 * D ≤ 13 * (b + 1)) (hDle : D ≤ b + 1) :
    (Finset.univ.filter (fun w : Fin (b + 1) → Bool =>
        wtF w = 2 * (k + 1) ∧ (b + 1) - D ≤ accWtF w)).card * 28 ^ (k + 1)
      ≤ 41 * 13 ^ k * ((b + 1) * (b + 1).choose (2 * (k + 1))) :=
  upper_tail_even_bound hkD hDb hDle

/-- The odd tail bound including `ℓ = 0`. -/
example {b ℓ D : ℕ} (hℓD : ℓ ≤ D) (hDb : 125 * D ≤ 13 * b) :
    (∑ h ∈ range (D + 1), accT b (2 * ℓ + 1) h) * 28 ^ ℓ
      ≤ 13 ^ ℓ * b.choose (2 * ℓ + 1) :=
  sum_accT_odd_le_pow' hℓD hDb

/-- Computable rational log enclosures, sound against `Real.log`.  Note these
are *evaluable by `norm_num`*, not by `decide` — see `DECISIONS.md` D2. -/
example {q : ℚ} (hq : 0 < q) {k n : ℕ} (hlt : q * 2 ^ k < 2) :
    Real.log (q : ℝ) ≤ ((Spin.Numeric.logUpper q k n : ℚ) : ℝ) :=
  Spin.Numeric.real_log_le_logUpper hq hlt

example {q : ℚ} (hq : 0 < q) {k n : ℕ} (hlt : q * 2 ^ k < 2) :
    ((Spin.Numeric.logLower q k n : ℚ) : ℝ) ≤ Real.log (q : ℝ) :=
  Spin.Numeric.logLower_le_real_log hq hlt


/-! ## Fixed-point enclosures

These pin the *meaning* of `Fix.Mem`, not just its existence.  If `Mem` were
weakened — to `True`, say — every soundness lemma below would still typecheck
and every box cover built on them would become vacuous while the build stayed
green.  The `Iff.rfl` pin is the guard against exactly that. -/

/-- `Fix.Mem` says what it is supposed to say. -/
example (a : Spin.Numeric.Fix) (x : ℝ) :
    Spin.Numeric.Fix.Mem a x ↔
      ((a.lo : ℝ) / ((Spin.Numeric.scale : Int) : ℝ) ≤ x ∧
        x ≤ (a.hi : ℝ) / ((Spin.Numeric.scale : Int) : ℝ)) :=
  Iff.rfl

/-- The denominator is positive, so `Mem` is not degenerate. -/
example : (0 : Int) < Spin.Numeric.scale := Spin.Numeric.scale_pos

/-- A fraction is enclosed by its own enclosure. -/
example {p q : Int} (hq : 0 < q) :
    Spin.Numeric.Fix.Mem (Spin.Numeric.Fix.ofFrac p q) ((p : ℝ) / (q : ℝ)) :=
  Spin.Numeric.Fix.ofFrac_mem hq

example (n : Int) : Spin.Numeric.Fix.Mem (Spin.Numeric.Fix.ofInt n) (n : ℝ) :=
  Spin.Numeric.Fix.ofInt_mem n

/-- Each operation returns a genuine enclosure of the corresponding real
operation, with no side condition beyond positivity of an explicit divisor. -/
example {a b : Spin.Numeric.Fix} {x y : ℝ}
    (hx : Spin.Numeric.Fix.Mem a x) (hy : Spin.Numeric.Fix.Mem b y) :
    Spin.Numeric.Fix.Mem (Spin.Numeric.Fix.add a b) (x + y) :=
  Spin.Numeric.Fix.add_mem hx hy

example {a b : Spin.Numeric.Fix} {x y : ℝ}
    (hx : Spin.Numeric.Fix.Mem a x) (hy : Spin.Numeric.Fix.Mem b y) :
    Spin.Numeric.Fix.Mem (Spin.Numeric.Fix.sub a b) (x - y) :=
  Spin.Numeric.Fix.sub_mem hx hy

example {a : Spin.Numeric.Fix} {x : ℝ} (hx : Spin.Numeric.Fix.Mem a x) :
    Spin.Numeric.Fix.Mem (Spin.Numeric.Fix.neg a) (-x) :=
  Spin.Numeric.Fix.neg_mem hx

example {a b : Spin.Numeric.Fix} {x y : ℝ}
    (hx : Spin.Numeric.Fix.Mem a x) (hy : Spin.Numeric.Fix.Mem b y) :
    Spin.Numeric.Fix.Mem (Spin.Numeric.Fix.mul a b) (x * y) :=
  Spin.Numeric.Fix.mul_mem hx hy

example {a : Spin.Numeric.Fix} {x : ℝ} {k : Int}
    (hx : Spin.Numeric.Fix.Mem a x) (hk : 0 < k) :
    Spin.Numeric.Fix.Mem (Spin.Numeric.Fix.divInt a k) (x / (k : ℝ)) :=
  Spin.Numeric.Fix.divInt_mem hx hk

example {a : Spin.Numeric.Fix} {x : ℝ} (hx : Spin.Numeric.Fix.Mem a x) (n : Nat) :
    Spin.Numeric.Fix.Mem (Spin.Numeric.Fix.pow a n) (x ^ n) :=
  Spin.Numeric.Fix.pow_mem hx n

/-- Reading a verdict off an enclosure.  This is the step a box cover ends
with, so it is the one that must not be weakened. -/
example {a : Spin.Numeric.Fix} {x : ℝ} (hx : Spin.Numeric.Fix.Mem a x)
    (h : Spin.Numeric.Fix.isNeg a = true) : x < 0 :=
  Spin.Numeric.Fix.neg_of_isNeg hx h

example {a : Spin.Numeric.Fix} {x : ℝ} (hx : Spin.Numeric.Fix.Mem a x)
    (h : Spin.Numeric.Fix.isNonneg a = true) : 0 ≤ x :=
  Spin.Numeric.Fix.nonneg_of_isNonneg hx h

/-! ### The fixed-point logarithm

`flog_mem` is the load-bearing statement for T7b and T7c: every box in those
covers reaches `Real.log` through it.  Pinned with its window hypotheses
intact, so neither adding a hypothesis nor weakening the conclusion can pass
unnoticed. -/

example {y : Spin.Numeric.Fix} {t : ℝ} (hy : Spin.Numeric.Fix.Mem y t) (n : Nat) :
    Spin.Numeric.Fix.Mem (Spin.Numeric.Fix.series n y) (Spin.Numeric.logSeries n t) :=
  Spin.Numeric.Fix.series_mem hy n

example : Spin.Numeric.Fix.Mem Spin.Numeric.Fix.log2 (Real.log 2) :=
  Spin.Numeric.Fix.log2_mem

example {p q : Int} {k n : Nat} (hp : 0 < p) (hq : 0 < q)
    (hlo : 3 * q ≤ 4 * (p * Spin.Numeric.Fix.ipow2 k))
    (hhi : 2 * (p * Spin.Numeric.Fix.ipow2 k) ≤ 3 * q) :
    Spin.Numeric.Fix.Mem (Spin.Numeric.Fix.flog p q k n)
      (Real.log ((p : ℝ) / (q : ℝ))) :=
  Spin.Numeric.Fix.flog_mem hp hq hlo hhi

/-! ### The odd (atanh) series

`2·∑ z^(2k+1)/(2k+1)` with `z = (P-Q)/(P+Q)`.  The window hypotheses on
`flogA_mem` are exactly what forces `|z| ≤ 1/5`, so they are pinned with it. -/

example {z : Spin.Numeric.Fix} {t : ℝ} (hz : Spin.Numeric.Fix.Mem z t) (m : Nat) :
    Spin.Numeric.Fix.Mem (Spin.Numeric.Fix.oddSeries m z)
      (Spin.Numeric.Fix.oddSeriesR m t) :=
  Spin.Numeric.Fix.oddSeries_mem hz m

/-- The even terms cancel: this is what makes the odd series the same series. -/
example (z : ℝ) (m : Nat) :
    2 * Spin.Numeric.Fix.oddSeriesR m z
      = Spin.Numeric.logSeries (2 * m) z - Spin.Numeric.logSeries (2 * m) (-z) :=
  Spin.Numeric.Fix.two_oddSeriesR z m

example {z : ℝ} (hz : |z| < 1) (m : Nat) :
    |Real.log ((1 + z) / (1 - z)) - 2 * Spin.Numeric.Fix.oddSeriesR m z|
      ≤ 2 * Spin.Numeric.logRem (2 * m) z :=
  Spin.Numeric.Fix.log_ratio_bound hz m

example {P Q : Int} {m : Nat} (hP : 0 < P) (hQ : 0 < Q)
    (h1 : 2 * Q ≤ 3 * P) (h2 : 2 * P ≤ 3 * Q) :
    Spin.Numeric.Fix.Mem (Spin.Numeric.Fix.flogA P Q m)
      (Real.log ((P : ℝ) / (Q : ℝ))) :=
  Spin.Numeric.Fix.flogA_mem hP hQ h1 h2

/-! ### Reciprocal, division, and the logarithm of an enclosure

The three primitives the box covers need beyond the ring operations.  `div` is
sound only for a divisor whose lower end is strictly positive, and `flogI` only
for an argument that stays positive and whose endpoints both land in the
reduction window; those side conditions are part of what is pinned. -/

example {a : Spin.Numeric.Fix} {y : ℝ} (hy : Spin.Numeric.Fix.Mem a y) (ha : 0 < a.lo) :
    Spin.Numeric.Fix.Mem (Spin.Numeric.Fix.inv a) (1 / y) :=
  Spin.Numeric.Fix.inv_mem hy ha

example {a b : Spin.Numeric.Fix} {x y : ℝ}
    (hx : Spin.Numeric.Fix.Mem a x) (hy : Spin.Numeric.Fix.Mem b y) (hb : 0 < b.lo) :
    Spin.Numeric.Fix.Mem (Spin.Numeric.Fix.div a b) (x / y) :=
  Spin.Numeric.Fix.div_mem hx hy hb

example {a : Spin.Numeric.Fix} {x : ℝ} {klo khi n : Nat}
    (hx : Spin.Numeric.Fix.Mem a x) (ha : 0 < a.lo)
    (hlo1 : 3 * Spin.Numeric.scale ≤ 4 * (a.lo * Spin.Numeric.Fix.ipow2 klo))
    (hlo2 : 2 * (a.lo * Spin.Numeric.Fix.ipow2 klo) ≤ 3 * Spin.Numeric.scale)
    (hhi1 : 3 * Spin.Numeric.scale ≤ 4 * (a.hi * Spin.Numeric.Fix.ipow2 khi))
    (hhi2 : 2 * (a.hi * Spin.Numeric.Fix.ipow2 khi) ≤ 3 * Spin.Numeric.scale) :
    Spin.Numeric.Fix.Mem (Spin.Numeric.Fix.flogI a klo khi n) (Real.log x) :=
  Spin.Numeric.Fix.flogI_mem hx ha hlo1 hlo2 hhi1 hhi2

/-! ### The BA outer exponent

The definitions are pinned by `rfl` against the paper's formulas, because a
drifted definition here would make every box in the cover check the wrong
thing while the build stayed green. -/

example (x : ℝ) :
    Spin.Numeric.hEnt x = -x * Real.log x - (1 - x) * Real.log (1 - x) := rfl

example (a c : ℝ) :
    Spin.Numeric.piBA a c
      = c * Spin.Numeric.hEnt (a / (2 * c))
        + (1 - c) * Spin.Numeric.hEnt (a / (2 * (1 - c)))
        - Spin.Numeric.hEnt a := rfl

example (u a : ℝ) :
    Spin.Numeric.gObj u a = Real.log (Spin.Numeric.GolayG u) / 24 - a * Real.log u := rfl

example (a : ℝ) :
    Spin.Numeric.gBA a = sInf ((fun u => Spin.Numeric.gObj u a) '' Set.Ioi 0) := rfl

/-- The paper's `π` and the interval verifier's division-free `p` agree. -/
example {a c : ℝ} (ha : 0 ≤ a) (ha1 : a < 1) (hlo : a / 2 < c) (hhi : c < 1 - a / 2) :
    Spin.Numeric.piBA a c
      = a * Real.log 2 + c * Real.log c + (1 - c) * Real.log (1 - c)
        - (c - a / 2) * Real.log (c - a / 2)
        - (1 - c - a / 2) * Real.log (1 - c - a / 2)
        + (1 - a) * Real.log (1 - a) :=
  Spin.Numeric.piBA_eq_piEval ha ha1 hlo hhi

/-! The partial derivatives of `π`, for the centered bound.  Pinned as
`HasDerivAt` statements, not as definitions: a wrong formula here would make
the mean-value bound unsound rather than merely loose. -/

example (a c : ℝ) :
    Spin.Numeric.Dpa a c
      = Real.log 2 + (Real.log (c - a / 2) + Real.log (1 - c - a / 2)) / 2
        - Real.log (1 - a) := rfl

example (a c : ℝ) :
    Spin.Numeric.Dpc a c
      = Real.log c - Real.log (1 - c) - Real.log (c - a / 2)
        + Real.log (1 - c - a / 2) := rfl

example {a c : ℝ} (h1 : 0 < c - a / 2) (h2 : 0 < 1 - c - a / 2) (h3 : a < 1) :
    HasDerivAt (fun t => Spin.Numeric.piEval t c) (Spin.Numeric.Dpa a c) a :=
  Spin.Numeric.hasDerivAt_piEval_fst h1 h2 h3

example {a c : ℝ} (h1 : 0 < c - a / 2) (h2 : 0 < 1 - c - a / 2)
    (h4 : 0 < c) (h5 : c < 1) :
    HasDerivAt (fun t => Spin.Numeric.piEval a t) (Spin.Numeric.Dpc a c) c :=
  Spin.Numeric.hasDerivAt_piEval_snd h1 h2 h4 h5

/-- A single witness `u` bounds the infimum — this is what lets one `r` per box
discharge `g`. -/
example {a u : ℝ} (ha0 : 0 ≤ a) (ha1 : a ≤ 1) (hu : 0 < u) :
    Spin.Numeric.gBA a ≤ Spin.Numeric.gObj u a :=
  Spin.Numeric.gBA_le ha0 ha1 hu

/-- The Golay generating function is the code's own, not a retyped constant. -/
example (u : ℝ) :
    Spin.Numeric.GolayG u = ∑ m : Fin 12 → Bool, u ^ (Spin.Structured.Golay.W m) :=
  Spin.Numeric.GolayG_eq_sum u

/-! ### The log oracle and the lookup table

`Oracle` is pinned by `rfl`, for the same reason `Fix.Mem` is: weaken it and
every evaluator soundness lemma below still typechecks while saying nothing.

The table's soundness deliberately does **not** mention any search-tree
ordering invariant.  `find` answers only at a node whose key it compared
equal, so a mis-ordered tree can make a lookup fail but cannot make it lie. -/

open Spin.Numeric.Fix in
example (lg : LogFn) :
    Oracle lg ↔ ∀ p v, lg p = some v →
      0 < p ∧ Mem v (Real.log ((p : ℝ) / ((Spin.Numeric.scale : Int) : ℝ))) :=
  Iff.rfl

open Spin.Numeric.Fix in
example (n : Nat) : Oracle (directLog n) := directLog_oracle n

open Spin.Numeric.Fix in
example {t : LogTree} {n : Nat} {k : Int} {v : Spin.Numeric.Fix}
    (hc : t.check n = true) (hf : t.find k = some v) :
    flogQ k Spin.Numeric.scale n = some v :=
  find_check hc hf

open Spin.Numeric.Fix in
example {t : LogTree} {n : Nat} (hc : t.check n = true) : Oracle (treeLog t) :=
  treeLog_oracle hc

/-! The evaluators over an arbitrary oracle.  The direct-instance versions
pinned below are these at `directLog n`. -/

open Spin.Numeric.Fix in
example {lg : LogFn} (hlg : Oracle lg) {a : Spin.Numeric.Fix} {x : ℝ}
    {v : Spin.Numeric.Fix} (hx : Mem a x) (h : flogIWL lg a = some v) :
    Mem v (Real.log x) :=
  flogIWL_mem hlg hx h

open Spin.Numeric.Fix in
example {lg : LogFn} (hlg : Oracle lg) {a : Spin.Numeric.Fix} {x : ℝ}
    {v : Spin.Numeric.Fix} (hx : Mem a x) (h : fxlogxL lg a = some v) :
    Mem v (Spin.Numeric.xlogx x) :=
  fxlogxL_mem hlg hx h

open Spin.Numeric.Fix in
example {lg : LogFn} (hlg : Oracle lg) {a c : Spin.Numeric.Fix} {al ga : ℝ}
    {v : Spin.Numeric.Fix} (ha : Mem a al) (hc : Mem c ga)
    (h : fpiEvalL lg a c = some v) : Mem v (Spin.Numeric.piEval al ga) :=
  fpiEvalL_mem hlg ha hc h

open Spin.Numeric.Fix in
example {lg : LogFn} (hlg : Oracle lg) {u a : Spin.Numeric.Fix} {w al : ℝ}
    {v : Spin.Numeric.Fix} (hu : Mem u w) (ha : Mem a al)
    (h : fgObjL lg u a = some v) : Mem v (Spin.Numeric.gObj w al) :=
  fgObjL_mem hlg hu ha h

/-! ### The centered bound

The mean-value expansion of `π` on a box, and its fixed-point evaluator.  This
is the bound the cover cannot do without, so both the real-side identity and
the feasibility guard are pinned. -/

example {alo ahi clo chi : ℝ}
    (h1 : 0 < clo - ahi / 2) (h2 : 0 < 1 - chi - ahi / 2) (h3 : ahi < 1)
    (h4 : 0 < clo) (h5 : chi < 1)
    {a c am cm : ℝ} (ha : a ∈ Set.Icc alo ahi) (hc : c ∈ Set.Icc clo chi)
    (ham : am ∈ Set.Icc alo ahi) (hcm : cm ∈ Set.Icc clo chi) :
    ∃ ξ ∈ Set.Icc alo ahi, ∃ η ∈ Set.Icc clo chi,
      Spin.Numeric.piEval a c
        = Spin.Numeric.piEval am cm
          + Spin.Numeric.Dpa ξ c * (a - am)
          + Spin.Numeric.Dpc am η * (c - cm) :=
  Spin.Numeric.piEval_centered h1 h2 h3 h4 h5 ha hc ham hcm

open Spin.Numeric.Fix in
example {lg : LogFn} (hlg : Oracle lg) {A C : Spin.Numeric.Fix} {x y : ℝ}
    {v : Spin.Numeric.Fix} (hx : Mem A x) (hy : Mem C y)
    (h : fDpaL lg A C = some v) : Mem v (Spin.Numeric.Dpa x y) :=
  fDpaL_mem hlg hx hy h

open Spin.Numeric.Fix in
example {lg : LogFn} (hlg : Oracle lg) {A C : Spin.Numeric.Fix} {x y : ℝ}
    {v : Spin.Numeric.Fix} (hx : Mem A x) (hy : Mem C y)
    (h : fDpcL lg A C = some v) : Mem v (Spin.Numeric.Dpc x y) :=
  fDpcL_mem hlg hx hy h

open Spin.Numeric.Fix in
example {lg : LogFn} (hlg : Oracle lg) {A C : Spin.Numeric.Fix} {a c : ℝ}
    {v : Spin.Numeric.Fix} (ha : Mem A a) (hc : Mem C c)
    (f1 : 0 < 2 * C.lo - A.hi) (f2 : 0 < 2 * Spin.Numeric.scale - 2 * C.hi - A.hi)
    (f3 : A.hi < Spin.Numeric.scale) (f4 : 0 < C.lo) (f5 : C.hi < Spin.Numeric.scale)
    (h : fpiCenteredL lg A C = some v) : Mem v (Spin.Numeric.piEval a c) :=
  fpiCenteredL_mem hlg ha hc f1 f2 f3 f4 f5 h

/-! ### The split tree

`checkTree_sound` is the covering argument, and it is deliberately parametric
in both the leaf test and the property proved: nothing about `π` or `g`
enters.  What it says is that if the walk succeeds then every point of the
original box lies in some leaf's box — which is the obligation a flat list of
leaves would have left open. -/

open Spin.Numeric.Fix in
example {a b : Spin.Numeric.Fix} {x : ℝ} (ha : Mem a x) (hb : Mem b x) :
    Mem (meet a b) x :=
  meet_mem ha hb

open Spin.Numeric.Fix in
example {lg : LogFn} (hlg : Oracle lg) {A C : Spin.Numeric.Fix} {a c : ℝ}
    {v : Spin.Numeric.Fix} (ha : Mem A a) (hc : Mem C c)
    (h : fpiCenteredG lg A C = some v) : Mem v (Spin.Numeric.piEval a c) :=
  fpiCenteredG_mem hlg ha hc h

open Spin.Numeric.Fix in
example {lg : LogFn} (hlg : Oracle lg) {A C : Spin.Numeric.Fix} {a c : ℝ}
    {v : Spin.Numeric.Fix} (ha : Mem A a) (hc : Mem C c)
    (h : fpiBestL lg A C = some v) : Mem v (Spin.Numeric.piEval a c) :=
  fpiBestL_mem hlg ha hc h

open Spin.Numeric.Fix in
example {leafOK : Int → Spin.Numeric.Fix → Spin.Numeric.Fix → Spin.Numeric.Fix → Bool}
    {P : ℝ → ℝ → ℝ → Prop}
    (hleaf : ∀ u A B W a b w, leafOK u A B W = true →
      Mem A a → Mem B b → Mem W w → P a b w)
    (t : BoxTree) (A B W : Spin.Numeric.Fix) (a b w : ℝ)
    (h : checkTree leafOK t A B W = true)
    (ha : Mem A a) (hb : Mem B b) (hw : Mem W w) : P a b w :=
  checkTree_sound hleaf t A B W a b w h ha hb hw

/-! ### The fixed-point BA evaluators

Each says: *if the evaluator answered at all, its answer encloses the real
quantity.*  No hypothesis about the shift search appears, because the search's
success is carried by the `Option` and checked by the definition. -/

open Spin.Numeric.Fix in
example {p q : Int} {n : Nat} {v : Spin.Numeric.Fix} (h : flogQ p q n = some v) :
    Mem v (Real.log ((p : ℝ) / (q : ℝ))) :=
  flogQ_mem h

open Spin.Numeric.Fix in
example {a : Spin.Numeric.Fix} {x : ℝ} {n : Nat} {v : Spin.Numeric.Fix}
    (hx : Mem a x) (h : flogIW a n = some v) : Mem v (Real.log x) :=
  flogIW_mem hx h

/-! `x log x` as a primitive, so the feasibility boundary `c = a/2` is an
ordinary point rather than a `log 0`. -/

open Spin.Numeric.Fix in
example {a : Spin.Numeric.Fix} {x : ℝ} {n : Nat} {v : Spin.Numeric.Fix}
    (hx : Mem a x) (h : fxlogx a n = some v) : Mem v (Spin.Numeric.xlogx x) :=
  fxlogx_mem hx h

/-- The tangent bound the lower end rests on. -/
example {x m : ℝ} (hx : 0 ≤ x) (hm : 0 < m) :
    x * Real.log m + x - m ≤ Spin.Numeric.xlogx x :=
  Spin.Numeric.xlogx_tangent hx hm

/-- The maximum principle the upper end rests on. -/
example {lo hi x : ℝ} (hlo : 0 ≤ lo) (hx : x ∈ Set.Icc lo hi) :
    Spin.Numeric.xlogx x ≤ max (Spin.Numeric.xlogx lo) (Spin.Numeric.xlogx hi) :=
  Spin.Numeric.xlogx_le_max hlo hx

open Spin.Numeric.Fix in
example {x : Spin.Numeric.Fix} {t : ℝ} {n : Nat} {v : Spin.Numeric.Fix}
    (hx : Mem x t) (h : fhEnt x n = some v) : Mem v (Spin.Numeric.hEnt t) :=
  fhEnt_mem hx h

open Spin.Numeric.Fix in
example {a c : Spin.Numeric.Fix} {α γ : ℝ} {n : Nat} {v : Spin.Numeric.Fix}
    (ha : Mem a α) (hc : Mem c γ) (h : fpiEval a c n = some v) :
    Mem v (Spin.Numeric.piEval α γ) :=
  fpiEval_mem ha hc h

open Spin.Numeric.Fix in
example {u : Spin.Numeric.Fix} {w : ℝ} (hu : Mem u w) :
    Mem (fGolayG u) (Spin.Numeric.GolayG w) :=
  fGolayG_mem hu

open Spin.Numeric.Fix in
example {u a : Spin.Numeric.Fix} {w α : ℝ} {n : Nat} {v : Spin.Numeric.Fix}
    (hu : Mem u w) (ha : Mem a α) (h : fgObj u a n = some v) :
    Mem v (Spin.Numeric.gObj w α) :=
  fgObj_mem hu ha h

/-! ### The dense-tail claim

`DenseClaim` is pinned by `rfl`.  It is the statement the whole cover exists
to prove, and it is an implication — weaken either side and the 13,513 leaves
would certify nothing while still checking out. -/

open Spin.Numeric.Fix in
example (thr : Int) (a b w : ℝ) :
    DenseClaim thr a b w ↔
      ((a / 2 < b ∧ b < 1 - a / 2 ∧ b / 2 < w ∧ w < 1 - b / 2 ∧ 0 ≤ a ∧ a < 1) →
        Spin.Numeric.gBA a + Spin.Numeric.piBA a b + Spin.Numeric.piBA b w
          < (thr : ℝ) / ((Spin.Numeric.scale : Int) : ℝ)) :=
  Iff.rfl

open Spin.Numeric.Fix in
example {lg : LogFn} (hlg : Oracle lg) {thr u : Int}
    {A B W : Spin.Numeric.Fix} {a b w : ℝ}
    (ha : Mem A a) (hb : Mem B b) (hw : Mem W w)
    (h : leafOK lg thr u A B W = true) : DenseClaim thr a b w :=
  leafOK_sound hlg ha hb hw h

/-! The bridge: a tree that checks out proves the claim at every point of the
root box. -/

open Spin.Numeric.Fix in
example {lg : LogFn} (hlg : Oracle lg) {thr : Int} (t : BoxTree)
    {A B W : Spin.Numeric.Fix} (h : checkTree (leafOK lg thr) t A B W = true)
    {a b w : ℝ} (ha : Mem A a) (hb : Mem B b) (hw : Mem W w) :
    DenseClaim thr a b w :=
  denseTail_of_checkTree hlg t h ha hb hw

/-! ### Route domination

Two of the three ingredients of `lem:structured-route-domination` reduce to
`le_mode`: a mass function on `n` points puts at least `1/n` on its largest
atom.  The conditioning cost is that bound applied to `Bin(b, x)`; the
method-of-types bound is it applied to `Bin(L, k/L)`. -/

example {Ω : Type} [Fintype Ω] (P : Spin.FinPMF Ω) {m : Ω}
    (hm : ∀ ω, P.p ω ≤ P.p m) : 1 / (Fintype.card Ω : ℝ) ≤ P.p m :=
  Spin.le_mode P hm

example {Ω : Type} [Fintype Ω] (P : Spin.FinPMF Ω) {m : Ω}
    (hm : ∀ ω, P.p ω ≤ P.p m) (hpos : 0 < P.p m) :
    1 / P.p m ≤ (Fintype.card Ω : ℝ) :=
  Spin.inv_mode_le P hm hpos

/-- The binomial mass function says what it should. -/
example (L : ℕ) (u : ℝ) (hu0 : 0 ≤ u) (hu1 : u ≤ 1) (j : Fin (L + 1)) :
    (Spin.binPMF L u hu0 hu1).p j
      = (L.choose (j : ℕ) : ℝ) * u ^ (j : ℕ) * (1 - u) ^ (L - (j : ℕ)) := rfl

example {L : ℕ} {u : ℝ} (hu0 : 0 ≤ u) (hu1 : u ≤ 1) {k : Fin (L + 1)}
    (hmode : ∀ j : Fin (L + 1),
      (Spin.binPMF L u hu0 hu1).p j ≤ (Spin.binPMF L u hu0 hu1).p k) :
    1 / ((L : ℝ) + 1)
      ≤ (L.choose (k : ℕ) : ℝ) * u ^ (k : ℕ) * (1 - u) ^ (L - (k : ℕ)) :=
  Spin.types_lower_bound hu0 hu1 hmode

/-- **The method-of-types lower bound**, hypothesis discharged: at `u = k/L`
the binomial mass at `k` is at least `1/(L+1)`. -/
example {L k : ℕ} (hL : 0 < L) (hk : k ≤ L)
    (h0 : (0 : ℝ) ≤ (k : ℝ) / (L : ℝ)) (h1 : (k : ℝ) / (L : ℝ) ≤ 1) :
    1 / ((L : ℝ) + 1)
      ≤ (L.choose k : ℝ) * ((k : ℝ) / (L : ℝ)) ^ k
        * (1 - (k : ℝ) / (L : ℝ)) ^ (L - k) :=
  Spin.types_lower_bound_at hL hk h0 h1

/-- The integer form the mode argument actually rests on. -/
example {L k j : ℕ} (hk : k ≤ L) (hj : j ≤ L) :
    L.choose j * (k ^ j * (L - k) ^ (L - j))
      ≤ L.choose k * (k ^ k * (L - k) ^ (L - k)) :=
  Spin.binPMF_mode_nat hk hj

/-- **Poisson-binomial MGF domination.**  Replacing the success probabilities
by their average can only increase the moment generating function; at
`c = e^t - 1` this is what reduces the Poisson-binomial Chernoff bound to the
binomial one.  Not in Mathlib. -/
example {L : ℕ} (hL : 0 < L) (p : Fin L → ℝ) (c : ℝ)
    (hp0 : ∀ i, 0 ≤ p i) (hp1 : ∀ i, p i ≤ 1) (hc : -1 ≤ c) :
    ∏ i, (1 + p i * c) ≤ (1 + ((∑ i, p i) / (L : ℝ)) * c) ^ L :=
  Spin.prod_one_add_mul_le hL p c hp0 hp1 hc

/-- **The Poisson-binomial law itself**, pinned by `rfl`.  Indexed by the
success set: `P(T) = ∏_{i∈T} pᵢ · ∏_{i∉T} (1-pᵢ)`.  Pinned as a definition
because a weakened law would leave every theorem below true and vacuous. -/
example {L : ℕ} (p : Fin L → ℝ) (hp0 : ∀ i, 0 ≤ p i) (hp1 : ∀ i, p i ≤ 1)
    (T : Finset (Fin L)) :
    (Spin.poissonBinom p hp0 hp1).p T
      = (∏ i ∈ T, p i) * ∏ i ∈ Finset.univ \ T, (1 - p i) := rfl

/-- The generating identity the Chernoff argument runs on. -/
example {L : ℕ} (p : Fin L → ℝ) (hp0 : ∀ i, 0 ≤ p i) (hp1 : ∀ i, p i ≤ 1)
    (z : ℝ) :
    ∑ T : Finset (Fin L), (Spin.poissonBinom p hp0 hp1).p T * z ^ T.card
      = ∏ i, (1 - p i + p i * z) :=
  Spin.poissonBinom_mgf p hp0 hp1 z

/-- **The Chernoff bound for a Poisson binomial.**  The right-hand side is
`exp(-L · D(k/L ‖ q))` written without an exponential, which is the form that
cancels exactly against the method-of-types bound. -/
example {L k : ℕ} (hL : 0 < L) (hk0 : 0 < k) (hkL : k < L)
    (p : Fin L → ℝ) (hp0 : ∀ i, 0 ≤ p i) (hp1 : ∀ i, p i ≤ 1)
    {q : ℝ} (hqval : (∑ i, p i) / (L : ℝ) = q) (hq0 : 0 < q) (hq1 : q < 1) :
    (Spin.poissonBinom p hp0 hp1).prob (fun T => T.card = k)
      ≤ q ^ k * (1 - q) ^ (L - k) * (L : ℝ) ^ L
          / ((k : ℝ) ^ k * ((L : ℝ) - k) ^ (L - k)) :=
  Spin.poissonBinom_prob_le hL hk0 hkL p hp0 hp1 hqval hq0 hq1

/-- **`lem:structured-route-domination`, pointwise form.**  The routed law puts
at most `L+1` times as much mass on any single value as the iid Bernoulli law
of the same mean.  The constant is not padding: the true ratio exceeds `1`. -/
example {L k : ℕ} (hL : 0 < L) (hk0 : 0 < k) (hkL : k < L)
    (p : Fin L → ℝ) (hp0 : ∀ i, 0 ≤ p i) (hp1 : ∀ i, p i ≤ 1)
    {q : ℝ} (hqval : (∑ i, p i) / (L : ℝ) = q) (hq0 : 0 < q) (hq1 : q < 1) :
    (Spin.poissonBinom p hp0 hp1).prob (fun T => T.card = k)
      ≤ ((L : ℝ) + 1) * ((L.choose k : ℝ) * q ^ k * (1 - q) ^ (L - k)) :=
  Spin.poissonBinom_le_binom hL hk0 hkL p hp0 hp1 hqval hq0 hq1

/-! ### Assembling route domination

`Dominates` is pinned as a *definition*: weakened to `True` every theorem
below would still typecheck and mean nothing. -/

example {Ω : Type} [Fintype Ω] (P Q : Spin.FinPMF Ω) (c : ℝ) :
    Spin.Dominates P Q c ↔ ∀ ω, P.p ω ≤ c * Q.p ω := Iff.rfl

example {ι : Type} [Fintype ι] [DecidableEq ι] {α : ι → Type}
    [∀ i, Fintype (α i)] (P : ∀ i, Spin.FinPMF (α i)) (f : ∀ i, α i) :
    (Spin.piPMF P).p f = ∏ i, (P i).p (f i) := rfl

/-- The paper's conclusion shape: nonnegative `F`, expectations transfer. -/
example {Ω : Type} [Fintype Ω] {P Q : Spin.FinPMF Ω} {c : ℝ}
    (h : Spin.Dominates P Q c) {F : Ω → ℝ} (hF : ∀ ω, 0 ≤ F ω) :
    P.expect F ≤ c * Q.expect F := h.expect_le hF

/-- **The shuffle step.**  Fibre-uniformity turns a fibre-mass bound into a
pointwise one. -/
example {Ω κ : Type} [Fintype Ω] [DecidableEq κ]
    (P Q : Spin.FinPMF Ω) (S : Ω → κ) (c : ℝ)
    (hP : ∀ ω ω', S ω = S ω' → P.p ω = P.p ω')
    (hQ : ∀ ω ω', S ω = S ω' → Q.p ω = Q.p ω')
    (hmass : ∀ k, P.prob (fun ω => S ω = k) ≤ c * Q.prob (fun ω => S ω = k)) :
    Spin.Dominates P Q c :=
  Spin.dominates_of_fiber_uniform P Q S c hP hQ hmass

/-- Costs multiply over independent coordinates. -/
example {ι : Type} [Fintype ι] [DecidableEq ι] {α : ι → Type}
    [∀ i, Fintype (α i)] (P Q : ∀ i, Spin.FinPMF (α i)) (c : ι → ℝ)
    (h : ∀ i, Spin.Dominates (P i) (Q i) (c i)) :
    Spin.Dominates (Spin.piPMF P) (Spin.piPMF Q) (∏ i, c i) :=
  Spin.dominates_piPMF P Q c h

/-- Conditioning on an event of probability at least `1/(b+1)` costs `b+1`. -/
example {Ω : Type} [Fintype Ω] (P : Spin.FinPMF Ω) (s : Ω → Prop)
    [DecidablePred s] {b : ℕ} (hb : 1 / ((b : ℝ) + 1) ≤ P.prob s)
    (h : 0 < P.prob s) :
    Spin.Dominates (P.condition s h) P ((b : ℝ) + 1) :=
  Spin.dominates_condition_le P s hb h

/-- The dominating law really is the binomial — the interface is not vacuous. -/
example {L : ℕ} (k : ℕ) {q : ℝ} (hq0 : ∀ _ : Fin L, (0 : ℝ) ≤ q)
    (hq1 : ∀ _ : Fin L, q ≤ 1) :
    (Spin.poissonBinom (fun _ => q) hq0 hq1).prob (fun T => T.card = k)
      = (L.choose k : ℝ) * q ^ k * (1 - q) ^ (L - k) :=
  Spin.poissonBinom_const_prob k hq0 hq1

/-- **One region shuffle costs `L+1`**, at every weight including the two
endpoints. -/
example {L : ℕ} (hL : 0 < L) (R : Spin.FinPMF (Finset (Fin L)))
    (p : Fin L → ℝ) (hp0 : ∀ i, 0 ≤ p i) (hp1 : ∀ i, p i ≤ 1)
    {q : ℝ} (hqval : (∑ i, p i) / (L : ℝ) = q) (hq0 : 0 < q) (hq1 : q < 1)
    (hRuniform : ∀ T T' : Finset (Fin L), T.card = T'.card → R.p T = R.p T')
    (hRmass : ∀ k, R.prob (fun T => T.card = k)
      = (Spin.poissonBinom p hp0 hp1).prob (fun T => T.card = k)) :
    Spin.Dominates R
      (Spin.poissonBinom (fun _ => q) (fun _ => hq0.le) (fun _ => hq1.le))
      ((L : ℝ) + 1) :=
  Spin.dominates_region hL R p hp0 hp1 hqval hq0 hq1 hRuniform hRmass

/-- **`eq:structured-route-domination`.** -/
example {Ω : Type} [Fintype Ω] {Route Mid Ber : Spin.FinPMF Ω} {b L Q : ℕ}
    (hrow : Spin.Dominates Route Mid (((b : ℝ) + 1) ^ Q))
    (hregion : Spin.Dominates Mid Ber (((L : ℝ) + 1) ^ b))
    {F : Ω → ℝ} (hF : ∀ ω, 0 ≤ F ω) :
    Route.expect F ≤ ((b : ℝ) + 1) ^ Q * ((L : ℝ) + 1) ^ b * Ber.expect F :=
  Spin.route_domination hrow hregion hF

/-- **The factor is `exp(o(N))`.** -/
example {ε : ℝ} (hε : 0 < ε) :
    ∃ M : ℕ, 0 < M ∧ ∀ L b Q : ℕ, M ≤ L → M ≤ b → Q ≤ L →
      Real.log (((b : ℝ) + 1) ^ Q * ((L : ℝ) + 1) ^ b) ≤ ε * ((L : ℝ) * b) :=
  Spin.route_factor_isLittleO hε

/-! ### Krawtchouk polynomials

The integer fibre bounds of `app:imt-finite-transfers` rest on the character
sum over a weight layer depending on `v` only through `|v|`.  The polynomial
is pinned as a definition; the identity is pinned as a theorem. -/

example (n j w : ℕ) :
    Spin.krawtchouk n j w
      = ∑ h ∈ Finset.range (j + 1),
          (-1 : ℤ) ^ h * (w.choose h : ℤ) * ((n - w).choose (j - h) : ℤ) := rfl

/-- **The weight-layer character sum is a Krawtchouk value.** -/
example {n : ℕ} (v : Finset (Fin n)) (j : ℕ) :
    ∑ x ∈ (Finset.univ : Finset (Fin n)).powersetCard j, (-1 : ℤ) ^ (x ∩ v).card
      = Spin.krawtchouk n j v.card :=
  Spin.krawtchouk_char_sum v j

/-- The layer split that proves it: inside `v` and outside are independent. -/
example {n : ℕ} (v : Finset (Fin n)) {j h : ℕ} (hh : h ≤ j) :
    ((((Finset.univ : Finset (Fin n)).powersetCard j)).filter
        (fun x => (x ∩ v).card = h)).card
      = v.card.choose h * (n - v.card).choose (j - h) :=
  Spin.card_meet_fiber v hh

/-! ### Fourier inversion and Parseval

Both identities of `app:imt-finite-transfers` hold for any subgroup `D` of
`(Finset (Fin n), ∆)` — no matrix, no syndrome space.  `V_j` appears in its
coset form: two weight-`j` words share a syndrome exactly when their symmetric
difference is orthogonal to the whole dual code. -/

example {n : ℕ} (u x : Finset (Fin n)) : Spin.chi u x = (-1 : ℤ) ^ (u ∩ x).card := rfl

example {n : ℕ} (D : Finset (Finset (Fin n))) (x : Finset (Fin n)) :
    Spin.OrthTo D x ↔ ∀ v ∈ D, Even (v ∩ x).card := Iff.rfl

/-- **Orthogonality**: a character of `(D, ∆)` is trivial or sums to zero. -/
example {n : ℕ} (D : Finset (Finset (Fin n)))
    (hD : ∀ u ∈ D, ∀ v ∈ D, symmDiff u v ∈ D) (x : Finset (Fin n)) :
    ∑ v ∈ D, Spin.chi v x = if Spin.OrthTo D x then (D.card : ℤ) else 0 :=
  Spin.sum_chi D hD x

/-- **Fourier inversion**: `|D| · k_j = ∑_{v ∈ D} K_j(|v|)`. -/
example {n : ℕ} (D : Finset (Finset (Fin n)))
    (hD : ∀ u ∈ D, ∀ v ∈ D, symmDiff u v ∈ D) (j : ℕ) :
    (D.card : ℤ)
        * (((Spin.layer n j).filter (fun x => Spin.OrthTo D x)).card : ℤ)
      = ∑ v ∈ D, Spin.krawtchouk n j v.card :=
  Spin.card_orth_layer D hD j

/-- **Parseval**: `|D| · V_j = ∑_{v ∈ D} K_j(|v|)²`. -/
example {n : ℕ} (D : Finset (Finset (Fin n)))
    (hD : ∀ u ∈ D, ∀ v ∈ D, symmDiff u v ∈ D) (j : ℕ) :
    (D.card : ℤ)
        * ((((Spin.layer n j) ×ˢ (Spin.layer n j)).filter
            (fun p => Spin.OrthTo D (symmDiff p.1 p.2))).card : ℤ)
      = ∑ v ∈ D, (Spin.krawtchouk n j v.card) ^ 2 :=
  Spin.card_orth_pairs D hD j

/-! ### Integer fibre bounds

Three of the four bounds `app:imt-finite-transfers` minimises over.  All are
stated for a fibre defined without a syndrome map. -/

example {n : ℕ} (D : Finset (Finset (Fin n))) (j : ℕ) (x : Finset (Fin n)) :
    Spin.fiber D j x
      = (Spin.layer n j).filter (fun y => Spin.OrthTo D (symmDiff x y)) := rfl

/-- **Fourier inversion at an arbitrary syndrome.** -/
example {n : ℕ} (D : Finset (Finset (Fin n)))
    (hD : ∀ u ∈ D, ∀ v ∈ D, symmDiff u v ∈ D) (j : ℕ) (x : Finset (Fin n)) :
    (D.card : ℤ) * ((Spin.fiber D j x).card : ℤ)
      = ∑ v ∈ D, Spin.chi v x * Spin.krawtchouk n j v.card :=
  Spin.card_fiber D hD j x

/-- **Bound 1**, `f_j ≤ a_j`, stated additively. -/
example {n : ℕ} (D : Finset (Finset (Fin n))) (j : ℕ) {x : Finset (Fin n)}
    (hx : ¬ Spin.OrthTo D x) :
    (Spin.fiber D j x).card
        + ((Spin.layer n j).filter (fun y => Spin.OrthTo D y)).card
      ≤ n.choose j :=
  Spin.card_fiber_add_card_kernel_le D j hx

/-- **Bound 2**, the triangle inequality on Fourier inversion. -/
example {n : ℕ} (D : Finset (Finset (Fin n)))
    (hD : ∀ u ∈ D, ∀ v ∈ D, symmDiff u v ∈ D) (j : ℕ) (x : Finset (Fin n)) :
    (D.card : ℤ) * ((Spin.fiber D j x).card : ℤ)
      ≤ ∑ v ∈ D, |Spin.krawtchouk n j v.card| :=
  Spin.card_fiber_le_abs_sum D hD j x

/-- **Bound 3**, constant-weight packing from the kernel distance. -/
example {n : ℕ} (D : Finset (Finset (Fin n))) (j : ℕ) {r d : ℕ} (hr : 2 * r < d)
    (hdist : ∀ u : Finset (Fin n), Spin.OrthTo D u → u ≠ ∅ → d ≤ u.card)
    (x : Finset (Fin n)) :
    (Spin.fiber D j x).card * j.choose (j - r) ≤ n.choose (j - r) :=
  Spin.card_fiber_mul_choose_le D j hr hdist x

/-- The complemented form, stronger when `j > n/2`. -/
example {n : ℕ} (D : Finset (Finset (Fin n))) (j : ℕ) {r d : ℕ} (hr : 2 * r < d)
    (hdist : ∀ u : Finset (Fin n), Spin.OrthTo D u → u ≠ ∅ → d ≤ u.card)
    (x : Finset (Fin n)) :
    (Spin.fiber D j x).card * (n - j).choose ((n - j) - r)
      ≤ n.choose ((n - j) - r) :=
  Spin.card_fiber_mul_choose_le_compl D j hr hdist x

/-! ### The variance bound

The fourth fibre bound.  Stated as the quadratic that Cauchy-Schwarz gives,
which is the appendix formula before it is solved for `t` and rounded
outward -- so no square root and no rounding appear. -/

example {n : ℕ} (D : Finset (Finset (Fin n))) (j : ℕ) :
    Spin.fibers D j
      = (Spin.nonKernelLayer D j).image (fun y => Spin.fiber D j y) := rfl

example {n : ℕ} (D : Finset (Finset (Fin n))) (j : ℕ) :
    Spin.nonKernelLayer D j
      = (Spin.layer n j).filter (fun y => ¬ Spin.OrthTo D y) := rfl

/-- **Cauchy-Schwarz on all but one term**, in `ℕ` with no subtraction. -/
example {ι : Type} [DecidableEq ι] (F : Finset ι) (g : ι → ℕ) {i₀ : ι}
    (hi₀ : i₀ ∈ F) {m a S : ℕ} (hm : F.card ≤ m + 1)
    (ha : ∑ i ∈ F, g i = a) (hS : ∑ i ∈ F, (g i) ^ 2 = S) :
    (m + 1) * (g i₀) ^ 2 + a ^ 2 ≤ 2 * a * g i₀ + m * S :=
  Spin.sq_max_le F g hi₀ hm ha hS

/-- The fibres partition the non-kernel layer: `∑ |Φ| = a_j`. -/
example {n : ℕ} (D : Finset (Finset (Fin n))) (j : ℕ) :
    ∑ Φ ∈ Spin.fibers D j, Φ.card = (Spin.nonKernelLayer D j).card :=
  Spin.sum_card_fibers D j

/-- `V_j = k_j² + ∑ |Φ|²`, the additive form of `V_j - k_j²`. -/
example {n : ℕ} (D : Finset (Finset (Fin n))) (j : ℕ) :
    (((Spin.layer n j) ×ˢ (Spin.layer n j)).filter
        (fun p => Spin.OrthTo D (symmDiff p.1 p.2))).card
      = (Spin.kernelLayer D j).card ^ 2 + ∑ Φ ∈ Spin.fibers D j, Φ.card ^ 2 :=
  Spin.card_orth_pairs_split D j

/-- **Bound 4**, the variance bound. -/
example {n : ℕ} (D : Finset (Finset (Fin n))) (j : ℕ) {x : Finset (Fin n)}
    (hxl : x ∈ Spin.layer n j) (hx : ¬ Spin.OrthTo D x) {m : ℕ}
    (hm : (Spin.fibers D j).card ≤ m + 1) :
    (m + 1) * (Spin.fiber D j x).card ^ 2 + (Spin.nonKernelLayer D j).card ^ 2
      ≤ 2 * (Spin.nonKernelLayer D j).card * (Spin.fiber D j x).card
        + m * ∑ Φ ∈ Spin.fibers D j, Φ.card ^ 2 :=
  Spin.variance_bound D j hxl hx hm

/-! ### The IMT transvection law

`L(M q) = ½ δ_q + ½ Unif(𝔽₂^s \ {0})` for `q ≠ 0`, as three exact counts over
the sample space.  Every entry of the transfer matrices rests on this. -/

example {s : ℕ} (u v q : Finset (Fin s)) :
    Spin.act u v q = if Even (q ∩ v).card then q else symmDiff q u := rfl

example {s : ℕ} (u : Finset (Fin s)) :
    Spin.perp u = Finset.univ.filter (fun v => Even (u ∩ v).card) := rfl

/-- `|u^⊥| = 2^(s-1)`, with no edge case in `s`. -/
example {s : ℕ} {u : Finset (Fin s)} (hu : u ≠ ∅) :
    2 * (Spin.perp u).card = 2 ^ s :=
  Spin.card_perp_double hu

/-- **Zero is unreachable** from a nonzero state. -/
example {s : ℕ} {q : Finset (Fin s)} (hq : q ≠ ∅) :
    ((Spin.transPairs s).filter (fun p => Spin.act p.1 p.2 q = ∅)).card = 0 :=
  Spin.count_target_zero hq

/-- **Each other nonzero target** gets half of one `u^⊥` — the `1/(2M)`. -/
example {s : ℕ} {q q' : Finset (Fin s)} (hq : q ≠ ∅) (hq' : q' ≠ ∅) (hne : q' ≠ q) :
    2 * ((Spin.transPairs s).filter (fun p => Spin.act p.1 p.2 q = q')).card
      = (Spin.perp (symmDiff q q')).card :=
  Spin.count_target_other hq hq' hne

/-- **The lazy branch**: `q` keeps all of `perp q` plus half of every other. -/
example {s : ℕ} {q : Finset (Fin s)} (hq : q ≠ ∅) :
    2 * ((Spin.transPairs s).filter (fun p => Spin.act p.1 p.2 q = q)).card
      = 2 * (Spin.perp q).card
        + ∑ u ∈ (Spin.nonzeroStates s).erase q, (Spin.perp u).card :=
  Spin.count_target_self hq

/-- The fair-bit step the law turns on. -/
example {s : ℕ} {u q : Finset (Fin s)} (hq : q ≠ ∅) (hne : q ≠ u) :
    2 * ((Spin.perp u).filter (fun v => ¬ Even (q ∩ v).card)).card
      = (Spin.perp u).card :=
  Spin.card_perp_fair hq hne

/-! ### The transvection law as an expectation

The form every row of `T_j(z)` consumes.  It is an exact identity for every
`g`, with no sign condition: the `½` and the `1/(2M)` are literally the two
halves of `½ δ_q + ½ Unif`. -/

example {s : ℕ} {q : Finset (Fin s)} (hq : q ≠ ∅) :
    (Spin.transPairs s).card
      = (Spin.nonzeroStates s).card * (Spin.perp q).card :=
  Spin.card_transPairs hq

/-- Integer form, no division. -/
example {s : ℕ} {q : Finset (Fin s)} (hq : q ≠ ∅) (g : Finset (Fin s) → ℝ) :
    2 * ∑ p ∈ Spin.transPairs s, g (Spin.act p.1 p.2 q)
      = ((Spin.perp q).card : ℝ)
        * (((Spin.nonzeroStates s).card : ℝ) * g q
            + ∑ w ∈ Spin.nonzeroStates s, g w) :=
  Spin.sum_act_eq hq g

/-- **`E[g(M q)] = ½ g(q) + (1/(2M)) ∑_{w ≠ 0} g(w)`.** -/
example {s : ℕ} {q : Finset (Fin s)} (hq : q ≠ ∅) (g : Finset (Fin s) → ℝ) :
    (∑ p ∈ Spin.transPairs s, g (Spin.act p.1 p.2 q))
        / ((Spin.transPairs s).card : ℝ)
      = g q / 2
        + (∑ w ∈ Spin.nonzeroStates s, g w)
            / (2 * ((Spin.nonzeroStates s).card : ℝ)) :=
  Spin.expect_act hq g

/-! ### The weighted-state abstraction

The seven coordinates of `app:imt-finite-transfers`, with the shells kept
abstract.  `D` is a *total* budget spread arbitrarily, so domination is an
existential over that spread; the rest is pointwise. -/

example {s : ℕ} {q : Finset (Fin s)} (hq : q ≠ ∅) (w : Finset (Fin s)) :
    ((((Spin.transPairs s).filter (fun p => Spin.act p.1 p.2 q = w)).card : ℝ))
        / ((Spin.transPairs s).card : ℝ)
      = (if w = q then 1 / 2 else 0)
        + (if w = ∅ then 0 else 1 / (2 * ((Spin.nonzeroStates s).card : ℝ))) :=
  Spin.prob_act hq w

example {k : ℕ} (c : Spin.Imt.Coords k) :
    c.total = c.Z + c.D + ∑ i, c.S i := rfl

/-- Domination, pinned as a definition. -/
example {s k : ℕ} (sys : Spin.Imt.ShellSystem s k) (c : Spin.Imt.Coords k)
    (μ : Finset (Fin s) → ℝ) :
    Spin.Imt.Dominates sys c μ
      ↔ ∃ ν : Finset (Fin s) → ℝ,
          (∀ q, 0 ≤ ν q) ∧ (∑ q, ν q ≤ c.D) ∧
          ∀ q, μ q ≤ (if q = ∅ then c.Z else 0) + ν q
              + ∑ i, (if q ∈ sys.shell i then c.S i / ((sys.shell i).card : ℝ) else 0) :=
  Iff.rfl

/-- **Terminal mass is bounded by the sum of coordinates.** -/
example {s k : ℕ} {sys : Spin.Imt.ShellSystem s k} {c : Spin.Imt.Coords k}
    {μ : Finset (Fin s) → ℝ} (h : Spin.Imt.Dominates sys c μ) :
    ∑ q, μ q ≤ c.total :=
  h.total_le

/-- Domination is monotone in the coordinates. -/
example {s k : ℕ} {sys : Spin.Imt.ShellSystem s k} {c c' : Spin.Imt.Coords k}
    {μ : Finset (Fin s) → ℝ} (h : Spin.Imt.Dominates sys c μ)
    (hZ : c.Z ≤ c'.Z) (hD : c.D ≤ c'.D) (hS : ∀ i, c.S i ≤ c'.S i) :
    Spin.Imt.Dominates sys c' μ :=
  h.mono hZ hD hS

/-- **The transfer row leaving a nonzero state**: `½` stays, and the other half
spreads as `c_h/(2M)` over the shells. -/
example {s k : ℕ} (sys : Spin.Imt.ShellSystem s k) {q : Finset (Fin s)} (hq : q ≠ ∅) :
    Spin.Imt.Dominates sys
      ⟨0, 1 / 2,
        fun h => ((sys.shell h).card : ℝ) / (2 * ((Spin.nonzeroStates s).card : ℝ))⟩
      (Spin.Imt.actLaw q) :=
  Spin.Imt.dominates_actLaw sys hq

/-! ### One step of the IMT recurrence

The transvection law composed with the syndrome shift.  The composition is
exact, so the zero row, the zero column and the `min` in it are all derived
rather than assumed.  Nothing needs `A` or `C` to be linear. -/

/-- **One step from a nonzero state**, exactly. -/
example {s t : ℕ} {q : Finset (Fin s)} (hq : q ≠ ∅)
    (Xs : Finset (Finset (Fin t))) (wgt : Finset (Fin t) → ℝ)
    (Cmap : Finset (Fin t) → Finset (Fin s)) (f : Finset (Fin s) → ℝ) :
    2 * ∑ x ∈ Xs, ∑ p ∈ Spin.transPairs s,
          wgt x * f (symmDiff (Spin.act p.1 p.2 q) (Cmap x))
      = ((Spin.perp q).card : ℝ)
        * (((Spin.nonzeroStates s).card : ℝ)
              * ∑ x ∈ Xs, wgt x * f (symmDiff q (Cmap x))
            + ∑ x ∈ Xs, wgt x * ((∑ w : Finset (Fin s), f w) - f (Cmap x))) :=
  Spin.step_sum hq Xs wgt Cmap f

/-- **The zero column.** -/
example {s t : ℕ} {q : Finset (Fin s)} (hq : q ≠ ∅)
    (Xs : Finset (Finset (Fin t))) (wgt : Finset (Fin t) → ℝ)
    (Cmap : Finset (Fin t) → Finset (Fin s)) :
    2 * ∑ x ∈ Xs, ∑ p ∈ Spin.transPairs s,
          wgt x * (if symmDiff (Spin.act p.1 p.2 q) (Cmap x) = ∅ then 1 else 0)
      = ((Spin.perp q).card : ℝ)
        * (((Spin.nonzeroStates s).card : ℝ)
              * ∑ x ∈ Xs, wgt x * (if Cmap x = q then 1 else 0)
            + ∑ x ∈ Xs, wgt x * (if Cmap x = ∅ then 0 else 1)) :=
  Spin.step_zero_column hq Xs wgt Cmap

/-- **The `min` in the zero column**, from both bounds on the refresh term. -/
example {s t : ℕ} (Xs : Finset (Finset (Fin t))) (wgt : Finset (Fin t) → ℝ)
    (Cmap : Finset (Fin t) → Finset (Fin s))
    (hw0 : ∀ x ∈ Xs, 0 ≤ wgt x) (hw1 : ∀ x ∈ Xs, wgt x ≤ 1) :
    ∑ x ∈ Xs, wgt x * (if Cmap x = ∅ then (0 : ℝ) else 1)
      ≤ min (∑ x ∈ Xs, wgt x)
          ((Xs.filter (fun x => Cmap x ≠ ∅)).card : ℝ) :=
  Spin.sum_refresh_le_min Xs wgt Cmap hw0 hw1

/-- **The zero row is exact** — the transvection fixes zero, so no `½`. -/
example {s t : ℕ} (Xs : Finset (Finset (Fin t))) (wgt : Finset (Fin t) → ℝ)
    (Cmap : Finset (Fin t) → Finset (Fin s)) (f : Finset (Fin s) → ℝ) :
    ∑ x ∈ Xs, ∑ p ∈ Spin.transPairs s,
        wgt x * f (symmDiff (Spin.act p.1 p.2 (∅ : Finset (Fin s))) (Cmap x))
      = ((Spin.transPairs s).card : ℝ) * ∑ x ∈ Xs, wgt x * f (Cmap x) :=
  Spin.step_from_zero Xs wgt Cmap f

/-! ### `eq:imt-moment`

Rows index the entering coordinate, so measures propagate as row vectors.
Pinned as definitions, because a transposed convention would typecheck. -/

example {k : ℕ} (T : Spin.Imt.Transfer k) (c : Spin.Imt.Coords k) :
    T.apply c
      = { Z := c.Z * T.rowZ.Z + c.D * T.rowD.Z + ∑ i, c.S i * (T.rowS i).Z,
          D := c.Z * T.rowZ.D + c.D * T.rowD.D + ∑ i, c.S i * (T.rowS i).D,
          S := fun h => c.Z * T.rowZ.S h + c.D * T.rowD.S h
                        + ∑ i, c.S i * (T.rowS i).S h } := rfl

example (k : ℕ) :
    Spin.Imt.Coords.eZ k = { Z := 1, D := 0, S := fun _ => 0 } := rfl

/-- The initial condition. -/
example {s k : ℕ} (sys : Spin.Imt.ShellSystem s k) :
    Spin.Imt.Dominates sys (Spin.Imt.Coords.eZ k)
      (fun q => if q = ∅ then (1 : ℝ) else 0) :=
  Spin.Imt.dominates_eZ sys

/-- **`eq:imt-moment`.** -/
example {s k : ℕ} {sys : Spin.Imt.ShellSystem s k} (T : Spin.Imt.Transfer k)
    (step : (Finset (Fin s) → ℝ) → (Finset (Fin s) → ℝ))
    (hstep : ∀ c μ, Spin.Imt.Dominates sys c μ →
      Spin.Imt.Dominates sys (T.apply c) (step μ)) (R : ℕ) :
    ∑ q, (step^[R] (fun q => if q = ∅ then (1 : ℝ) else 0)) q
      ≤ ((T.apply)^[R] (Spin.Imt.Coords.eZ k)).total :=
  Spin.Imt.imt_moment_eZ T step hstep R

/-- Mixtures, for `T_occ`. -/
example {s k : ℕ} {sys : Spin.Imt.ShellSystem s k} {ι : Type} [Fintype ι]
    {cs : ι → Spin.Imt.Coords k} {μs : ι → Finset (Fin s) → ℝ}
    (h : ∀ i, Spin.Imt.Dominates sys (cs i) (μs i)) :
    Spin.Imt.Dominates sys (Spin.Imt.Coords.sum cs) (fun q => ∑ i, μs i q) :=
  Spin.Imt.dominates_sum h

example {s k : ℕ} {sys : Spin.Imt.ShellSystem s k} {c : Spin.Imt.Coords k}
    {μ : Finset (Fin s) → ℝ} (h : Spin.Imt.Dominates sys c μ) {a : ℝ} (ha : 0 ≤ a) :
    Spin.Imt.Dominates sys (Spin.Imt.Coords.smul a c) (fun q => a * μ q) :=
  Spin.Imt.dominates_smul h ha

/-- **The scalar envelope `T_sc`**: every row total at most `λ` gives `λ^R`. -/
example {k : ℕ} {T : Spin.Imt.Transfer k} {lam : ℝ} (hlam : 0 ≤ lam)
    (hT : T.Nonneg) (hZ : T.rowZ.total ≤ lam) (hD : T.rowD.total ≤ lam)
    (hS : ∀ i, (T.rowS i).total ≤ lam) (R : ℕ) :
    ((T.apply)^[R] (Spin.Imt.Coords.eZ k)).total ≤ lam ^ R :=
  Spin.Imt.total_iterate_le hlam hT hZ hD hS R

/-! ### The KL chain-rule bound

`D(αx ‖ py) ≤ D(α‖p) + α D(x‖y)`, the likelihood cost of moving the iid
reference probability from `αx` to `py` in `eq:imt-dense-exponent`.  Holds on
the paper's closed range, `α` and `x` up to and including `1`. -/

example (u v : ℝ) :
    Spin.binKL u v
      = u * Real.log (u / v) + (1 - u) * Real.log ((1 - u) / (1 - v)) := rfl

/-- **Log-sum, two terms**, allowing zero numerators. -/
example {a₁ a₂ b₁ b₂ : ℝ} (ha₁ : 0 ≤ a₁) (ha₂ : 0 ≤ a₂)
    (hb₁ : 0 < b₁) (hb₂ : 0 < b₂) :
    (a₁ + a₂) * Real.log ((a₁ + a₂) / (b₁ + b₂))
      ≤ a₁ * Real.log (a₁ / b₁) + a₂ * Real.log (a₂ / b₂) :=
  Spin.logSum2 ha₁ ha₂ hb₁ hb₂

/-- **The chain-rule bound.** -/
example {α x p y : ℝ} (hα0 : 0 < α) (hα1 : α ≤ 1)
    (hx0 : 0 < x) (hx1 : x ≤ 1) (hp0 : 0 < p) (hp1 : p < 1)
    (hy0 : 0 < y) (hy1 : y < 1) :
    Spin.binKL (α * x) (p * y) ≤ Spin.binKL α p + α * Spin.binKL x y :=
  Spin.binKL_chain hα0 hα1 hx0 hx1 hp0 hp1 hy0 hy1

/-! ### Convexity and the vertex check

What justifies "fixes a witness on each box and checks four vertices".  The
`ConvexOn` hypothesis is on the *box*, which is load-bearing: in `(α, αx)`
coordinates the feasible region is a cone, so a rectangle is admissible only
when it lies inside it. -/

/-- **Four vertices suffice.** -/
example {f : ℝ × ℝ → ℝ} {a₁ b₁ a₂ b₂ : ℝ}
    (hf : ConvexOn ℝ (Set.Icc a₁ b₁ ×ˢ Set.Icc a₂ b₂) f)
    {z : ℝ × ℝ} (hz : z ∈ Set.Icc a₁ b₁ ×ˢ Set.Icc a₂ b₂) :
    f z ≤ max (max (f (a₁, a₂)) (f (a₁, b₂))) (max (f (b₁, a₂)) (f (b₁, b₂))) :=
  Spin.le_max_vertices hf hz

example (t : Set ℝ) :
    Spin.perspectiveDomain t = {q : ℝ × ℝ | 0 < q.1 ∧ q.2 / q.1 ∈ t} := rfl

/-- **The perspective transform is convex** — this is what makes `α·D(x‖y)`
convex in `(α, αx)`.  Not in Mathlib. -/
example {g : ℝ → ℝ} {t : Set ℝ} (hg : ConvexOn ℝ t g) :
    ConvexOn ℝ (Spin.perspectiveDomain t) (fun q => q.1 * g (q.2 / q.1)) :=
  Spin.convexOn_perspective hg

/-- `D(·‖p)` is convex. -/
example {p : ℝ} (hp0 : 0 < p) (hp1 : p < 1) :
    ConvexOn ℝ (Set.Icc (0 : ℝ) 1) (fun u => Spin.binKL u p) :=
  Spin.convexOn_binKL_left hp0 hp1

/-- Restricting a convex function to an axis-parallel line. -/
example {f : ℝ × ℝ → ℝ} {s₁ s₂ : Set ℝ} (hs₁ : Convex ℝ s₁)
    (hf : ConvexOn ℝ (s₁ ×ˢ s₂) f) {c : ℝ} (hc : c ∈ s₂) :
    ConvexOn ℝ s₁ (fun t => f (t, c)) :=
  Spin.convexOn_slice₁ hs₁ hf hc

/-! ### The Collatz bound

The alternative to the scalar envelope in `eq:imt-dense-exponent`: a *right*
eigen-inequality against a positive column.  `λ` and `w` are inputs and only
`T w ≤ λ w` is checked — "no numerical eigenvalue is trusted". -/

example {k : ℕ} (c d : Spin.Imt.Coords k) :
    c.dot d = c.Z * d.Z + c.D * d.D + ∑ i, c.S i * d.S i := rfl

example {k : ℕ} (T : Spin.Imt.Transfer k) (w : Spin.Imt.Coords k) :
    T.applyCol w
      = { Z := T.rowZ.dot w, D := T.rowD.dot w,
          S := fun h => (T.rowS h).dot w } := rfl

example {k : ℕ} (c d : Spin.Imt.Coords k) :
    Spin.Imt.Coords.le c d ↔ c.Z ≤ d.Z ∧ c.D ≤ d.D ∧ ∀ i, c.S i ≤ d.S i := Iff.rfl

/-- **Adjointness**: `(c T) · w = c · (T w)`. -/
example {k : ℕ} (T : Spin.Imt.Transfer k) (c w : Spin.Imt.Coords k) :
    (T.apply c).dot w = c.dot (T.applyCol w) :=
  Spin.Imt.dot_apply T c w

/-- **The Collatz bound**, multiplicatively: no division, no eigenvalue. -/
example {k : ℕ} {T : Spin.Imt.Transfer k} (hT : T.Nonneg) {w : Spin.Imt.Coords k}
    {lam : ℝ} (hw : Spin.Imt.Coords.le (T.applyCol w) (Spin.Imt.Coords.smul lam w))
    {wmin : ℝ} (hwmin : 0 < wmin) (hZ : wmin ≤ w.Z) (hD : wmin ≤ w.D)
    (hS : ∀ i, wmin ≤ w.S i) (R : ℕ) :
    ((T.apply)^[R] (Spin.Imt.Coords.eZ k)).total * wmin ≤ lam ^ R * w.Z :=
  Spin.Imt.collatz_total hT hw hwmin hZ hD hS R

/-! ### Empty-epoch estimates

`P = (I+Π)/2` is a fair coin between "stay" and "resample", so the conditional
mean obeys a scalar recurrence and everything the appendix needs follows from
it and two finite geometric sums. -/

/-- **The conditional mean**, `m_g = μ + 2^{-g}(m_0 - μ)`. -/
example {m : ℕ → ℝ} {mu : ℝ} (h : ∀ g, m (g + 1) = (m g + mu) / 2) (g : ℕ) :
    m g = mu + (1 / 2 : ℝ) ^ g * (m 0 - mu) :=
  Spin.geom_recurrence h g

/-- **`|E S_g − μg| ≤ 2t`.**  The constant `2` is sharp. -/
example {m : ℕ → ℝ} {mu t : ℝ} (h : ∀ g, m (g + 1) = (m g + mu) / 2)
    (ht : |m 0 - mu| ≤ t) (g : ℕ) :
    |(∑ i ∈ Finset.range g, m i) - mu * g| ≤ 2 * t :=
  Spin.mean_sum_bound h ht g

/-- **`Var(S_g) ≤ 3t²g`.** -/
example {g : ℕ} {t : ℝ} (v : ℕ → ℝ) (hv0 : ∀ i, 0 ≤ v i) (hv : ∀ i, v i ≤ t ^ 2) :
    (∑ i ∈ Finset.range g, v i)
        + 2 * ∑ i ∈ Finset.range g, ∑ d ∈ Finset.range g,
            (1 / 2 : ℝ) ^ (d + 1) * v i
      ≤ 3 * t ^ 2 * g :=
  Spin.var_sum_bound v hv0 hv

/-- **`G_Q ≤ G_3`**, pointwise in `y`. -/
example {sigma tau y : ℝ} (hsig0 : 0 < sigma) (hsig1 : sigma < 1) (hy0 : 0 ≤ y)
    {Q Q' : ℕ} (hQ' : 0 < Q') (hQQ : Q' ≤ Q) :
    -tau * y + (1 + 1 / (Q : ℝ)) * Real.log (1 - y + y / sigma)
      ≤ -tau * y + (1 + 1 / (Q' : ℝ)) * Real.log (1 - y + y / sigma) :=
  Spin.G_antitone hsig0 hsig1 hy0 hQ' hQQ

/-! ### The two-state coarse-graining

`R J = I₂`, and `J D R` has the live block constant at `d/M` — so
`eq:imt-empty-limit` is literally the entrywise distance to `J D R`. -/

example {s : ℕ} (q : Finset (Fin s)) (i : Fin 2) :
    Spin.lift q i
      = if i = 0 then (if q = ∅ then 1 else 0) else (if q = ∅ then 0 else 1) := rfl

example {s : ℕ} (i : Fin 2) (q : Finset (Fin s)) :
    Spin.proj i q
      = if i = 0 then (if q = ∅ then 1 else 0)
        else (if q = ∅ then 0 else 1 / ((Spin.nonzeroStates s).card : ℝ)) := rfl

/-- **`R J = I₂`.** -/
example {s : ℕ} (hs : 0 < (Spin.nonzeroStates s).card) (i j : Fin 2) :
    ∑ q : Finset (Fin s), Spin.proj i q * Spin.lift q j = if i = j then 1 else 0 :=
  Spin.proj_lift hs i j

/-- **`J D R` entry by entry.** -/
example {s : ℕ} (d : ℝ) (q q' : Finset (Fin s)) :
    ∑ i : Fin 2, ∑ j : Fin 2, Spin.lift q i * Spin.coarseD d i j * Spin.proj j q'
      = if q = ∅ then (if q' = ∅ then 1 else 0)
        else (if q' = ∅ then 0 else d / ((Spin.nonzeroStates s).card : ℝ)) :=
  Spin.lift_coarseD_proj d q q'

/-- The Lipschitz step behind `eq:imt-empty-limit`. -/
example {a b : ℝ} (ha : 0 ≤ a) (hb : 0 ≤ b) :
    |Real.exp (-a) - Real.exp (-b)| ≤ |a - b| :=
  Spin.abs_expNeg_sub_le ha hb

/-! ### The continuum region kernel

The integrands are pinned as they come out of Mathlib's matrix product, with
the exponent arithmetic in separate lemmas; the scalar integrals are pinned
with their closed forms; `K_1^+` is pinned entry by entry. -/

example (gam u : ℝ) :
    Spin.Dg gam u = !![1, 0; 0, Real.exp (-gam * u)] := rfl

example (r : ℝ) : Spin.Pplus r = !![0, 1; r, 1] := rfl

/-- **The `a = 1` integrand.** -/
example (gam r u : ℝ) :
    Spin.Dg gam u * Spin.Pplus r * Spin.Dg gam (1 - u)
      = !![0, Real.exp (-gam * (1 - u));
           r * Real.exp (-gam * u),
           Real.exp (-gam * u) * Real.exp (-gam * (1 - u))] :=
  Spin.integrand_one gam r u

/-- **The `a = 2` integrand.** -/
example (gam r u0 u1 u2 : ℝ) :
    Spin.Dg gam u0 * Spin.Pplus r * Spin.Dg gam u1 * Spin.Pplus r * Spin.Dg gam u2
      = !![r * Real.exp (-gam * u1), Real.exp (-gam * u1) * Real.exp (-gam * u2);
           r * (Real.exp (-gam * u0) * Real.exp (-gam * u1)),
           r * (Real.exp (-gam * u0) * Real.exp (-gam * u2))
             + Real.exp (-gam * u0) * Real.exp (-gam * u1) * Real.exp (-gam * u2)] :=
  Spin.integrand_two gam r u0 u1 u2

/-- On the simplex the durations total `1`. -/
example {gam u0 u1 u2 : ℝ} (h : u0 + u1 + u2 = 1) :
    Real.exp (-gam * u0) * Real.exp (-gam * u1) * Real.exp (-gam * u2)
      = Real.exp (-gam) :=
  Spin.exp_prod_two h

/-- The three scalar integrals. -/
example {gam : ℝ} (hg : gam ≠ 0) :
    (∫ u in (0 : ℝ)..1, Real.exp (-gam * u)) = (1 - Real.exp (-gam)) / gam :=
  Spin.integral_expNeg hg

example {gam : ℝ} (hg : gam ≠ 0) :
    (∫ u in (0 : ℝ)..1, Real.exp (-gam * (1 - u))) = (1 - Real.exp (-gam)) / gam :=
  Spin.integral_expNeg_rev hg

example {gam : ℝ} (hg : gam ≠ 0) :
    (∫ u in (0 : ℝ)..1, u * Real.exp (-gam * u))
      = (1 - (1 + gam) * Real.exp (-gam)) / gam ^ 2 :=
  Spin.integral_mul_expNeg hg

/-- **`K_1^+ = [[0, f], [r f, a_0]]`**, entry by entry. -/
example (gam r : ℝ) :
    (∫ u in (0 : ℝ)..1, (Spin.Dg gam u * Spin.Pplus r * Spin.Dg gam (1 - u)) 0 0) = 0 :=
  Spin.K1_entry_00 gam r

example {gam : ℝ} (r : ℝ) (hg : gam ≠ 0) :
    (∫ u in (0 : ℝ)..1, (Spin.Dg gam u * Spin.Pplus r * Spin.Dg gam (1 - u)) 0 1)
      = (1 - Real.exp (-gam)) / gam :=
  Spin.K1_entry_01 r hg

example {gam : ℝ} (r : ℝ) (hg : gam ≠ 0) :
    (∫ u in (0 : ℝ)..1, (Spin.Dg gam u * Spin.Pplus r * Spin.Dg gam (1 - u)) 1 0)
      = r * ((1 - Real.exp (-gam)) / gam) :=
  Spin.K1_entry_10 r hg

example (gam r : ℝ) :
    (∫ u in (0 : ℝ)..1, (Spin.Dg gam u * Spin.Pplus r * Spin.Dg gam (1 - u)) 1 1)
      = Real.exp (-gam) :=
  Spin.K1_entry_11 gam r

/-! ### `K_2^+`

The `a = 2` kernel as a nested `intervalIntegral` over the triangle, with
`u₂ = 1 - u₀ - u₁`.  All four entries match the paper's
`[[rg, e], [re, re + a₀]]`. -/

/-- Variable-endpoint exponential integrals. -/
example {c : ℝ} (hc : c ≠ 0) (b : ℝ) :
    (∫ u in (0 : ℝ)..b, Real.exp (c * u)) = (Real.exp (c * b) - 1) / c :=
  Spin.integral_expLin hc b

example {gam : ℝ} (hg : gam ≠ 0) (b : ℝ) :
    (∫ u in (0 : ℝ)..b, Real.exp (-gam * (1 - u)))
      = (Real.exp (-gam * (1 - b)) - Real.exp (-gam)) / gam :=
  Spin.integral_expRev hg b

/-- `K_2^+` entry `(0,0) = r g`. -/
example {gam : ℝ} (r : ℝ) (hg : gam ≠ 0) :
    (2 : ℝ) * ∫ u0 in (0 : ℝ)..1, ∫ u1 in (0 : ℝ)..(1 - u0),
        (Spin.Dg gam u0 * Spin.Pplus r * Spin.Dg gam u1 * Spin.Pplus r
          * Spin.Dg gam (1 - u0 - u1)) 0 0
      = r * (2 * (gam - 1 + Real.exp (-gam)) / gam ^ 2) :=
  Spin.K2_entry_00 r hg

/-- `K_2^+` entry `(0,1) = e`. -/
example {gam : ℝ} (r : ℝ) (hg : gam ≠ 0) :
    (2 : ℝ) * ∫ u0 in (0 : ℝ)..1, ∫ u1 in (0 : ℝ)..(1 - u0),
        (Spin.Dg gam u0 * Spin.Pplus r * Spin.Dg gam u1 * Spin.Pplus r
          * Spin.Dg gam (1 - u0 - u1)) 0 1
      = 2 * (1 - (1 + gam) * Real.exp (-gam)) / gam ^ 2 :=
  Spin.K2_entry_01 r hg

/-- `K_2^+` entry `(1,0) = r e`. -/
example {gam : ℝ} (r : ℝ) (hg : gam ≠ 0) :
    (2 : ℝ) * ∫ u0 in (0 : ℝ)..1, ∫ u1 in (0 : ℝ)..(1 - u0),
        (Spin.Dg gam u0 * Spin.Pplus r * Spin.Dg gam u1 * Spin.Pplus r
          * Spin.Dg gam (1 - u0 - u1)) 1 0
      = r * (2 * (1 - (1 + gam) * Real.exp (-gam)) / gam ^ 2) :=
  Spin.K2_entry_10 r hg

/-- `K_2^+` entry `(1,1) = r e + a_0`. -/
example {gam : ℝ} (r : ℝ) (hg : gam ≠ 0) :
    (2 : ℝ) * ∫ u0 in (0 : ℝ)..1, ∫ u1 in (0 : ℝ)..(1 - u0),
        (Spin.Dg gam u0 * Spin.Pplus r * Spin.Dg gam u1 * Spin.Pplus r
          * Spin.Dg gam (1 - u0 - u1)) 1 1
      = r * (2 * (1 - (1 + gam) * Real.exp (-gam)) / gam ^ 2) + Real.exp (-gam) :=
  Spin.K2_entry_11 r hg

/-! ### The weighted row norm

The bound is carried as a predicate rather than a supremum, so no division by
`v₁` appears.  `m_v(u)` is the larger of the two row requirements, and is the
norm exactly, not merely a bound. -/

example (v1 c : ℝ) (A : Matrix (Fin 2) (Fin 2) ℝ) :
    Spin.RowNormLe v1 c A
      ↔ |A 0 0| + |A 0 1| * v1 ≤ c ∧ |A 1 0| + |A 1 1| * v1 ≤ c * v1 := Iff.rfl

example (sig v1 r u : ℝ) :
    Spin.mv sig v1 r u = max (1 + u * sig * v1) (u * r / v1 + sig * (1 + u)) := rfl

/-- **Submultiplicativity.** -/
example {v1 a b : ℝ} (hv1 : 0 ≤ v1) (hb : 0 ≤ b)
    {A B : Matrix (Fin 2) (Fin 2) ℝ}
    (hA : Spin.RowNormLe v1 a A) (hB : Spin.RowNormLe v1 b B) :
    Spin.RowNormLe v1 (a * b) (A * B) :=
  hA.mul hv1 hb hB

/-- `I + uP_+` really is the identity plus `u P_+`. -/
example (r u : ℝ) : Spin.IuP r u = 1 + u • Spin.Pplus r := Spin.IuP_eq r u

/-- **`‖D_σ‖_v ≤ 1`.** -/
example {sig v1 : ℝ} (hsig0 : 0 ≤ sig) (hsig1 : sig ≤ 1) (hv1 : 0 ≤ v1) :
    Spin.RowNormLe v1 1 (Spin.Dsig sig) :=
  Spin.rowNormLe_Dsig hsig0 hsig1 hv1

/-- **`‖(I+uP_+)D_σ‖_v = m_v(u)`.** -/
example {sig v1 r u : ℝ} (hsig0 : 0 ≤ sig) (hv1 : 0 < v1) (hr : 0 ≤ r) (hu : 0 ≤ u) :
    Spin.RowNormLe v1 (Spin.mv sig v1 r u) (Spin.IuP r u * Spin.Dsig sig) :=
  Spin.rowNormLe_step hsig0 hv1 hr hu

/-- **`eq:imt-product-norm`, the norm half.** -/
example {sig v1 r : ℝ} (hsig0 : 0 ≤ sig) (hv1 : 0 < v1) (hr : 0 ≤ r)
    (us : List ℝ) (hus : ∀ u ∈ us, 0 ≤ u) :
    Spin.RowNormLe v1 ((us.map (Spin.mv sig v1 r)).prod) (Spin.pathProduct sig r us) :=
  Spin.rowNormLe_pathProduct hsig0 hv1 hr us hus

/-! ### The Beta identity

`E[(1-Y+Y/σ)^{-(Q+1)}] = σ^l`, written with `a = l-1`, `b = Q-l` so no
truncated subtraction appears.  The Beta value is on both sides and cancels,
so no Beta or Gamma machinery is involved — only the change of variables. -/

example (sig u : ℝ) : Spin.betaSub sig u = u * sig / (1 - u * (1 - sig)) := rfl

example (sig u : ℝ) : Spin.betaSub' sig u = sig / (1 - u * (1 - sig)) ^ 2 := rfl

example {sig : ℝ} (hsig0 : 0 < sig) : Spin.betaSub sig 1 = 1 :=
  Spin.betaSub_one hsig0

example {sig : ℝ} (hsig0 : 0 < sig) (hsig1 : sig ≤ 1) {u : ℝ}
    (hu : u ∈ Set.Icc (0 : ℝ) 1) :
    HasDerivAt (Spin.betaSub sig) (Spin.betaSub' sig u) u :=
  Spin.hasDerivAt_betaSub hsig0 hsig1 hu

/-- **The Beta identity.** -/
example {sig : ℝ} (hsig0 : 0 < sig) (hsig1 : sig ≤ 1) (a b : ℕ) :
    (∫ y in (0 : ℝ)..1, y ^ a * (1 - y) ^ b / (1 - y + y / sig) ^ (a + b + 2))
      = sig ^ (a + 1) * ∫ u in (0 : ℝ)..1, u ^ a * (1 - u) ^ b :=
  Spin.beta_substitution hsig0 hsig1 a b

/-! ## The headline conclusion -/

example (C : ScalableCertificate) : Tendsto C.probBad atTop (nhds 0) :=
  C.distance_whp

end Spin.Pin
