// Generated by rs16_outer_codegen.py; regenerate rather than hand-edit.
// Source rs16_maps.py: 8f6689862cd5d55e1217cc0f4f7300f54f306367c9f9ec1a3c60a0bfc43d0f4f
#pragma once
#include "RsPrototype.h"
namespace spin::research::rs::fast16 {
static SPIN_FORCEINLINE void mixSymbol(const Block* input,__m512i* packed,const std::uint64_t* coeff){
const auto index0=_mm512_setr_epi64(0x0141115100401050ULL,0x0343135302421252ULL,0x0545155504441454ULL,0x0747175706461656ULL,0x0949195908481858ULL,0x0b4b1b5b0a4a1a5aULL,0x0d4d1d5d0c4c1c5cULL,0x0f4f1f5f0e4e1e5eULL);
const auto index1=_mm512_setr_epi64(0x2161317120603070ULL,0x2363337322623272ULL,0x2565357524643474ULL,0x2767377726663676ULL,0x2969397928683878ULL,0x2b6b3b7b2a6a3a7aULL,0x2d6d3d7d2c6c3c7cULL,0x2f6f3f7f2e6e3e7eULL);
const auto index2=_mm512_setr_epi64(0x0302434201004140ULL,0x0706474605044544ULL,0x0b0a4b4a09084948ULL,0x0f0e4f4e0d0c4d4cULL,0x1312535211105150ULL,0x1716575615145554ULL,0x1b1a5b5a19185958ULL,0x1f1e5f5e1d1c5d5cULL);
const auto index3=_mm512_setr_epi64(0x2322636221206160ULL,0x2726676625246564ULL,0x2b2a6b6a29286968ULL,0x2f2e6f6e2d2c6d6cULL,0x3332737231307170ULL,0x3736777635347574ULL,0x3b3a7b7a39387978ULL,0x3f3e7f7e3d3c7d7cULL);
const auto raw0=_mm512_loadu_si512(input+0);
const auto raw1=_mm512_loadu_si512(input+4);
const auto raw2=_mm512_loadu_si512(input+8);
const auto raw3=_mm512_loadu_si512(input+12);
const auto a0=_mm512_permutex2var_epi8(raw0,index0,raw1);
const auto a1=_mm512_permutex2var_epi8(raw0,index1,raw1);
const auto a2=_mm512_permutex2var_epi8(raw2,index0,raw3);
const auto a3=_mm512_permutex2var_epi8(raw2,index1,raw3);
const auto b0=_mm512_permutex2var_epi8(a0,index2,a2);
const auto b1=_mm512_permutex2var_epi8(a0,index3,a2);
const auto b2=_mm512_permutex2var_epi8(a1,index2,a3);
const auto b3=_mm512_permutex2var_epi8(a1,index3,a3);
const auto basis=_mm512_set1_epi64(0x0102040810204080ULL);
const auto v0=_mm512_gf2p8affine_epi64_epi8(basis,b0,0);
const auto m0=_mm512_set1_epi64(coeff[0]);
const auto v1=_mm512_gf2p8affine_epi64_epi8(basis,b1,0);
const auto m1=_mm512_set1_epi64(coeff[1]);
const auto v2=_mm512_gf2p8affine_epi64_epi8(basis,b2,0);
const auto m2=_mm512_set1_epi64(coeff[2]);
const auto v3=_mm512_gf2p8affine_epi64_epi8(basis,b3,0);
const auto m3=_mm512_set1_epi64(coeff[3]);
_mm512_store_si512(packed+0,_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(v0,m0,0),_mm512_gf2p8affine_epi64_epi8(v2,m1,0)));
_mm512_store_si512(packed+1,_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(v1,m0,0),_mm512_gf2p8affine_epi64_epi8(v3,m1,0)));
_mm512_store_si512(packed+2,_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(v0,m2,0),_mm512_gf2p8affine_epi64_epi8(v2,m3,0)));
_mm512_store_si512(packed+3,_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(v1,m2,0),_mm512_gf2p8affine_epi64_epi8(v3,m3,0)));
}
template<unsigned plane> static SPIN_FORCEINLINE void parityPlane(__m512i* packed){
static_assert(plane<4);
const auto m2=_mm512_set1_epi64(0x0204080320408030ULL);
const auto m5=_mm512_set1_epi64(0x050a070e50a070e0ULL);
const auto m8=_mm512_set1_epi64(0x0803060c803060c0ULL);
const auto m11=_mm512_set1_epi64(0x0b050a07b050a070ULL);
const auto m12=_mm512_set1_epi64(0x0c0b050ac0b050a0ULL);
const auto m13=_mm512_set1_epi64(0x0d090102d0901020ULL);
auto x0=_mm512_load_si512(packed+32+plane);
auto x1=_mm512_load_si512(packed+36+plane);
auto x2=_mm512_load_si512(packed+40+plane);
auto x3=_mm512_load_si512(packed+44+plane);
auto x4=_mm512_load_si512(packed+48+plane);
auto x5=_mm512_load_si512(packed+52+plane);
auto x6=_mm512_load_si512(packed+56+plane);
auto x7=_mm512_load_si512(packed+60+plane);
x0=_mm512_xor_si512(x0,x1);
x2=_mm512_xor_si512(x2,x3);
x4=_mm512_xor_si512(x4,x5);
x6=_mm512_xor_si512(x6,x7);
x0=_mm512_xor_si512(x0,x2);
x1=_mm512_xor_si512(x1,x3);
x4=_mm512_xor_si512(x4,x6);
x5=_mm512_xor_si512(x5,x7);
x0=_mm512_xor_si512(x0,x4);
x1=_mm512_xor_si512(x1,x5);
x2=_mm512_xor_si512(x2,x6);
x3=_mm512_xor_si512(x3,x7);
auto y0=x0;
auto y1=x1;
y1=_mm512_xor_si512(y1,_mm512_gf2p8affine_epi64_epi8(x0,m11,0));
auto y2=x2;
y2=_mm512_xor_si512(y2,_mm512_gf2p8affine_epi64_epi8(x0,m2,0));
auto y3=x3;
y3=_mm512_xor_si512(y3,_mm512_gf2p8affine_epi64_epi8(x0,m13,0));
y3=_mm512_xor_si512(y3,_mm512_gf2p8affine_epi64_epi8(x1,m2,0));
y3=_mm512_xor_si512(y3,_mm512_gf2p8affine_epi64_epi8(x2,m11,0));
auto y4=x4;
y4=_mm512_xor_si512(y4,_mm512_gf2p8affine_epi64_epi8(x0,m5,0));
auto y5=x5;
y5=_mm512_xor_si512(y5,_mm512_gf2p8affine_epi64_epi8(x0,m12,0));
y5=_mm512_xor_si512(y5,_mm512_gf2p8affine_epi64_epi8(x1,m5,0));
y5=_mm512_xor_si512(y5,_mm512_gf2p8affine_epi64_epi8(x4,m11,0));
auto y6=x6;
y6=_mm512_xor_si512(y6,_mm512_gf2p8affine_epi64_epi8(x0,m11,0));
y6=_mm512_xor_si512(y6,_mm512_gf2p8affine_epi64_epi8(x2,m5,0));
y6=_mm512_xor_si512(y6,_mm512_gf2p8affine_epi64_epi8(x4,m2,0));
auto y7=x7;
y7=_mm512_xor_si512(y7,_mm512_gf2p8affine_epi64_epi8(x0,m8,0));
y7=_mm512_xor_si512(y7,_mm512_gf2p8affine_epi64_epi8(x1,m11,0));
y7=_mm512_xor_si512(y7,_mm512_gf2p8affine_epi64_epi8(x2,m12,0));
y7=_mm512_xor_si512(y7,_mm512_gf2p8affine_epi64_epi8(x3,m5,0));
y7=_mm512_xor_si512(y7,_mm512_gf2p8affine_epi64_epi8(x4,m13,0));
y7=_mm512_xor_si512(y7,_mm512_gf2p8affine_epi64_epi8(x5,m2,0));
y7=_mm512_xor_si512(y7,_mm512_gf2p8affine_epi64_epi8(x6,m11,0));
y0=_mm512_xor_si512(y0,y1);
y2=_mm512_xor_si512(y2,y3);
y4=_mm512_xor_si512(y4,y5);
y6=_mm512_xor_si512(y6,y7);
y0=_mm512_xor_si512(y0,y2);
y1=_mm512_xor_si512(y1,y3);
y4=_mm512_xor_si512(y4,y6);
y5=_mm512_xor_si512(y5,y7);
y0=_mm512_xor_si512(y0,y4);
y1=_mm512_xor_si512(y1,y5);
y2=_mm512_xor_si512(y2,y6);
y3=_mm512_xor_si512(y3,y7);
_mm512_store_si512(packed+0+plane,_mm512_xor_si512(_mm512_load_si512(packed+0+plane),y0));
_mm512_store_si512(packed+4+plane,_mm512_xor_si512(_mm512_load_si512(packed+4+plane),y1));
_mm512_store_si512(packed+8+plane,_mm512_xor_si512(_mm512_load_si512(packed+8+plane),y2));
_mm512_store_si512(packed+12+plane,_mm512_xor_si512(_mm512_load_si512(packed+12+plane),y3));
_mm512_store_si512(packed+16+plane,_mm512_xor_si512(_mm512_load_si512(packed+16+plane),y4));
_mm512_store_si512(packed+20+plane,_mm512_xor_si512(_mm512_load_si512(packed+20+plane),y5));
_mm512_store_si512(packed+24+plane,_mm512_xor_si512(_mm512_load_si512(packed+24+plane),y6));
_mm512_store_si512(packed+28+plane,_mm512_xor_si512(_mm512_load_si512(packed+28+plane),y7));
}
template<unsigned symbol> static SPIN_FORCEINLINE void storeSymbol(const __m512i* packed,Block* out){
static_assert(symbol<8);
const auto index0=_mm512_setr_epi64(0x3830282018100800ULL,0x7870686058504840ULL,0x3931292119110901ULL,0x7971696159514941ULL,0x3a322a221a120a02ULL,0x7a726a625a524a42ULL,0x3b332b231b130b03ULL,0x7b736b635b534b43ULL);
const auto index1=_mm512_setr_epi64(0x3c342c241c140c04ULL,0x7c746c645c544c44ULL,0x3d352d251d150d05ULL,0x7d756d655d554d45ULL,0x3e362e261e160e06ULL,0x7e766e665e564e46ULL,0x3f372f271f170f07ULL,0x7f776f675f574f47ULL);
const auto basis=_mm512_set1_epi64(0x8040201008040201ULL);
const auto x0=_mm512_gf2p8affine_epi64_epi8(basis,_mm512_load_si512(packed+4*symbol+0),0);
const auto x1=_mm512_gf2p8affine_epi64_epi8(basis,_mm512_load_si512(packed+4*symbol+1),0);
const auto x2=_mm512_gf2p8affine_epi64_epi8(basis,_mm512_load_si512(packed+4*symbol+2),0);
const auto x3=_mm512_gf2p8affine_epi64_epi8(basis,_mm512_load_si512(packed+4*symbol+3),0);
_mm512_storeu_si512(out+0+4*symbol,_mm512_permutex2var_epi8(x0,index0,x1));
_mm512_storeu_si512(out+32+4*symbol,_mm512_permutex2var_epi8(x0,index1,x1));
_mm512_storeu_si512(out+64+4*symbol,_mm512_permutex2var_epi8(x2,index0,x3));
_mm512_storeu_si512(out+96+4*symbol,_mm512_permutex2var_epi8(x2,index1,x3));
}
static SPIN_NOINLINE void outerGroup(const Block* __restrict input,Block* __restrict output,const std::uint64_t* __restrict coeff){
alignas(64) __m512i packed[64];
for(unsigned symbol=0;symbol<16;++symbol)mixSymbol(input+16*symbol,packed+4*symbol,coeff+4*symbol);
parityPlane<0>(packed);
parityPlane<1>(packed);
parityPlane<2>(packed);
parityPlane<3>(packed);
storeSymbol<0>(packed,output);
storeSymbol<1>(packed,output);
storeSymbol<2>(packed,output);
storeSymbol<3>(packed,output);
storeSymbol<4>(packed,output);
storeSymbol<5>(packed,output);
storeSymbol<6>(packed,output);
storeSymbol<7>(packed,output);
}
} // namespace spin::research::rs::fast16
