// Generated by rs_outer_codegen.py; regenerate rather than hand-edit.
// Source packed_bch_tune_codegen.py: d58daea63388b6bb9cf0a6b3d7f3c7014d1f7b04cff3bf21c34e22369dab26eb
// Source outer_layout_codegen.py: 729d6133911e3e94bc7774c4c56b69f6f3a84ba58087d0fc6151ac8207ac4fbf
// Source outer_unpack_codegen.py: 64520ba7b61c9ae31dc0228fc4a1db968e5d0a443bb69dd2b900a32a6cc0d326
// Source rs_maps.py: a8034bb2632ff47a0da5335aa8afe0a61ca09c5ba6def15a9411af5e0bb88784
#pragma once
#include "RsPrototype.h"
namespace spin::research::rs::fast {
static SPIN_FORCEINLINE void packedTuneByteTranspose5(__m512i& x0,__m512i& x1,__m512i& x2,__m512i& x3,__m512i& x4,__m512i& x5,__m512i& x6,__m512i& x7) {
const auto t0=_mm512_unpacklo_epi8(x0,x1);
const auto t1=_mm512_unpackhi_epi8(x0,x1);
const auto t2=_mm512_unpacklo_epi8(x2,x3);
const auto t3=_mm512_unpackhi_epi8(x2,x3);
const auto t4=_mm512_unpacklo_epi8(x4,x5);
const auto t5=_mm512_unpackhi_epi8(x4,x5);
const auto t6=_mm512_unpacklo_epi8(x6,x7);
const auto t7=_mm512_unpackhi_epi8(x6,x7);
const auto u0=_mm512_unpacklo_epi16(t0,t2);
const auto u1=_mm512_unpackhi_epi16(t0,t2);
const auto u2=_mm512_unpacklo_epi16(t1,t3);
const auto u3=_mm512_unpackhi_epi16(t1,t3);
const auto u4=_mm512_unpacklo_epi16(t4,t6);
const auto u5=_mm512_unpackhi_epi16(t4,t6);
const auto u6=_mm512_unpacklo_epi16(t5,t7);
const auto u7=_mm512_unpackhi_epi16(t5,t7);
x0=_mm512_unpacklo_epi32(u0,u4);
x1=_mm512_unpackhi_epi32(u0,u4);
x2=_mm512_unpacklo_epi32(u1,u5);
x3=_mm512_unpackhi_epi32(u1,u5);
x4=_mm512_unpacklo_epi32(u2,u6);
x5=_mm512_unpackhi_epi32(u2,u6);
x6=_mm512_unpacklo_epi32(u3,u7);
x7=_mm512_unpackhi_epi32(u3,u7);
}
static SPIN_FORCEINLINE void packedTunePack5(__m512i& x0,__m512i& x1,__m512i& x2,__m512i& x3,__m512i& x4,__m512i& x5,__m512i& x6,__m512i& x7) {
packedTuneByteTranspose5(x7,x6,x5,x4,x3,x2,x1,x0);
const auto basis=_mm512_set1_epi64(0x0102040810204080ULL);
const auto y0=_mm512_gf2p8affine_epi64_epi8(basis,x7,0);
const auto y1=_mm512_gf2p8affine_epi64_epi8(basis,x6,0);
const auto y2=_mm512_gf2p8affine_epi64_epi8(basis,x5,0);
const auto y3=_mm512_gf2p8affine_epi64_epi8(basis,x4,0);
const auto y4=_mm512_gf2p8affine_epi64_epi8(basis,x3,0);
const auto y5=_mm512_gf2p8affine_epi64_epi8(basis,x2,0);
const auto y6=_mm512_gf2p8affine_epi64_epi8(basis,x1,0);
const auto y7=_mm512_gf2p8affine_epi64_epi8(basis,x0,0);
x0=y0;
x1=y1;
x2=y2;
x3=y3;
x4=y4;
x5=y5;
x6=y6;
x7=y7;
}
static SPIN_FORCEINLINE void mixSymbol(const Block* a,__m512i* packed,const std::uint64_t* coeff){
auto v0=_mm512_loadu_si512(a+4*0);
auto v1=_mm512_loadu_si512(a+4*1);
auto v2=_mm512_loadu_si512(a+4*2);
auto v3=_mm512_loadu_si512(a+4*3);
auto v4=_mm512_loadu_si512(a+4*4);
auto v5=_mm512_loadu_si512(a+4*5);
auto v6=_mm512_loadu_si512(a+4*6);
auto v7=_mm512_loadu_si512(a+4*7);
packedTunePack5(v0,v1,v2,v3,v4,v5,v6,v7);
const auto duplicate=_mm512_setr_epi64(0,0,1,1,2,2,3,3);
const auto duplicateOdd=_mm512_setr_epi64(3,3,0,0,1,1,2,2);
const auto c0=_mm256_load_si256(reinterpret_cast<const __m256i*>(coeff+0));
const auto m0=_mm512_permutexvar_epi64(duplicate,_mm512_castsi256_si512(c0));
const auto c1=_mm256_load_si256(reinterpret_cast<const __m256i*>(coeff+4));
const auto m1=_mm512_permutexvar_epi64(duplicateOdd,_mm512_castsi256_si512(c1));
const auto c2=_mm256_load_si256(reinterpret_cast<const __m256i*>(coeff+8));
const auto m2=_mm512_permutexvar_epi64(duplicate,_mm512_castsi256_si512(c2));
const auto c3=_mm256_load_si256(reinterpret_cast<const __m256i*>(coeff+12));
const auto m3=_mm512_permutexvar_epi64(duplicateOdd,_mm512_castsi256_si512(c3));
{
const auto half=_mm512_shuffle_i32x4(v0,v0,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(v0,m1,0),_mm512_gf2p8affine_epi64_epi8(half,m3,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(v0,m0,0),_mm512_gf2p8affine_epi64_epi8(half,m2,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(packed+0,mixed);
}
{
const auto half=_mm512_shuffle_i32x4(v1,v1,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(v1,m1,0),_mm512_gf2p8affine_epi64_epi8(half,m3,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(v1,m0,0),_mm512_gf2p8affine_epi64_epi8(half,m2,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(packed+1,mixed);
}
{
const auto half=_mm512_shuffle_i32x4(v2,v2,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(v2,m1,0),_mm512_gf2p8affine_epi64_epi8(half,m3,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(v2,m0,0),_mm512_gf2p8affine_epi64_epi8(half,m2,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(packed+2,mixed);
}
{
const auto half=_mm512_shuffle_i32x4(v3,v3,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(v3,m1,0),_mm512_gf2p8affine_epi64_epi8(half,m3,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(v3,m0,0),_mm512_gf2p8affine_epi64_epi8(half,m2,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(packed+3,mixed);
}
{
const auto half=_mm512_shuffle_i32x4(v4,v4,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(v4,m1,0),_mm512_gf2p8affine_epi64_epi8(half,m3,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(v4,m0,0),_mm512_gf2p8affine_epi64_epi8(half,m2,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(packed+4,mixed);
}
{
const auto half=_mm512_shuffle_i32x4(v5,v5,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(v5,m1,0),_mm512_gf2p8affine_epi64_epi8(half,m3,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(v5,m0,0),_mm512_gf2p8affine_epi64_epi8(half,m2,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(packed+5,mixed);
}
{
const auto half=_mm512_shuffle_i32x4(v6,v6,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(v6,m1,0),_mm512_gf2p8affine_epi64_epi8(half,m3,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(v6,m0,0),_mm512_gf2p8affine_epi64_epi8(half,m2,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(packed+6,mixed);
}
{
const auto half=_mm512_shuffle_i32x4(v7,v7,0x4e);
const auto odd=_mm512_xor_si512(_mm512_gf2p8affine_epi64_epi8(v7,m1,0),_mm512_gf2p8affine_epi64_epi8(half,m3,0));
const auto mixed=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(v7,m0,0),_mm512_gf2p8affine_epi64_epi8(half,m2,0),_mm512_shuffle_i32x4(odd,odd,0x39),0x96);
_mm512_store_si512(packed+7,mixed);
}
}
template<unsigned plane> static SPIN_FORCEINLINE void parityPlane(__m512i* packed){
static_assert(plane<8);
const auto m6=_mm512_set1_epi64(0x060c183060c09b2dULL);
const auto m8=_mm512_set1_epi64(0x08102040801b366cULL);
const auto m26=_mm512_set1_epi64(0x1a3468d0bb6ddaafULL);
const auto a=_mm512_load_si512(packed+32+plane);
const auto b=_mm512_load_si512(packed+40+plane);
const auto c=_mm512_load_si512(packed+48+plane);
const auto d=_mm512_load_si512(packed+56+plane);
const auto total=_mm512_ternarylogic_epi64(a,b,_mm512_xor_si512(c,d),0x96);
const auto u=_mm512_gf2p8affine_epi64_epi8(total,m6,0);
const auto v=_mm512_gf2p8affine_epi64_epi8(total,m8,0);
const auto common=_mm512_ternarylogic_epi64(_mm512_gf2p8affine_epi64_epi8(total,m26,0),_mm512_gf2p8affine_epi64_epi8(_mm512_xor_si512(b,d),m6,0),_mm512_gf2p8affine_epi64_epi8(_mm512_xor_si512(c,d),m8,0),0x96);
const auto commonU=_mm512_xor_si512(common,u);
_mm512_store_si512(packed+0+plane,_mm512_ternarylogic_epi64(_mm512_load_si512(packed+0+plane),a,common,0x96));
_mm512_store_si512(packed+8+plane,_mm512_ternarylogic_epi64(_mm512_load_si512(packed+8+plane),b,commonU,0x96));
_mm512_store_si512(packed+16+plane,_mm512_ternarylogic_epi64(_mm512_load_si512(packed+16+plane),c,_mm512_xor_si512(common,v),0x96));
_mm512_store_si512(packed+24+plane,_mm512_ternarylogic_epi64(_mm512_load_si512(packed+24+plane),d,_mm512_xor_si512(commonU,v),0x96));
}
template<unsigned symbol> static SPIN_FORCEINLINE void storeSymbol(const __m512i* packed,Block* out){
static_assert(symbol<4);
const auto index0=_mm512_setr_epi64(0x4941090148400800ULL,0x4b430b034a420a02ULL,0x5951191158501810ULL,0x5b531b135a521a12ULL,0x6961292168602820ULL,0x6b632b236a622a22ULL,0x7971393178703830ULL,0x7b733b337a723a32ULL);
const auto index1=_mm512_setr_epi64(0x4d450d054c440c04ULL,0x4f470f074e460e06ULL,0x5d551d155c541c14ULL,0x5f571f175e561e16ULL,0x6d652d256c642c24ULL,0x6f672f276e662e26ULL,0x7d753d357c743c34ULL,0x7f773f377e763e36ULL);
const auto index2=_mm512_setr_epi64(0x4342414003020100ULL,0x4746454407060504ULL,0x4b4a49480b0a0908ULL,0x4f4e4d4c0f0e0d0cULL,0x5352515013121110ULL,0x5756555417161514ULL,0x5b5a59581b1a1918ULL,0x5f5e5d5c1f1e1d1cULL);
const auto index3=_mm512_setr_epi64(0x6362616023222120ULL,0x6766656427262524ULL,0x6b6a69682b2a2928ULL,0x6f6e6d6c2f2e2d2cULL,0x7372717033323130ULL,0x7776757437363534ULL,0x7b7a79783b3a3938ULL,0x7f7e7d7c3f3e3d3cULL);
const auto index4=_mm512_setr_epi64(0x0706050403020100ULL,0x4746454443424140ULL,0x0f0e0d0c0b0a0908ULL,0x4f4e4d4c4b4a4948ULL,0x1716151413121110ULL,0x5756555453525150ULL,0x1f1e1d1c1b1a1918ULL,0x5f5e5d5c5b5a5958ULL);
const auto index5=_mm512_setr_epi64(0x2726252423222120ULL,0x6766656463626160ULL,0x2f2e2d2c2b2a2928ULL,0x6f6e6d6c6b6a6968ULL,0x3736353433323130ULL,0x7776757473727170ULL,0x3f3e3d3c3b3a3938ULL,0x7f7e7d7c7b7a7978ULL);
const auto basis=_mm512_set1_epi64(0x8040201008040201ULL);
const auto x0=_mm512_gf2p8affine_epi64_epi8(basis,_mm512_load_si512(packed+8*symbol+0),0);
const auto x1=_mm512_gf2p8affine_epi64_epi8(basis,_mm512_load_si512(packed+8*symbol+1),0);
const auto x2=_mm512_gf2p8affine_epi64_epi8(basis,_mm512_load_si512(packed+8*symbol+2),0);
const auto x3=_mm512_gf2p8affine_epi64_epi8(basis,_mm512_load_si512(packed+8*symbol+3),0);
const auto x4=_mm512_gf2p8affine_epi64_epi8(basis,_mm512_load_si512(packed+8*symbol+4),0);
const auto x5=_mm512_gf2p8affine_epi64_epi8(basis,_mm512_load_si512(packed+8*symbol+5),0);
const auto x6=_mm512_gf2p8affine_epi64_epi8(basis,_mm512_load_si512(packed+8*symbol+6),0);
const auto x7=_mm512_gf2p8affine_epi64_epi8(basis,_mm512_load_si512(packed+8*symbol+7),0);
const auto a0=_mm512_permutex2var_epi8(x0,index0,x1);
const auto a1=_mm512_permutex2var_epi8(x0,index1,x1);
const auto a2=_mm512_permutex2var_epi8(x2,index0,x3);
const auto a3=_mm512_permutex2var_epi8(x2,index1,x3);
const auto a4=_mm512_permutex2var_epi8(x4,index0,x5);
const auto a5=_mm512_permutex2var_epi8(x4,index1,x5);
const auto a6=_mm512_permutex2var_epi8(x6,index0,x7);
const auto a7=_mm512_permutex2var_epi8(x6,index1,x7);
const auto b0=_mm512_permutex2var_epi8(a0,index2,a2);
const auto b1=_mm512_permutex2var_epi8(a0,index3,a2);
const auto b2=_mm512_permutex2var_epi8(a1,index2,a3);
const auto b3=_mm512_permutex2var_epi8(a1,index3,a3);
const auto b4=_mm512_permutex2var_epi8(a4,index2,a6);
const auto b5=_mm512_permutex2var_epi8(a4,index3,a6);
const auto b6=_mm512_permutex2var_epi8(a5,index2,a7);
const auto b7=_mm512_permutex2var_epi8(a5,index3,a7);
const auto c0=_mm512_permutex2var_epi8(b0,index4,b4);
_mm512_storeu_si512(out+0+8*symbol+0,c0);
const auto c1=_mm512_permutex2var_epi8(b0,index5,b4);
_mm512_storeu_si512(out+32+8*symbol+0,c1);
const auto c2=_mm512_permutex2var_epi8(b1,index4,b5);
_mm512_storeu_si512(out+64+8*symbol+0,c2);
const auto c3=_mm512_permutex2var_epi8(b1,index5,b5);
_mm512_storeu_si512(out+96+8*symbol+0,c3);
const auto c4=_mm512_permutex2var_epi8(b2,index4,b6);
_mm512_storeu_si512(out+0+8*symbol+4,c4);
const auto c5=_mm512_permutex2var_epi8(b2,index5,b6);
_mm512_storeu_si512(out+32+8*symbol+4,c5);
const auto c6=_mm512_permutex2var_epi8(b3,index4,b7);
_mm512_storeu_si512(out+64+8*symbol+4,c6);
const auto c7=_mm512_permutex2var_epi8(b3,index5,b7);
_mm512_storeu_si512(out+96+8*symbol+4,c7);
}
static SPIN_NOINLINE void outerGroup(const Block* __restrict a,Block* __restrict out,const std::uint64_t* __restrict coeff){
alignas(64) __m512i packed[64];
for(unsigned symbol=0;symbol<8;++symbol)mixSymbol(a+32*symbol,packed+8*symbol,coeff+16*symbol);
parityPlane<0>(packed);
parityPlane<1>(packed);
parityPlane<2>(packed);
parityPlane<3>(packed);
parityPlane<4>(packed);
parityPlane<5>(packed);
parityPlane<6>(packed);
parityPlane<7>(packed);
storeSymbol<0>(packed,out);
storeSymbol<1>(packed,out);
storeSymbol<2>(packed,out);
storeSymbol<3>(packed,out);
}
} // namespace spin::research::rs::fast
