/- Generated by emit_majorant.py: 1 leaves, 0 logs. -/
import SpinCodes.Numeric.MajorantDefs
set_option maxRecDepth 8000000
set_option maxHeartbeats 0
namespace Spin.Majorant.S6.P27
open Spin.Numeric Spin.Numeric.Fix
def table : LogTree := .leaf
def tree : BoxTree := .leaf (1)
def A : Fix := ⟨500000000000000000000000000000, 1000000000000000000000000000000⟩
def B : Fix := ⟨500000000000000000000000000000, 1000000000000000000000000000000⟩
def W : Fix := ⟨186080216750413333333333333333, 214306711397326500000000000000⟩
def S : Fix := ⟨1400000000000000000000000000000, 1400000000000000000000000000000⟩
def I : Fix := ⟨-126133170725692000000000000000, -126133170725692000000000000000⟩
theorem logs_ok : table.check 10 = true := by decide
theorem tree_ok : checkTree (majorantLeaf (treeLog table) S I) tree A B W = true := by decide
end Spin.Majorant.S6.P27
