#!/usr/bin/env python3
"""Build and bind the exact BCH250-124 transposed XOR circuit.

The parent is the parity extension of primitive narrow-sense BCH(255,37).
The script shortens coordinates 0 through 5, obtains the deterministic
nullspace basis used by the audited BCH250 code, and retains basis rows
0 through 123.  The omitted final basis coordinate defines the fixed
codimension-one subcode used by the finite certificate implementation.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path


WORKSTREAM = Path(__file__).resolve().parent
REPO_ROOT = WORKSTREAM.parents[1]
SCRIPTS = REPO_ROOT / "scripts"
sys.path.insert(0, str(SCRIPTS))

import probe_bch_forward_xor_circuit as paar  # noqa: E402
from check_bch_transposed_inner import extended_bch_check_rows, row_rank  # noqa: E402
from exact_bch_spectrum_small import nullspace_basis  # noqa: E402


PARENT_LENGTH = 256
PARENT_DIMENSION = 131
SHORTENED_LENGTH = 250
SHORTENED_DIMENSION = 125
SUBCODE_DIMENSION = 124
M = 8
DESIGNED_DISTANCE = 37


def sha256_rows(rows: list[int], length: int) -> str:
    byte_length = (length + 7) // 8
    return hashlib.sha256(
        b"".join(row.to_bytes(byte_length, "little") for row in rows)
    ).hexdigest()


def build_rows() -> tuple[list[int], int, str]:
    checks, length, dimension, rank = extended_bch_check_rows(M, DESIGNED_DISTANCE)
    if (length, dimension, rank) != (PARENT_LENGTH, PARENT_DIMENSION, 125):
        raise RuntimeError(f"unexpected parent {(length, dimension, rank)}")

    shortening_checks = [1 << coordinate for coordinate in range(6)]
    ladder = [
        row_rank(checks + shortening_checks[:prefix])
        for prefix in range(7)
    ]
    if ladder != [125, 126, 127, 128, 129, 130, 131]:
        raise RuntimeError(f"shortening checks are not independent: {ladder}")

    parent_basis = list(
        nullspace_basis(checks + shortening_checks, PARENT_LENGTH)
    )
    shortened = [row >> 6 for row in parent_basis]
    if len(shortened) != SHORTENED_DIMENSION:
        raise RuntimeError("shortened BCH basis has the wrong dimension")
    if row_rank(shortened) != SHORTENED_DIMENSION:
        raise RuntimeError("shortened BCH generator has the wrong rank")
    if any(row >> SHORTENED_LENGTH for row in shortened):
        raise RuntimeError("shortened generator uses an out-of-range coordinate")
    if any(row.bit_count() & 1 for row in shortened):
        raise RuntimeError("shortened BCH generator is not even")

    subcode = shortened[:SUBCODE_DIMENSION]
    if row_rank(subcode) != SUBCODE_DIMENSION:
        raise RuntimeError("selected BCH250-124 subcode has the wrong rank")
    omitted = shortened[SUBCODE_DIMENSION]
    return subcode, omitted, sha256_rows(shortened, SHORTENED_LENGTH)


def columns(rows: list[int]) -> list[int]:
    result = [0] * SHORTENED_LENGTH
    for row_index, row in enumerate(rows):
        remaining = row
        while remaining:
            bit = (remaining & -remaining).bit_length() - 1
            result[bit] |= 1 << row_index
            remaining &= remaining - 1
    return result


def packed_terms(circuit: paar.Circuit) -> list[list[tuple[str, int]]]:
    return paar.transpose_terms(circuit)


def write_pair_header(path: Path, circuit: paar.Circuit, seed: int) -> None:
    terms = packed_terms(circuit)
    schedule = paar.descending_transpose_schedule(circuit)

    def term_name(term: tuple[str, int]) -> str:
        kind, index = term
        return f"word[{index}]" if kind == "word" else f"a{index}"

    lines = [
        "#pragma once",
        "",
        "// Generated by build_bch250_124_transpose_circuit.py.",
        f"// Two-row AVX2 transposition of the exact seed-{seed} circuit.",
        "",
        "#include <immintrin.h>",
        "#include <cryptoTools/Common/Defines.h>",
        "",
        "namespace osuCrypto::detail",
        "{",
        "    struct Bch250x124PackedBlock",
        "    {",
        "        __m256i value;",
        "    };",
        "",
        "    OC_FORCEINLINE Bch250x124PackedBlock operator^(" ,
        "        Bch250x124PackedBlock left, Bch250x124PackedBlock right) noexcept",
        "    {",
        "        return { _mm256_xor_si256(left.value, right.value) };",
        "    }",
        "",
        "#if defined(_MSC_VER)",
        "#define BCH250_NOINLINE __declspec(noinline)",
        "#else",
        "#define BCH250_NOINLINE __attribute__((noinline))",
        "#endif",
        "    BCH250_NOINLINE inline void bch250x124TransposeCircuit2(",
        "        const block* __restrict word0,",
        "        const block* __restrict word1,",
        "        block* __restrict message0,",
        "        block* __restrict message1)",
        "    {",
        "        Bch250x124PackedBlock word[250];",
        "        for (u64 index = 0; index < 250; ++index)",
        "            word[index].value = _mm256_set_m128i(",
        "                word1[index].mData, word0[index].mData);",
    ]
    for signal in schedule:
        expression = " ^ ".join(term_name(term) for term in terms[signal])
        if signal < SUBCODE_DIMENSION:
            lines.extend(
                [
                    f"        const Bch250x124PackedBlock output{signal} = {expression};",
                    f"        message0[{signal}].mData = _mm256_castsi256_si128(output{signal}.value);",
                    f"        message1[{signal}].mData = _mm256_extracti128_si256(output{signal}.value, 1);",
                ]
            )
        else:
            if not expression:
                raise RuntimeError("transpose circuit contains an unused signal")
            lines.append(
                f"        const Bch250x124PackedBlock a{signal} = {expression};"
            )
    lines.extend(["    }", "#undef BCH250_NOINLINE", "}", ""])
    path.write_text("\n".join(lines), encoding="utf-8")


def write_wrapper(
    path: Path,
    rows: list[int],
    omitted: int,
    shortened_hash: str,
    circuit: paar.Circuit,
) -> None:
    row_lines = []
    for row in rows:
        words = [(row >> (64 * index)) & ((1 << 64) - 1) for index in range(4)]
        row_lines.append(
            "            {{" + ", ".join(f"0x{word:016x}ULL" for word in words) + "}},"
        )
    omitted_words = [
        (omitted >> (64 * index)) & ((1 << 64) - 1) for index in range(4)
    ]
    lines = [
        "#pragma once",
        "",
        '#include "Bch250x124TransposeCircuit.h"',
        '#include "Bch250x124TransposeCircuit2.h"',
        "",
        "#include <array>",
        "#include <bit>",
        "#include <cryptoTools/Common/Defines.h>",
        "",
        "namespace osuCrypto",
        "{",
        "    struct Bch250x124",
        "    {",
        "        static constexpr u64 dimension = 124;",
        "        static constexpr u64 length = 250;",
        f"        static constexpr u64 transposeXorCount = {paar.transpose_xor_count(circuit)};",
        f'        static constexpr const char* shortenedGeneratorSha256 = "{shortened_hash}";',
        f'        static constexpr const char* subcodeGeneratorSha256 = "{sha256_rows(rows, SHORTENED_LENGTH)}";',
        "        static constexpr std::array<std::array<u64, 4>, dimension> generatorRows = {{",
        *row_lines,
        "        }};",
        "        static constexpr std::array<u64, 4> omittedBasisRow{{",
        "            " + ", ".join(f"0x{word:016x}ULL" for word in omitted_words),
        "        }};",
        "",
        "        static void transposeBlock(",
        "            const block* __restrict word, block* __restrict message)",
        "        {",
        "            detail::bch250x124TransposeCircuit(word, message);",
        "        }",
        "",
        "        static void transposeBlock2(",
        "            const block* __restrict word0,",
        "            const block* __restrict word1,",
        "            block* __restrict message0,",
        "            block* __restrict message1)",
        "        {",
        "            detail::bch250x124TransposeCircuit2(",
        "                word0, word1, message0, message1);",
        "        }",
        "",
        "        static void transposeReference(",
        "            const block* __restrict word, block* __restrict message)",
        "        {",
        "            for (u64 row = 0; row < dimension; ++row)",
        "            {",
        "                message[row] = block{};",
        "                for (u64 chunk = 0; chunk < 4; ++chunk)",
        "                {",
        "                    u64 mask = generatorRows[row][chunk];",
        "                    while (mask)",
        "                    {",
        "                        const u64 bit = static_cast<u64>(std::countr_zero(mask));",
        "                        const u64 coordinate = 64 * chunk + bit;",
        "                        if (coordinate < length) message[row] ^= word[coordinate];",
        "                        mask &= mask - 1;",
        "                    }",
        "                }",
        "            }",
        "        }",
        "    };",
        "}",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--trials", type=int, default=8)
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument("--min-overlap", type=int, default=2)
    args = parser.parse_args()

    rows, omitted, shortened_hash = build_rows()
    target = columns(rows)
    paar.DIMENSION = SUBCODE_DIMENSION
    paar.LENGTH = SHORTENED_LENGTH

    best: tuple[tuple[int, int, int], paar.Circuit] | None = None
    for seed in range(args.seed, args.seed + args.trials):
        circuit = paar.synthesize(seed, args.min_overlap, target)
        score = (paar.transpose_xor_count(circuit), circuit.xor_count, seed)
        if best is None or score < best[0]:
            best = (score, circuit)
    assert best is not None
    (transpose_xors, forward_xors, seed), circuit = best

    scalar = WORKSTREAM / "Bch250x124TransposeCircuit.h"
    pair = WORKSTREAM / "Bch250x124TransposeCircuit2.h"
    wrapper = WORKSTREAM / "Bch250x124.h"
    receipt = WORKSTREAM / "bch250_124_transpose_circuit.json"
    paar.write_production_transpose_header(
        scalar,
        circuit,
        seed,
        args.min_overlap,
        "bch250x124TransposeCircuit",
        False,
    )
    write_pair_header(pair, circuit, seed)
    write_wrapper(wrapper, rows, omitted, shortened_hash, circuit)

    payload = {
        "schema": "bch250-124-transpose-circuit-v1",
        "status": "EXACT_VERIFIED",
        "parent": "parity-extended primitive narrow-sense BCH(255,37)",
        "shortening_coordinates": list(range(6)),
        "subcode_basis_indices": list(range(SUBCODE_DIMENSION)),
        "omitted_basis_index": SUBCODE_DIMENSION,
        "parameters": {
            "length": SHORTENED_LENGTH,
            "dimension": SUBCODE_DIMENSION,
            "minimum_distance_floor": 38,
        },
        "hashes": {
            "shortened_250x125_generator_rows_sha256": shortened_hash,
            "subcode_250x124_generator_rows_sha256": sha256_rows(
                rows, SHORTENED_LENGTH
            ),
            "omitted_basis_row_sha256": hashlib.sha256(
                omitted.to_bytes(32, "little")
            ).hexdigest(),
        },
        "circuit": {
            "trials": args.trials,
            "seed": seed,
            "minimum_overlap": args.min_overlap,
            "forward_xors": forward_xors,
            "transpose_xors": transpose_xors,
            "shared_gates": len(circuit.gates),
            "max_depth_upper": circuit.max_depth,
        },
        "scope": (
            "GF(2) ranks, generator selection, circuit synthesis, and both "
            "forward and transposed circuit identities are checked exactly. "
            "The distance floor is inherited from the BCH construction."
        ),
    }
    receipt.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"best_seed,{seed}")
    print(f"forward_xors,{forward_xors}")
    print(f"transpose_xors,{transpose_xors}")
    print(f"subcode_hash,{payload['hashes']['subcode_250x124_generator_rows_sha256']}")
    print(f"wrote,{scalar}")
    print(f"wrote,{pair}")
    print(f"wrote,{wrapper}")
    print(f"wrote,{receipt}")


if __name__ == "__main__":
    main()
