"""Reproduce the paper's parameter slices from the retained, rounded grid tables.

No numerical search or proof replay. --check verifies the generated TeX bytewise.
The source fingerprint uses normalized newlines for portable Git checkouts.
"""
import argparse
from collections import Counter
import hashlib
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'workstreams/finite_asymptotic_theory/landscape_db/CURRENT_RESULTS_TABLES.md'
OUT = ROOT / 'paper/figures'
COLORS = {64: 'blue!70!black', 128: 'orange!85!black', 256: 'purple!80!black'}


def read_grid():
    source = SOURCE.read_text(encoding='utf-8')
    rows = {}

    def add(b, t, s, m, cell):
        match = re.fullmatch(r'([OW]) \(([-\d.e+]+)\)', cell)
        if match:
            status, value = match.groups()
            record = dict(status=status, value=float(value), full=None, q1=None)
            assert (record['value'] > 0) == (status == 'O')
        else:
            match = re.fullmatch(r'([-\d.]+) \(([-\d.e+]+)\)', cell)
            assert match, cell
            full, loss = map(float, match.groups())
            assert full > 0 and loss >= 0
            record = dict(status='U', value=full, full=full, q1=full + loss)
        key = b, t, s, m
        if key in rows:
            assert rows[key] == record, key
        rows[key] = record

    section = ''
    for line in source.splitlines():
        if line.startswith('## Matched'):
            break
        if line.startswith('### '):
            section = line
        if not re.match(r'\| \d', line):
            continue
        cells = [x.strip() for x in line.strip('|').split('|')]
        if 'Message size' in section:
            m = int(cells[0])
            for b, cell in zip((64, 128), cells[1:]):
                add(b, 64, 20, m, cell)
        elif 'Epoch/state' in section:
            t, s = map(int, cells[:2])
            for b, cell in zip((64, 128), cells[2:]):
                add(b, t, s, 20, cell)
        elif 'Additional' in section:
            b, s = map(int, cells[:2])
            for m, cell in zip((16, 18, 22, 24), cells[2:]):
                add(b, 64, s, m, cell)
    assert len(rows) == 130
    assert Counter(r['status'] for r in rows.values()) == {'U': 77, 'W': 7, 'O': 46}
    expected = {(b, 64, 20, m) for b in (64, 128) for m in range(12, 27)}
    expected |= {(b, t, s, 20) for b in (64, 128)
                 for t in (64, 128, 256) for s in range(t.bit_length(), 21)}
    expected |= {(b, 64, s, m) for b in (64, 128) for s in (10, 12, 16)
                 for m in (16, 18, 20, 22, 24)}
    assert set(rows) == expected
    return rows, hashlib.sha256(source.encode()).hexdigest()


def plot(points, style):
    if not any(y is not None for _, y in points):
        return ''
    coords = ' '.join(f'({x},{y:.9f})' if y is not None else f'({x},nan)' for x, y in points)
    return f'\\addplot[{style}] coordinates {{{coords}}};\n'


def curve(rows, keys, xindex, color, mark='*'):
    # Never interpolate through a weak or obstructed full-bound point.
    full = [(k[xindex], rows[k]['full']) for k in keys]
    q1 = [(k[xindex], rows[k]['q1']) for k in keys]
    return (plot(full, f'{color},thick,mark={mark},mark size=1.7pt,unbounded coords=jump')
            + plot(q1, f'{color},densely dashed,opacity=.5,unbounded coords=jump,forget plot'))


BASE = (r'tick label style={font=\footnotesize},label style={font=\small},'
        r'title style={font=\small},grid=major,grid style={black!10},'
        r'axis line style={black!50},legend style={font=\footnotesize,draw=none},')


def panel(options, content, width=r'.485\linewidth'):
    return (f'\\begin{{minipage}}[t]{{{width}}}\n\\centering\n'
            '\\begin{tikzpicture}\n\\begin{axis}[' + BASE + options + ']\n'
            + content + '\\end{axis}\n\\end{tikzpicture}\n\\end{minipage}\n')


def figures(rows, digest):
    header = ('% Generated by paper/build_parameter_figures.py; do not hand edit.\n'
              f'% Source: CURRENT_RESULTS_TABLES.md; normalized SHA-256 {digest}\n'
              '% Rounded binary64 diagnostics, not new outward-rounded certificates.\n')
    outputs = {}
    body = ''
    for b in (64, 128):
        keys = [(b, 64, 20, m) for m in range(12, 27)]
        body += curve(rows, keys, 3, COLORS[b])
        body += f'\\addlegendentry{{$B={b}$}}\n'
    body += plot([(12, 40), (26, 40)], 'black,dotted')
    body += '\\addlegendentry{40-bit target}\n'
    outputs['parameter_k_b.tex'] = header + r'''\begin{figure}[!hbp]
\centering
''' + panel(r'width=.92\linewidth,height=5.6cm,xlabel={$\log_2 K$},'
            r'ylabel={Margin (bits)},xmin=11.7,xmax=26.3,ymin=0,ymax=43,'
            r'xtick={12,14,16,18,20,22,24,26},ytick={0,10,20,30,40},'
            r'legend style={at={(.5,.57)},anchor=center,legend columns=3},', body, r'\linewidth') + r'''
\caption{Outer length and message length, with $(t,s)=(64,20)$ fixed.
Solid curves give full first-moment upper-bound margins; faint dashed curves
give the one-active-row ($q=1$) margins and mostly overlap the solid curves.
The inner map is shared across the two outer lengths. Points are evaluated
configurations; connecting segments are guides, not bounds between points.}
\label{fig:finite-k-b}
\end{figure}
'''

    panels = []
    for b in (64, 128):
        body = ''
        for t in (64, 128, 256):
            keys = [(b, t, s, 20) for s in range(t.bit_length(), 21)]
            body += curve(rows, keys, 2, COLORS[t], {64: '*', 128: 'square*', 256: 'triangle*'}[t])
        top = panel(r'width=\linewidth,height=5.0cm,title={BCH-' + str(b) + r'},'
                    r'xmin=6.5,xmax=20.5,ymin=0,ymax=40,xtick={8,12,16,20},'
                    r'ytick={0,10,20,30,40},ylabel={Margin (bits)},', body, r'\linewidth')
        body = ''
        for t, y in ((64, 3), (128, 2), (256, 1)):
            for status, mark in (('U', '*'), ('W', 'o'), ('O', 'x')):
                pts = [(s, y) for s in range(t.bit_length(), 21)
                       if rows[b, t, s, 20]['status'] == status]
                body += plot(pts, f'only marks,{COLORS[t]},mark={mark},mark size=2pt,thick')
        bottom = panel(r'width=\linewidth,height=2.4cm,xmin=6.5,xmax=20.5,'
                       r'ymin=.5,ymax=3.5,xtick={8,12,16,20},xlabel={State bits $s$},'
                       r'ytick={1,2,3},yticklabels={$t=256$,$t=128$,$t=64$},grid=none,',
                       body, r'\linewidth')
        panels.append(r'\begin{minipage}[t]{.485\linewidth}' + top + '\n\\par\n' + bottom + r'\end{minipage}')
    outputs['parameter_s_t.tex'] = header + r'''\begin{figure}[tb]
\centering
''' + '\\hfill\n'.join(panels) + r'''
\caption{State and step size at $K=2^{20}$. Blue circles: $t=64$; orange
squares: $t=128$. Solid and faint dashed curves have the meanings in
Figure~\ref{fig:finite-k-b}. The strips below show every tested state:
filled dots denote useful full bounds, open circles weak full upper bounds,
and crosses a positive first-moment lower obstruction. No useful full curve
is available for $t=256$ (purple). Strip heights are categories, not margins.
An obstruction rules out a small first moment for that map, not the code's
distance property.}
\label{fig:finite-s-t}
\end{figure}
'''

    panels = []
    kcolors = {16: 'blue!70!black', 20: 'orange!85!black', 24: 'purple!80!black'}
    for b in (64, 128):
        body = ''
        for m in (16, 20, 24):
            keys = [(b, 64, s, m) for s in (10, 12, 16, 20)]
            body += curve(rows, keys, 2, kcolors[m])
            body += f'\\addlegendentry{{$\\log_2 K={m}$}}\n'
            weak = [(k[2], 0) for k in keys if rows[k]['status'] == 'W']
            if weak:
                body += plot(weak, f'only marks,{kcolors[m]},mark=o,mark size=2pt,forget plot')
        panels.append(panel(r'width=\linewidth,height=5.5cm,title={BCH-' + str(b) + r'},'
                            r'xlabel={State bits $s$},ylabel={Margin (bits)},'
                            r'xmin=9.5,xmax=20.5,ymin=-1,ymax=40,xtick={10,12,16,20},'
                            r'ytick={0,10,20,30,40},legend pos='
                            + ('north east,' if b == 64 else 'south east,'), body))
    outputs['parameter_k_s.tex'] = header + r'''\begin{figure}[tb]
\centering
''' + '\\hfill\n'.join(panels) + r'''
\caption{The state curve at three message lengths, with $t=64$ fixed.
Only the four marked states are compared at every length. Solid and faint
dashed curves denote full and $q=1$ margins. Open circles on the baseline
flag negative full-bound margins, rather than zero-margin measurements;
no line crosses these points. Smaller states amplify the higher-occupancy
loss for BCH-64 at the largest message length.}
\label{fig:finite-k-s}
\end{figure}
'''
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    rows, digest = read_grid()
    outputs = figures(rows, digest)
    if not args.check:
        OUT.mkdir(exist_ok=True)
    for name, contents in outputs.items():
        path = OUT / name
        if args.check:
            assert path.read_text(encoding='utf-8') == contents, f'Stale figure: {path}'
        else:
            path.write_text(contents, encoding='utf-8', newline='\n')
    print(f'{"Checked" if args.check else "Generated"} {len(outputs)} figures; '
          '130 unique geometries: 77 useful, 7 weak, 46 obstructed. '
          'Input precision: retained rounded tables; no proof replay.')


if __name__ == '__main__':
    main()
