"""Render compact, pinned application measurements; never runs benchmarks."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data" / "application_results.json"
PATHS = {
    "encoding": "results/spin-brakedown/peach-paired/summary.json",
    "pcs": "results/spin-brakedown/peach-security/summary.json",
    "bolt": "results/bolt-one-thread/summary.json",
    "flock": "results/flock-spin/native-current-comparison/summary.json",
}


def import_results(source):
    records, receipts = {}, {}
    for key, name in PATHS.items():
        raw = (source / name).read_bytes()
        records[key] = json.loads(raw)
        receipts[key] = {"path": name, "sha256": hashlib.sha256(raw).hexdigest()}
    enc = records["encoding"]
    return {
        "source_repository": "hypercat",
        "source_revision": "015a4f8",
        "flock_revision": "2d667ca",
        "receipts": receipts,
        "encoding": {
            "method": enc["method"],
            "source_revision": enc["spin_revision"],
            "runs": {k: v for k, v in enc["runs"].items()
                     if k.startswith("fused-") or k.startswith("confirm-fused-")},
        },
        "pcs": {
            "scope": records["pcs"]["scope"],
            "budget": records["pcs"]["budget"],
            "rows": {k: records["pcs"]["stages"]["pooled_optimized"][k]
                     for k in ("k16-w2", "k18-w2")},
        },
        "bolt": records["bolt"],
        "flock": {
            log: {backend: records["flock"][log]["backends"][backend]["mean_process_medians"]
                  for backend in ("spin", "native-fast100")}
            for log in ("14", "16")
        },
    }


def render(data):
    rows = []
    for field, label in (("forward_ms", "Ordinary"), ("transpose_ms", "Transposed")):
        values = [data["encoding"]["runs"][f"fused-k{k}"][field]["median"]
                  for k in (16, 18, 20)]
        rows.append(label + " & " + " & ".join(f"{v:.3f}" for v in values) + r" \\")
    tables = {"ordinary_encoding": rows}
    rows = []
    for key in ("k16-w2", "k18-w2"):
        r = data["pcs"]["rows"][key]
        rows.append(f"${r['rows']}\\times {r['k']}$ & {r['total_ms']:.2f} & "
                    f"{r['verify_ms']:.2f} & {r['proof_bytes']/2**20:.3f}" + r" \\")
    tables["pcs_standalone"] = rows
    rows = []
    for log in ("14", "16"):
        for backend, label in (("spin", "SPIN--Brakedown"), ("native-fast100", "Ligerito")):
            r = data["flock"][log][backend]
            rows.append(f"${2**int(log):,}$ & {label} & {r['total_ms']:.2f} & "
                        f"{r['verify_ms']:.2f} & {r['proof_bytes']/2**20:.3f}" + r" \\")
    tables["flock_comparison"] = rows
    digest = hashlib.sha256(DATA.read_bytes()).hexdigest()
    return {ROOT / "tables" / (name + ".tex"):
            f"% Generated by build_application_tables.py; data SHA-256 {digest}\n"
            + "\n".join(rows) + "\n\\bottomrule\n" for name, rows in tables.items()}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, help="Import the pinned summaries from Hypercat")
    parser.add_argument("--check", action="store_true", help="Check generated tables without writing")
    args = parser.parse_args()
    if args.source and args.check:
        parser.error("--source and --check are separate operations")
    if args.source:
        DATA.parent.mkdir(parents=True, exist_ok=True)
        DATA.write_text(json.dumps(import_results(args.source), indent=2) + "\n", encoding="utf-8")
    data = json.loads(DATA.read_text(encoding="utf-8"))
    for row in data["pcs"]["budget"]:
        a, n, t = row["e"] + 1, row["n"], row["queries"]
        assert 3 * row["e"] < row["assumed_distance"]
        assert (a * n**t + (n-a)**t * 2**128) * 2**100 <= 2**128 * n**t
    row = data["pcs"]["budget"][0]
    a, n, t = row["e"] + 1, row["n"], 2110
    assert 2 * (a * n**t + (n-a)**t * 2**128) * 2**102 < 2**128 * n**t
    for path, content in render(data).items():
        if args.check:
            assert path.read_text(encoding="utf-8") == content, f"Stale table: {path}"
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    print("Application tables and exact conditional parameter bounds checked.")


if __name__ == "__main__":
    main()
