"""Reproduce the fixed-map mixing comparison from authenticated Q1 receipts."""
import argparse
from pathlib import Path

import imt_results as evidence

GRID_PIN = ('finite_migration/MIXING_ROUNDS_Q1_v1.json',
            '1c65c5da992e7b646fdfb09d33bd1874dc344281122d2ba7bf6d9a46103cbf1a')
REPLAY_PIN = ('finite_migration/MIXING_ROUNDS_Q1_v1_native_replay.json',
              '95e2edd75af19960488d22015e772a9e4e958b6b603a0fc3919f56ad02362a4a')
OUT = Path(__file__).resolve().parent / 'figures/imt_mixing_rounds.tex'
require = evidence.require


def validate(grid, replay, selected_inner=None):
    require(grid['status'] == 'OUTWARD_IMT_MIXING_ROUNDS_Q1', 'Wrong mixing study')
    require(replay['status'] == 'IMT_MIXING_ROUNDS_Q1_512_BIT_NATIVE_REPLAY_PASSED', 'Wrong mixing replay')
    require(replay['producer_sha256'] == GRID_PIN[1], 'Mixing replay binds another producer')
    require(not grid['full_distance_proved'] and not replay['full_distance_proved'], 'Q1 scope changed')
    require(replay['cells_checked'] == 18, 'Incomplete mixing replay')
    rows, fixed = {}, None
    for row in grid['cells']:
        m, rounds = row['exponent'], row['rounds']
        key = m, rounds
        require(key not in rows, 'Duplicate mixing cell')
        instance, inner = row['instance'], row['instance']['inner']
        require((instance['message_bits'], instance['output_bits'], instance['cutoff']) ==
                (2**m, 2**(m+1), 2**(m+1)//10), 'Wrong mixing geometry')
        require((instance['outer_length'], instance['outer_dimension'], instance['distance']) ==
                (256,128,'1/10'), 'Wrong mixing outer or distance')
        require((inner['t'],inner['s'],inner['feedback_name']) == (128,19,'weight5_seed0'), 'Wrong IMT maps')
        require(inner['transvection_rounds'] == (None if rounds == 'refresh' else int(rounds)), 'Wrong round count')
        require(inner['mixing_law'] == ('ideal_uniform_nonzero_marginal' if rounds == 'refresh'
                                      else 'independent_transvection_product'), 'Wrong mixer law')
        maps = inner['expansion_columns'], inner['feedback_columns']
        if fixed is None:
            fixed = maps
        require(maps == fixed, 'Mixing comparison changes maps')
        if selected_inner is not None:
            require(maps == (selected_inner['expansion_columns'], selected_inner['feedback_columns']),
                    'Mixing maps differ from selected certificate')
        bound = evidence.fraction(row['q1_upper'])
        require(0 < bound < 1, 'Invalid Q1 bound')
        margin = evidence.margin(bound)
        require(abs(margin-row['q1_margin_bits']) < 1e-9, 'Mixing margin differs from rational bound')
        rows[key] = margin
    require(set(rows) == {(m,r) for m in (16,18,20) for r in ('1','2','3','4','8','refresh')},
            'Missing or extra mixing cells')
    return rows


def load(selected_inner=None):
    seen = {}
    return validate(evidence.authenticate(GRID_PIN,seen), evidence.authenticate(REPLAY_PIN,seen), selected_inner)


def render(rows):
    text = ('% Generated by paper/build_imt_mixing_figure.py; do not hand edit.\n'
            f'% Q1 producer SHA-256: {GRID_PIN[1]}\n')
    text += r'''\begin{figure}[tb]
\centering
\begin{tikzpicture}
\begin{axis}[width=.92\linewidth,height=6cm,
tick label style={font=\footnotesize},label style={font=\small},
grid=major,grid style={black!10},
xlabel={$\log_2 K$},ylabel={Q1 margin (bits)},
xmin=15.7,xmax=20.3,ymin=43,ymax=55,xtick={16,18,20},ytick={44,46,48,50,52,54},
legend style={font=\footnotesize,draw=none,at={(.5,1.03)},anchor=south,legend columns=2}]
'''
    for rounds, style, label in (
        ('1','blue!70!black,thick,mark=*',r'IMT, $r=1$'),
        ('2','orange!85!black,thick,mark=square*',r'IMT, $r=2$'),
        ('4','purple!80!black,thick,mark=triangle*',r'IMT, $r=4$'),
        ('refresh','black,dashed,thick,mark=o','Ideal full refresh')):
        points = ' '.join(f'({m},{rows[m,rounds]:.10f})' for m in (16,18,20))
        text += f'\\addplot[{style}] coordinates {{{points}}};\n\\addlegendentry{{{label}}}\n'
    return text + r'''\end{axis}
\end{tikzpicture}
\caption{Effect of mixing depth $r$ on the length curve, using the BCH-256
outer and fixed IMT maps of Section~\ref{sec:finite-selected-construction},
$(t,s)=(128,19)$. Additional transvections recover most of the
short-length Q1 gap; the benefit is smaller at larger $K$. All points are
outward Q1 bounds, not full-distance certificates. Segments connect tested
lengths only.}
\label{fig:finite-imt-mixing}
\end{figure}
'''


def check(selected=None):
    rows = load(selected['half'][16]['instance']['inner'] if selected else None)
    require(OUT.read_text() == render(rows), 'Mixing figure differs from authenticated bounds')
    return dict(q1_cells=18, plotted_rounds=[1,2,4,'refresh'], full_distance_proved=False)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args = parser.parse_args()
    if args.check:
        print(check())
    else:
        OUT.write_text(render(load()),encoding='utf-8',newline='\n')
